import{createRoomStore,activeRecords}from'./room-store.js?v=6.6.1-room-layout';

const store=createRoomStore(),text=value=>String(value??'').trim();
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const dateKey=(value=new Date)=>{const year=value.getFullYear(),month=String(value.getMonth()+1).padStart(2,'0'),day=String(value.getDate()).padStart(2,'0');return`${year}-${month}-${day}`};
const addDays=(date,count)=>{const value=new Date(`${date}T12:00:00`);value.setDate(value.getDate()+count);return dateKey(value)};
const pretty=date=>date?new Date(`${date}T12:00:00`).toLocaleDateString([],{weekday:'short',month:'short',day:'numeric'}):'Whenever';
const stamp=row=>[pretty(row.remindDate),row.remindTime].filter(Boolean).join(' · ');

export function reminderBucket(row,today=dateKey()){
 if(row.status==='Waiting / Follow Up')return'waiting';
 if(row.status==='Someday'||!row.remindDate)return'someday';
 const effective=row.snoozedUntil||row.remindDate;
 if(effective<=today)return'today';
 return'upcoming';
}
export function chimeWindow(row,today=dateKey()){
 const date=row.snoozedUntil||row.remindDate;if(!date)return'later';
 if(date<=today)return'today';if(date===addDays(today,1))return'tomorrow';
 return date<=addDays(today,7)?'week':'later';
}
export function saveBellReminder(targetStore,fields,id=''){
 const values={title:text(fields.title),remindDate:text(fields.remindDate),remindTime:text(fields.remindTime),repeat:text(fields.repeat)||'Never',linkedItem:text(fields.linkedItem),note:text(fields.note),status:text(fields.status)||'Active',snoozedUntil:text(fields.snoozedUntil)};
 if(!values.title)throw new Error('Name the reminder first.');
 return id?targetStore.update('bell','reminders',id,values):targetStore.create('bell','reminders',values);
}

let app,page;
const records=()=>activeRecords(store.load().bell.reminders).sort((a,b)=>`${a.snoozedUntil||a.remindDate||'9999'}${a.remindTime||'99:99'}`.localeCompare(`${b.snoozedUntil||b.remindDate||'9999'}${b.remindTime||'99:99'}`));
const button=(label,action,id,kind='ghost')=>`<button class="btn ${kind}" type="button" data-bell-action="${action}" data-id="${esc(id)}">${esc(label)}</button>`;
const empty=(title,copy)=>`<div class="v6-bell-empty"><b>${esc(title)}</b><span>${esc(copy)}</span></div>`;
const card=row=>`<article class="v6-chime-card" data-bell-edit="${esc(row.id)}" tabindex="0"><div class="v6-chime-time"><b>${esc(row.remindTime||'○')}</b><span>${esc(pretty(row.snoozedUntil||row.remindDate))}</span></div><div class="v6-chime-copy"><div><span class="v6-room-tag">${esc(row.status||'Active')}</span>${row.repeat&&row.repeat!=='Never'?`<span class="v6-room-tag">↻ ${esc(row.repeat)}</span>`:''}</div><h3>${esc(row.title)}</h3>${row.note?`<p>${esc(row.note)}</p>`:''}${row.linkedItem?`<small>Linked: ${esc(row.linkedItem)}</small>`:''}</div><div class="v6-chime-actions">${button('Snooze','snooze',row.id,'soft')}${button('Done','complete',row.id,'success')}</div></article>`;
const group=(title,copy,rows,kind)=>`<section class="v6-chime-group" data-bell-group="${kind}"><header><div><h2>${esc(title)}</h2><p>${esc(copy)}</p></div><span>${rows.length}</span></header><div>${rows.map(card).join('')||empty(`No ${title.toLowerCase()}.`,'The tower is quiet here.')}</div></section>`;

export function bellTowerMarkup(state=store.load(),today=dateKey()){
 const all=activeRecords(state.bell.reminders),open=all.filter(row=>!['Completed','Dismissed'].includes(row.status)),recent=all.filter(row=>['Completed','Dismissed'].includes(row.status)).sort((a,b)=>text(b.updatedAt).localeCompare(text(a.updatedAt))).slice(0,5),buckets={today:[],upcoming:[],waiting:[],someday:[]};open.forEach(row=>buckets[reminderBucket(row,today)].push(row));
 const windows=['today','tomorrow','week','later'].map(kind=>{const rows=open.filter(row=>chimeWindow(row,today)===kind),label={today:'Today',tomorrow:'Tomorrow',week:'This Week',later:'Later'}[kind];return`<div class="v6-bell-window ${rows.length?'has-chimes':''}"><i></i><b>${label}</b><span>${rows.length} chime${rows.length===1?'':'s'}</span></div>`}).join('');
 const snoozed=open.filter(row=>row.snoozedUntil);
 return`<section class="v6-bell-hero"><div><div class="ey">🔔 BELL TOWER</div><h1>Let the right things chime back in.</h1><p>Reminders and follow-ups live here independently from Royal Duties.</p></div><button class="btn primary" type="button" data-bell-action="add">＋ Quick-add Ping</button></section><section class="v6-bell-timeline" aria-label="Upcoming Chimes timeline">${windows}</section><div class="v6-bell-layout"><main>${group('Today','Signals arriving now.',buckets.today,'today')}${group('Upcoming','Dated reminders beyond today.',buckets.upcoming,'upcoming')}${group('Waiting / Follow Up','Things to bring back when someone or something responds.',buckets.waiting,'waiting')}${group('Someday Pings','Useful reminders without pressure or an overdue state.',buckets.someday,'someday')}</main><aside><section class="v6-bell-side"><header><h2>Snoozed</h2><span>${snoozed.length}</span></header>${snoozed.slice(0,5).map(row=>`<button type="button" data-bell-edit="${row.id}"><b>${esc(row.title)}</b><small>Returns ${esc(pretty(row.snoozedUntil))}</small></button>`).join('')||empty('No snoozed chimes.','Everything is where you left it.')}</section><section class="v6-bell-side"><header><h2>Recent</h2><span>${recent.length}</span></header>${recent.map(row=>`<button type="button" data-bell-edit="${row.id}"><b>${esc(row.title)}</b><small>${esc(row.status)}</small></button>`).join('')||empty('No recent chimes.','Completed and dismissed reminders appear here.')}</section><button class="v6-bell-quick" type="button" data-bell-action="add"><span>＋</span><b>Quick-add Ping</b><small>Bring something back at the right time.</small></button></aside></div>`;
}

export function renderBellTower(target){page=target;page.querySelector('.v6-command-room')?.remove();page.querySelector('.v6-detail-toolbar')?.remove();page.classList.remove('v6-detail-mode');page.classList.add('v6-overview-mode');[...page.children].filter(node=>!node.classList.contains('detail-modal-backdrop')).forEach(node=>node.classList.add('v6-source-section'));page.insertAdjacentHTML('beforeend',`<div class="v6-command-room v6-bell-tower" data-v6-room="bell-tower">${bellTowerMarkup()}</div>`)}
function close(){app.querySelector('[data-bell-modal]')?.remove()}
function modal(record={}){close();app.insertAdjacentHTML('beforeend',`<div class="v6-room-modal-backdrop" data-bell-modal><section class="v6-room-modal v6-bell-modal" role="dialog" aria-modal="true" aria-labelledby="bell-title"><header><div><span>🔔</span><div><small>BELL TOWER</small><h2 id="bell-title">${record.id?'Edit Ping':'Quick-add Ping'}</h2></div></div><button type="button" data-bell-close aria-label="Close">×</button></header><form data-bell-form data-id="${esc(record.id||'')}"><div class="v6-room-form-grid"><label class="wide"><span>Reminder</span><input name="title" required value="${esc(record.title||'')}" autofocus></label><label><span>Remind date</span><input type="date" name="remindDate" value="${esc(record.remindDate||'')}"></label><label><span>Time</span><input type="time" name="remindTime" value="${esc(record.remindTime||'')}"></label><label><span>Repeat</span><select name="repeat">${['Never','Daily','Weekly','Monthly'].map(value=>`<option ${record.repeat===value?'selected':''}>${value}</option>`).join('')}</select></label><label><span>Kind</span><select name="status">${['Active','Waiting / Follow Up','Someday','Completed','Dismissed'].map(value=>`<option ${record.status===value?'selected':''}>${value}</option>`).join('')}</select></label><label class="wide"><span>Linked KatOS item (optional)</span><input name="linkedItem" value="${esc(record.linkedItem||'')}" placeholder="Reference only"></label><label class="wide"><span>Note</span><textarea name="note" rows="3">${esc(record.note||'')}</textarea></label></div><footer><div>${record.id?button('Dismiss','dismiss',record.id,'danger'):''}</div><div><button type="button" class="btn soft" data-bell-close>Cancel</button><button type="submit" class="btn primary">Save Ping</button></div></footer></form></section></div>`)}
function refresh(){if(page?.isConnected)renderBellTower(page)}
function act(name,id){const record=store.load().bell.reminders.find(row=>row.id===id);if(name==='add')return modal();if(!record)return;if(name==='edit')return modal(record);if(name==='snooze'){store.update('bell','reminders',id,{snoozedUntil:addDays(dateKey(),1),status:'Active'});refresh();return}if(name==='complete'){store.update('bell','reminders',id,{status:'Completed',completedAt:new Date().toISOString(),snoozedUntil:''});refresh();return}if(name==='dismiss'){if(confirm('Dismiss this reminder? The related KatOS item will not be changed.')){store.update('bell','reminders',id,{status:'Dismissed',dismissedAt:new Date().toISOString(),snoozedUntil:''});close();refresh()}}}
export function installBellTower(root){app=root;app.addEventListener('click',event=>{if(event.target.matches('[data-bell-modal]')||event.target.closest('[data-bell-close]')){event.preventDefault();close();return}const action=event.target.closest('[data-bell-action]');if(action){event.preventDefault();event.stopPropagation();act(action.dataset.bellAction,action.dataset.id);return}const edit=event.target.closest('[data-bell-edit]');if(edit){event.preventDefault();act('edit',edit.dataset.bellEdit)}},true);app.addEventListener('submit',event=>{const form=event.target.closest('[data-bell-form]');if(!form)return;event.preventDefault();const fields=Object.fromEntries(new FormData(form));try{saveBellReminder(store,fields,form.dataset.id);close();refresh()}catch(error){form.querySelector('input[name="title"]')?.setCustomValidity(error.message);form.reportValidity()}},true)}
