const{ensureSingleDeviceIpadMode}=await import('../v5/sync/single-device-mode.js?v=7.0.12-ipad-only');
ensureSingleDeviceIpadMode(localStorage);
const{ensureDeviceBootstrapState}=await import('../v5/sync/sync-device-bootstrap.js?v=7.0.12-ipad-only');
ensureDeviceBootstrapState(localStorage);
await import('../v5/app.js?v=7.5.0-rbt-hub');
try{await import('./command-shell.js?v=6.7.13-treasury-controls')}catch(error){console.error('KatOS V6 shell failed to mount.',error);document.body.insertAdjacentHTML('afterbegin',`<div role="alert" style="position:fixed;z-index:9999;inset:8px 8px auto;padding:10px;border:1px solid #b65780;border-radius:12px;background:#fff7fb;color:#6b4352;font:12px system-ui">V6 shell error: ${String(error?.message||error)}</div>`)}
await import('../v5/sync/sync-lab.js?v=7.0.12-ipad-only');
await import('../v5/daily-step-popup-fix.js?v=5.6.5-routine-step-modal');
await import('../v5/money-budgets.js?v=5.6.6-spending-budgets');
await import('../v5/gig-goals-fix.js?v=7.3.6-single-mission');
await import('../v5/study-history-popup-fix.js?v=5.6.7-completed-course-edit');
await import('../v5/schedule-gig-labels.js?v=5.6.9-gig-shift-labels');
await import('../v5/brain-dump-v5.js?v=5.7.2-brain-dump');
await import('../v5/fixed-events-safe.js?v=5.7.8-fixed-events-safe');
await import('../v5/bill-skip-month.js?v=5.8.0-bill-skip-month');
await import('../v5/doordash-shift-modal.js?v=7.0.22-odometer-sunday-payout');
await import('../v5/flex-shift-modal.js?v=7.4.0-intelligence-pass');
await import('../v5/flex-hours.js?v=7.4.0-intelligence-pass');
await import('../v5/unified-gig-planner.js?v=7.0.19-flex-hours');
await import('./gig-shift-checkin.js?v=6.7.13-treasury-controls');
await import('../v5/gig-archive-display-fix.js?v=5.8.5-gig-archive-filter');
await import('../v5/routine-player.js?v=7.0.20-daily-routines');
await import('../v5/routine-builder-layout-fix.js?v=6.15.1-routine-builder-layout');
await import('../v5/mochini-avatar.js?v=7.4.2-v6-assets');
await import('./mochini-living.js?v=6.6.0-living-palace');
await import('../v5/mochini-face-patch.js?v=7.4.2-v6-assets');
await import('../v5/mochini-approved-art.js?v=6.10.2-v6-assets');
await import('../v5/mochini-chat.js?v=6.0.0-canonical-rig');
await import('../v5/mochini-polish.js?v=5.9.5-safari-art-fix');
await import('../v5/shipt-daily-groups.js?v=5.9.2-shipt-persistent-groups');
await import('../v5/optimization-health.js?v=7.1.0-optimization-pass');
await import('../v5/optimization-money.js?v=7.4.0-intelligence-pass');
await import('../v5/optimization-schedule-study.js?v=7.1.0-optimization-pass');
await import('../v5/optimization-safety.js?v=7.1.0-optimization-pass');
await import('../v5/money-mission.js?v=7.3.4-account-goals');
await import('../v5/weekly-mirror.js?v=7.4.2-weekly-mirror-modal');
await import('../v5/intelligence-upgrade.js?v=7.4.1-v6-lifecycle');
window.dispatchEvent(new Event('katos:v6-refresh'));
