const list=value=>Array.isArray(value)?value:[];
const text=value=>String(value??'').trim();
const num=value=>Number(value)||0;
const round=value=>Math.round(num(value)*100)/100;
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const cash=value=>round(value).toLocaleString([],{style:'currency',currency:'USD',maximumFractionDigits:2});
const isFlex=row=>/amazon\s*flex|\bflex\b/i.test(text(row?.source||row?.platform||row?.label||row?.shiftLabel));
const isDash=row=>/door\s*dash/i.test(text(row?.source||row?.platform||row?.label||row?.shiftLabel));
const clockMinutes=(start,end)=>{if(!/^\d{1,2}:\d{2}$/.test(text(start))||!/^\d{1,2}:\d{2}$/.test(text(end)))return 0;const[sh,sm]=start.split(':').map(Number),[eh,em]=end.split(':').map(Number);let value=eh*60+em-(sh*60+sm);if(value<0)value+=1440;return value};
const durationLabel=value=>{const minutes=Math.max(0,Math.round(num(value)));if(!minutes)return'—';const hours=Math.floor(minutes/60),rest=minutes%60;return[hours?`${hours}h`:'',rest?`${rest}m`:''].filter(Boolean).join(' ')};
const dateLabel=value=>{if(!value)return'Date open';const date=new Date(`${value}T12:00:00`);return Number.isNaN(date.getTime())?value:date.toLocaleDateString([],{weekday:'short',month:'short',day:'numeric'})};
const timeLabel=value=>{if(!/^\d{1,2}:\d{2}$/.test(text(value)))return'';const[hours,minutes]=value.split(':').map(Number),date=new Date;date.setHours(hours,minutes,0,0);return date.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})};
const timeRange=row=>[timeLabel(row?.startTime),timeLabel(row?.endTime)].filter(Boolean).join(' – ')||'Time open';
const expenseTotal=row=>round(num(row?.gasExpense)+num(row?.foodExpense)+num(row?.tollsParkingExpense)+num(row?.otherShiftExpense));

export function carriageShiftMetrics(shift={},order={}){
 const flex=isFlex(shift)||isFlex(order),gross=round(order.total??order.basePay??shift.actualAmount??shift.targetAmount),expenses=expenseTotal(shift),actualMinutes=num(shift.actualMinutes||order.activeMinutes)||clockMinutes(shift.actualStartTime||order.actualStartTime,shift.actualEndTime||order.actualEndTime),scheduledMinutes=num(shift.scheduledMinutes)||clockMinutes(shift.startTime,shift.endTime),start=shift.startOdometer??order.startOdometer,end=shift.endOdometer??order.endOdometer,odometerMiles=start!==''&&start!=null&&end!==''&&end!=null&&num(end)>=num(start)?round(num(end)-num(start)):0,mileage=round(order.mileage??shift.mileage??odometerMiles),packages=Math.max(0,Math.round(num(order.packageCount??shift.packageCount))),stops=Math.max(0,Math.round(num(order.stopCount??shift.stopCount))),net=round(gross-expenses);
 return{flex,gross,expenses,net,actualMinutes,scheduledMinutes,mileage,packages,stops,profitPerHour:actualMinutes?round(net/(actualMinutes/60)):null,profitPerMile:mileage?round(net/mileage):null,orders:Math.max(0,Math.round(num(order.deliveryCount??order.orderCount??order.orders)))};
}

export function buildCarriageModel({today='',state={},finance={}}={}){
 const shifts=list(state?.work?.gigShifts).filter(row=>!row?.archivedAt&&(isFlex(row)||isDash(row))),orders=list(finance?.gig?.orders),orderById=new Map(orders.map(row=>[String(row.id),row])),planned=shifts.filter(row=>!row.summaryOrderId&&!['completed','cancelled','canceled','archived'].includes(text(row.status).toLowerCase())).sort((a,b)=>`${a.date||''}${a.startTime||''}`.localeCompare(`${b.date||''}${b.startTime||''}`)),completed=shifts.filter(row=>row.summaryOrderId||text(row.status).toLowerCase()==='completed').sort((a,b)=>`${b.date||''}${b.startTime||''}`.localeCompare(`${a.date||''}${a.startTime||''}`)).map(shift=>({shift,order:orderById.get(String(shift.summaryOrderId))||{},metrics:carriageShiftMetrics(shift,orderById.get(String(shift.summaryOrderId))||{})})),progress=finance.dailyGigGoal||null,goal=progress?.goal||progress||null,earned=num(finance?.gigToday?.gross),target=num(goal?.targetAmount),remaining=Math.max(0,round(progress?.remaining??target-earned)),next=planned.find(row=>!row.date||row.date>=today)||planned[0]||null;
 return{today,planned,completed,next,goal,target,earned,remaining,week:finance.gigWeek||{},comparison:list(finance.gigComparison),payouts:list(finance.pendingPayouts),allPayouts:list(finance?.gig?.payouts),goals:list(finance?.gig?.goals),orders,platforms:list(finance?.gig?.platforms),accounts:list(finance?.hq?.accounts).filter(row=>row.active!==false&&!row.archivedAt)};
}

function stat(label,value,note=''){return`<div class="v6-carriage-stat"><small>${esc(label)}</small><b>${esc(value)}</b>${note?`<span>${esc(note)}</span>`:''}</div>`}
function empty(copy){return`<p class="v6-soft-empty">${esc(copy)}</p>`}
function shiftButton(shift){const flex=isFlex(shift),open=flex?'data-flex-plan-open':'data-doordash-plan-open',place=shift.station||shift.area||shift.zone||'Area open';return`<button type="button" class="v6-ride-row" ${open}="${esc(shift.id)}"><span class="v6-ride-platform">${flex?'📦':'🚗'}<b>${flex?'Amazon Flex':'DoorDash'}</b></span><span><b>${esc(dateLabel(shift.date))}</b><small>${esc(timeRange(shift))}</small></span><span><b>${cash(shift.targetAmount)}</b><small>${esc(place)}</small></span><em>${esc(text(shift.status)||'planned')}</em></button>`}
function workCard(item){const{shift,metrics}=item,flex=metrics.flex;return`<button type="button" class="v6-gig-work-card" ${flex?'data-flex-plan-open':'data-doordash-plan-open'}="${esc(shift.id)}"><header><span>${flex?'📦':'🚗'}</span><div><b>${flex?'Amazon Flex':'DoorDash'}</b><small>${esc(dateLabel(shift.date))} · ${esc(durationLabel(metrics.actualMinutes))}</small></div><strong>${cash(metrics.net)} net</strong></header>${flex?`<p class="v6-route-load">${metrics.packages} packages <i>•</i> ${metrics.stops} stops</p>`:`<p class="v6-route-load">${metrics.orders||'—'} orders <i>•</i> ${esc(durationLabel(metrics.actualMinutes))} active</p>`}<div class="v6-gig-metrics"><span><small>MILES</small><b>${metrics.mileage||'—'}</b></span><span><small>GROSS</small><b>${cash(metrics.gross)}</b></span><span><small>EXPENSES</small><b>${cash(metrics.expenses)}</b></span><span><small>PROFIT / HR</small><b>${metrics.profitPerHour==null?'—':cash(metrics.profitPerHour)}</b></span><span><small>PROFIT / MI</small><b>${metrics.profitPerMile==null?'—':cash(metrics.profitPerMile)}</b></span></div></button>`}
function options(rows,current='',label=row=>row.name||row.title||row.id,blank=''){return`${blank?`<option value="">${esc(blank)}</option>`:''}${rows.map(row=>`<option value="${esc(row.id)}"${String(row.id)===String(current)?' selected':''}>${esc(label(row))}</option>`).join('')}`}
function moneyModal(id,ey,title,copy,body){return`<div class="detail-modal-backdrop money-modal" data-money-modal="${esc(id)}" hidden><section class="detail-modal" role="dialog" aria-modal="true"><div class="detail-modal-head"><div><div class="ey">${ey}</div><h2>${esc(title)}</h2><p>${esc(copy)}</p></div><button type="button" class="detail-modal-close" data-money-close aria-label="Close">×</button></div>${body}</section></div>`}
function goalModal(model,goal={}){const id=goal.id?`gig-goal-${goal.id}`:'new-gig-goal';return moneyModal(id,'🎯 GIG GOAL',goal.name||'Set a gig goal','Progress uses completed earnings. KatOS never schedules a shift for you.',`<form data-money-form="gig-goal-save"${goal.id?` data-money-id="${esc(goal.id)}"`:''}><div class="room-detail-fields"><label class="money-field wide"><span>Goal name</span><input name="name" value="${esc(goal.name||'Today’s gig goal')}"></label><label class="money-field"><span>Period</span><select name="period">${['day','week','month','custom'].map(value=>`<option${(goal.period||'day')===value?' selected':''}>${value}</option>`).join('')}</select></label><label class="money-field"><span>Target amount</span><input name="targetAmount" type="number" min="0" step="0.01" value="${esc(goal.targetAmount||0)}" required></label><label class="money-field"><span>Start date</span><input name="startDate" type="date" value="${esc(goal.startDate||model.today)}"></label><label class="money-field"><span>End date</span><input name="endDate" type="date" value="${esc(goal.endDate||model.today)}"></label><label class="money-field"><span>Platform · optional</span><select name="platformId">${options(model.platforms,goal.platformId,row=>row.name,'All platforms')}</select></label><label class="money-field wide"><span>Notes</span><textarea name="notes" rows="3">${esc(goal.notes||'')}</textarea></label></div><div class="button-row"><button class="btn primary">Save goal</button><button type="button" class="btn soft" data-money-close>Cancel</button></div></form>`)}
function payoutModal(model,payout={}){const id=payout.id?`payout-${payout.id}`:'new-payout',eligible=model.orders.filter(order=>!order.payoutId||list(payout.orderIds).includes(order.id));return moneyModal(id,'💌 GIG PAYOUT',payout.id?'Review payout':'Create a payout','Only marking a received payout creates one linked Treasury deposit.',`<form data-money-form="payout-save"${payout.id?` data-money-id="${esc(payout.id)}"`:''}><div class="room-detail-fields"><label class="money-field wide"><span>Platform</span><select name="platformId" required>${options(model.platforms,payout.platformId,row=>row.name,'Choose platform')}</select></label><label class="money-field"><span>Amount</span><input name="amount" type="number" min="0" step="0.01" value="${esc(payout.amount??'')}"></label><label class="money-field"><span>Status</span><select name="status">${['pending','available','processing','received'].map(value=>`<option${(payout.status||'pending')===value?' selected':''}>${value}</option>`).join('')}</select></label><label class="money-field"><span>Available date</span><input name="availableDate" type="date" value="${esc(payout.availableDate||'')}"></label><label class="money-field"><span>Destination account</span><select name="destinationAccountId">${options(model.accounts,payout.destinationAccountId,row=>row.name,'Choose when received')}</select></label><label class="money-field wide"><span>Notes</span><textarea name="notes" rows="3">${esc(payout.notes||'')}</textarea></label></div><fieldset class="money-order-picker"><legend>Orders in this payout</legend>${eligible.map(order=>`<label><input type="checkbox" name="orderIds" value="${esc(order.id)}"${list(payout.orderIds).includes(order.id)?' checked':''}> ${esc(dateLabel(order.date))} · ${cash(order.total||order.basePay)}</label>`).join('')||'<span>No unpaid orders are waiting.</span>'}</fieldset><div class="button-row"><button class="btn primary">Save payout</button><button type="button" class="btn soft" data-money-close>Cancel</button></div></form>${payout.id&&payout.status!=='received'?`<form class="money-receive" data-money-form="payout-receive" data-money-id="${esc(payout.id)}"><b>Deposit arrived?</b><select name="accountId" required>${options(model.accounts,payout.destinationAccountId,row=>row.name,'Choose account')}</select><input name="date" type="date" value="${esc(payout.depositDate||model.today)}"><button class="btn primary">Mark received + add one deposit</button></form>`:''}`)}

export function carriageHouseMarkup(model){
 const next=model.next,nextFlex=isFlex(next),weekGross=num(model.week?.gross),weekNet=num(model.week?.simpleNet??model.week?.net??weekGross),comparisons=model.comparison.slice(0,3),payoutTotal=model.payouts.reduce((sum,row)=>sum+num(row.amount||row.expectedAmount),0);
 const goalRows=model.goals.slice(0,4).map(goal=>`<button type="button" class="v6-carriage-manage-row" data-money-open="gig-goal-${esc(goal.id)}"><span><b>${esc(goal.name||'Gig goal')}</b><small>${esc(goal.period||'custom')} · ${cash(goal.targetAmount)}</small></span><em>Edit</em></button>`).join('');
 const payoutRows=model.allPayouts.slice(0,5).map(payout=>`<button type="button" class="v6-carriage-manage-row" data-money-open="payout-${esc(payout.id)}"><span><b>${esc(dateLabel(payout.availableDate||payout.createdAt?.slice?.(0,10)))} payout</b><small>${cash(payout.amount)} · ${esc(payout.status||'pending')}</small></span><em>Open</em></button>`).join('');
 const comparisonRows=comparisons.map(row=>`<p><b>${esc(row.platform?.name||row.platformName||row.name||'Platform')}</b><span>${cash(row.gross||row.total)} · ${num(row.count||row.orders)} orders</span></p>`).join('');
 const controls=`<div class="v6-carriage-controls"><section><header><div><div class="ey">GOALS</div><h3>Earning targets</h3></div><button type="button" class="btn soft" data-money-open="new-gig-goal">＋ Goal</button></header>${goalRows||empty('No gig goal has been set.')}</section><section><header><div><div class="ey">PAYOUTS</div><h3>Treasury connections</h3></div><button type="button" class="btn soft" data-money-open="new-payout">＋ Payout</button></header>${payoutRows||empty('No gig payout records yet.')}</section></div>`;
 const modals=goalModal(model)+model.goals.map(goal=>goalModal(model,goal)).join('')+payoutModal(model)+model.allPayouts.map(payout=>payoutModal(model,payout)).join('');
 return`<section class="v6-carriage-hero"><div><div class="ey">🎠 CARRIAGE HOUSE</div><h1>Gig work, ready to roll.</h1><p>Plan the block, record the real route, and keep earnings connected to Royal Treasury once.</p></div><div class="v6-carriage-actions"><button type="button" class="btn primary" data-flex-add>＋ Flex block</button><button type="button" class="btn soft" data-doordash-add>＋ DoorDash shift</button></div></section><section class="v6-carriage-today">${stat('TODAY’S GOAL',model.target?cash(model.target):'Set a goal',model.goal?.name||'editable suggestion')}${stat('EARNED',cash(model.earned),'completed gig earnings')}${stat('REMAINING',model.target?cash(model.remaining):'—','nothing is auto-scheduled')}${stat('NEXT',next?nextFlex?'Amazon Flex':'DoorDash':'No block waiting',next?`${timeLabel(next.startTime)||dateLabel(next.date)} · ${cash(next.targetAmount)}`:'Add work only when you choose')}</section><div class="v6-carriage-layout"><main><section class="v6-carriage-panel"><header><div><div class="ey">UPCOMING RIDES</div><h2>Planned blocks & shifts</h2></div><span>${model.planned.length}</span></header><div class="v6-ride-list">${model.planned.length?model.planned.slice(0,8).map(shiftButton).join(''):empty('No Flex blocks or DoorDash shifts are planned.')}</div></section><section class="v6-carriage-panel"><header><div><div class="ey">TODAY’S WORK</div><h2>Real route results</h2></div><span>${model.completed.length}</span></header><div class="v6-work-grid">${model.completed.length?model.completed.slice(0,6).map(workCard).join(''):empty('Completed shifts will show mileage, expenses, and profitability here.')}</div></section><details class="v6-carriage-ledger"><summary>Goals, payouts & Treasury controls</summary>${controls}</details></main><aside class="v6-carriage-side"><section><div class="ey">ADAPTIVE GIG GOAL</div><h2>${model.remaining?`${cash(model.remaining)} left`:'Today can stay flexible'}</h2><p>Suggestions respond to real completed earnings. They never schedule a shift for you.</p><button type="button" class="btn soft" data-smart-action="adaptive">Review earning plan</button></section><section><div class="ey">THIS WEEK</div><div class="v6-carriage-week">${stat('GROSS',cash(weekGross))}${stat('NET',cash(weekNet))}${stat('ORDERS',String(num(model.week?.count||model.week?.orders)))}</div><div class="v6-carriage-comparison">${comparisonRows||empty('Platform comparison appears after completed shifts.')}</div></section><section><div class="ey">PAYOUTS</div><h2>${cash(payoutTotal)} in transit</h2><p>${model.payouts.length?`${model.payouts.length} payout${model.payouts.length===1?'':'s'} waiting or processing.`:'No pending payouts.'}</p><button type="button" class="btn soft" data-money-open="new-payout">Manage payouts</button></section></aside></div>${modals}`;
}
