import{activeRecords,createRoomStore}from'./room-store.js?v=6.6.0-living-palace';
import{arrangedWidgets,dueConcreteMessages,groupLifeChapters,habitGarden,kingdomMap,milestoneTimeline,referenceCatalog,resolveReference}from'./living-store.js?v=6.6.0-living-palace';
import{localDateKey,selectV5DailyShit,snapshotV4}from'../v5/data.js?v=7.5.0-rbt-hub';

const store=createRoomStore(),list=value=>Array.isArray(value)?value:[],text=value=>String(value??'').trim();
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const prettyMonth=value=>{if(!value)return'Unsorted chapter';const date=new Date(`${value}-01T12:00:00`);return Number.isNaN(date.getTime())?value:date.toLocaleDateString([],{month:'long',year:'numeric'})};
const pretty=value=>value?new Date(`${value}T12:00:00`).toLocaleDateString([],{month:'short',day:'numeric',year:'numeric'}):'';
let app,lastRoom='',lastFocus=null;
const state=()=>store.load(),planner=()=>snapshotV4()?.state||{};
const close=()=>{app.querySelector('[data-living-modal]')?.remove();lastFocus?.focus?.();lastFocus=null};
const button=(label,action,id='',extra='')=>`<button type="button" class="btn tiny" data-living-action="${action}"${id?` data-id="${esc(id)}"`:''} ${extra}>${esc(label)}</button>`;
const empty=(title,copy,action,label)=>`<div class="v6-room-empty"><b>${esc(title)}</b><p>${esc(copy)}</p>${action?`<button type="button" class="btn soft" data-living-action="${action}">${esc(label)}</button>`:''}</div>`;
const head=(icon,title,copy='')=>`<header><div><span>${icon}</span><div><div class="ey">LIVING PALACE · YOUR HISTORY</div><h2>${esc(title)}</h2>${copy?`<p>${esc(copy)}</p>`:''}</div></div><button type="button" class="icon-btn" data-living-close aria-label="Close">×</button></header>`;
function modal(name,title,body,{icon='✦',copy='',wide=false}={}){close();lastFocus=document.activeElement;app.insertAdjacentHTML('beforeend',`<div class="detail-modal-backdrop v6-smart-backdrop v6-living-backdrop" data-living-modal="${esc(name)}"><section class="detail-modal v6-smart-modal v6-living-modal ${wide?'is-wide':''}" role="dialog" aria-modal="true" aria-label="${esc(title)}">${head(icon,title,copy)}<div class="v6-smart-modal-body">${body}</div></section></div>`);requestAnimationFrame(()=>app.querySelector('[data-living-modal] input,[data-living-modal] select,[data-living-modal] textarea,[data-living-modal] button')?.focus())}
const footer=(save='Save',extra='')=>`<footer><div>${extra}</div><div><button type="button" class="btn soft" data-living-close>Cancel</button><button class="btn primary">${esc(save)}</button></div></footer>`;
const field=(label,name,type='text',value='',options=[],wide=false)=>`<label class="${wide?'wide':''}"><span>${esc(label)}</span>${type==='textarea'?`<textarea name="${name}" rows="4">${esc(value)}</textarea>`:type==='select'?`<select name="${name}">${options.map(option=>{const raw=typeof option==='string'?option:option.value,labelText=typeof option==='string'?option:option.label;return`<option value="${esc(raw)}"${String(raw)===String(value)?' selected':''}>${esc(labelText)}</option>`}).join('')}</select>`:`<input type="${type}" name="${name}" value="${esc(value)}"${['title','date','month'].includes(name)?' required':''}>`}</label>`;
const fields=content=>`<div class="v6-smart-fields">${content}</div>`;
const refOptions=(selected='')=>[{value:'',label:'No linked record'},...referenceCatalog(state(),planner()).map(row=>({value:row.key,label:`${row.label} · ${row.kind.replace('.', ' ')}`}))].map(option=>`<option value="${esc(option.value)}"${option.value===selected?' selected':''}>${esc(option.label)}</option>`).join('');
const refLabel=key=>resolveReference(key,state(),planner())?.label||'Linked item no longer available';

function chapterForm(record={}){const refs=new Set(list(record.references));modal('chapter',record.id?'Edit Life Chapter':'New Life Chapter',`<form data-living-form="chapter" data-id="${esc(record.id||'')}">${fields(field('Month','month','month',record.month||localDateKey().slice(0,7))+field('Chapter title','title','text',record.title)+field('Notes · your words only','notes','textarea',record.notes,[],true)+`<label class="wide"><span>Linked records · optional</span><select name="references" multiple size="6">${referenceCatalog(state(),planner()).map(option=>`<option value="${esc(option.key)}"${refs.has(option.key)?' selected':''}>${esc(option.label)} · ${esc(option.kind.replace('.',' '))}</option>`).join('')}</select><small>References stay connected to their original records.</small></label>`)}${footer('Save chapter',record.id?button(record.archivedAt?'Restore':'Archive','chapter-archive',record.id)+button('Delete','chapter-delete',record.id,'data-danger="true"'):'')}</form>`,{icon:'📖',copy:'A chapter holds facts and your own notes—not an automatic emotional interpretation.',wide:true})}
function milestoneForm(record={}){modal('milestone',record.id?'Edit Milestone':'Add Milestone',`<form data-living-form="milestone" data-id="${esc(record.id||'')}">${fields(field('Date','date','date',record.date||localDateKey())+field('Area','area','select',record.area||'Personal',['Career','School','Money','Trip','Relationship','Goal','Life Change','Fun','Home','Personal'])+field('Milestone','title','text',record.title)+`<label><span>Linked record · optional</span><select name="reference">${refOptions(record.reference)}</select></label>`+field('Notes','notes','textarea',record.notes,[],true))}${footer('Save milestone',record.id?button(record.archivedAt?'Restore':'Archive','milestone-archive',record.id)+button('Delete','milestone-delete',record.id,'data-danger="true"'):'')}</form>`,{icon:'✦',copy:'Link the original record when one exists instead of duplicating it.',wide:true})}
function pinForm(record={}){modal('pin',record.id?'Edit Pin':'Pin a Reference',`<form data-living-form="pin" data-id="${esc(record.id||'')}">${fields(`<label class="wide"><span>Reference</span><select name="reference" required>${refOptions(record.reference)}</select></label>`+field('Short note · optional','note','textarea',record.note,[],true))}${footer('Save pin',record.id?button(record.archivedAt?'Restore':'Archive','pin-archive',record.id)+button('Delete','pin-delete',record.id,'data-danger="true"'):'')}</form>`,{icon:'📌',copy:'The pin points to the original record; it does not make a copy.'})}

function archiveManager(){const s=state(),row=(kind,record,label)=>`<article class="v6-smart-row"><div><b>${esc(label)}</b><span>${record.archivedAt?'Archived':'Active'}</span></div><div>${button(record.archivedAt?'Restore':'Archive',`${kind}-archive`,record.id)}</div></article>`,chapters=s.living.chapters.map(record=>row('chapter',record,record.title||prettyMonth(record.month))),milestones=s.living.milestones.map(record=>row('milestone',record,record.title)),pins=s.living.pins.map(record=>row('pin',record,refLabel(record.reference)));modal('living-archive','Archive & Restore',`<div class="v6-smart-list">${[...chapters,...milestones,...pins].join('')||'<div class="v6-smart-empty">Nothing has been saved or archived yet.</div>'}</div>`,{icon:'🗃️',copy:'Archive hides a record. Restore brings it back. Delete remains separate.',wide:true})}
function kingdomPopup(){const areas=kingdomMap(state(),planner());modal('kingdom','Kingdom Map',`<div class="v6-kingdom-map">${areas.map(area=>`<article><span>${area.icon}</span><div><h3>${esc(area.label)}</h3><p>${esc(area.indicator)}</p><small>${area.activeItems} active · ${area.openLoops} open loop${area.openLoops===1?'':'s'}</small></div></article>`).join('')}</div><p class="v6-smart-note">This overview uses counts and neutral indicators. Private relationship and cycle details stay inside their rooms.</p>`,{icon:'🗺️',copy:'A small overview of the life areas currently holding something.',wide:true})}
function arrangeFoyer(){const settings=state().living.settings,labels={capacity:'Current capacity',schedule:'Next schedule',focus:'One useful focus',context:'Context nearby','next-hour':'Build My Next Hour'},rows=arrangedWidgets(Object.keys(labels),settings);modal('foyer-arrange','Arrange Palace Foyer',`<form data-living-form="foyer"><div class="v6-foyer-arrange">${rows.map((row,index)=>`<article><label><input type="checkbox" name="visible" value="${row.key}"${row.hidden?'':' checked'}><span>${labels[row.key]}</span></label><div>${button('↑','foyer-move',row.key,`data-direction="up"${index===0?' disabled':''}`)}${button('↓','foyer-move',row.key,`data-direction="down"${index===rows.length-1?' disabled':''}`)}</div></article>`).join('')}</div>${footer('Save visibility')}</form>`,{icon:'🏰',copy:'Keep only the few cards that help right now.'})}

function chapterMarkup(){const groups=groupLifeChapters(state().living.chapters);return groups.length?groups.slice(0,6).map(group=>`<section class="v6-chapter-group"><h3>${esc(prettyMonth(group.month))}</h3><div>${group.items.map(chapter=>`<button type="button" data-living-action="chapter-edit" data-id="${esc(chapter.id)}"><b>${esc(chapter.title||prettyMonth(chapter.month))}</b><span>${esc(chapter.notes||'No chapter note yet.')}</span><small>${list(chapter.references).length} linked record${list(chapter.references).length===1?'':'s'}</small></button>`).join('')}</div></section>`).join(''):empty('Your first chapter is waiting 📖','Add a month when something becomes worth remembering.','chapter-add','New chapter')}
function timelineMarkup(){const rows=milestoneTimeline(state().living.milestones);return rows.length?rows.slice(0,8).map(record=>`<button type="button" class="v6-timeline-row" data-living-action="milestone-edit" data-id="${esc(record.id)}"><time>${esc(pretty(record.date))}</time><span></span><div><b>${esc(record.title)}</b><small>${esc(record.area||'Personal')}${record.reference?` · ${esc(refLabel(record.reference))}`:''}</small></div></button>`).join(''):empty('No milestones pinned yet ✦','Save real moments without scoring your life.','milestone-add','Add milestone')}
function habitsMarkup(){let routines=[];try{routines=selectV5DailyShit(localDateKey()).routines||[]}catch{}const rows=habitGarden(routines);return rows.length?rows.slice(0,8).map(item=>`<article class="v6-habit-plant"><span aria-hidden="true">${item.growth>=4?'🌸':item.growth>=2?'🌿':item.growth?'🌱':'🪴'}</span><div><b>${esc(item.icon)} ${esc(item.title)}</b><small>${esc(item.label)} · ${item.complete} complete${item.partial?` · ${item.partial} partial`:''}</small></div></article>`).join(''):empty('The Habit Garden is resting 🌱','Routine history will grow here gently. Missing days never reset it.')}
function keepsakeMarkup(){return`<section data-living-keepsake class="v6-living-keepsake"><div class="v6-living-toolbar"><div><div class="ey">📖 LIFE CHAPTERS</div><h2>The story, without inventing the meaning.</h2></div><div>${button('New chapter','chapter-add')}${button('Add milestone','milestone-add')}${button('Kingdom Map','kingdom')}${button('Archive & restore','living-archive')}</div></div><div class="v6-living-grid"><section class="v6-room-section"><header><div><h2>Life Chapters</h2><p>Monthly notes and links to the moments already saved.</p></div></header>${chapterMarkup()}</section><section class="v6-room-section"><header><div><h2>Milestone Timeline</h2><p>Career, school, money, trips, relationships, goals, and changes.</p></div></header><div class="v6-timeline">${timelineMarkup()}</div></section><section class="v6-room-section"><header><div><h2>Habit Garden</h2><p>Consistency grows gently. Quiet days do not kill the garden.</p></div></header><div class="v6-habit-garden">${habitsMarkup()}</div></section></div></section>`}
function pinboardMarkup(){const pins=activeRecords(state().living.pins);return`<section class="v6-room-section v6-pinboard" data-living-pinboard><header><div><h2>Dream Board / Pinboard</h2><p>References to things already living elsewhere in KatOS.</p></div><button type="button" class="v6-plus" data-living-action="pin-add" aria-label="Pin a reference">＋</button></header><div class="v6-pin-grid">${pins.length?pins.slice(0,12).map(pin=>{const reference=resolveReference(pin.reference,state(),planner());return`<button type="button" data-living-action="pin-edit" data-id="${esc(pin.id)}"><span>📌</span><b>${esc(reference?.label||'Linked item unavailable')}</b><small>${esc(pin.note||reference?.kind.replace('.',' ')||'Reference')}</small></button>`}).join(''):empty('The pinboard is ready ✨','Pin a plan, idea, project, note, milestone, or goal without copying it.','pin-add','Pin something')}</div></section>`}

function decorateKeepsake(){const room=app.querySelector('[data-v6-room="archive"]');if(!room||room.querySelector('[data-living-keepsake]'))return;room.querySelector('.v6-command-hero')?.insertAdjacentHTML('afterend',keepsakeMarkup())}
function decorateWishing(){const room=app.querySelector('[data-v6-room="wishing-tower"]');if(!room||room.querySelector('[data-living-pinboard]'))return;room.insertAdjacentHTML('beforeend',pinboardMarkup());const due=dueConcreteMessages(state().wishing.messages,localDateKey(),{plans:state().wishing.plans,courses:planner().education?.courses,goals:planner().growth?.goals});room.dataset.futureMessagesDue=String(due.length)}
function decorateFoyer(){const room=app.querySelector('[data-v6-room="home"]'),foyer=room?.querySelector('[data-smart-foyer]');if(!room||!foyer)return;const keys=['capacity','schedule','focus','context','next-hour'],settings=state().living.settings,layout=arrangedWidgets(keys,settings),children=[...foyer.children];children.forEach((child,index)=>{if(!child.dataset.livingWidget)child.dataset.livingWidget=keys[index]||`extra-${index}`});layout.forEach(item=>{const child=foyer.querySelector(`[data-living-widget="${item.key}"]`);if(child){child.hidden=item.hidden;foyer.append(child)}});if(!room.querySelector('[data-living-foyer-controls]'))foyer.insertAdjacentHTML('afterend',`<div class="v6-living-foyer-controls" data-living-foyer-controls>${button('Arrange Foyer','foyer-arrange')}${button('Kingdom Map','kingdom')}</div>`)}
const reactions={home:{mood:'happy',line:'The Palace is awake. I am inspecting today with one tiny crown.',activityId:'princessing',activity:'holding court in the Palace Foyer'},'rose-garden':{mood:'playful',line:'Rose Garden time. Productivity is not invited unless it brings snacks.',activityId:'cats',activity:'finding recreational enrichment'},'moon-garden':{mood:'peaceful',line:'Moon Garden can stay quiet. We are observing, not judging.',activityId:'plant',activity:'sitting calmly in the Moon Garden'},'love-letters':{mood:'love',line:'Warm little room. Private things stay inside it.',activityId:'princessing',activity:'guarding the Love Letters room'},'wishing-tower':{mood:'curious',line:'Future Kat has ideas. We can look without turning them into pressure.',activityId:'plant',activity:'looking out from the Wishing Tower'},study:{mood:'focused',line:'Tiny scholar mode. I brought the very serious little book.',activityId:'study-book',activity:'studying beside you'},money:{mood:'thinking',line:'Calculator Mochini has arrived. Real numbers only.',activityId:'money-check',activity:'checking the Treasury math'},boss:{mood:'determined',line:'Clipboard ready. We can prep the next real work block.',activityId:'clipboard',activity:'preparing for work'},archive:{mood:'cozy',line:'Keepsake Chest time. I will handle the memories gently.',activityId:'memory-box',activity:'looking through saved chapters'}};
function roomReaction(){const room=app.querySelector('.v6-command-room')?.dataset.v6Room||'';if(!room||room===lastRoom)return;lastRoom=room;const detail=reactions[room];if(detail)window.dispatchEvent(new CustomEvent('katos:v6-room-reaction',{detail:{...detail,duration:1500,open:false}}))}
export function decorateLivingPalace(){decorateKeepsake();decorateWishing();decorateFoyer();roomReaction()}
function refresh(){app.querySelector('[data-living-keepsake]')?.remove();app.querySelector('[data-living-pinboard]')?.remove();app.querySelector('[data-living-foyer-controls]')?.remove();decorateLivingPalace()}

function saveForm(form){const data=new FormData(form),kind=form.dataset.livingForm,id=form.dataset.id,s=state(),save=(collection,fields)=>id?store.update('living',collection,id,fields):store.create('living',collection,fields);if(kind==='chapter')save('chapters',{month:text(data.get('month')),title:text(data.get('title')),notes:text(data.get('notes')),references:data.getAll('references').map(String)});if(kind==='milestone')save('milestones',{date:text(data.get('date')),area:text(data.get('area')),title:text(data.get('title')),reference:text(data.get('reference')),notes:text(data.get('notes'))});if(kind==='pin'){const reference=text(data.get('reference'));if(!reference)return;save('pins',{reference,note:text(data.get('note'))})}if(kind==='foyer'){const visible=new Set(data.getAll('visible').map(String)),keys=['capacity','schedule','focus','context','next-hour'];store.settings('living',{hiddenWidgets:keys.filter(key=>!visible.has(key))})}close();refresh();window.dispatchEvent(new Event('katos:v6-refresh'))}
function moveFoyer(key,direction){const settings=state().living.settings,keys=arrangedWidgets(['capacity','schedule','focus','context','next-hour'],settings).map(row=>row.key),from=keys.indexOf(key),to=from+(direction==='up'?-1:1);if(from<0||to<0||to>=keys.length)return;[keys[from],keys[to]]=[keys[to],keys[from]];store.settings('living',{foyerOrder:keys});arrangeFoyer();refresh()}
function mutate(kind,id,operation){const collection={chapter:'chapters',milestone:'milestones',pin:'pins'}[kind],record=state().living[collection].find(row=>row.id===id);if(!record)return;if(operation==='archive')store.archive('living',collection,id,!record.archivedAt);if(operation==='delete'&&confirm('Delete this record permanently? Linked source records will not be changed.'))store.remove('living',collection,id);close();refresh()}
function openAction(name,id,target){if(name==='chapter-add')return chapterForm();if(name==='chapter-edit')return chapterForm(state().living.chapters.find(row=>row.id===id)||{});if(name==='milestone-add')return milestoneForm();if(name==='milestone-edit')return milestoneForm(state().living.milestones.find(row=>row.id===id)||{});if(name==='pin-add')return pinForm();if(name==='pin-edit')return pinForm(state().living.pins.find(row=>row.id===id)||{});if(name==='kingdom')return kingdomPopup();if(name==='living-archive')return archiveManager();if(name==='foyer-arrange')return arrangeFoyer();if(name==='foyer-move')return moveFoyer(id,target.dataset.direction);const match=name.match(/^(chapter|milestone|pin)-(archive|delete)$/);if(match)return mutate(match[1],id,match[2])}

export function installLivingPalace(root){app=root;app.addEventListener('click',event=>{const closeButton=event.target.closest('[data-living-close]');if(closeButton||event.target.matches('[data-living-modal]')){event.preventDefault();close();return}const action=event.target.closest('[data-living-action]');if(action){event.preventDefault();openAction(action.dataset.livingAction,action.dataset.id,action);return}const context=event.target.closest('[data-context-mode]');if(context){const map={Study:'focused',Delivery:'determined','Bed Mode':'sleepy'};if(map[context.dataset.contextMode])setTimeout(()=>window.dispatchEvent(new CustomEvent('katos:mochini-state',{detail:{mood:map[context.dataset.contextMode],duration:1800,open:false}})),0)}const complete=event.target.closest('[data-daily-action="complete"]');if(complete)setTimeout(()=>window.dispatchEvent(new CustomEvent('katos:mochini-state',{detail:{mood:'proud',line:'That one was real. Tiny victory dance approved.',duration:1800,open:false}})),0)},true);app.addEventListener('submit',event=>{const form=event.target.closest('[data-living-form]');if(form){event.preventDefault();saveForm(form);return}const wish=event.target.closest('[data-room-form="wish"]');if(wish&&text(new FormData(wish).get('status'))==='Achieved')setTimeout(()=>window.dispatchEvent(new CustomEvent('katos:mochini-state',{detail:{mood:'proud',line:'A real wish became real life. Future Kat gets to keep that.',duration:2200,open:false}})),0)},true);document.addEventListener('keydown',event=>{if(event.key==='Escape'&&app.querySelector('[data-living-modal]'))close()});window.addEventListener('storage',refresh)}
