import{normalizeMochiniLife,mochiniAutonomy,mochiniBerry,mochiniPoke,BERRY_LIMIT,MOCHINI_MOODS}from'../v5/mochini-life.js?v=7.4.1-mood-layers';
import{canonicalAutonomousLife,mergeReactionSideEffects}from'../v5/mochini-state-core.js?v=7.4.1-mood-layers';
import{legacyFaceFallback,setMoodFace}from'../v5/mochini-face-manifest.js?v=6.6.1-v6-assets';
import{blinkFrame,clearEventReaction,clearManualMood,createMochiniLayers,displayLife,displayMood,publicMoodState,setAutonomousMood,setEventReaction,setManualMood}from'./mochini-layers.js?v=6.6.0-living-palace';

const KEYS=['sm_v5_data','sm_v4_beta'],ROOT_ID='katos-mochini-companion';
const obj=value=>value&&typeof value==='object'&&!Array.isArray(value)?value:{};
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const since=stamp=>{const value=Date.parse(stamp||'');return Number.isFinite(value)?Date.now()-value:Infinity};
const reduced=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;
let root=null,layers=null,open=false,eventTimer=null,blinkTimer=null,tickTimer=null,blinking=false,lastRoom='';

function unwrap(container){let value=container;for(let i=0;i<3&&value?.data&&typeof value.data==='object'&&!Array.isArray(value.data);i++)value=value.data;return value}
function parse(key){try{const container=JSON.parse(localStorage.getItem(key)||'null'),state=unwrap(container);return state&&typeof state==='object'?{key,container,state}:null}catch{return null}}
function lifeFrom(state){return state?.v4?.mochiniLife||state?.mochini?.life||state?.mochini||{}}
function storedLife(){const source=KEYS.map(parse).find(value=>value?.state);return normalizeMochiniLife(source?lifeFrom(source.state):{})}
function writeAutonomous(reason='autonomy'){
 const life=canonicalAutonomousLife(layers.autonomousLife,MOCHINI_MOODS),now=new Date().toISOString();let wrote=false;
 for(const key of KEYS){const record=parse(key);if(!record)continue;const state=record.state;if(state.v4&&typeof state.v4==='object')state.v4.mochiniLife=life;else if(state.mochini?.life&&typeof state.mochini.life==='object')state.mochini.life=life;else state.mochini={...obj(state.mochini),life};state.meta={...obj(state.meta),updatedAt:now};state.__smUpdatedAt=now;try{localStorage.setItem(key,JSON.stringify(record.container));wrote=true}catch{}}
 if(wrote)window.dispatchEvent(new CustomEvent('katos:local-change',{detail:{source:`v6-mochini-${reason}`}}));
}

function roomId(){return document.querySelector('.v6-command-room')?.dataset.v6Room||document.querySelector('.nav-btn.active[data-view]')?.dataset.view||'home'}
function contextFor(room=roomId()){return({'rose-garden':'hobbies','moon-garden':'home','love-letters':'home','wishing-tower':'growth',study:'study',boss:'work',money:'money',time:'schedule',daily:'daily',archive:'archive','royal-archives':'archive',settings:'settings',mochini:'mochini'})[room]||'home'}
function sceneFor(life){const map={'tucked-in':['🛏️','sleeping'],'study-book':['📖','studying'],'car-ride':['🚗','driving'],clipboard:['📋','working'],'money-check':['🧾','money'],calendar:['🗓️','calendar'],plant:['🪴','growth'],notes:['✏️','notes'],'memory-box':['📦','archive'],checklist:['🍓✓','daily'],'berry-coma':['🍓💤','sleeping'],'eating-berries':['🍓','berries'],princessing:['👑','princessing']};return map[life.currentActivityId]||map.princessing}
const moodLabel=mood=>String(mood||'content').replace(/-/g,' ').replace(/^./,letter=>letter.toUpperCase());
const moodOptions=()=>['<option value="">Autonomous</option>',...MOCHINI_MOODS.map(mood=>`<option value="${esc(mood)}">${esc(moodLabel(mood))}</option>`)].join('');

function markup(life){const[prop,scene]=sceneFor(life);return`<aside id="${ROOT_ID}" class="mochini-companion scene-${scene}" data-mc-root data-mood="${esc(life.mood)}"><div class="mc-bubble" data-mc-bubble role="dialog" aria-label="Mochini Concierge"><button class="mc-bubble-close" type="button" data-mc-close aria-label="Close Mochini">×</button><div class="mc-bubble-top"><span>${esc(prop)}</span><div><b>What do you need?</b><small>${esc(moodLabel(life.mood))} · ${esc(life.currentActivity)}</small></div></div><p>${esc(life.currentLine)}</p><div class="mc-concierge" aria-label="Mochini Concierge choices"><button type="button" data-mc-concierge="right-now">🌸 What do I do?</button><button type="button" data-mc-concierge="kitchen">🍽 Meal prep</button><button type="button" data-mc-concierge="overwhelmed">🧹 I’m overwhelmed</button><button type="button" data-mc-concierge="leaving">🚪 Leaving soon</button><button type="button" data-mc-concierge="no-energy">🫧 No energy</button><button type="button" data-mc-concierge="brain">🧠 Brain dump</button><button type="button" data-mc-concierge="bored">🎲 I’m bored</button><button type="button" data-mc-concierge="where">📦 Where is it?</button><button type="button" data-mc-concierge="buy">🛒 Buy something</button><button type="button" data-mc-concierge="shutdown">🌙 Close the day</button></div><details class="mc-mood-settings"><summary>Mood & care</summary><label class="mc-mood-control"><span data-mc-mode>${life.displayMode==='manual'?'Manual mood':'Autonomous mood'}</span><select data-mc-manual-mood aria-label="Temporarily choose Mochini's mood">${moodOptions()}</select></label><div class="mc-actions"><button type="button" data-mc-forgetting>What am I forgetting?</button><button type="button" data-mc-action="poke">👉 Poke</button><button type="button" data-mc-action="berry">🍓 Berry</button></div></details></div><button class="mc-body" type="button" data-mc-toggle aria-label="Open Mochini Concierge"><span class="mc-scene-prop" aria-hidden="true">${esc(prop)}</span><img class="mc-art" data-mc-art src="${legacyFaceFallback(life.mood)}" alt="Mochini, your tiny strawberry-princess companion" decoding="async"><span class="mc-mood-chip">${esc(moodLabel(life.mood))}</span></button></aside>`}
function ensure(){if(!layers){layers=createMochiniLayers(storedLife(),MOCHINI_MOODS);writeAutonomous('legacy-migration')}root=document.getElementById(ROOT_ID);if(!root){document.body.insertAdjacentHTML('beforeend',markup(displayLife(layers)));root=document.getElementById(ROOT_ID)}return root}
function broadcast(life){window.dispatchEvent(new CustomEvent('katos:mochini-display',{detail:{...life,...publicMoodState(layers)}}))}
function sync(){ensure();const life=displayLife(layers),[prop,scene]=sceneFor(life);root.className=`mochini-companion scene-${scene} ${roomId()==='mochini'&&!open?'is-hidden':''}`;root.dataset.mood=life.mood;root.dataset.displayMode=life.displayMode;const bubble=root.querySelector('[data-mc-bubble]');bubble?.classList.toggle('is-open',open);const top=bubble?.querySelector('.mc-bubble-top');if(top)top.innerHTML=`<span>${esc(prop)}</span><div><b>${esc(moodLabel(life.mood))}</b><small>${esc(life.currentActivity)}</small></div>`;const copy=bubble?.querySelector('p');if(copy)copy.textContent=life.currentLine;const select=bubble?.querySelector('[data-mc-manual-mood]');if(select)select.value=layers.manualMood||'';const mode=bubble?.querySelector('[data-mc-mode]');if(mode)mode.textContent=life.displayMode==='event'?'Event reaction':life.displayMode==='manual'?'Manual mood':'Autonomous mood';const berry=bubble?.querySelector('[data-mc-action="berry"]');if(berry){berry.disabled=Number(layers.autonomousLife.berriesFedToday)>=BERRY_LIMIT;berry.textContent=berry.disabled?'🍓 Full':'🍓 Berry'}const chip=root.querySelector('.mc-mood-chip');if(chip)chip.textContent=moodLabel(life.mood);const body=root.querySelector('[data-mc-toggle]');body?.setAttribute('aria-label',`Mochini is ${life.mood} and ${life.currentActivity}`);if(!blinking)setMoodFace(root.querySelector('[data-mc-art]'),life.mood);broadcast(life)}

function react(detail={},duration=1800){clearTimeout(eventTimer);layers=setEventReaction(layers,detail,MOCHINI_MOODS);const id=layers.eventId;if(!layers.eventReaction)return;if(detail.open===true)open=true;sync();eventTimer=setTimeout(()=>{layers=clearEventReaction(layers,id);sync()},Math.max(300,Number(detail.duration)||duration))}
function direct(type){const baseline=layers.autonomousLife,result=type==='berry'?mochiniBerry(baseline):mochiniPoke(baseline),persistent=mergeReactionSideEffects(baseline,result.life,MOCHINI_MOODS);layers=setAutonomousMood(layers,persistent,MOCHINI_MOODS);writeAutonomous(type);react({mood:result.mood,line:result.line,activityId:result.life.currentActivityId,activity:result.life.currentActivity,open:true},1800);window.dispatchEvent(new CustomEvent('katos:mochini-reaction',{detail:result}))}
function blink(){if(!root||blinking)return;blinking=true;const frame=blinkFrame(layers),art=root.querySelector('[data-mc-art]');setMoodFace(art,frame.returnMood,{blink:true});setTimeout(()=>{blinking=false;setMoodFace(art,displayMood(layers));sync()},170)}
function scheduleBlink(){clearTimeout(blinkTimer);if(document.hidden||reduced())return;blinkTimer=setTimeout(()=>{blink();scheduleBlink()},3200+Math.random()*3600)}
function scheduleTick(){clearTimeout(tickTimer);if(document.hidden)return;tickTimer=setTimeout(()=>tick(),90_000+Math.random()*180_000)}
function tick(force=false){const life=layers.autonomousLife;if(!force&&since(life.lastAutonomyAt)<90_000)return scheduleTick();const result=mochiniAutonomy(life,contextFor());if(result.accepted){layers=setAutonomousMood(layers,result.life,MOCHINI_MOODS);writeAutonomous('autonomy')}sync();scheduleTick()}

document.addEventListener('click',event=>{const legacy=event.target.closest?.('[data-mochini-action]');if(legacy&&['poke','berry'].includes(legacy.dataset.mochiniAction)){event.preventDefault();event.stopImmediatePropagation();direct(legacy.dataset.mochiniAction);return}const toggle=event.target.closest?.('[data-mc-toggle]');if(toggle){open=!open;sync();return}if(event.target.closest?.('[data-mc-close]')){open=false;sync();return}if(event.target.closest?.('[data-mc-forgetting]')){open=false;sync();document.querySelector('[data-smart-action="hub"]')?.click();return}const concierge=event.target.closest?.('[data-mc-concierge]');if(concierge){const choice=concierge.dataset.mcConcierge,navigation={'right-now':'home',kitchen:'royal-kitchen',bored:'hobbies',where:'royal-archives',shutdown:'daily'},actions={overwhelmed:'reset-manager',leaving:'pack-manager','no-energy':'energy',brain:'brain',buy:'inventory-manager'};open=false;sync();if(navigation[choice])window.dispatchEvent(new CustomEvent('katos:v6-navigate',{detail:{id:navigation[choice]}}));else{const action=actions[choice],button=action&&document.querySelector(`[data-smart-action="${action}"]`);button?.click()}return}const action=event.target.closest?.('[data-mc-action]');if(action){direct(action.dataset.mcAction);return}},true);
document.addEventListener('change',event=>{const select=event.target.closest?.('[data-mc-manual-mood]');if(!select)return;layers=select.value?setManualMood(layers,select.value,MOCHINI_MOODS,{line:`Manual ${moodLabel(select.value).toLowerCase()} mood is temporary. Autonomous Mochini is still living underneath.`}):clearManualMood(layers);sync()},true);
window.addEventListener('katos:rendered',()=>{ensure();const room=roomId();if(room!==lastRoom){lastRoom=room;layers={...layers,autonomousLife:{...layers.autonomousLife,currentContext:contextFor(room)}}}sync()});
window.addEventListener('katos:mochini-open',()=>{ensure();open=true;sync()});
window.addEventListener('katos:mochini-state',event=>react(obj(event.detail),Number(event.detail?.duration)||2200));
window.addEventListener('katos:v6-room-reaction',event=>react(obj(event.detail),Number(event.detail?.duration)||1500));
window.addEventListener('katos:mochini',event=>{const detail=obj(event.detail);if(detail.autonomous&&detail.life){layers=setAutonomousMood(layers,detail.life,MOCHINI_MOODS);writeAutonomous('external-autonomy');sync();return}const reaction={...detail,...obj(detail.life),mood:detail.mood||detail.reaction||detail.expression||detail.life?.mood,line:detail.line||detail.life?.currentLine};if(reaction.mood)react(reaction,Number(detail.duration)||1800)});
document.addEventListener('visibilitychange',()=>{if(document.hidden){clearTimeout(blinkTimer);clearTimeout(tickTimer);return}sync();scheduleBlink();tick(since(layers.autonomousLife.lastAutonomyAt)>90_000)});
window.addEventListener('focus',()=>{sync();if(since(layers.autonomousLife.lastAutonomyAt)>120_000)tick(true)});

ensure();sync();scheduleBlink();setTimeout(()=>tick(since(layers.autonomousLife.lastAutonomyAt)>240_000),1200);
window.KatOSV6Mochini={snapshot:()=>publicMoodState(layers),setAutonomous:mood=>{layers=setAutonomousMood(layers,{...layers.autonomousLife,mood,autonomousMood:mood,lastAutonomyAt:new Date().toISOString()},MOCHINI_MOODS);writeAutonomous('qa-autonomy');sync();return publicMoodState(layers)},setManual:mood=>{layers=mood?setManualMood(layers,mood,MOCHINI_MOODS):clearManualMood(layers);sync();return publicMoodState(layers)},react:(mood,duration=600)=>{react({mood,open:false},duration);return publicMoodState(layers)},blink:()=>blink(),open:()=>{open=true;sync();return publicMoodState(layers)}};
