import test from'node:test';
import assert from'node:assert/strict';
import{readFile}from'node:fs/promises';
import{createRoomStore,kitchenWeekProposal,generateKitchenGroceries,scaleKitchenIngredients}from'./room-store.js';

class MemoryStorage{constructor(){this.data=new Map}getItem(key){return this.data.get(key)||null}setItem(key,value){this.data.set(key,String(value))}}
const files=async(...names)=>Promise.all(names.map(name=>readFile(new URL(name,import.meta.url),'utf8')));

test('Batch 1 rooms use separate Palace compositions without changing the Foyer renderer',async()=>{const[duties,calendar,career,kitchen,command,styles,parity]=await files('./rooms/royal-duties.js','./rooms/royal-calendar.js','./rooms/crown-career.js','./rooms/royal-kitchen.js','./command-shell.js','./palace-room-system.css','./palace-batch1-parity.css');assert.match(duties,/Today’s Plan/);assert.match(duties,/Daily Rituals/);assert.match(duties,/Medication & Wellness/);assert.match(calendar,/v6-calendar-grid/);assert.match(calendar,/v6-calendar-track/);assert.match(calendar,/Leave By/);assert.match(career,/v6-career-top/);assert.match(career,/Next Session/);assert.match(career,/Today’s Work Schedule/);assert.match(kitchen,/This Week’s Meal Plan/);assert.match(kitchen,/kitchenWeekBoard/);assert.match(command,/renderRoyalKitchen/);assert.match(styles,/data-v6-room="royal-kitchen"/);assert.match(parity,/v6-carriage-parity/);assert.doesNotMatch(parity,/data-v6-room="home"\][^{]*\{/)});

test('Royal Kitchen preserves records and Build My Week never saves a proposal automatically',async()=>{const store=createRoomStore(new MemoryStorage),recipe=store.create('kitchen','recipes',{name:'Rice Bowl',mealType:'Dinner',servings:2,ingredients:[{amount:'1',unit:'cup',name:'Rice'},{amount:'2',unit:'tbsp',name:'Sauce'}],tags:['low effort']});const before=store.load().kitchen.mealPlans.length,proposal=kitchenWeekProposal(store.load().kitchen,{dinners:3,tags:'low effort'});assert.equal(before,0);assert.equal(store.load().kitchen.mealPlans.length,0);assert.equal(proposal.length,3);assert.ok(proposal.every(row=>row.recipeId===recipe.id));store.create('kitchen','mealPlans',{recipeId:recipe.id,date:'2026-10-02',servings:4,mealType:'Dinner'});const groceries=generateKitchenGroceries(store.load().kitchen);assert.deepEqual(groceries.map(row=>[row.ingredient,row.amount]),[['Rice',2],['Sauce',4]]);assert.equal(scaleKitchenIngredients(recipe,6)[0].amount,3);const[kitchenSource]=await files('./rooms/royal-kitchen.js');assert.match(kitchenSource,/Build-a-Meal/);assert.match(kitchenSource,/Meal Rotation/)});

test('Mochini Concierge routes to real Palace destinations and tools',async()=>{const[mochini,command,primitives,calendar,parity]=await files('./mochini-living.js','./command-shell.js','./rooms/palace-primitives.js','./rooms/royal-calendar.js','./palace-batch1-parity.css');for(const route of['right-now','kitchen','overwhelmed','leaving','no-energy','brain','bored','where','buy','shutdown'])assert.match(mochini,new RegExp(`data-mc-concierge="${route}"`));assert.match(mochini,/kitchen:'royal-kitchen'/);assert.match(mochini,/katos:mochini-minimize/);assert.match(parity,/is-minimized/);assert.match(command,/katos:v6-navigate/);assert.match(primitives,/prep-manager.*pack-manager/s);assert.match(calendar,/LEAVING CALCULATOR/);assert.match(calendar,/startGettingReady/)});

test('Batch 1 layout remains iPad-responsive and avoids blue theme tokens',async()=>{const[styles,parity]=await files('./palace-room-system.css','./palace-batch1-parity.css');assert.match(styles,/@media\(max-width:900px\)/);assert.match(styles,/@media\(max-width:680px\)/);assert.match(parity,/@media\(max-width:900px\)/);assert.match(parity,/grid-template-columns:43px repeat\(7,minmax\(105px,1fr\)\)/);assert.doesNotMatch(`${styles}\n${parity}`,/#[0-9a-f]{0,4}(?:00f|06f|3b82f6)|\bblue\b/i)});

test('Royal Calendar gives overlapping events separate tappable lanes',async()=>{const[calendar,parity]=await files('./rooms/royal-calendar.js','./palace-batch1-parity.css');assert.match(calendar,/function collisionLayout\(items\)/);assert.match(calendar,/--event-left:\$\{left\}%/);assert.match(calendar,/--event-width:\$\{width\}%/);assert.match(parity,/left:calc\(var\(--event-left,0%\) \+ 3px\)/);assert.match(parity,/width:calc\(var\(--event-width,100%\) - 6px\)/)});
