import{activeRecords,newRecord}from'./room-store.js?v=6.5.0-smart-palace-stage3';

const list=value=>Array.isArray(value)?value:[];
const text=value=>String(value??'').trim();
const clone=value=>JSON.parse(JSON.stringify(value));
const dayMs=86400000;
export const BRAIN_DESTINATIONS=['Royal Duties','Royal Calendar','Bell Tower','Crown & Career','Scholar’s Tower','Royal Treasury','Rose Garden','Moon Garden','Love Letters','Wishing Tower','Royal Archives'];
export const ENERGY_TAGS=['Tiny energy','Medium energy','Big brain','Leaving the house'];

export function suggestBrainDestination(line){const value=text(line).toLowerCase();if(/date idea|jordan|gift|tell (him|her|them)|relationship/.test(value))return'Love Letters';if(/watch|movie|anime|game|hobby|fun|recipe to try|cosplay/.test(value))return'Rose Garden';if(/period|cycle|mood|energy|symptom|experiment/.test(value))return'Moon Garden';if(/someday|future|dream|move to|trip to|wish/.test(value))return'Wishing Tower';if(/study|chapter|course|class|assignment|exam/.test(value))return'Scholar’s Tower';if(/doordash|amazon flex|flex block|rbt|client|work shift/.test(value))return'Crown & Career';if(/bill|budget|paycheck|money|bank|savings/.test(value))return'Royal Treasury';if(/remind|ping me|remember to/.test(value))return'Bell Tower';if(/at \d|appointment|calendar|friday|monday|tuesday|wednesday|thursday|saturday|sunday/.test(value))return'Royal Calendar';if(/reference|serial|measurement|printer|car info|formula|how to/.test(value))return'Royal Archives';return'Royal Duties'}
export function brainDumpProposals(raw){return text(raw).split(/\n+/).map(text).filter(Boolean).map(line=>({line,destination:suggestBrainDestination(line)}))}

export function applyBrainRoutes(store,proposals,adapter=()=>({ok:true})){const saved=[];for(const proposal of list(proposals)){if(!BRAIN_DESTINATIONS.includes(proposal.destination))throw new Error('Choose a valid destination for every entry.');let result={ok:true};const fields={source:'Brain Dump',sourceText:proposal.line};if(proposal.destination==='Rose Garden')result=store.create('rose','ideas',{idea:proposal.line,...fields});else if(proposal.destination==='Moon Garden')result=store.create('moon','checkins',{date:new Date().toISOString().slice(0,10),note:proposal.line,...fields});else if(proposal.destination==='Love Letters')result=store.create('love','topics',{title:proposal.line,kind:'Other',private:true,...fields});else if(proposal.destination==='Wishing Tower')result=store.create('wishing','plans',{title:proposal.line,horizon:'Someday',status:'Dreaming',category:'Other',milestones:[],...fields});else if(proposal.destination==='Royal Archives')result=store.create('smart','wiki',{title:proposal.line,category:'Inbox',content:'',tags:'brain dump',pinned:false,...fields});else result=adapter(proposal.destination,proposal.line);if(result?.ok===false)throw new Error(result.error||`Could not save ${proposal.line}`);saved.push({line:proposal.line,destination:proposal.destination,id:result?.id||result?.result?.id||''})}for(const row of saved)store.create('smart','brainRoutes',row);return saved}

export function capacityMode(checkin,override=''){if(['Gentle','Normal','High Capacity'].includes(override))return{mode:override,source:'Manual override'};if(!checkin)return{mode:'Normal',source:'No check-in yet'};const physical=Number(checkin.physicalEnergy)||3,mental=Number(checkin.mentalEnergy)||3,focus=Number(checkin.focus)||3,stress=Number(checkin.stress)||3,social=Number(checkin.socialBattery)||3,score=(physical+mental+focus+social+(6-stress))/5;if(score<=2.35)return{mode:'Gentle',score,source:'Latest capacity check-in'};if(score>=4)return{mode:'High Capacity',score,source:'Latest capacity check-in'};return{mode:'Normal',score,source:'Latest capacity check-in'}}
const energyRank=value=>({'tiny energy':1,tiny:1,'medium energy':2,medium:2,'big brain':4,'leaving the house':3,leaving:3}[text(value).toLowerCase()]||2);
export function tasksForCapacity(tasks,mode='Normal'){const limit=mode==='Gentle'?1:mode==='High Capacity'?4:2;return list(tasks).filter(row=>!row.done&&!row.completed&&!row.archivedAt&&energyRank(row.energy||row.energyTag)<=limit).sort((a,b)=>(Number(a.minutes)||30)-(Number(b.minutes)||30))}

export function upsertTaskMeta(store,taskId,fields={}){const state=store.load(),existing=state.smart.taskMeta.find(row=>row.taskId===taskId);return existing?store.update('smart','taskMeta',existing.id,fields):store.create('smart','taskMeta',{taskId,energyTag:'Medium energy',substeps:[],friction:[],durationHistory:[],...fields})}
export function addTaskSubsteps(store,taskId,steps){const state=store.load(),meta=state.smart.taskMeta.find(row=>row.taskId===taskId),next=[...list(meta?.substeps),...list(steps).map(label=>newRecord({label:text(label),done:false})).filter(row=>row.label)];return upsertTaskMeta(store,taskId,{substeps:next})}
export function recordFriction(store,taskId,reason,note=''){const state=store.load(),meta=state.smart.taskMeta.find(row=>row.taskId===taskId),friction=[...list(meta?.friction),newRecord({reason,note,date:new Date().toISOString().slice(0,10)})];return upsertTaskMeta(store,taskId,{friction})}
export function frictionPatterns(taskMeta,min=3){const counts={};for(const meta of list(taskMeta))for(const row of list(meta.friction))counts[row.reason]=(counts[row.reason]||0)+1;return Object.entries(counts).filter(([,count])=>count>=min).sort((a,b)=>b[1]-a[1]).map(([reason,count])=>({reason,count,text:`In your recent logs, ${reason.toLowerCase()} has shown up as friction ${count} times.`}))}
export function logDuration(store,taskId,estimated,actual,kind='task'){const state=store.load(),meta=state.smart.taskMeta.find(row=>row.taskId===taskId),durationHistory=[...list(meta?.durationHistory),newRecord({kind,estimated:Number(estimated)||0,actual:Number(actual)||0,date:new Date().toISOString().slice(0,10)})].slice(-40);return upsertTaskMeta(store,taskId,{durationHistory})}
export function realityInsight(history,estimate){const values=list(history).map(row=>Number(row.actual)).filter(value=>value>0);if(values.length<3)return{ready:false,samples:values.length};return{ready:true,samples:values.length,estimated:Number(estimate)||0,average:Math.round(values.reduce((sum,value)=>sum+value,0)/values.length)}}

export function buildNextHour({available=60,capacity='Normal',context='Home',items=[]}){let remaining=Math.max(5,Number(available)||60);const eligible=list(items).filter(row=>{const contexts=list(row.contexts).map(text);return(!contexts.length||contexts.includes(context)||contexts.includes('Other'))&&tasksForCapacity([{...row,done:false,energy:row.energy}],capacity).length}).sort((a,b)=>(Number(b.priority)||0)-(Number(a.priority)||0)||(Number(a.duration)||15)-(Number(b.duration)||15)),chosen=[];for(const row of eligible){const duration=Math.max(5,Number(row.duration)||15);if(duration<=remaining&&chosen.length<4){chosen.push({...clone(row),duration});remaining-=duration}}return{available:Number(available)||60,capacity,context,items:chosen,total:chosen.reduce((sum,row)=>sum+row.duration,0),openMinutes:remaining,accepted:false}}
export function recoveryEssentials(items){return list(items).filter(row=>['work','bill','medication','care','schedule','food','hygiene','reset'].includes(row.kind)&&row.essential!==false).sort((a,b)=>(Number(b.priority)||0)-(Number(a.priority)||0)).slice(0,8)}

export function nextMaintenanceDate(lastDone,frequencyDays){if(!lastDone)return'';const date=new Date(`${lastDone}T12:00:00`);date.setDate(date.getDate()+Math.max(1,Number(frequencyDays)||30));return date.toISOString().slice(0,10)}
export function maintenanceDue(rows,date=new Date().toISOString().slice(0,10)){return activeRecords(rows).filter(row=>row.nextSuggestedDate&&row.nextSuggestedDate<=date).sort((a,b)=>a.nextSuggestedDate.localeCompare(b.nextSuggestedDate))}
export function restockList(rows){return activeRecords(rows).filter(row=>['need soon','out'].includes(text(row.state).toLowerCase())).sort((a,b)=>text(a.state).toLowerCase()==='out'?-1:text(b.state).toLowerCase()==='out'?1:text(a.item).localeCompare(text(b.item)))}

export function flexMetrics(route){const gross=Number(route.actualEarnings)||0,expenses=['gas','food','tolls','otherExpenses'].reduce((sum,key)=>sum+(Number(route[key])||0),0),mileage=Math.max(0,(Number(route.endingOdometer)||0)-(Number(route.startingOdometer)||0)),minutes=Number(route.actualDuration)||minutesBetween(route.actualStart,route.actualEnd),hours=minutes/60,packages=Number(route.packages)||0,stops=Number(route.stops)||0;return{gross,totalExpenses:expenses,net:gross-expenses,mileage,durationMinutes:minutes,profitPerHour:hours?(gross-expenses)/hours:0,profitPerMile:mileage?(gross-expenses)/mileage:0,packagesPerHour:hours?packages/hours:0,stopsPerHour:hours?stops/hours:0,packages,stops}}
function minutesBetween(start,end){if(!/^\d{1,2}:\d{2}$/.test(text(start))||!/^\d{1,2}:\d{2}$/.test(text(end)))return 0;const toMin=value=>{const[h,m]=value.split(':').map(Number);return h*60+m},a=toMin(start),b=toMin(end);return b>=a?b-a:b+1440-a}
export function adaptiveGigTargets({remaining,targetDate,today=new Date().toISOString().slice(0,10),scheduled={},overrides={}}){let days=Math.max(1,Math.ceil((new Date(`${targetDate}T12:00:00`)-new Date(`${today}T12:00:00`))/dayMs)+1),left=Math.max(0,Number(remaining)||0),rows=[];for(let index=0;index<days;index++){const date=new Date(`${today}T12:00:00`);date.setDate(date.getDate()+index);const key=date.toISOString().slice(0,10),fixed=Number(scheduled[key])||0,manual=overrides[key];const suggested=manual==null?Math.max(0,Math.ceil((left-fixed)/(days-index))):Math.max(0,Number(manual)||0);rows.push({date:key,scheduled:fixed,suggested,editable:manual!=null});left=Math.max(0,left-fixed-suggested)}return{remaining:Number(remaining)||0,rows,totalSuggested:rows.reduce((sum,row)=>sum+row.scheduled+row.suggested,0)}}

export function linkCalendarRecord(store,source,createEvent){const state=store.load(),sourceKey=`${source.room}:${source.collection}:${source.id}`,existing=activeRecords(state.smart.calendarLinks).find(row=>row.sourceKey===sourceKey);if(existing)return{created:false,link:existing};const event=createEvent(source);if(event?.ok===false)return event;const link=store.create('smart','calendarLinks',{sourceKey,sourceRoom:source.room,sourceCollection:source.collection,sourceId:source.id,eventId:event?.id||event?.result?.id||'',eventDate:source.date||source.targetDate||''});return{created:true,link}}
export function linkTreasuryGoal(store,planId,goalId){return store.update('wishing','plans',planId,{treasuryGoalId:goalId})}

export function searchWiki(rows,query=''){const needle=text(query).toLowerCase();return activeRecords(rows).filter(row=>!needle||`${row.title} ${row.category} ${row.content} ${row.tags}`.toLowerCase().includes(needle)).sort((a,b)=>Number(Boolean(b.pinned))-Number(Boolean(a.pinned))||text(a.title).localeCompare(text(b.title)))}
export function skillAvailable(skill,skills){return!skill.prerequisiteId||list(skills).some(row=>row.id===skill.prerequisiteId&&row.status==='Comfortable')}

export function patternObservations(state){const observations=[],friction=frictionPatterns(state?.smart?.taskMeta);observations.push(...friction.map(row=>row.text));const checkins=activeRecords(state?.moon?.checkins);if(checkins.length>=4){const low=checkins.filter(row=>(Number(row.physicalEnergy)||3)<=2),high=checkins.filter(row=>(Number(row.physicalEnergy)||3)>=4);if(low.length>=2&&high.length>=2){const lowFocus=low.reduce((sum,row)=>sum+(Number(row.focus)||3),0)/low.length,highFocus=high.reduce((sum,row)=>sum+(Number(row.focus)||3),0)/high.length;if(Math.abs(highFocus-lowFocus)>=.75)observations.push('In your recent logs, focus has tended to be lower on lower-physical-energy days. This is an observation, not a cause.')}}const histories=list(state?.smart?.taskMeta).flatMap(row=>list(row.durationHistory));if(histories.length>=3){const average=Math.round(histories.reduce((sum,row)=>sum+Number(row.actual||0),0)/histories.length);observations.push(`Across ${histories.length} recent time logs, actual duration averaged ${average} minutes.`)}return observations.slice(0,5)}
export function whatAmIForgetting(items,max=5){return list(items).filter(row=>row.relevant!==false).sort((a,b)=>(Number(b.urgency)||0)-(Number(a.urgency)||0)).slice(0,max)}
