import test from'node:test';
import assert from'node:assert/strict';
import{createRoomStore,ROOM_SCHEMA_VERSION}from'./room-store.js';
import{brainDumpProposals,applyBrainRoutes,capacityMode,tasksForCapacity,upsertTaskMeta,addTaskSubsteps,recordFriction,frictionPatterns,logDuration,realityInsight,buildNextHour,recoveryEssentials,nextMaintenanceDate,maintenanceDue,restockList,flexMetrics,adaptiveGigTargets,linkCalendarRecord,linkTreasuryGoal,searchWiki,skillAvailable,patternObservations,whatAmIForgetting}from'./smart-store.js';

class MemoryStorage{constructor(seed={}){this.data=new Map(Object.entries(seed))}getItem(key){return this.data.has(key)?this.data.get(key):null}setItem(key,value){this.data.set(key,String(value))}}
const fresh=()=>createRoomStore(new MemoryStorage());

test('Stage 2 and Stage 3 records normalize forward into the versioned Living Palace schema',()=>{const storage=new MemoryStorage({katos_v6_new_rooms_v1:JSON.stringify({schemaVersion:2,rose:{watches:[{id:'show',title:'Severance'}]},moon:{checkins:[]},love:{settings:{privacyMode:true}},wishing:{plans:[{id:'wish',title:'Texas'}]},smart:{settings:{contextMode:'Study'},openLoops:[{id:'loop',title:'Credentialing'}]}})}),state=createRoomStore(storage).load();assert.equal(ROOM_SCHEMA_VERSION,4);assert.equal(state.rose.watches[0].title,'Severance');assert.equal(state.love.settings.privacyMode,true);assert.equal(state.wishing.plans[0].title,'Texas');assert.equal(state.smart.openLoops[0].title,'Credentialing');assert.equal(state.smart.settings.contextMode,'Study');assert.deepEqual(state.living.settings.hiddenWidgets,[]);assert.deepEqual(state.living.chapters,[]);assert.deepEqual(state.bell.reminders,[])});

test('Brain Dump proposes all relevant V6 destinations and saves only approved routes',()=>{const proposed=brainDumpProposals('call dentist\nwatch Severance\nDoorDash Friday 5–9\nstudy Chapter 4\ndate idea: aquarium\nprinter serial reference');assert.deepEqual(proposed.map(row=>row.destination),['Royal Duties','Rose Garden','Crown & Career','Scholar’s Tower','Love Letters','Royal Archives']);const store=fresh(),external=[];applyBrainRoutes(store,[{line:'watch Severance',destination:'Rose Garden'},{line:'call dentist',destination:'Royal Duties'},{line:'move to Texas',destination:'Wishing Tower'}],(destination,line)=>{external.push({destination,line});return{ok:true,id:'external'}});assert.equal(store.load().rose.ideas[0].idea,'watch Severance');assert.equal(store.load().wishing.plans[0].horizon,'Someday');assert.equal(external[0].destination,'Royal Duties');assert.equal(store.load().smart.brainRoutes.length,3)});

test('Open Loops and Decision Dock persist without becoming tasks',()=>{const store=fresh();store.create('smart','openLoops',{title:'Credentialing',state:'Waiting on someone',area:'Career'});store.create('smart','decisions',{question:'Flex or DoorDash?',options:[{name:'Flex',pros:'Known pay'},{name:'DoorDash',pros:'Flexible'}],finalDecision:''});const reloaded=store.load();assert.equal(reloaded.smart.openLoops[0].state,'Waiting on someone');assert.equal(reloaded.smart.decisions[0].options.length,2);assert.equal(reloaded.smart.taskMeta.length,0)});

test('capacity keeps dimensions separate, supports override, and filters existing tasks without mutation',()=>{const checkin={physicalEnergy:2,mentalEnergy:2,focus:2,stress:5,socialBattery:2};assert.equal(capacityMode(checkin).mode,'Gentle');assert.equal(capacityMode(checkin,'High Capacity').mode,'High Capacity');const tasks=[{id:'a',energy:'Tiny energy',minutes:10},{id:'b',energy:'Big brain',minutes:30}],copy=structuredClone(tasks);assert.deepEqual(tasksForCapacity(tasks,'Gentle').map(row=>row.id),['a']);assert.deepEqual(tasks,copy)});

test('task decomposition, friction, and Reality Check remain attached support data',()=>{const store=fresh();upsertTaskMeta(store,'task-1',{energyTag:'Big brain'});addTaskSubsteps(store,'task-1',['Open the form','Find insurance card']);for(let i=0;i<3;i++)recordFriction(store,'task-1','too big');for(const actual of[25,30,32])logDuration(store,'task-1',45,actual);const meta=store.load().smart.taskMeta[0];assert.equal(meta.substeps.length,2);assert.equal(frictionPatterns([meta])[0].reason,'too big');assert.deepEqual(realityInsight(meta.durationHistory,45),{ready:true,samples:3,estimated:45,average:29})});

test('Build My Next Hour never exceeds available time and waits for acceptance',()=>{const plan=buildNextHour({available:30,capacity:'Gentle',context:'Home',items:[{title:'Tiny reset',duration:10,energy:'Tiny energy',contexts:['Home'],priority:7},{title:'Tea',duration:15,energy:'Tiny energy',contexts:['Home'],priority:3},{title:'Huge work',duration:45,energy:'Big brain',contexts:['Home'],priority:9}]});assert.equal(plan.total,25);assert.equal(plan.openMinutes,5);assert.equal(plan.accepted,false);assert.deepEqual(plan.items.map(row=>row.title),['Tiny reset','Tea'])});

test('Recovery Day only selects essentials and does not mutate source rows',()=>{const input=[{title:'Work',kind:'work',priority:9},{title:'Optional project',kind:'project',priority:7},{title:'Food',kind:'food',priority:5}],copy=structuredClone(input);assert.deepEqual(recoveryEssentials(input).map(row=>row.title),['Work','Food']);assert.deepEqual(input,copy)});

test('Reset Recipes, Context Modes, and Prep Packs share the central store',()=>{const store=fresh();store.create('smart','resetRecipes',{name:'Apartment exploded',steps:'Trash\nDishes'});store.create('smart','prepPacks',{name:'RBT Session',items:'Badge\nWater'});store.settings('smart',{contextMode:'Study'});const state=store.load();assert.equal(state.smart.resetRecipes[0].name,'Apartment exploded');assert.equal(state.smart.prepPacks[0].name,'RBT Session');assert.equal(state.smart.settings.contextMode,'Study')});

test('calendar links are explicit, deduplicated, and leave source records alone',()=>{const store=fresh(),source={room:'love',collection:'plans',id:'plan-1',title:'Aquarium',date:'2026-10-02'},events=[];const first=linkCalendarRecord(store,source,row=>{events.push(row);return{ok:true,id:'event-1'}}),second=linkCalendarRecord(store,source,row=>{events.push(row);return{ok:true,id:'event-2'}});assert.equal(first.created,true);assert.equal(second.created,false);assert.equal(events.length,1);assert.equal(store.load().smart.calendarLinks[0].sourceId,'plan-1')});

test('Flex routes keep packages and stops separate and calculate every profitability measure',()=>{const metrics=flexMetrics({actualStart:'10:00',actualEnd:'14:00',startingOdometer:100,endingOdometer:180,packages:41,stops:23,actualEarnings:120,gas:15,food:5,tolls:4,otherExpenses:6});assert.equal(metrics.packages,41);assert.equal(metrics.stops,23);assert.equal(metrics.mileage,80);assert.equal(metrics.totalExpenses,30);assert.equal(metrics.net,90);assert.equal(metrics.profitPerHour,22.5);assert.equal(metrics.profitPerMile,1.125);assert.equal(metrics.packagesPerHour,10.25);assert.equal(metrics.stopsPerHour,5.75)});

test('adaptive gig suggestions redistribute only the remaining amount',()=>{const plan=adaptiveGigTargets({remaining:100,targetDate:'2026-10-02',today:'2026-10-01',scheduled:{'2026-10-01':20}});assert.equal(plan.rows.length,2);assert.equal(plan.rows[0].scheduled,20);assert.equal(plan.totalSuggested,100);const reduced=adaptiveGigTargets({remaining:60,targetDate:'2026-10-02',today:'2026-10-01',scheduled:{}});assert.equal(reduced.totalSuggested,60)});

test('Wishing Tower links an existing Treasury goal without creating transactions',()=>{const store=fresh(),plan=store.create('wishing','plans',{title:'Trip',horizon:'1 Year'});linkTreasuryGoal(store,plan.id,'goal-existing');const state=store.load();assert.equal(state.wishing.plans[0].treasuryGoalId,'goal-existing');assert.equal(state.smart.gigRoutes.length,0)});

test('maintenance and Inventory Lite surface relevant records only',()=>{const due={id:'a',item:'Clean cat fountain',nextSuggestedDate:'2026-09-30'},later={id:'b',item:'Clean car',nextSuggestedDate:'2026-11-01'};assert.equal(nextMaintenanceDate('2026-09-01',29),'2026-09-30');assert.deepEqual(maintenanceDue([due,later],'2026-10-01').map(row=>row.id),['a']);assert.deepEqual(restockList([{id:'1',item:'Litter',state:'out'},{id:'2',item:'Soap',state:'plenty'},{id:'3',item:'Shampoo',state:'need soon'}]).map(row=>row.id),['1','3'])});

test('Skill Trees respect entered prerequisites without claiming competency',()=>{const prerequisite={id:'base',skill:'Basics',status:'Learning'},advanced={id:'advanced',skill:'Advanced',status:'Locked',prerequisiteId:'base'};assert.equal(skillAvailable(advanced,[prerequisite,advanced]),false);prerequisite.status='Comfortable';assert.equal(skillAvailable(advanced,[prerequisite,advanced]),true)});

test('Pattern Lab waits for repeated evidence and uses observational wording',()=>{const sparse={moon:{checkins:[{physicalEnergy:1,focus:1}]},smart:{taskMeta:[]}};assert.equal(patternObservations(sparse).length,0);const repeated={moon:{checkins:[{id:'1',physicalEnergy:1,focus:1},{id:'2',physicalEnergy:2,focus:2},{id:'3',physicalEnergy:4,focus:4},{id:'4',physicalEnergy:5,focus:5}]},smart:{taskMeta:[{friction:[{reason:'leaving house required'},{reason:'leaving house required'},{reason:'leaving house required'}],durationHistory:[]}]}};const patterns=patternObservations(repeated);assert.ok(patterns.some(value=>/In your recent logs/.test(value)));assert.ok(patterns.some(value=>/not a cause/.test(value)))});

test('Royal Archives search prioritizes pinned matches',()=>{const rows=[{id:'a',title:'Printer WiFi',category:'Printer',content:'reset instructions',tags:'office',pinned:false},{id:'b',title:'Apartment measurements',category:'Apartment',content:'living room',tags:'home',pinned:true}];assert.equal(searchWiki(rows,'printer')[0].id,'a');assert.equal(searchWiki(rows,'')[0].id,'b')});

test('What Am I Forgetting returns a short relevance-ranked list',()=>{const rows=Array.from({length:8},(_,index)=>({title:`Item ${index}`,urgency:index,relevant:true}));const result=whatAmIForgetting(rows);assert.equal(result.length,5);assert.equal(result[0].title,'Item 7')});
