import{loadV5Ui,saveV5Ui,saveV5DailyNote,saveV5RoomDetail,saveV5LedgerEntry,saveV5Workspace,updateV5Record,archiveV5Record,restoreV5Record,runV5DailyAction,selectV5DailyShit,runV5WorkAction,selectV5WorkHQ,runV5StudyAction,selectV5StudyNook,runV5MoneyGigAction,selectV5MoneyGig,runV5LifestyleAction,selectV5Lifestyle,snapshotV4,migrateV4ToV5,restoreCloudV4Data,importV4Export}from'./data.js?v=5.5.0-lifestyle';
import{renderBoss}from'./boss.js?v=5.3.0-study-nook';
import{renderStudy}from'./study.js?v=5.3.0-study-nook';
import{renderMoney}from'./money.js?v=5.4.0-money-gig';
import{renderMovement,renderHobbies,renderGrowth}from'./lifestyle-render.js?v=5.5.0-lifestyle';
import{renderRoom,renderDailyNoteModal}from'./rooms.js?v=5.5.0-lifestyle';

const app=document.getElementById('app');
const ui=loadV5Ui();
if(ui.view==='review')ui.view='time';
if(ui.view==='people')ui.view='hobbies';
ui.scheduleView=ui.scheduleView||'day';
ui.moneyLane=ui.moneyLane||'money';
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const titleCase=value=>String(value).replace(/([A-Z])/g,' $1').replace(/^./,letter=>letter.toUpperCase());
function unpackRecord(value){try{return JSON.parse(decodeURIComponent(escape(atob(value))))}catch{return null}}
const RECORD_OPTIONS={status:['planned','active','paused','waiting','in-progress','completed','skipped','canceled','archived'],completed:['No','Yes'],done:['No','Yes'],recurring:['No','Yes'],repeat:['Once','Daily','Weekly','Monthly','Yearly'],recurrence:['once','daily','weekly','monthly','yearly'],priority:['Now','Today','High','Normal','Soon','Whenever'],kind:['income','expense','transfer','refund','fee','adjustment','payment','other'],type:['Appointment','Birthday','Work','School','Reminder','Personal','Other'],category:['Rent','Bills','Food','Transportation','Work','Fun','Savings','Subscriptions','Other'],setting:['Home','Clinic','School','Community','Telehealth','Other'],schedule:['Monday–Friday','Monday–Thursday','Weekdays','Weekends','Custom']};
const technicalKey=key=>['id','createdAt','updatedAt','sourceId','sourceType','externalId','linkedDebtId','linkedTransferId','paymentTransactionId','billInstanceId'].includes(key);
function optionControl(key,value,path){let values=RECORD_OPTIONS[key];const state=snapshotV4().state||{};if(['account','accountId','toAccount','toAccountId'].includes(key))values=(state.money?.hq?.accounts||[]).map(row=>row.name||row.id);if(key==='supervisor'||key==='supervisorId')values=(state.work?.hq?.supervisors||[]).map(row=>row.code||row.name||row.id);if(!values?.length)return'';if(typeof value==='boolean')return`<select data-record-key="${esc(key)}" data-record-type="boolean"><option value="false"${!value?' selected':''}>No</option><option value="true"${value?' selected':''}>Yes</option></select>`;const current=String(value??''),choices=[...new Set([current,...values].filter(Boolean))];return`<select data-record-key="${esc(key)}" data-record-type="text">${choices.map(choice=>`<option value="${esc(choice)}"${choice===current?' selected':''}>${esc(titleCase(choice))}</option>`).join('')}</select>`}
function recordField(path,key,value){if(technicalKey(key))return'';const label=esc(titleCase(key)),known=optionControl(key,value,path);if(known)return`<label class="daily-field"><span>${label}</span>${known}</label>`;if(Array.isArray(value)||value&&typeof value==='object'){const readable=Array.isArray(value)?value.map(item=>typeof item==='object'?(item.label||item.title||item.name||'Saved item'):item).join(', '):Object.entries(value).map(([name,item])=>`${titleCase(name)}: ${typeof item==='object'?'Saved details':item}`).join(' · ');return`<label class="daily-field daily-field-wide"><span>${label}</span><textarea rows="2" disabled>${esc(readable)}</textarea></label>`}const isDate=/(^date$|Date$|^due$)/.test(key)&&!/(created|updated|At$)/.test(key),isTime=/(^time$|Time$)/.test(key),isNumber=typeof value==='number',isMoney=isNumber&&/(amount|balance|pay|rate|limit|minimum|apr|price|cost)/i.test(key),type=isDate?'date':isTime?'time':isNumber?'number':'text';return`<label class="daily-field"><span>${label}</span><input data-record-key="${esc(key)}" data-record-type="${isNumber?'number':'text'}" type="${type}"${isNumber?` step="${isMoney?'0.01':'1'}" inputmode="decimal"`:''} value="${esc(value??'')}"></label>`}
function openRecordEditor(path,record){if(!record?.id)return;app.querySelector('[data-record-editor]')?.remove();const fields=Object.entries(record).map(([key,value])=>recordField(path,key,value)).join('');app.insertAdjacentHTML('beforeend',`<div class="detail-modal-backdrop" data-record-editor><section class="detail-modal compact-record-modal" role="dialog" aria-modal="true" aria-labelledby="record-editor-title"><div class="detail-modal-head"><div><div class="ey">🍓 SAVED ENTRY</div><h2 id="record-editor-title">${esc(record.title||record.text||record.name||record.label||'Saved entry')}</h2><p>Edit the useful details here. Technical links stay safely tucked away.</p></div><button type="button" class="detail-modal-close" data-record-close aria-label="Close entry editor">×</button></div><form data-record-edit data-record-path="${esc(path)}" data-record-id="${esc(record.id)}"><div class="room-detail-fields">${fields}</div><div class="button-row daily-actions"><button type="submit" class="btn primary">🍓 Save changes</button><button type="button" class="btn soft" data-record-archive>📦 Archive entry</button><button type="button" class="btn soft" data-record-close>Close</button></div></form></section></div>`)}
function recordFormValues(form){const values={};form.querySelectorAll('[data-record-key]').forEach(input=>{const key=input.dataset.recordKey,type=input.dataset.recordType,value=input.value;if(type==='json'){try{values[key]=JSON.parse(value)}catch{throw new Error(`${titleCase(key)} needs valid JSON.`)}}else if(type==='boolean')values[key]=value==='true';else if(type==='number')values[key]=value===''?0:Number(value);else values[key]=value});return values}

const NAV=[['',[
  ['home','🌸','Home'],['time','🗓️','Schedule'],['boss','💼','Boss Bitch'],['money','☕','Money Café'],['daily','🍓','Daily Shit'],['mochini','🍡','Mochini'],
  ['motion','🌿','Get movin'],['hobbies','🎨','Hobby Shelf'],
  ['study','🎓','Study Nook'],
  ['growth','🌱','Growth'],['dump','🧠','Brain dump'],['archive','📦','Memory Box'],['settings','⚙️','Settings']
]]];
const LABELS=Object.fromEntries(NAV.flatMap(([,items])=>items.map(([id,,label])=>[id,label])));

function sidebar(){const items=NAV.flatMap(([,groupItems])=>groupItems);return`<aside class="sidebar ${ui.sidebarOpen?'open':''}"><div class="brand"><div class="brand-row"><div class="berry">🍓</div><div><h1>KatOS V5</h1><div class="scribble">pretty, smart, and nosy enough</div></div></div><span class="build">KatOS V5</span></div><nav class="nav">${items.map(([id,icon,label])=>`<button type="button" class="nav-btn ${ui.view===id?'active':''}" data-view="${id}"><span class="nav-icon">${icon}</span><span>${label}</span></button>`).join('')}</nav><div class="sidebar-foot"><b>KatOS V5</b><br>Your personal planner. 🍓</div></aside>${ui.sidebarOpen?'<button type="button" class="sidebar-backdrop" data-action="close-sidebar" aria-label="Close navigation"></button>':''}`}
function topbar(){return`<header class="topbar"><button type="button" class="btn menu" data-action="toggle-sidebar">☰</button><div class="top-title">${esc(LABELS[ui.view]||'KatOS V5')}</div><div class="top-spacer"></div><div class="mode-switch" aria-label="Energy mode"><button type="button" class="mode-btn ${ui.mode==='normal'?'active':''}" data-mode="normal">🍓 <span>Normal</span></button><button type="button" class="mode-btn ${ui.mode==='tiny'?'active':''}" data-mode="tiny">🫧 <span>Tiny</span></button><button type="button" class="mode-btn ${ui.mode==='power'?'active':''}" data-mode="power">⚡ <span>Power</span></button></div></header>`}
function render(){const oldSidebar=app.querySelector('.sidebar'),scrollTop=oldSidebar?.scrollTop||0,scrollLeft=oldSidebar?.scrollLeft||0,snapshot=snapshotV4(),lifestyle=['motion','hobbies','growth'].includes(ui.view)?selectV5Lifestyle(snapshot.today):null,content=ui.view==='boss'?renderBoss(snapshot,ui.bossLane,selectV5WorkHQ(snapshot.today)):ui.view==='study'?renderStudy(snapshot,selectV5StudyNook(snapshot.today)):ui.view==='money'?renderMoney(snapshot,selectV5MoneyGig(snapshot.today),ui.moneyLane):ui.view==='motion'?renderMovement(lifestyle):ui.view==='hobbies'?renderHobbies(lifestyle):ui.view==='growth'?renderGrowth(lifestyle):renderRoom(ui.view,snapshot,{scheduleView:ui.scheduleView,mode:ui.mode});document.body.className=`mode-${ui.mode}`;app.className='katos';app.innerHTML=`${sidebar()}${topbar()}<main class="main">${content}</main>`;const newSidebar=app.querySelector('.sidebar');if(newSidebar){newSidebar.scrollTop=scrollTop;newSidebar.scrollLeft=scrollLeft}}
function persist(){saveV5Ui(ui)}
function chooseView(view){if(!LABELS[view])return;ui.view=view;ui.sidebarOpen=false;persist();render()}

app.addEventListener('click',event=>{
  const view=event.target.closest?.('[data-view]');if(view&&app.contains(view)){if(view.dataset.view==='money'&&view.dataset.moneyTarget==='gig')ui.moneyLane='gig';chooseView(view.dataset.view);return}
  const mode=event.target.closest?.('[data-mode]');if(mode&&app.contains(mode)){ui.mode=mode.dataset.mode;persist();render();return}
  const moneyLane=event.target.closest?.('[data-money-lane]');if(moneyLane&&app.contains(moneyLane)){ui.moneyLane=moneyLane.dataset.moneyLane==='gig'?'gig':'money';persist();render();return}
  const moneyClose=event.target.closest?.('[data-money-close]');if(moneyClose&&app.contains(moneyClose)){moneyClose.closest('[data-money-modal]')?.setAttribute('hidden','');return}
  const moneyAction=event.target.closest?.('[data-money-action]');if(moneyAction&&app.contains(moneyAction)){const type=moneyAction.dataset.moneyAction;if(type==='archive'&&!window.confirm('Archive this record? It will move to Memory Box, not be deleted.'))return;const result=runV5MoneyGigAction({type,id:moneyAction.dataset.moneyId,kind:moneyAction.dataset.moneyKind,date:moneyAction.dataset.moneyDate});if(!result.ok)window.alert(result.error||'That Money Café action could not be saved.');render();return}
  const moneyOpen=event.target.closest?.('[data-money-open]'),moneyControl=event.target.closest?.('button,input,select,textarea,a');if(moneyOpen&&app.contains(moneyOpen)&&(!moneyControl||moneyControl===moneyOpen)){const modal=[...app.querySelectorAll('[data-money-modal]')].find(node=>node.dataset.moneyModal===moneyOpen.dataset.moneyOpen);if(modal){modal.hidden=false;modal.querySelector('input,select,textarea')?.focus()}return}
  if(event.target.matches?.('[data-money-modal]')){event.target.setAttribute('hidden','');return}
  const lifestyleClose=event.target.closest?.('[data-lifestyle-close]');if(lifestyleClose&&app.contains(lifestyleClose)){lifestyleClose.closest('[data-lifestyle-modal]')?.setAttribute('hidden','');return}
  const lifestyleAction=event.target.closest?.('[data-lifestyle-action]');if(lifestyleAction&&app.contains(lifestyleAction)){if(lifestyleAction.dataset.lifestyleAction==='archive'&&!window.confirm('Archive this record? It will stay recoverable in Memory Box.'))return;const result=runV5LifestyleAction({type:lifestyleAction.dataset.lifestyleAction,kind:lifestyleAction.dataset.lifestyleKind,id:lifestyleAction.dataset.lifestyleId});if(!result.ok)window.alert(result.error||'That lifestyle record could not be saved.');render();return}
  const lifestyleOpen=event.target.closest?.('[data-lifestyle-open]'),lifestyleControl=event.target.closest?.('button,input,select,textarea,a');if(lifestyleOpen&&app.contains(lifestyleOpen)&&(!lifestyleControl||lifestyleControl===lifestyleOpen)){const modal=[...app.querySelectorAll('[data-lifestyle-modal]')].find(node=>node.dataset.lifestyleModal===lifestyleOpen.dataset.lifestyleOpen);if(modal){modal.hidden=false;modal.querySelector('input,select,textarea')?.focus()}return}
  const lifestylePick=event.target.closest?.('[data-lifestyle-pick]');if(lifestylePick&&app.contains(lifestylePick)){const view=selectV5Lifestyle(snapshotV4().today),caps={tiny:[0,10],chill:[1,45],normal:[2,90],'locked-in':[3,999]},[energy,max]=caps[lifestylePick.dataset.lifestylePick]||caps.normal,rank={tiny:0,low:1,medium:2,high:3},choice=view.hobbies.items.filter(row=>['current','exploring','want-to-try'].includes(row.status)&&(rank[row.energy]??1)<=energy&&(Number(row.minutes)||30)<=max).sort((a,b)=>(Number(a.minutes)||30)-(Number(b.minutes)||30)||a.title.localeCompare(b.title))[0],result=app.querySelector('[data-lifestyle-pick-result]');if(result)result.innerHTML=choice?`Try <b>${esc(choice.title)}</b> · ${Number(choice.minutes)||30} min.`:'Nothing on the shelf fits that mode yet.';return}
  if(event.target.matches?.('[data-lifestyle-modal]')){event.target.setAttribute('hidden','');return}
  const studyClose=event.target.closest?.('[data-study-close]');if(studyClose&&app.contains(studyClose)){studyClose.closest('[data-study-modal]')?.setAttribute('hidden','');return}
  const studyAction=event.target.closest?.('[data-study-action]');if(studyAction&&app.contains(studyAction)){const result=runV5StudyAction({type:studyAction.dataset.studyAction,id:studyAction.dataset.studyId,kind:studyAction.dataset.studyKind,direction:studyAction.dataset.studyDirection,title:studyAction.dataset.studyTitle});if(!result.ok)window.alert(result.error||'That Study Nook action could not be saved.');render();return}
  const studyOpen=event.target.closest?.('[data-study-open]'),studyControl=event.target.closest?.('button,input,select,textarea,a,details');if(studyOpen&&app.contains(studyOpen)&&(!studyControl||studyControl===studyOpen)){const modal=[...app.querySelectorAll('[data-study-modal]')].find(node=>node.dataset.studyModal===studyOpen.dataset.studyOpen);if(modal){modal.hidden=false;modal.querySelector('input,select,textarea')?.focus()}return}
  if(event.target.matches?.('[data-study-modal]')){event.target.setAttribute('hidden','');return}
  const lane=event.target.closest?.('[data-boss-lane]');if(lane&&app.contains(lane)){ui.bossLane=lane.dataset.bossLane==='gig'?'gig':'rbt';persist();render();return}
  const workClose=event.target.closest?.('[data-work-close]');if(workClose&&app.contains(workClose)){workClose.closest('[data-work-modal]')?.setAttribute('hidden','');return}
  const workAction=event.target.closest?.('[data-work-action]');if(workAction&&app.contains(workAction)){const result=runV5WorkAction({type:workAction.dataset.workAction,id:workAction.dataset.workId,kind:workAction.dataset.workKind,itemId:workAction.dataset.workItemId,key:workAction.dataset.workKey,linkKind:workAction.dataset.workLinkKind,occurrenceId:workAction.dataset.workOccurrenceId});if(!result.ok)window.alert(result.error||'That Work HQ action could not be saved.');render();return}
  const gigArchive=event.target.closest?.('[data-work-gig-archive]');if(gigArchive&&app.contains(gigArchive)){const result=archiveV5Record('work.gigShifts',gigArchive.dataset.workGigArchive);if(!result.ok)window.alert(result.error||'That gig shift could not be archived.');render();return}
  const workOpen=event.target.closest?.('[data-work-open]'),workControl=event.target.closest?.('button,input,select,textarea,a,details');if(workOpen&&app.contains(workOpen)&&(!workControl||workControl===workOpen)){const modal=[...app.querySelectorAll('[data-work-modal]')].find(node=>node.dataset.workModal===workOpen.dataset.workOpen);if(modal){modal.hidden=false;modal.querySelector('input,select,textarea')?.focus()}return}
  if(event.target.matches?.('[data-work-modal]')){event.target.setAttribute('hidden','');return}
  const schedule=event.target.closest?.('[data-schedule-view]');if(schedule&&app.contains(schedule)){ui.scheduleView=['day','week','calendar'].includes(schedule.dataset.scheduleView)?schedule.dataset.scheduleView:'day';persist();render();return}
  const noteDate=event.target.closest?.('[data-daily-note-date]');if(noteDate&&app.contains(noteDate)){app.querySelector('[data-daily-note-calendar]')?.remove();app.insertAdjacentHTML('beforeend',renderDailyNoteModal(noteDate.dataset.dailyNoteDate));app.querySelector('[data-daily-note-calendar] select,input,textarea')?.focus();return}
  const noteClose=event.target.closest?.('[data-daily-note-close]');if(noteClose&&app.contains(noteClose)){noteClose.closest('[data-daily-note-calendar]')?.remove();return}
  if(event.target.matches?.('[data-daily-note-calendar]')){event.target.remove();return}
  const dailyClose=event.target.closest?.('[data-daily-close]');if(dailyClose&&app.contains(dailyClose)){dailyClose.closest('[data-daily-modal]')?.setAttribute('hidden','');return}
  const daily=event.target.closest?.('[data-daily-action]');if(daily&&app.contains(daily)){const type=daily.dataset.dailyAction,payload={type,id:daily.dataset.dailyId,kind:daily.dataset.dailyKind,date:daily.dataset.dailyDate,toDate:daily.dataset.dailyToDate,until:daily.dataset.dailyToDate,index:daily.dataset.dailyIndex,from:daily.dataset.dailyFrom,to:daily.dataset.dailyTo,status:daily.dataset.dailyStatus};const result=runV5DailyAction(payload);if(!result.ok)window.alert(result.error||'That Daily Shit action could not be saved.');render();return}
  const dailyOpen=event.target.closest?.('[data-daily-open]'),control=event.target.closest?.('button,input,select,textarea,a');if(dailyOpen&&app.contains(dailyOpen)&&(!control||control===dailyOpen)){const modal=[...app.querySelectorAll('[data-daily-modal]')].find(node=>node.dataset.dailyModal===dailyOpen.dataset.dailyOpen);if(modal){modal.hidden=false;modal.querySelector('input,select,textarea')?.focus()}return}
  const tired=event.target.closest?.('[data-daily-tired]');if(tired&&app.contains(tired)){const dailyState=selectV5DailyShit(snapshotV4().today,{mode:'tiny'}),items=dailyState.tired;app.querySelector('[data-tired-modal]')?.remove();app.insertAdjacentHTML('beforeend',`<div class="detail-modal-backdrop" data-tired-modal><section class="detail-modal" role="dialog" aria-modal="true"><div class="detail-modal-head"><div><div class="ey">🫧 TOO TIRED</div><h2>Only tiny things count right now</h2><p>These are existing short, low-energy actions—not bonus chores.</p></div><button type="button" class="detail-modal-close" data-tired-close>×</button></div>${items.length?`<div class="room-list">${items.map(item=>`<div class="room-row"><div class="room-row-main"><b>${esc(item.title)}</b><span>${esc(`${item.duration||5} min · ${item.energy||'low'} energy`)}</span></div><button type="button" class="btn tiny" data-daily-action="complete" data-daily-kind="task" data-daily-id="${esc(item.id)}" data-daily-date="${esc(dailyState.date)}">✓ Count it</button></div>`).join('')}</div>`:'<div class="empty">No low-energy task is waiting. Rest is allowed.</div>'}</section></div>`);return}
  const tiredClose=event.target.closest?.('[data-tired-close]');if(tiredClose&&app.contains(tiredClose)){tiredClose.closest('[data-tired-modal]')?.remove();return}
  const stuck=event.target.closest?.('[data-daily-stuck]');if(stuck&&app.contains(stuck)){const item=unpackRecord(stuck.dataset.dailyItem),steps=Array.isArray(item?.source?.childSteps)?item.source.childSteps:[];app.querySelector('[data-stuck-modal]')?.remove();app.insertAdjacentHTML('beforeend',`<div class="detail-modal-backdrop" data-stuck-modal><section class="detail-modal" role="dialog" aria-modal="true"><div class="detail-modal-head"><div><div class="ey">🧠 I’M STUCK</div><h2>${esc(item?.title||'Tiny next step')}</h2><p>Look at the steps that already exist, then add one physically tiny move.</p></div><button type="button" class="detail-modal-close" data-stuck-close>×</button></div>${steps.length?`<div class="room-list">${steps.map(step=>`<div class="room-row"><div class="room-row-main"><b>${esc(step.label||step.text||'Step')}</b></div></div>`).join('')}</div>`:'<div class="empty">No child steps yet. Make the first one absurdly small.</div>'}<form class="button-row daily-actions" data-daily-child-step data-daily-id="${esc(item?.id||'')}"><input name="label" placeholder="Open the app, stand up, find the bag…" required><button class="btn primary">Add tiny step</button></form></section></div>`);return}
  const stuckClose=event.target.closest?.('[data-stuck-close]');if(stuckClose&&app.contains(stuckClose)){stuckClose.closest('[data-stuck-modal]')?.remove();return}
  const record=event.target.closest?.('[data-v5-record]');if(record&&app.contains(record)){openRecordEditor(record.dataset.v5RecordPath,unpackRecord(record.dataset.v5Record));return}
  const recordClose=event.target.closest?.('[data-record-close]');if(recordClose&&app.contains(recordClose)){recordClose.closest('[data-record-editor]')?.remove();return}
  const archive=event.target.closest?.('[data-record-archive]');if(archive&&app.contains(archive)){const form=archive.closest('[data-record-edit]');if(form&&window.confirm('Archive this entry? It will move to Memory Box, not be deleted.')){const result=archiveV5Record(form.dataset.recordPath,form.dataset.recordId);if(!result.ok)window.alert(result.error||'That entry could not be archived.');render()}return}
  const restore=event.target.closest?.('[data-archive-restore]');if(restore&&app.contains(restore)){if(window.confirm('Restore this entry to where it was before it was archived?')){const result=restoreV5Record(restore.dataset.archiveRestore);if(!result.ok)window.alert(result.error||'That entry could not be restored.');render()}return}
  const action=event.target.closest?.('[data-action]');if(action&&app.contains(action)){if(action.dataset.action==='toggle-sidebar')ui.sidebarOpen=!ui.sidebarOpen;if(action.dataset.action==='close-sidebar')ui.sidebarOpen=false;if(action.dataset.action==='reimport-v4'){if(window.confirm('Copy the current V4 snapshot into V5 again? Your current V5 data will be backed up first.'))migrateV4ToV5();render();return}if(action.dataset.action==='pick-v4-export'){app.querySelector('[data-v4-export-file]')?.click();return}if(action.dataset.action==='restore-cloud-v4'){action.disabled=true;action.textContent='☁️ Restoring your data…';restoreCloudV4Data().then(result=>{if(result.ok){window.alert('Your cloud planner data is now in V5.');location.reload()}else{window.alert(result.error||'Cloud restore did not finish.');render()}});return}render();return}
  const remove=event.target.closest?.('[data-ledger-remove]');if(remove&&app.contains(remove)){if(window.confirm('Archive this V5 ledger entry? You can restore it from Memory Box.')){const result=archiveV5Record('v5.ledger',remove.dataset.ledgerRemove);if(!result.ok)window.alert(result.error||'That ledger entry could not be archived.');render()}return}
  const focus=event.target.closest?.('[data-focus]');if(focus&&app.contains(focus)){const target=focus.dataset.focus==='clients'?app.querySelector('#v5-client-roster'):app.querySelector('#v5-note-queue');target?.scrollIntoView({behavior:'smooth',block:'start'})}
  const detailOpen=event.target.closest?.('[data-detail-open]');if(detailOpen&&app.contains(detailOpen)){const modal=[...app.querySelectorAll('[data-detail-modal]')].find(node=>node.dataset.detailModal===detailOpen.dataset.detailOpen);if(modal){modal.hidden=false;modal.querySelector('select,input,textarea')?.focus()}return}
  const detailClose=event.target.closest?.('[data-detail-close]');if(detailClose&&app.contains(detailClose)){detailClose.closest('[data-detail-modal]')?.setAttribute('hidden','');return}
  if(event.target.matches?.('[data-detail-modal]')){event.target.setAttribute('hidden','');return}
});
app.addEventListener('keydown',event=>{if(event.key==='Escape'){app.querySelectorAll('[data-detail-modal]:not([hidden]),[data-daily-modal]:not([hidden]),[data-work-modal]:not([hidden]),[data-study-modal]:not([hidden]),[data-money-modal]:not([hidden]),[data-lifestyle-modal]:not([hidden])').forEach(modal=>modal.setAttribute('hidden',''));app.querySelector('[data-daily-note-calendar]')?.remove();app.querySelector('[data-tired-modal]')?.remove();app.querySelector('[data-stuck-modal]')?.remove()}if(event.key==='Enter'&&event.target?.matches?.('[data-daily-open],[data-work-open],[data-study-open],[data-money-open],[data-lifestyle-open]')){const dailyId=event.target.dataset.dailyOpen,workId=event.target.dataset.workOpen,studyId=event.target.dataset.studyOpen,moneyId=event.target.dataset.moneyOpen,lifestyleId=event.target.dataset.lifestyleOpen,modal=dailyId?[...app.querySelectorAll('[data-daily-modal]')].find(node=>node.dataset.dailyModal===dailyId):workId?[...app.querySelectorAll('[data-work-modal]')].find(node=>node.dataset.workModal===workId):studyId?[...app.querySelectorAll('[data-study-modal]')].find(node=>node.dataset.studyModal===studyId):moneyId?[...app.querySelectorAll('[data-money-modal]')].find(node=>node.dataset.moneyModal===moneyId):[...app.querySelectorAll('[data-lifestyle-modal]')].find(node=>node.dataset.lifestyleModal===lifestyleId);if(modal){event.preventDefault();modal.hidden=false;modal.querySelector('input,select,textarea')?.focus()}}});
app.addEventListener('submit',event=>{const form=event.target.closest?.('[data-daily-note-form]');if(!form||!app.contains(form))return;event.preventDefault();const fields=Object.fromEntries(new FormData(form));fields.date=form.dataset.noteDate||fields.date;saveV5DailyNote(fields);app.querySelector('[data-daily-note-calendar]')?.remove();render()});
app.addEventListener('submit',event=>{const form=event.target.closest?.('[data-record-edit]');if(!form||!app.contains(form))return;event.preventDefault();try{const result=updateV5Record(form.dataset.recordPath,form.dataset.recordId,recordFormValues(form));if(!result.ok)window.alert(result.error||'That entry could not be saved.');render()}catch(error){window.alert(error.message||'Check that entry and try again.')}});
app.addEventListener('submit',event=>{const form=event.target.closest?.('[data-work-form]');if(!form||!app.contains(form))return;event.preventDefault();const data=new FormData(form),fields=Object.fromEntries(data);fields.goalCodes=data.getAll('goalCodes');fields.materialIds=data.getAll('materialIds');const result=runV5WorkAction({type:form.dataset.workForm,id:form.dataset.workId,...fields});if(!result.ok)window.alert(result.error||'That Work HQ record could not be saved.');render()});
app.addEventListener('submit',event=>{const form=event.target.closest?.('[data-work-exam-pass]');if(!form||!app.contains(form))return;event.preventDefault();const result=runV5WorkAction({type:'exam-pass',confirmed:new FormData(form).get('confirmed')==='on'});if(!result.ok)window.alert(result.error||'The exam result could not be saved.');render()});
app.addEventListener('submit',event=>{const form=event.target.closest?.('[data-work-gig-form]');if(!form||!app.contains(form))return;event.preventDefault();const result=updateV5Record('work.gigShifts',form.dataset.workId,Object.fromEntries(new FormData(form)));if(!result.ok)window.alert(result.error||'That gig shift could not be saved.');render()});
app.addEventListener('submit',event=>{const form=event.target.closest?.('[data-study-form]');if(!form||!app.contains(form))return;event.preventDefault();const data=new FormData(form),fields=Object.fromEntries(data);fields.requirementIds=data.getAll('requirementIds');const result=runV5StudyAction({type:form.dataset.studyForm,id:form.dataset.studyId,...fields});if(!result.ok)window.alert(result.error||'That Study Nook record could not be saved.');render()});
app.addEventListener('submit',event=>{const form=event.target.closest?.('[data-study-confer]');if(!form||!app.contains(form))return;event.preventDefault();const data=new FormData(form),result=runV5StudyAction({type:'program-confer',id:form.dataset.studyId,confirmed:data.get('confirmed')==='on',completionDate:data.get('completionDate')});if(!result.ok)window.alert(result.error||'That program could not be moved to the Academic Shelf.');render()});
app.addEventListener('submit',event=>{const form=event.target.closest?.('[data-money-form]');if(!form||!app.contains(form))return;event.preventDefault();if(form.dataset.moneyForm==='payout-receive'&&!window.confirm('Confirm this payout reached the selected account? KatOS will create one linked ledger deposit.'))return;const data=new FormData(form),fields=Object.fromEntries(data);fields.orderIds=data.getAll('orderIds');const result=runV5MoneyGigAction({type:form.dataset.moneyForm,id:form.dataset.moneyId,...fields});if(!result.ok)window.alert(result.error||'That Money Café record could not be saved.');render()});
app.addEventListener('submit',event=>{const form=event.target.closest?.('[data-lifestyle-form]');if(!form||!app.contains(form))return;event.preventDefault();const fields=Object.fromEntries(new FormData(form)),result=runV5LifestyleAction({type:form.dataset.lifestyleForm,id:form.dataset.lifestyleId,...fields});if(!result.ok)window.alert(result.error||'That lifestyle record could not be saved.');render()});
app.addEventListener('submit',event=>{const form=event.target.closest?.('[data-room-detail-form]');if(!form||!app.contains(form))return;event.preventDefault();const fields=Object.fromEntries(new FormData(form));saveV5RoomDetail(form.dataset.roomDetail,fields);const view=form.dataset.roomDetail;const result=view==='money'?saveV5LedgerEntry({label:fields.entry,kind:{Spending:'expense',Income:'income',Transfer:'transfer',Bill:'expense',Savings:'transfer'}[fields.kind]||'expense',amount:fields.amount,date:fields.date,category:fields.category,account:fields.account,toAccount:fields.toAccount,note:fields.moneyNotes}):saveV5Workspace(view,fields);if(!result.ok){window.alert(result.error||'That could not be saved.');return}render()});
app.addEventListener('submit',event=>{const form=event.target.closest?.('[data-money-ledger-form]');if(!form||!app.contains(form))return;event.preventDefault();const result=saveV5LedgerEntry(Object.fromEntries(new FormData(form)));if(result.ok)render();else{const error=form.querySelector('.ledger-error');if(error)error.textContent=result.error}});
app.addEventListener('submit',event=>{const form=event.target.closest?.('[data-daily-quick-add]');if(!form||!app.contains(form))return;event.preventDefault();const fields=Object.fromEntries(new FormData(form)),result=runV5DailyAction({type:'quick-add',...fields});if(!result.ok)window.alert(result.error||'That Daily Shit item could not be added.');render()});
app.addEventListener('submit',event=>{const form=event.target.closest?.('[data-daily-task-edit]');if(!form||!app.contains(form))return;event.preventDefault();const fields=Object.fromEntries(new FormData(form)),patch={...fields,[form.dataset.dailyKind==='task'?'text':'title']:fields.title};delete patch.title;const result=runV5DailyAction({type:'update',kind:form.dataset.dailyKind,id:form.dataset.dailyId,patch});if(!result.ok)window.alert(result.error||'That Daily Shit item could not be saved.');render()});
app.addEventListener('submit',event=>{const form=event.target.closest?.('[data-daily-routine-edit]');if(!form||!app.contains(form))return;event.preventDefault();const fields=Object.fromEntries(new FormData(form)),result=runV5DailyAction({type:'routine-update',id:form.dataset.dailyId,...fields});if(!result.ok)window.alert(result.error||'That routine could not be saved.');render()});
app.addEventListener('submit',event=>{const form=event.target.closest?.('[data-daily-routine-step]');if(!form||!app.contains(form))return;event.preventDefault();const fields=Object.fromEntries(new FormData(form)),result=runV5DailyAction({type:'routine-add-step',id:form.dataset.dailyId,label:fields.label});if(!result.ok)window.alert(result.error||'That routine step could not be added.');render()});
app.addEventListener('submit',event=>{const form=event.target.closest?.('[data-daily-child-step]');if(!form||!app.contains(form))return;event.preventDefault();const fields=Object.fromEntries(new FormData(form)),result=runV5DailyAction({type:'add-child-step',kind:'task',id:form.dataset.dailyId,label:fields.label});if(!result.ok)window.alert(result.error||'That tiny step could not be added.');render()});
app.addEventListener('change',event=>{const program=event.target.closest?.('[data-study-program-switch]');if(program&&app.contains(program)){const result=runV5StudyAction({type:'select-program',id:program.value});if(!result.ok)window.alert(result.error||'That academic program could not be opened.');render();return}const input=event.target.closest?.('[data-v4-export-file]');const file=input?.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{const result=importV4Export(String(reader.result||''));if(result.ok){window.alert(`Your V4 export is now loaded in V5 (${Number(result.counts?.total)||0} planner records).`);location.reload()}else window.alert(result.error||'That export could not be loaded.');};reader.readAsText(file);input.value=''});
render();
if(!snapshotV4().found)restoreCloudV4Data().then(result=>{if(result.ok)render()}).catch(()=>{});
