import{prepareCloudSync}from'./cloud-sync.js?v=5.7.0-phone-sync';

await prepareCloudSync();
await import('./app.js?v=6.0.0-canonical-mochini');
await import('./cloud-resume-sync.js?v=6.2.0-routine-player-sync');
await import('./daily-step-popup-fix.js?v=5.6.5-routine-step-modal');
await import('./money-budgets.js?v=5.6.6-spending-budgets');
await import('./study-history-popup-fix.js?v=5.6.7-completed-course-edit');
await import('./schedule-gig-labels.js?v=5.6.9-gig-shift-labels');
await import('./brain-dump-v5.js?v=5.7.2-brain-dump');
await import('./fixed-events-safe.js?v=5.7.8-fixed-events-safe');
await import('./cloud-account.js?v=5.7.6-cloud-account');
await import('./bill-skip-month.js?v=5.8.0-bill-skip-month');
await import('./doordash-shift-modal.js?v=5.8.3-doordash-modal');
await import('./gig-archive-display-fix.js?v=5.8.5-gig-archive-filter');
await import('./routine-player.js?v=6.2.0-routine-player-sync');
await import('./mochini-avatar.js?v=6.4.0-face-slots');
await import('./mochini-companion.js?v=6.3.1-context-aware');
await import('./mochini-face-patch.js?v=6.4.0-face-slots');
await import('./mochini-chat.js?v=6.0.0-canonical-rig');
await import('./mochini-polish.js?v=5.9.5-safari-art-fix');
await import('./shipt-daily-groups.js?v=5.9.2-shipt-persistent-groups');
