const{ensureSingleDeviceIpadMode}=await import('./sync/single-device-mode.js?v=7.0.12-ipad-only');
ensureSingleDeviceIpadMode(localStorage);
const{ensureDeviceBootstrapState}=await import('./sync/sync-device-bootstrap.js?v=7.0.12-ipad-only');
ensureDeviceBootstrapState(localStorage);
await import('./app.js?v=7.0.12-ipad-only');
await import('./sync/sync-lab.js?v=7.0.12-ipad-only');
await import('./daily-step-popup-fix.js?v=5.6.5-routine-step-modal');
await import('./money-budgets.js?v=5.6.6-spending-budgets');
await import('./gig-goals-fix.js?v=6.18.0-gig-goals-fix');
await import('./study-history-popup-fix.js?v=5.6.7-completed-course-edit');
await import('./schedule-gig-labels.js?v=5.6.9-gig-shift-labels');
await import('./brain-dump-v5.js?v=5.7.2-brain-dump');
await import('./fixed-events-safe.js?v=5.7.8-fixed-events-safe');
await import('./bill-skip-month.js?v=5.8.0-bill-skip-month');
await import('./doordash-shift-modal.js?v=6.17.0-doordash-planner');
await import('./gig-archive-display-fix.js?v=5.8.5-gig-archive-filter');
await import('./routine-player.js?v=6.8.0-routine-builder');
await import('./routine-builder-layout-fix.js?v=6.15.1-routine-builder-layout');
await import('./mochini-avatar.js?v=6.6.0-approved-atlas-final');
await import('./mochini-companion.js?v=7.0.1-render-safe');
await import('./mochini-face-patch.js?v=6.4.0-face-slots');
await import('./mochini-approved-art.js?v=6.10.1-normal-pose-companion');
await import('./mochini-chat.js?v=6.0.0-canonical-rig');
await import('./mochini-polish.js?v=5.9.5-safari-art-fix');
await import('./shipt-daily-groups.js?v=5.9.2-shipt-persistent-groups');
