const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const money=value=>`${(Number(value)||0).toFixed(2)}`;
const recordData=(path,row)=>{try{const packed=btoa(unescape(encodeURIComponent(JSON.stringify(row||{}))));return`data-v5-record-path="${esc(path)}" data-v5-record="${packed}"`}catch{return''}};

function clientCode(snapshot,id){return snapshot.clients.find(client=>String(client.id)===String(id))?.code||'Client code missing'}
function noteLabel(value){return value==='submitted'?'Submitted':value==='ready'?'Ready':'Draft'}
function timeRange(row){const start=row?.startTime||'',end=row?.endTime||'';return start&&end?`${start} to ${end}`:start||end||'time not set'}
function sessionRow(snapshot,row){const state=row.noteStatus||'draft';return`<div class="mini-row" role="button" tabindex="0" style="cursor:pointer" ${recordData('work.rbt.sessions',row)}><div><b>${esc(clientCode(snapshot,row.clientId))}</b><span>${esc(row.date||snapshot.today)} · ${esc(timeRange(row))} · ${esc(row.setting||'setting not set')}</span></div><span class="pill ${esc(state)}">${esc(noteLabel(state))}</span></div>`}
function todayPanel(snapshot){const rows=snapshot.todaySessions;return`<section class="card boss-compact" id="v5-today"><div class="card-head"><div><div class="ey">🌞 TODAY AT WORK</div><h2>What actually needs your brain</h2><p>No productivity theater. Just today.</p></div><span class="count">${rows.length}</span></div><div class="mini-list">${rows.length?rows.map(row=>sessionRow(snapshot,row)).join(''):'<div class="empty">No RBT sessions are logged for today yet.</div>'}</div></section>`}
function notesPanel(snapshot){const rows=snapshot.waitingNotes.slice(0,6);return`<section class="card boss-compact" id="v5-note-queue"><div class="card-head"><div><div class="ey">📝 NOTES + ADMIN</div><h2>Finish, submit, escape</h2><p>The paperwork goblin gets one small box.</p></div><span class="count">${snapshot.waitingNotes.length}</span></div><div class="mini-list">${rows.length?rows.map(row=>sessionRow(snapshot,row)).join(''):'<div class="empty">No session notes waiting. Suspiciously peaceful. ✨</div>'}</div></section>`}
function clientsPanel(snapshot){const clients=snapshot.activeClients.slice(0,9);return`<section class="card full boss-compact" id="v5-client-roster"><div class="card-head"><div><div class="ey">🧠 CLIENT ROSTER</div><h2>Your RBT people, at a glance</h2><p>Client codes only. The actual clinical record stays in the approved work system.</p></div><span class="count">${snapshot.activeClients.length}</span></div><div class="privacy-strip"><b>Privacy:</b> V5 is only previewing the de-identified client data already stored in V4. It does not copy or modify it.</div><div class="client-grid" style="margin-top:10px">${clients.length?clients.map(client=>`<article class="client-tile" role="button" tabindex="0" style="cursor:pointer" ${recordData('work.rbt.clients',client)}><b>${esc(client.code||'Unnamed client')}</b><span>${esc(client.setting||'Setting not set')}${client.schedule?` · ${esc(client.schedule)}`:''}</span>${client.focus?`<span><b style="display:inline">Focus:</b> ${esc(client.focus)}</span>`:''}</article>`).join(''):'<div class="empty">No active client codes found in V4 yet.</div>'}</div></section>`}
function quickShelf(snapshot){return`<section class="card full boss-compact tiny-hide"><div class="card-head"><div><div class="ey">✨ QUICK SHELF</div><h2>Actions without giant forms</h2><p>Creation tools stay tucked away until you ask for them.</p></div></div><div class="quick-actions"><button type="button" class="quick-action" data-focus="clients"><b>🧒 Client roster</b><span>${snapshot.activeClients.length} active client codes</span></button><button type="button" class="quick-action" data-focus="notes"><b>📝 Note queue</b><span>${snapshot.waitingNotes.length} notes still waiting</span></button><a class="quick-action" href="../v4/?source=v5-preview"><b>🍓 Open work details</b><span>Your work details are carried into V5.</span></a></div></section>`}
function rbtLane(snapshot){const submitted=snapshot.sessions.filter(row=>row.noteStatus==='submitted').length;return`<div class="stat-grid"><div class="stat"><small>ACTIVE CLIENTS</small><b>${snapshot.activeClients.length}</b><span>coded roster</span></div><div class="stat"><small>TODAY'S SESSIONS</small><b>${snapshot.todaySessions.length}</b><span>${esc(snapshot.today)}</span></div><div class="stat"><small>NOTES TO FINISH</small><b>${snapshot.waitingNotes.length}</b><span>draft + ready</span></div><div class="stat"><small>SUBMITTED NOTES</small><b>${submitted}</b><span>in local V4 data</span></div></div><div class="grid">${todayPanel(snapshot)}${notesPanel(snapshot)}${quickShelf(snapshot)}${clientsPanel(snapshot)}</div>`}
function gigLane(snapshot){const receipts=snapshot.recentGigs||[],shifts=(snapshot.gigShifts||[]).slice().sort((a,b)=>String(b?.date||'').localeCompare(String(a?.date||''))).slice(0,12),earned=receipts.reduce((sum,row)=>sum+(Number(row._v5Amount)||0),0),scheduled=shifts.reduce((sum,row)=>sum+(Number(row.actualAmount||row.targetAmount)||0),0);return`<div class="grid"><section class="card two-thirds boss-compact"><div class="ey">⚡ GIG WORK</div><h2>Separate lane, same work brain</h2><p>Gig work does not need to compete with your RBT career for screen space.</p><div class="gig-total">${money(earned||scheduled)}</div><div class="subtle">earned receipts and planned shifts from your V4 data</div></section><section class="card third boss-compact"><div class="ey">🍓 V5 RULE</div><h2>RBT first</h2><p>Boss Bitch opens around your main career. Gig work stays available without taking over.</p></section><section class="card full boss-compact"><div class="card-head"><div><div class="ey">GIG SHIFTS</div><h2>Shifts already on your calendar</h2></div><div style="display:flex;gap:8px;align-items:center"><span class="count">${shifts.length}</span><button type="button" class="btn soft" data-detail-open="boss">＋ Add shift</button></div></div><div class="mini-list">${shifts.length?shifts.map(row=>`<div class="mini-row" role="button" tabindex="0" style="cursor:pointer" ${recordData('work.gigShifts',row)}><div><b>${esc(row.source||row.platform||row.label||'Gig work')}</b><span>${esc(row.date||'date not set')}${row.startTime?` · ${esc(timeRange(row))}`:''}</span></div><span class="pill">${money(row.actualAmount||row.targetAmount)}</span></div>`).join(''):'<div class="empty">No gig shifts found in the V4 snapshot.</div>'}</div></section><section class="card full boss-compact"><div class="card-head"><div><div class="ey">GIG RECEIPTS</div><h2>Money that landed</h2></div><span class="count">${receipts.length}</span></div><div class="mini-list">${receipts.length?receipts.map(row=>`<div class="mini-row" role="button" tabindex="0" style="cursor:pointer" ${recordData('money.earnings',row)}><div><b>${esc(row.platform||row.name||'Gig work')}</b><span>${esc(row.date||'date not set')}</span></div><span class="pill">${money(row._v5Amount)}</span></div>`).join(''):'<div class="empty">No completed gig receipts found yet.</div>'}</div></section></div>`}

function bossWorkspace(){return`<div class="detail-modal-backdrop" data-detail-modal="boss" hidden><section class="detail-modal" role="dialog" aria-modal="true" aria-labelledby="boss-modal-title"><div class="detail-modal-head"><div><div class="ey">⚡ GIG WORK</div><h2 id="boss-modal-title">Add a gig shift</h2><p>Set a realistic target, then your schedule and Boss Bitch will both know about it.</p></div><button type="button" class="detail-modal-close" data-detail-close aria-label="Close gig shift">×</button></div><form class="room-detail-form" data-room-detail-form data-room-detail="boss"><div class="room-detail-fields"><label class="daily-field"><span>App</span><select name="source"><option>DoorDash</option><option>Shipt</option><option>Uber Eats</option><option>Other gig work</option></select></label><label class="daily-field"><span>Date</span><input name="date" type="date" required></label><label class="daily-field"><span>Start time</span><input name="startTime" type="time"></label><label class="daily-field"><span>End time</span><input name="endTime" type="time"></label><label class="daily-field"><span>Money target</span><input name="targetAmount" type="number" min="0" step="0.01" inputmode="decimal" placeholder="0.00"></label><label class="daily-field daily-field-wide"><span>Notes</span><textarea name="note" rows="3" placeholder="Dinner rush, goal for this block, anything useful…"></textarea></label></div><div class="button-row daily-actions"><button type="submit" class="btn primary">🍓 Save gig shift</button><button type="button" class="btn soft" data-detail-close>Keep editing later</button></div></form></section></div>`}

export function renderBoss(snapshot,lane='rbt'){
  return`<section class="page"><section class="hero boss-hero"><div class="ey">💼 BOSS BITCH · V5</div><h2>Work brain, minus the office-supply aisle</h2><p class="boss-lede">Your RBT career gets the front seat. Client work, session notes, schedule and admin surface what matters without giant empty cards yelling at you.</p><div class="boss-lanes" role="tablist"><button type="button" class="boss-lane ${lane==='rbt'?'active':''}" data-boss-lane="rbt">🧠 RBT job</button><button type="button" class="boss-lane ${lane==='gig'?'active':''}" data-boss-lane="gig">⚡ Gig work</button></div><br><span class="source-pill">🔒 ${snapshot.found?'Using your imported planner data':'No V4 local snapshot detected yet'}</span></section>${bossWorkspace()}${lane==='gig'?gigLane(snapshot):rbtLane(snapshot)}</section>`;
}
