import{snapshotV4,saveV5Workspace,updateV5Record,archiveV5Record}from'./data.js?v=5.6.0-final-integration';

const app=document.getElementById('app');
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const text=value=>String(value??'').trim();
const list=value=>Array.isArray(value)?value:[];
const BUCKETS=['inbox','do','decide','remember','feel','let go'];
const BUCKET_LABEL={inbox:'Inbox',do:'Do',decide:'Decide',remember:'Remember',feel:'Feel','let go':'Let go'};
const URGENCY=['Quiet','Low','Medium','Loud','Emergency'];
const KEEP=['A next step','A reminder','A conversation','A place to sit','Nothing'];

function normalizeBucket(value){const raw=text(value).toLowerCase().replace(/[-_]+/g,' ').replace(/\s+/g,' ');if(!raw||raw==='unsorted')return'inbox';if(raw==='letgo')return'let go';return BUCKETS.includes(raw)?raw:'inbox'}
function state(){return snapshotV4().state||{}}
function thoughts(){return list(state()?.v4?.brainDump).filter(row=>text(row?.bucket).toLowerCase()!=='closed').map(row=>({...row,__bucket:normalizeBucket(row.bucket)})).sort((a,b)=>String(b.updatedAt||b.createdAt||'').localeCompare(String(a.updatedAt||a.createdAt||'')))}
function titleOf(row){return text(row?.text||row?.thought||row?.title||row?.label)||'Brain note'}
function metaOf(row){const parts=[];if(text(row.urgency))parts.push(text(row.urgency));if(text(row.keep))parts.push(text(row.keep));if(text(row.nextStep))parts.push(`Next: ${text(row.nextStep)}`);return parts.join(' · ')}
function rowHtml(row){return`<button type="button" class="brain-row" data-brain-open="${esc(row.id||'')}"><span class="brain-row-main"><b>${esc(titleOf(row))}</b><small>${esc(metaOf(row)||BUCKET_LABEL[row.__bucket])}</small></span><span class="brain-bucket-chip">${esc(BUCKET_LABEL[row.__bucket])}</span></button>`}
function listHtml(rows,empty){return rows.length?`<div class="brain-list">${rows.map(rowHtml).join('')}</div>`:`<div class="empty">${esc(empty)}</div>`}
function sortedSection(bucket,rows){const matching=rows.filter(row=>row.__bucket===bucket);return`<section class="brain-mini-section"><div class="brain-mini-head"><span>${bucket==='do'?'✅':bucket==='decide'?'🧩':bucket==='remember'?'🚨':bucket==='feel'?'💗':'🍃'}</span><div><b>${esc(BUCKET_LABEL[bucket])}</b><small>${matching.length} thought${matching.length===1?'':'s'}</small></div></div>${listHtml(matching,`Nothing in ${BUCKET_LABEL[bucket]} right now.`)}</section>`}
function pageHtml(){const rows=thoughts(),inbox=rows.filter(row=>row.__bucket==='inbox'),action=rows.filter(row=>['do','decide','remember'].includes(row.__bucket)),soft=rows.filter(row=>['feel','let go'].includes(row.__bucket));return`<section class="page brain-native-page" data-brain-native-page>
  <section class="hero brain-hero"><div class="ey">🧠 BRAIN DUMP · V5</div><h2>Get it out. Sort it later.</h2><p>Your head is allowed to be temporary storage for zero things. Dump first, organize only if it helps.</p><div class="brain-hero-action"><button type="button" class="btn primary" data-brain-add>🍓 ＋ Dump a thought</button></div></section>
  <div class="room-stat-grid"><div class="room-stat"><small>INBOX</small><b>${inbox.length}</b><span>unsorted</span></div><div class="room-stat"><small>NEEDS SOMETHING</small><b>${action.length}</b><span>do · decide · remember</span></div><div class="room-stat"><small>FEEL / LET GO</small><b>${soft.length}</b><span>allowed to just exist</span></div><div class="room-stat"><small>TOTAL</small><b>${rows.length}</b><span>open thoughts</span></div></div>
  <div class="grid brain-grid">
    <section class="card full brain-inbox-card"><div class="card-head"><div><div class="ey">🧺 INBOX</div><h2>Things living outside your head</h2><p>Unsorted is a valid permanent category.</p></div><button type="button" class="btn primary" data-brain-add>＋ Dump thought</button></div>${listHtml(inbox,'Brain inbox is suspiciously peaceful.')}</section>
    <section class="card full brain-sorted-card"><div class="card-head"><div><div class="ey">✨ SORTED, IF USEFUL</div><h2>Give thoughts somewhere to sit</h2><p>Tap anything to edit, move it to another bucket, add a next step, or archive it.</p></div></div><div class="brain-bucket-grid">${['do','decide','remember','feel','let go'].map(bucket=>sortedSection(bucket,rows)).join('')}</div></section>
  </div>
</section>`}
function modalHtml(row=null){const editing=!!row,id=editing?text(row.id):'',bucket=normalizeBucket(row?.bucket);return`<div class="detail-modal-backdrop brain-modal-backdrop" data-brain-modal><section class="detail-modal brain-modal" role="dialog" aria-modal="true" aria-labelledby="brain-modal-title"><div class="detail-modal-head"><div><div class="ey">🧠 ${editing?'SAVED THOUGHT':'BRAIN DUMP'}</div><h2 id="brain-modal-title">${editing?'Edit this thought':'Dump it here'}</h2><p>${editing?'Change what it needs without losing the original thought.':'No polishing required. You can sort it now or leave it in Inbox.'}</p></div><button type="button" class="detail-modal-close" data-brain-close aria-label="Close">×</button></div><form data-brain-form data-brain-id="${esc(id)}"><div class="room-detail-fields"><label class="daily-field daily-field-wide"><span>What is on your mind?</span><textarea name="thought" rows="4" required placeholder="Put the whole brain blob here…">${esc(row?.text||row?.thought||'')}</textarea></label><label class="daily-field"><span>Where does it belong?</span><select name="bucket">${BUCKETS.map(value=>`<option value="${esc(value)}"${bucket===value?' selected':''}>${esc(BUCKET_LABEL[value])}</option>`).join('')}</select></label><label class="daily-field"><span>How loud is it?</span><select name="urgency"><option value="">Not sure</option>${URGENCY.map(value=>`<option${text(row?.urgency)===value?' selected':''}>${esc(value)}</option>`).join('')}</select></label><label class="daily-field"><span>What does it need?</span><select name="keep"><option value="">Nothing decided</option>${KEEP.map(value=>`<option${text(row?.keep)===value?' selected':''}>${esc(value)}</option>`).join('')}</select></label><label class="daily-field daily-field-wide"><span>Next step · optional</span><input name="next" value="${esc(row?.nextStep||row?.next||'')}" placeholder="Only if this thought actually needs one"></label><label class="daily-field daily-field-wide"><span>Extra context · optional</span><textarea name="dumpNotes" rows="3">${esc(row?.notes||row?.dumpNotes||'')}</textarea></label></div><div class="button-row daily-actions"><button class="btn primary">🍓 ${editing?'Save thought':'Add to Brain Dump'}</button>${editing?'<button type="button" class="btn soft" data-brain-archive>📦 Archive</button>':''}<button type="button" class="btn soft" data-brain-close>Close</button><span class="brain-form-status" data-brain-status></span></div></form></section></div>`}
function isBrainView(){return app.querySelector('.nav-btn.active')?.dataset.view==='dump'||text(app.querySelector('.top-title')?.textContent)==='Brain dump'}
function mount(force=false){if(!isBrainView())return;const main=app.querySelector('main.main');if(!main)return;if(!force&&main.querySelector('[data-brain-native-page]'))return;main.innerHTML=pageHtml()}
function openModal(row=null){app.querySelector('[data-brain-modal]')?.remove();app.insertAdjacentHTML('beforeend',modalHtml(row));app.querySelector('[data-brain-modal] textarea,input,select')?.focus()}
function closeModal(){app.querySelector('[data-brain-modal]')?.remove()}
function refresh(){closeModal();mount(true)}

app.addEventListener('click',event=>{if(!isBrainView()&&!event.target.closest?.('[data-brain-modal]'))return;const add=event.target.closest?.('[data-brain-add]');if(add){openModal();return}const open=event.target.closest?.('[data-brain-open]');if(open){const row=thoughts().find(item=>String(item.id)===String(open.dataset.brainOpen));if(row)openModal(row);return}const close=event.target.closest?.('[data-brain-close]');if(close){closeModal();return}if(event.target.matches?.('[data-brain-modal]')){closeModal();return}const archive=event.target.closest?.('[data-brain-archive]');if(archive){const form=archive.closest('[data-brain-form]'),id=form?.dataset.brainId;if(!id)return;if(archive.dataset.confirm!=='yes'){archive.dataset.confirm='yes';archive.textContent='Tap again to archive';return}const result=archiveV5Record('v4.brainDump',id);if(result.ok)refresh();else{const status=form.querySelector('[data-brain-status]');if(status)status.textContent=result.error||'Could not archive this thought.'}return}});

app.addEventListener('submit',event=>{const form=event.target.closest?.('[data-brain-form]');if(!form)return;event.preventDefault();const data=new FormData(form),fields=Object.fromEntries(data),id=form.dataset.brainId;let result;if(id){result=updateV5Record('v4.brainDump',id,{text:text(fields.thought),bucket:normalizeBucket(fields.bucket),urgency:text(fields.urgency),keep:text(fields.keep),nextStep:text(fields.next),notes:text(fields.dumpNotes)})}else result=saveV5Workspace('dump',fields);if(result.ok)refresh();else{const status=form.querySelector('[data-brain-status]');if(status)status.textContent=result.error||'That thought could not be saved.'}});

let queued=false;const queueMount=()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;mount()})};new MutationObserver(queueMount).observe(app,{childList:true,subtree:true});window.addEventListener('pageshow',queueMount);queueMount();
