import{cloudSignedIn,cloudSignOut,syncNow,useThisDeviceAsCloud,signInAndLoad}from'./cloud-sync-v3.js?v=6.13.0-canonical-cloud';

const SESSION_KEY='sm_v16_session';
const SUPABASE_SESSION_KEY='sb-sigjwmgekmrwehylvuvu-auth-token';
const app=document.getElementById('app');
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const text=value=>String(value??'').trim();
function normalizeSession(value){const session=value?.currentSession||value?.session||value;return session?.access_token&&session?.user?.id?session:null}
function storedSession(){for(const key of[SESSION_KEY,SUPABASE_SESSION_KEY]){try{const session=normalizeSession(JSON.parse(localStorage.getItem(key)||'null'));if(session)return session}catch{}}return null}
function accountEmail(){return text(storedSession()?.user?.email)}
function signedIn(){return cloudSignedIn()||!!storedSession()}

function statusButton(){return`<button type="button" class="cloud-status-pill ${signedIn()?'is-synced':'is-offline'}" data-cloud-account-open title="Cloud Sync">☁️ <span>${signedIn()?'Synced':'Sign in'}</span></button>`}
function settingsCard(){const email=accountEmail();return`<section class="card full cloud-account-card" data-cloud-account-card><div class="card-head"><div><div class="ey">☁️ CLOUD SYNC</div><h2>${signedIn()?'One KatOS everywhere':'Keep KatOS the same on every device'}</h2><p>${signedIn()?`Signed in${email?` as ${esc(email)}`:''}. Supabase is the shared planner; Safari and Home Screen copies are only local caches.`:'Sign in with the same KatOS account on every device.'}</p></div><span class="cloud-account-state ${signedIn()?'ready':'offline'}">${signedIn()?'Connected':'Offline'}</span></div><div class="button-row cloud-account-actions">${signedIn()?'<button type="button" class="btn primary" data-cloud-sync-now>☁️ Pull shared KatOS</button><button type="button" class="btn soft" data-cloud-use-device>🍓 Use this device as cloud copy</button><button type="button" class="btn soft" data-cloud-sign-out>Sign out this device</button>':'<button type="button" class="btn primary" data-cloud-account-open>🍓 Sign in & sync</button>'}<span data-cloud-account-message>${signedIn()?'Normal edits save automatically. Use the recovery button only when this device has the copy you intentionally want to make canonical.':'Sign in first.'}</span></div></section>`}
function loginModal(){return`<div class="detail-modal-backdrop cloud-login-modal" data-cloud-login-modal><section class="detail-modal" role="dialog" aria-modal="true" aria-labelledby="cloud-login-title"><div class="detail-modal-head"><div><div class="ey">☁️ KATOS CLOUD SYNC</div><h2 id="cloud-login-title">Bring your KatOS with you</h2><p>Use the same KatOS email and password on every copy.</p></div><button type="button" class="detail-modal-close" data-cloud-login-close aria-label="Close">×</button></div><form data-cloud-login-form><div class="room-detail-fields"><label class="daily-field daily-field-wide"><span>Email</span><input name="email" type="email" autocomplete="username" required></label><label class="daily-field daily-field-wide"><span>Password</span><input name="password" type="password" autocomplete="current-password" required></label></div><div class="cloud-login-error" data-cloud-login-error aria-live="polite"></div><div class="button-row daily-actions"><button class="btn primary" data-cloud-login-submit>🍓 Sign in & sync</button><button type="button" class="btn soft" data-cloud-login-close>Cancel</button></div></form></section></div>`}
function openLogin(){document.querySelector('[data-cloud-login-modal]')?.remove();app.insertAdjacentHTML('beforeend',loginModal());document.querySelector('[data-cloud-login-modal] input')?.focus()}
function closeLogin(){document.querySelector('[data-cloud-login-modal]')?.remove()}
function mountTopbar(){const topbar=document.querySelector('.topbar'),mode=topbar?.querySelector('.mode-switch');if(!topbar||!mode||topbar.querySelector('[data-cloud-account-open]'))return;mode.insertAdjacentHTML('beforebegin',statusButton())}
function mountSettings(){const title=document.querySelector('.top-title'),page=document.querySelector('.main .page');if(!page||text(title?.textContent)!=='Settings'||page.querySelector('[data-cloud-account-card]'))return;const stats=page.querySelector('.room-stat-grid');if(stats)stats.insertAdjacentHTML('afterend',settingsCard());else page.insertAdjacentHTML('afterbegin',settingsCard())}
function enhance(){mountTopbar();mountSettings()}
function setMessage(message){const node=document.querySelector('[data-cloud-account-message]');if(node)node.textContent=message}

app?.addEventListener('click',async event=>{
 if(event.target.closest?.('[data-cloud-account-open]')){if(signedIn()){document.querySelector('[data-view="settings"]')?.click()}else openLogin();return}
 if(event.target.closest?.('[data-cloud-login-close]')||event.target.matches?.('[data-cloud-login-modal]')){closeLogin();return}
 if(event.target.closest?.('[data-cloud-sync-now]')){const button=event.target.closest('[data-cloud-sync-now]');button.disabled=true;setMessage('Pulling the shared Supabase copy…');try{const result=await syncNow();if(result?.action==='needs-seed'){setMessage('No canonical cloud copy exists yet. On the iPad with 314 records, tap “Use this device as cloud copy”.')}else{setMessage('Shared KatOS loaded.');setTimeout(()=>location.reload(),300)}}catch(error){setMessage(error?.message||'Sync did not finish.')}finally{button.disabled=false}return}
 if(event.target.closest?.('[data-cloud-use-device]')){if(!confirm('Make THIS device the canonical KatOS cloud copy? Only do this on the device that currently has the data you want to keep.'))return;const button=event.target.closest('[data-cloud-use-device]');button.disabled=true;setMessage('Saving this device as the canonical cloud copy…');try{const result=await useThisDeviceAsCloud();setMessage(`Saved as shared KatOS revision ${result?.revision||1}. Other devices can now pull this copy.`)}catch(error){setMessage(error?.message||'Recovery save did not finish.')}finally{button.disabled=false}return}
 if(event.target.closest?.('[data-cloud-sign-out]')){if(!confirm('Sign out of cloud sync on this copy? Local cache will stay on this device.'))return;cloudSignOut();location.reload();return}
});

app?.addEventListener('submit',async event=>{const form=event.target.closest?.('[data-cloud-login-form]');if(!form)return;event.preventDefault();const button=form.querySelector('[data-cloud-login-submit]'),error=form.querySelector('[data-cloud-login-error]');button.disabled=true;error.textContent='';try{const data=new FormData(form);const result=await signInAndLoad(data.get('email'),data.get('password'));if(result?.action==='needs-seed'){error.classList.add('success');error.textContent='Signed in. No canonical copy exists yet; keep this device open if it is the recovery copy.';setTimeout(()=>location.reload(),700)}else{error.classList.add('success');error.textContent='Shared KatOS loaded.';setTimeout(()=>location.reload(),400)}}catch(err){error.classList.remove('success');error.textContent=String(err?.message||err||'Sign-in failed.');button.disabled=false}});

window.addEventListener('katos:cloud-sync',event=>{const status=event.detail?.status;if(status==='saved')setMessage('Saved to shared KatOS.');if(status==='pulled')setMessage('Updated from shared KatOS.');if(status==='needs-seed')setMessage('No canonical cloud copy yet. Use the recovery button on the correct device.');if(status==='error')setMessage('Cloud sync paused.');});
new MutationObserver(()=>queueMicrotask(enhance)).observe(app,{childList:true,subtree:true});
enhance();
