const URL='https://sigjwmgekmrwehylvuvu.supabase.co';
const KEY='sb_publishable_MrtltNJt8EufDKM1UqqDCQ_JphJneJt';
const TABLE='planner_data', V5='sm_v5_data', V4='sm_v4_beta';
const SESSION='sm_cloud_session', LAST='sm_cloud_last_sync';
const EXTRA={dailyNotes:'sm_v5_detailed_daily_notes',roomDetails:'sm_v5_room_details',ledger:'sm_v5_money_ledger'};
let busy=false,started=false,pushTimer=null,pollTimer=null,pullTimer=null,lastSnap=null,lastCloud=0;

const json=(raw,fallback=null)=>{try{return raw?JSON.parse(raw):fallback}catch{return fallback}};
const time=v=>{const n=Date.parse(v||'');return Number.isFinite(n)?n:0};
const stateTime=s=>time(s?.__smUpdatedAt)||time(s?.meta?.updatedAt)||time(s?.meta?.lastSavedAt)||0;
function score(s){if(!s||typeof s!=='object')return 0;let n=0;for(const v of [s.tasks,s.routines,s.pings,s.dailyNotes,s.schedule?.appointments,s.work?.clients,s.work?.sessions,s.study?.courses,s.money?.ledger,s.money?.bills,s.money?.subscriptions,s.gig?.orders,s.gig?.payouts])if(Array.isArray(v))n+=v.length;return n}
const local=()=>json(localStorage.getItem(V5));
const snap=()=>[localStorage.getItem(V5)||'',...Object.values(EXTRA).map(k=>localStorage.getItem(k)||'')];
const same=(a,b)=>!!a&&!!b&&a.length===b.length&&a.every((v,i)=>v===b[i]);
function extras(){const out={};for(const [name,key] of Object.entries(EXTRA)){const raw=localStorage.getItem(key);if(raw!=null)out[name]=json(raw)}return out}
function writeExtras(x){if(!x||typeof x!=='object')return;for(const [name,key] of Object.entries(EXTRA)){if(!(name in x))continue;x[name]==null?localStorage.removeItem(key):localStorage.setItem(key,JSON.stringify(x[name]))}}
function writeState(s){if(!s||typeof s!=='object')return;localStorage.setItem(V5,JSON.stringify(s));const old=json(localStorage.getItem(V4));const env=old?.data&&typeof old.data==='object'?{...old,data:s}:{data:s};localStorage.setItem(V4,JSON.stringify(env))}
function outgoing(s){const out=structuredClone(s||{});out.__smUpdatedAt=new Date().toISOString();out.__v5CloudExtras=extras();return out}
function apply(s){if(!s||typeof s!=='object')return false;writeExtras(s.__v5CloudExtras);writeState(s);lastSnap=snap();return true}
const session=()=>json(localStorage.getItem(SESSION));
const saveSession=s=>s?localStorage.setItem(SESSION,JSON.stringify(s)):localStorage.removeItem(SESSION);
function status(value,detail={}){try{window.dispatchEvent(new CustomEvent('katos:cloud-sync',{detail:{status:value,...detail}}))}catch{}}

async function auth(path,body){const r=await fetch(`${URL}/auth/v1/${path}`,{method:'POST',headers:{apikey:KEY,Authorization:`Bearer ${KEY}`,'Content-Type':'application/json'},body:JSON.stringify(body)});const p=await r.json().catch(()=>({}));if(!r.ok)throw Error(p?.msg||p?.error_description||p?.message||'Cloud sign-in failed.');return p}
async function refresh(s){if(!s?.refresh_token)return null;try{const next=await auth('token?grant_type=refresh_token',{refresh_token:s.refresh_token});saveSession(next);return next}catch{saveSession(null);return null}}
async function valid(){let s=session();if(!s?.access_token)return null;const exp=Number(s.expires_at||0)*1000;if(exp&&exp<Date.now()+60000)s=await refresh(s);return s?.access_token?s:null}
async function rest(path,{method='GET',body=null,prefer=''}={}){let s=await valid();if(!s)throw Error('Not signed in.');const run=t=>fetch(`${URL}/rest/v1/${path}`,{method,headers:{apikey:KEY,Authorization:`Bearer ${t}`,'Content-Type':'application/json',...(prefer?{Prefer:prefer}:{})},body:body==null?null:JSON.stringify(body)});let r=await run(s.access_token);if(r.status===401){s=await refresh(s);if(!s)throw Error('Cloud session expired.');r=await run(s.access_token)}if(!r.ok)throw Error((await r.text().catch(()=>''))||`Cloud request failed (${r.status}).`);if(r.status===204)return null;return r.json().catch(()=>null)}
async function cloud(){const rows=await rest(`${TABLE}?select=data,updated_at&limit=1`);const row=Array.isArray(rows)?rows[0]:null;return row?{state:row.data,updatedAt:row.updated_at}:null}
async function push(s){const authSession=await valid(),uid=authSession?.user?.id;if(!uid)throw Error('Cloud account is missing a user id.');const out=outgoing(s);const rows=await rest(`${TABLE}?on_conflict=user_id`,{method:'POST',prefer:'resolution=merge-duplicates,return=representation',body:[{user_id:uid,data:out}]});writeState(out);lastSnap=snap();const row=Array.isArray(rows)?rows[0]:null;const server=time(row?.updated_at)||stateTime(out)||Date.now();lastCloud=Math.max(lastCloud,server);localStorage.setItem(LAST,new Date(server).toISOString());status('synced',{direction:'push',at:server});return{state:out,serverTime:server}}

async function reconcile(){if(busy)return{ok:false,action:'busy'};busy=true;status('syncing');try{const l=local(),c=await cloud();if(!c?.state){if(l&&score(l)>0){await push(l);return{ok:true,action:'pushed-initial'}}status('synced');return{ok:true,action:'empty'}}const ct=time(c.updatedAt)||stateTime(c.state),lt=stateTime(l);lastCloud=ct;if(!l||ct>lt||(ct===lt&&score(c.state)>score(l))){apply(c.state);localStorage.setItem(LAST,new Date(ct||Date.now()).toISOString());status('synced',{direction:'pull',at:ct});return{ok:true,action:'pulled'}}if(lt>ct){await push(l);return{ok:true,action:'pushed-newer-local'}}status('synced',{direction:'none',at:ct});return{ok:true,action:'already-current'}}catch(error){console.warn('[KatOS V5] cloud sync skipped:',error);status('offline',{error:String(error?.message||error)});return{ok:false,action:'offline',error}}finally{busy=false}}
function schedulePush(){clearTimeout(pushTimer);pushTimer=setTimeout(async()=>{if(busy)return schedulePush();const s=await valid(),l=local();if(!s||!l||score(l)<=0)return;busy=true;status('syncing');try{await push(l)}catch(error){console.warn('[KatOS V5] auto-push failed:',error);status('offline',{error:String(error?.message||error)})}finally{busy=false}},800)}
function start(){if(started)return;started=true;lastSnap=snap();pollTimer=setInterval(()=>{const now=snap();if(!same(now,lastSnap)){lastSnap=now;schedulePush()}},900);pullTimer=setInterval(async()=>{if(busy||document.visibilityState==='hidden'||!(await valid()))return;busy=true;try{const c=await cloud(),ct=time(c?.updatedAt)||stateTime(c?.state),lt=stateTime(local());if(c?.state&&ct>lt&&ct>lastCloud){apply(c.state);lastCloud=ct;localStorage.setItem(LAST,new Date(ct||Date.now()).toISOString());status('synced',{direction:'pull',at:ct});location.reload()}}catch(error){console.warn('[KatOS V5] periodic pull failed:',error)}finally{busy=false}},15000)}
function stop(){clearTimeout(pushTimer);clearInterval(pollTimer);clearInterval(pullTimer);pushTimer=pollTimer=pullTimer=null;started=false}

function gate(){return new Promise(resolve=>{const el=document.createElement('div');el.style.cssText='position:fixed;inset:0;z-index:99999;display:grid;place-items:center;padding:20px;background:linear-gradient(135deg,#fff7fb,#f7f5ff,#f5fbf6);font-family:system-ui;color:#5b3f4a';el.innerHTML=`<div style="width:min(480px,100%);padding:26px;border:1px solid #e7cbd7;border-radius:26px;background:#fff;box-shadow:0 24px 70px #65405322"><h1 style="font-family:Georgia,serif;margin:0 0 8px">KatOS Cloud 🍓</h1><p>Sign in on this device so your iPad and phone use the same planner.</p><label>Email<input data-email type="email" autocomplete="email" style="display:block;width:100%;box-sizing:border-box;margin:6px 0 12px;padding:12px;border:1px solid #dec6d0;border-radius:12px"></label><label>Password<input data-pass type="password" autocomplete="current-password" style="display:block;width:100%;box-sizing:border-box;margin:6px 0 14px;padding:12px;border:1px solid #dec6d0;border-radius:12px"></label><div><button data-in>Sign in</button> <button data-up>Create account</button> <button data-off>Continue offline</button></div><p data-msg style="min-height:20px;font-size:13px"></p></div>`;document.body.appendChild(el);const email=el.querySelector('[data-email]'),pass=el.querySelector('[data-pass]'),msg=el.querySelector('[data-msg]');const finish=v=>{el.remove();resolve(v)};const submit=async mode=>{const e=email.value.trim(),p=pass.value;if(!e||!p){msg.textContent='Enter your email and password.';return}msg.textContent=mode==='signup'?'Creating account…':'Signing in…';try{let s;if(mode==='signup'){s=await auth('signup',{email:e,password:p});if(!s?.access_token){msg.textContent='Account created. Check your email if confirmation is required, then sign in.';return}}else s=await auth('token?grant_type=password',{email:e,password:p});saveSession(s);finish('signed-in')}catch(err){msg.textContent=err?.message||'Could not sign in.'}};el.querySelector('[data-in]').onclick=()=>submit('signin');el.querySelector('[data-up]').onclick=()=>submit('signup');el.querySelector('[data-off]').onclick=()=>finish('offline')})}

export async function prepareCloudSync(){let s=await valid();if(!s){const choice=await gate();if(choice==='offline')return{ready:true,offline:true};s=await valid()}if(!s)return{ready:true,offline:true};const result=await reconcile();start();return{ready:true,signedIn:true,result}}
export async function syncNow(){const before=snap();const result=await reconcile();const changed=result?.action==='pulled'&&!same(before,snap());if(changed)setTimeout(()=>location.reload(),0);return result}
export function cloudSignedIn(){return!!session()?.access_token}
export function cloudSignOut(){stop();saveSession(null);localStorage.removeItem(LAST);status('offline')}
