import{archiveV5Record,getGigGoalProgress,localDateKey,runV5DailyAction,saveV5GigShift,saveV5Workspace,selectV5DailyShit,selectV5MoneyGig,snapshotV4,updateV5Record}from'./data.js?v=7.4.0-intelligence-pass';
import{buildAdaptivePlan,classifyBrainDumpLine,decomposeTask,durationInsight,nextMaintenanceDate,unusuallyRelevant}from'./intelligence-core.js?v=7.4.0-intelligence-pass';
import{isAutomaticGigExpense}from'./money-mission-core.js?v=7.4.0-intelligence-pass';

const app=document.getElementById('app'),RECOVERY_KEY='sm_v5_recovery_days',ADAPTIVE_KEY='sm_v5_adaptive_goal_overrides';
const list=value=>Array.isArray(value)?value:[];
const obj=value=>value&&typeof value==='object'&&!Array.isArray(value)?value:{};
const text=value=>String(value??'').trim();
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const money=value=>Number(value||0).toLocaleString([],{style:'currency',currency:'USD'});
const parseStore=(key,fallback={})=>{try{return obj(JSON.parse(localStorage.getItem(key)||'null'))}catch{return fallback}};
const saveStore=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value))}catch{}}
const state=()=>obj(snapshotV4()?.state),today=()=>snapshotV4()?.today||localDateKey();
const currentView=()=>app.querySelector('.nav-btn.active[data-view]')?.dataset.view||'home';
const close=node=>node?.remove();
const modal=(name,content)=>{app.querySelector(`[data-intelligence-modal="${name}"]`)?.remove();app.insertAdjacentHTML('beforeend',`<div class="detail-modal-backdrop intelligence-backdrop" data-intelligence-modal="${name}"><section class="detail-modal intelligence-modal" role="dialog" aria-modal="true">${content}</section></div>`)};
const head=(ey,title,copy)=>`<div class="detail-modal-head"><div><div class="ey">${ey}</div><h2>${esc(title)}</h2><p>${esc(copy)}</p></div><button type="button" class="detail-modal-close" data-intelligence-close aria-label="Close">×</button></div>`;
const rerender=()=>app.querySelector(`.nav-btn.active[data-view="${currentView()}"]`)?.click();

function decorateGlobal(){
 const top=app.querySelector('.topbar .top-spacer');if(!top||app.querySelector('[data-global-brain-dump]'))return;
 top.insertAdjacentHTML('afterend','<div class="intelligence-global-actions"><button type="button" class="btn soft" data-global-brain-dump>🧠 Brain Dump</button><button type="button" class="btn soft" data-energy-help>🫧 I have 2 brain cells</button></div>');
}

function openBrainDump(){modal('brain-dump',`${head('🧠 QUICK CAPTURE','Brain Dump','One thought per line. KatOS will propose where each belongs before anything is saved.')}<form data-brain-dump-form><label class="daily-field daily-field-wide"><span>What is bouncing around?</span><textarea name="thoughts" rows="7" placeholder="call dentist\nbuy cat litter\nstudy definitions\nDoorDash Friday 5–9" required></textarea></label><div class="button-row daily-actions"><button class="btn primary">Suggest destinations</button><button type="button" class="btn soft" data-intelligence-close>Cancel</button></div></form>`)}
function routeLabel(value){return{task:'Daily Shit task',ping:'Little Ping',schedule:'Schedule',note:'Shopping / life note',study:'Study Nook',gig:'Gig Work'}[value]||'Daily Shit task'}
function proposals(lines){return lines.map((line,index)=>{const choice=classifyBrainDumpLine(line);return`<div class="brain-proposal"><b>${esc(line)}</b><label><span>Proposed destination</span><select name="destination-${index}">${['task','ping','schedule','note','study','gig'].map(value=>`<option value="${value}" ${value===choice?'selected':''}>${routeLabel(value)}</option>`).join('')}</select></label><input type="hidden" name="line-${index}" value="${esc(line)}"></div>`}).join('')}
function nextWeekday(dayName){const names=['sun','mon','tue','wed','thu','fri','sat'],wanted=names.findIndex(name=>dayName.toLowerCase().startsWith(name)),date=new Date(`${today()}T12:00:00`);if(wanted<0)return today();let delta=(wanted-date.getDay()+7)%7;if(!delta)delta=7;date.setDate(date.getDate()+delta);return localDateKey(date)}
function parseGigLine(line){const lower=line.toLowerCase(),day=lower.match(/\b(mon|tue|wed|thu|fri|sat|sun)(?:day)?\b/)?.[1],range=lower.match(/\b(\d{1,2})(?::(\d{2}))?\s*(am|pm)?\s*[–-]\s*(\d{1,2})(?::(\d{2}))?\s*(am|pm)?/);let start='17:00',end='21:00';if(range){const convert=(hour,minute,ampm)=>{let h=Number(hour);if(ampm==='pm'&&h<12)h+=12;if(ampm==='am'&&h===12)h=0;return`${String(h).padStart(2,'0')}:${String(Number(minute)||0).padStart(2,'0')}`};start=convert(range[1],range[2],range[3]||range[6]);end=convert(range[4],range[5],range[6]||range[3]);}return{source:/flex/.test(lower)?'Amazon Flex':'DoorDash',date:day?nextWeekday(day):today(),startTime:start,endTime:end,targetAmount:0,note:line,status:'planned'}}
function saveProposal(line,destination){if(destination==='task'||destination==='ping')return runV5DailyAction({type:'quick-add',kind:destination,title:line,date:today(),forToday:destination==='ping',energy:'medium'});if(destination==='schedule')return saveV5Workspace('time',{anchor:line,date:today(),startTime:'',endTime:'',scheduleNotes:'Added from Brain Dump'});if(destination==='study')return saveV5Workspace('study',{goal:line,activity:'Study',due:'',next:'Open the course'});if(destination==='gig')return saveV5GigShift(parseGigLine(line));return saveV5Workspace('dump',{thought:line,bucket:/buy|grocery|litter|shopping/i.test(line)?'Shopping':'Inbox',keep:'Keep',next:'Review when relevant'})}

function openEnergyHelp(){const tasks=list(state()?.life?.tasks).filter(row=>!row.archivedAt&&!row.done&&!row.completed),rank=row=>({tiny:0,low:1,medium:2,'tiny energy':0,'medium energy':2,'big brain':4,'leaving the house':3}[text(row.energy).toLowerCase()]??2),rows=tasks.filter(row=>rank(row)<=1||(Number(row.minutes)||99)<=15).sort((a,b)=>(Number(a.minutes)||99)-(Number(b.minutes)||99)).slice(0,7);modal('energy',`${head('🫧 LOW-ENERGY FILTER','I have 2 brain cells','These are existing tasks that fit low capacity. Nothing was deleted or moved.')}<div class="energy-task-list">${rows.map(row=>`<button type="button" class="room-row" data-open-task-id="${esc(row.id)}"><span class="room-row-main"><b>${esc(row.text||row.title)}</b><small>${Number(row.minutes)||5} min · ${esc(row.energy||'tiny energy')}</small></span></button>`).join('')||'<div class="empty">No tiny task is waiting. Rest is still a valid use of the moment.</div>'}</div><div class="button-row daily-actions"><button type="button" class="btn soft" data-intelligence-close>Done</button></div>`)}

function decorateTaskModals(){for(const form of app.querySelectorAll('[data-daily-task-edit][data-daily-kind="task"]')){if(form.dataset.intelligence==='1')continue;form.dataset.intelligence='1';const id=form.dataset.dailyId,record=list(state()?.life?.tasks).find(row=>String(row.id)===String(id))||{},fields=form.querySelector('.room-detail-fields'),actions=form.querySelector('.daily-actions'),insight=durationInsight(record.minutes,record.durationHistory);fields?.insertAdjacentHTML('beforeend',`<label class="daily-field"><span>Actual minutes · optional</span><input name="actualMinutes" type="number" min="0" value="${esc(record.actualMinutes||'')}"></label><label class="daily-field"><span>Energy kind</span><select name="energy"><option value="tiny" ${record.energy==='tiny'?'selected':''}>Tiny energy</option><option value="medium" ${record.energy==='medium'?'selected':''}>Medium energy</option><option value="big-brain" ${record.energy==='big-brain'?'selected':''}>Big brain</option><option value="leaving" ${record.energy==='leaving'?'selected':''}>Leaving the house</option></select></label>${insight.ready?`<p class="daily-duration-insight wide">You estimated ${insight.estimated} min. Your average is ${insight.average} min across ${insight.samples} logs. That is useful information, not a grade.</p>`:''}`);const original=form.querySelectorAll('select[name="energy"]');if(original.length>1)original[0].closest('label')?.remove();actions?.insertAdjacentHTML('afterbegin',`<button type="button" class="btn soft" data-task-huge="${esc(id)}">This feels huge</button><button type="button" class="btn soft" data-task-one="${esc(id)}">Give me literally one step</button>`)}
}
function taskById(id){return list(state()?.life?.tasks).find(row=>String(row.id)===String(id))}
function openDecomposer(id,one=false){const task=taskById(id);if(!task)return;const steps=decomposeTask(task.text||task.title);modal('decompose',`${head('🧩 TASK DECOMPOSER',one?'Literally one step':'Let’s make this smaller',one?'Only the first actionable step is showing.':'These are optional. Choose only the steps that would help.')}<form data-decompose-form data-task-id="${esc(id)}">${(one?steps.slice(0,1):steps).map((step,index)=>`<label class="decompose-step"><input type="checkbox" name="step" value="${esc(step)}" ${one||index===0?'checked':''}><span>${esc(step)}</span></label>`).join('')}<div class="button-row daily-actions"><button class="btn primary">Add selected step${one?'':'s'}</button><button type="button" class="btn soft" data-intelligence-close>Cancel</button></div></form>`)}

function recoveryActive(){return Boolean(parseStore(RECOVERY_KEY)[today()])}
function recoveryEssentials(){const s=state(),date=today(),items=[];list(s?.work?.rbt?.sessions||s?.work?.hq?.sessions).filter(row=>row.date===date).forEach(row=>items.push({label:row.clientName||row.client||'Client session',meta:[row.startTime,row.endTime].filter(Boolean).join(' – '),kind:'Work commitment'}));list(s?.life?.events).filter(row=>row.date===date).forEach(row=>items.push({label:row.title||'Appointment',meta:row.startTime||'',kind:'Schedule'}));list(s?.health?.medications).filter(row=>row.active!==false&&!row.archived).slice(0,4).forEach(row=>items.push({label:row.name||'Medication',meta:row.time||row.dose||'',kind:'Medication'}));selectV5MoneyGig(date).bills.filter(row=>row.dueDate<=date&&!['paid','skipped'].includes(text(row.status).toLowerCase())).slice(0,3).forEach(row=>items.push({label:row.name||'Bill',meta:money(row.expectedAmount||row.amount),kind:'Bill'}));items.push({label:'Eat or drink something useful',meta:'Basic care counts',kind:'Care'},{label:'One hygiene step',meta:'Choose the smallest useful version',kind:'Care'});const tiny=selectV5DailyShit(date,{mode:'tiny'}).tired[0];if(tiny)items.push({label:tiny.title,meta:'Optional small reset',kind:'Optional'});return items}
function decorateRecovery(){if(currentView()!=='daily')return;const tools=app.querySelector('.daily-shit-tools');tools?.closest('.card')?.classList.add('daily-quick-card');if(tools&&!tools.querySelector('[data-recovery-toggle]'))tools.insertAdjacentHTML('beforeend',`<button type="button" class="btn ${recoveryActive()?'primary':'soft'}" data-recovery-toggle>${recoveryActive()?'Return to full day':'Today went off the rails'}</button>`);const grid=app.querySelector('.page .grid');if(!grid)return;grid.classList.toggle('recovery-day',recoveryActive());if(!recoveryActive()){grid.querySelector('[data-recovery-card]')?.remove();return}if(!grid.querySelector('[data-recovery-card]')){const items=recoveryEssentials();grid.insertAdjacentHTML('afterbegin',`<section class="card full intelligence-recovery-card" data-recovery-card><div class="card-head"><div><div class="ey">🛟 RECOVERY DAY</div><h2>Protect the essentials. Let the rest be neutral.</h2><p>Hidden tasks are not failed. Nothing was completed, deleted, or rescheduled automatically.</p></div><button type="button" class="btn soft" data-recovery-toggle>Return to full day</button></div><div class="recovery-list">${items.map(item=>`<div><small>${esc(item.kind)}</small><b>${esc(item.label)}</b><span>${esc(item.meta)}</span></div>`).join('')}</div></section>`)}}

function maintenanceRows(){return list(state()?.life?.tasks).filter(row=>row.maintenance===true&&!row.archivedAt)}
function decorateMaintenance(){if(currentView()!=='daily')return;const grid=app.querySelector('.page .grid');if(!grid||grid.querySelector('[data-maintenance-card]'))return;const date=today(),rows=maintenanceRows().sort((a,b)=>text(a.nextSuggestedDate).localeCompare(text(b.nextSuggestedDate))),relevant=rows.filter(row=>!row.nextSuggestedDate||row.nextSuggestedDate<=date).slice(0,6),html=relevant.map(row=>{const overdue=row.nextSuggestedDate&&row.nextSuggestedDate<date;return`<div class="maintenance-row ${overdue?'overdue':''}"><div><b>${esc(row.text||row.title)}</b><span>${overdue?'Overdue':'Suggested now'} · every ${Number(row.maintenanceFrequencyDays)||30} days${row.lastCompleted?` · last ${esc(row.lastCompleted)}`:''}</span></div><button type="button" class="btn tiny" data-maintenance-complete="${esc(row.id)}">✓ Done</button><button type="button" class="btn tiny" data-maintenance-edit="${esc(row.id)}">Edit</button></div>`}).join('');grid.insertAdjacentHTML('beforeend',`<section class="card full maintenance-card" data-maintenance-card><div class="card-head"><div><div class="ey">🧺 LIFE MAINTENANCE</div><h2>Only surfacing when relevant</h2><p>Recurring care lives here instead of flooding Daily Shit.</p></div><button type="button" class="btn tiny" data-maintenance-add>＋ Add maintenance</button></div>${html||'<div class="empty">Nothing needs maintenance attention right now.</div>'}</section>`)}
function openMaintenance(record={}){modal('maintenance',`${head('🧺 LIFE MAINTENANCE',record.id?'Edit maintenance':'Add maintenance','KatOS suggests the next date from the frequency. It only surfaces when relevant.')}<form data-maintenance-form data-id="${esc(record.id||'')}"><div class="room-detail-fields"><label class="daily-field wide"><span>Maintenance item</span><input name="title" value="${esc(record.text||record.title||'')}" placeholder="Clean cat fountain" required></label><label class="daily-field"><span>Last completed</span><input name="lastCompleted" type="date" value="${esc(record.lastCompleted||today())}" required></label><label class="daily-field"><span>Preferred frequency · days</span><input name="frequency" type="number" min="1" value="${esc(record.maintenanceFrequencyDays||30)}" required></label><label class="daily-field wide"><span>Notes · optional</span><textarea name="notes" rows="2">${esc(record.notes||'')}</textarea></label></div><div class="button-row daily-actions"><button class="btn primary">Save maintenance</button>${record.id?'<button type="button" class="btn soft" data-maintenance-archive>Archive</button>':''}<button type="button" class="btn soft" data-intelligence-close>Cancel</button></div></form>`)}

function trackedGoal(){const snap=snapshotV4(),view=selectV5MoneyGig(snap.today),goals=list(view.gig?.goals).filter(row=>!row.archivedAt&&row.active!==false&&text(row.endDate)>=snap.today).sort((a,b)=>text(a.endDate).localeCompare(text(b.endDate))),goal=goals[0];if(!goal)return null;const progress=getGigGoalProgress(snap.state,goal.id,snap.today)||{},from=goal.startDate||snap.today,to=goal.endDate||snap.today,target=Number(goal.targetAmount)||0,account=list(view.hq?.accounts).find(row=>String(row.id)===String(goal.linkedAccountId)),expenses=list(view.transactions).filter(row=>isAutomaticGigExpense(row)&&row.date>=from&&row.date<=to).reduce((sum,row)=>sum+(Number(row.amount)||0),0),actual=account?Number(view.accountBalances?.[account.id]?.posted)||0:Math.max(0,(Number(progress.earned)||0)+(Number(goal.progressAdjustment)||0)-expenses),remaining=Math.max(0,target-actual),scheduledByDate={};list(snap.state?.work?.gigShifts).filter(row=>!row.archivedAt&&row.status!=='completed'&&row.date>=snap.today&&row.date<=to).forEach(row=>scheduledByDate[row.date]=(scheduledByDate[row.date]||0)+(Number(row.targetAmount)||0));const overrides=parseStore(ADAPTIVE_KEY)[goal.id]||{},plan=buildAdaptivePlan({remaining,from:snap.today,to,scheduledByDate,overrides});return{goal,actual,expenses,remaining,plan}}
function decorateAdaptiveGoal(){if(currentView()!=='boss')return;const mission=app.querySelector('[data-money-mission]');if(!mission||mission.querySelector('[data-adaptive-goal]'))return;const tracked=trackedGoal();if(!tracked)return;const rows=tracked.plan.rows.slice(0,8).map(row=>{const date=new Date(`${row.date}T12:00:00`).toLocaleDateString([],{weekday:'long'});return`<label class="adaptive-day"><span><b>${esc(date)}</b><small>${row.scheduled?`${money(row.scheduled)} scheduled`:'Suggested goal'}</small></span>${row.scheduled?`<strong>${money(row.scheduled)}</strong>`:`<input type="number" min="0" step="1" value="${row.suggested}" data-adaptive-date="${esc(row.date)}" aria-label="Suggested goal for ${esc(date)}">`}</label>`}).join('');mission.insertAdjacentHTML('beforeend',`<section class="adaptive-goal" data-adaptive-goal data-goal-id="${esc(tracked.goal.id)}"><div><small>ADAPTIVE PLAN · SUGGESTIONS ONLY</small><h3>${money(tracked.remaining)} remaining by ${new Date(`${tracked.goal.endDate}T12:00:00`).toLocaleDateString([],{weekday:'long'})}</h3><p>Completed net earnings, planned shifts, linked gig costs, and remaining days rebalance this list. You can edit any suggested day.</p></div><div class="adaptive-days">${rows}</div></section>`)}

function decorateLaunchPad(){const card=app.querySelector('.launch-pad-card');if(!card||card.querySelector('[data-launch-context]'))return;const hour=new Date().getHours(),s=state(),date=today(),upcoming=list(s?.work?.gigShifts).filter(row=>row.date===date&&!row.archivedAt&&row.status!=='completed').sort((a,b)=>text(a.startTime).localeCompare(text(b.startTime)))[0],sessions=list(s?.work?.rbt?.sessions||s?.work?.hq?.sessions).filter(row=>row.date===date).sort((a,b)=>text(a.startTime).localeCompare(text(b.startTime)))[0];let title='Morning setup',copy='Morning routine, appointments, and the important task belong here first.';if(upcoming){const flex=/flex/i.test(upcoming.source||'');title=flex?'Flex route prep':'Delivery shift prep';copy=`${upcoming.station?`${upcoming.station} · `:''}${upcoming.startTime||'Time not set'}–${upcoming.endTime||''} · ${money(upcoming.targetAmount)} expected${upcoming.area?` · ${upcoming.area}`:''}. Afterward, add mileage, ${flex?'packages, stops, ':''}earnings, and expenses.`}else if(sessions){title='Session prep';copy=`${sessions.clientName||sessions.client||'Client session'}${sessions.startTime?` at ${sessions.startTime}`:''}. Check planned materials and the session schedule.`}else if(hour>=18){title='Evening landing';copy='Finish only the essentials, then look at tomorrow without borrowing trouble from it.'}card.querySelector('.launch-pad')?.insertAdjacentHTML('afterbegin',`<div class="launch-context" data-launch-context><small>RIGHT NOW</small><b>${esc(title)}</b><span>${esc(copy)}</span></div>`)}

function forgettingItems(){const s=state(),date=today(),items=[];list(s?.life?.events).filter(row=>row.date===date).forEach(row=>items.push({key:`event-${row.id}`,label:row.title||'Appointment',time:row.startTime,urgency:8,meta:row.startTime||'Today'}));selectV5DailyShit(date).open.filter(row=>row.hard||['now','today','high'].includes(row.priority)).forEach(row=>items.push({key:`task-${row.id}`,label:row.title,time:row.time,urgency:row.hard?10:7,meta:row.hard?'Hard deadline':'Important task'}));selectV5MoneyGig(date).bills.filter(row=>row.dueDate<=date&&!['paid','skipped'].includes(text(row.status).toLowerCase())).forEach(row=>items.push({key:`bill-${row.id}`,label:row.name||'Bill',urgency:10,meta:`Due · ${money(row.expectedAmount||row.amount)}`}));list(s?.health?.medications).filter(row=>row.active!==false&&!row.archived).forEach(row=>items.push({key:`med-${row.id}`,label:row.name||'Medication',time:row.time,urgency:8,meta:row.time||'Scheduled today'}));maintenanceRows().filter(row=>row.nextSuggestedDate<=date).forEach(row=>items.push({key:`maint-${row.id}`,label:row.text||row.title,urgency:4,meta:'Maintenance is due'}));list(s?.education?.items).filter(row=>!row.done&&row.dueDate&&row.dueDate<=date).forEach(row=>items.push({key:`study-${row.id}`,label:row.title||'Study obligation',urgency:9,meta:'Study due'}));list(s?.work?.gigShifts).filter(row=>row.date===date&&!row.archivedAt&&row.status!=='completed').forEach(row=>items.push({key:`gig-${row.id}`,label:`${row.source||'Gig'} block`,time:row.startTime,urgency:8,meta:`${row.startTime||''} · ${money(row.targetAmount)}`}));return unusuallyRelevant(items,5)}
function openForgetting(){const rows=forgettingItems();modal('forgetting',`${head('🍡 MOCHINI CHECK','What am I forgetting?','Only unusually relevant things are shown. Mochini did not change anything.')}<div class="forgetting-list">${rows.map(row=>`<div><b>${esc(row.label)}</b><span>${esc(row.meta||row.time||'Relevant today')}</span></div>`).join('')||'<div class="empty">Nothing unusual is waving for attention right now.</div>'}</div><div class="button-row daily-actions"><button type="button" class="btn soft" data-intelligence-close>Done</button></div>`)}
let lastMochiniContext='';function syncMochini(){const view=currentView(),hour=new Date().getHours(),moneyView=selectV5MoneyGig(today()),urgent=moneyView.bills.some(row=>row.dueDate<today()&&!['paid','skipped'].includes(text(row.status).toLowerCase())),mission=trackedGoal(),celebrations=parseStore('sm_v5_intelligence_celebrations'),goalWon=mission&&mission.remaining<=0&&!celebrations[`goal-${mission.goal.id}`],context=goalWon?'goal':urgent?'urgent':view==='money'?'money':view==='boss'?'delivery':hour>=23||hour<6?'sleepy':'';if(!context||context===lastMochiniContext)return;lastMochiniContext=context;const map={goal:{mood:'proud',activityId:'princessing',activity:'doing a tiny goal victory dance',line:'You hit the goal. That is real—not motivational-poster real. Actual numbers real.',open:true},money:{mood:'focused',activityId:'money-check',activity:'checking the real ledger math',line:'Calculator out. I am checking the numbers with you.'},delivery:{mood:'determined',activityId:'car-ride',activity:'riding delivery mode shotgun',line:'Delivery mode. Route details first, tiny victory dance after.'},sleepy:{mood:'sleepy',activityId:'tucked-in',activity:'getting sleepy under a strawberry blanket',line:'It is late. I can help you find the one thing that truly cannot wait.'},urgent:{mood:'thinking',activityId:'money-check',activity:'checking one genuinely urgent bill',line:'One bill looks time-sensitive. Let’s look at the exact due date and amount—no panic arithmetic.'}};if(goalWon){celebrations[`goal-${mission.goal.id}`]=new Date().toISOString();saveStore('sm_v5_intelligence_celebrations',celebrations)}window.dispatchEvent(new CustomEvent('katos:mochini-state',{detail:{...map[context],open:map[context].open??false}}))}

function decorate(){decorateGlobal();decorateTaskModals();decorateRecovery();decorateMaintenance();decorateAdaptiveGoal();decorateLaunchPad();syncMochini()}
let queued=false;function queue(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;decorate()})}

app.addEventListener('click',event=>{const completing=event.target.closest('[data-daily-action="complete"][data-daily-kind="task"]');if(completing){const task=taskById(completing.dataset.dailyId),difficult=task&&(task.deadlineType==='hard'||['high','big-brain'].includes(text(task.priority||task.energy).toLowerCase())||(Number(task.minutes)||0)>=45);if(difficult)setTimeout(()=>window.dispatchEvent(new CustomEvent('katos:mochini-state',{detail:{mood:'proud',activityId:'princessing',activity:'performing a deserved victory animation',line:'That was a real difficult task. Victory dance approved.',open:true}})),80)}let button=event.target.closest('[data-intelligence-close]');if(button){close(button.closest('[data-intelligence-modal]'));return}if(event.target.matches('[data-intelligence-modal]')){close(event.target);return}if(event.target.closest('[data-global-brain-dump]')){openBrainDump();return}if(event.target.closest('[data-energy-help]')){openEnergyHelp();return}button=event.target.closest('[data-task-huge]');if(button){openDecomposer(button.dataset.taskHuge,false);return}button=event.target.closest('[data-task-one]');if(button){openDecomposer(button.dataset.taskOne,true);return}button=event.target.closest('[data-open-task-id]');if(button){close(button.closest('[data-intelligence-modal]'));app.querySelector('[data-view="daily"]')?.click();setTimeout(()=>{const open=app.querySelector(`[data-daily-open="edit-task-${CSS.escape(button.dataset.openTaskId)}"]`);open?.click()},50);return}if(event.target.closest('[data-recovery-toggle]')){const saved=parseStore(RECOVERY_KEY);if(saved[today()])delete saved[today()];else saved[today()]={active:true,startedAt:new Date().toISOString()};saveStore(RECOVERY_KEY,saved);decorateRecovery();return}if(event.target.closest('[data-maintenance-add]')){openMaintenance();return}button=event.target.closest('[data-maintenance-edit]');if(button){openMaintenance(maintenanceRows().find(row=>String(row.id)===String(button.dataset.maintenanceEdit))||{});return}button=event.target.closest('[data-maintenance-complete]');if(button){const row=maintenanceRows().find(item=>String(item.id)===String(button.dataset.maintenanceComplete));if(row){const done=today(),next=nextMaintenanceDate(done,row.maintenanceFrequencyDays),history=[...list(row.maintenanceHistory),{date:done,completedAt:new Date().toISOString()}];updateV5Record('life.tasks',row.id,{lastCompleted:done,nextSuggestedDate:next,date:next,dueDate:next,done:false,completed:false,maintenanceHistory:history});rerender()}return}if(event.target.closest('[data-maintenance-archive]')){const form=event.target.closest('[data-intelligence-modal]')?.querySelector('[data-maintenance-form]');if(form?.dataset.id&&window.confirm('Archive this maintenance item?')){archiveV5Record('life.tasks',form.dataset.id);close(form.closest('[data-intelligence-modal]'));rerender()}return}if(event.target.closest('[data-mc-forgetting]')){openForgetting();return}},true);

app.addEventListener('submit',event=>{let form=event.target.closest('[data-brain-dump-form]');if(form){event.preventDefault();const lines=text(new FormData(form).get('thoughts')).split(/\n+/).map(text).filter(Boolean);if(!lines.length)return;form.outerHTML=`<form data-brain-approve>${proposals(lines)}<p class="brain-approval-note">Review every destination. Nothing saves until you approve this list.</p><div class="button-row daily-actions"><button class="btn primary">Approve + save</button><button type="button" class="btn soft" data-intelligence-close>Cancel</button></div></form>`;return}form=event.target.closest('[data-brain-approve]');if(form){event.preventDefault();const data=new FormData(form),lines=[...form.querySelectorAll('input[name^="line-"]')];for(const input of lines){const index=input.name.split('-').pop(),result=saveProposal(input.value,data.get(`destination-${index}`));if(!result?.ok){window.alert(result?.error||`Could not save “${input.value}”.`);return}}close(form.closest('[data-intelligence-modal]'));window.dispatchEvent(new CustomEvent('katos:mochini-state',{detail:{mood:'proud',activityId:'notes',activity:'sorting the brain dump with you',line:`Sorted ${lines.length} thought${lines.length===1?'':'s'} after you approved every destination.`}}));rerender();return}form=event.target.closest('[data-decompose-form]');if(form){event.preventDefault();const steps=new FormData(form).getAll('step');if(!steps.length)return;for(const label of steps)runV5DailyAction({type:'add-child-step',kind:'task',id:form.dataset.taskId,label});close(form.closest('[data-intelligence-modal]'));rerender();return}form=event.target.closest('[data-maintenance-form]');if(form){event.preventDefault();const data=Object.fromEntries(new FormData(form)),frequency=Math.max(1,Number(data.frequency)||30),next=nextMaintenanceDate(data.lastCompleted,frequency);if(form.dataset.id)updateV5Record('life.tasks',form.dataset.id,{text:text(data.title),title:text(data.title),lastCompleted:data.lastCompleted,maintenanceFrequencyDays:frequency,nextSuggestedDate:next,date:next,dueDate:next,notes:text(data.notes),maintenance:true,done:false});else{const result=runV5DailyAction({type:'quick-add',kind:'task',title:text(data.title),date:next,forToday:false,energy:'medium'});if(result.ok)updateV5Record('life.tasks',result.result.id,{maintenance:true,lastCompleted:data.lastCompleted,maintenanceFrequencyDays:frequency,nextSuggestedDate:next,date:next,dueDate:next,notes:text(data.notes),done:false})}close(form.closest('[data-intelligence-modal]'));rerender();return}},true);

app.addEventListener('change',event=>{const input=event.target.closest('[data-adaptive-date]');if(!input)return;const container=input.closest('[data-adaptive-goal]'),saved=parseStore(ADAPTIVE_KEY),goal={...(saved[container.dataset.goalId]||{})};goal[input.dataset.adaptiveDate]=Math.max(0,Number(input.value)||0);saved[container.dataset.goalId]=goal;saveStore(ADAPTIVE_KEY,saved);container.remove();decorateAdaptiveGoal()});

app.addEventListener('submit',event=>{const form=event.target.closest('[data-daily-task-edit][data-daily-kind="task"]');if(!form)return;const actual=Math.max(0,Number(form.elements.namedItem('actualMinutes')?.value)||0),id=form.dataset.dailyId;if(!actual)return;setTimeout(()=>{const task=taskById(id);if(!task||Number(task.lastLoggedActualMinutes)===actual)return;const history=[...list(task.durationHistory),{date:today(),estimatedMinutes:Number(task.minutes)||0,actualMinutes:actual,loggedAt:new Date().toISOString()}].slice(-30);updateV5Record('life.tasks',id,{actualMinutes:actual,lastLoggedActualMinutes:actual,durationHistory:history})},0)},true);
window.addEventListener('katos:rendered',queue);
new MutationObserver(queue).observe(app,{childList:true,subtree:true});
decorate();
