import{applyDailyAction}from'./daily-shit.js?v=5.5.0-lifestyle';

const list=value=>Array.isArray(value)?value:[];
const obj=value=>value&&typeof value==='object'&&!Array.isArray(value)?value:{};
const text=value=>String(value??'').trim();
const clone=value=>{try{return structuredClone(value)}catch{return JSON.parse(JSON.stringify(value||{}))}};
const now=()=>new Date().toISOString();
const makeId=prefix=>`${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;
const validDate=value=>/^\d{4}-\d{2}-\d{2}$/.test(text(value));
const todayKey=value=>validDate(value)?text(value):new Date(value||Date.now()).toISOString().slice(0,10);
const byId=(rows,id)=>list(rows).find(row=>String(row?.id)===String(id));
const active=row=>!row?.archivedAt&&row?.status!=='archived';

export const EMPTY_LIFESTYLE={version:1,movement:{types:[],plans:[],activities:[],goals:[]},hobbies:{items:[],projects:[],resources:[]},growth:{areas:[],goals:[],milestones:[],wins:[],reflections:[]},migration:{version:1,receipts:[]}};

function normalize(source){const input=obj(source?.lifestyle),state={...clone(EMPTY_LIFESTYLE),...clone(input)};state.movement={...EMPTY_LIFESTYLE.movement,...obj(input.movement)};state.hobbies={...EMPTY_LIFESTYLE.hobbies,...obj(input.hobbies)};state.growth={...EMPTY_LIFESTYLE.growth,...obj(input.growth)};for(const group of ['movement','hobbies','growth'])for(const key of Object.keys(EMPTY_LIFESTYLE[group]))state[group][key]=list(state[group][key]);state.migration={...EMPTY_LIFESTYLE.migration,...obj(input.migration),receipts:list(input.migration?.receipts)};return state}
function titleOf(row,fallback='Untitled'){return text(row?.title||row?.name||row?.label||row?.hobby||row?.goal||row?.type)||fallback}
function stableId(prefix,row,index){return`${prefix}:${text(row?.id)||index}`}
function addLegacy(rows,id,record){if(rows.some(row=>row.id===id||text(row.legacyId)===text(record.legacyId)))return 0;rows.push(record);return 1}
function archivePeople(source,state){source.v4=obj(source.v4);source.v4.archive=list(source.v4.archive);let added=0;list(source.v4.people).forEach((row,index)=>{const legacyId=text(row?.id)||String(index),words=`${titleOf(row)} ${text(row?.notes||row?.important||row?.plan)}`.toLowerCase();if(/hobby|anime|game|art|cosplay|collect|music|book/.test(words)){added+=addLegacy(state.hobbies.items,`myloves-hobby:${legacyId}`,{id:`myloves-hobby:${legacyId}`,legacyId,title:titleOf(row),category:'interest',status:'on-shelf',energy:'low',minutes:30,nextStep:'',notes:text(row?.notes||row?.important),source:'my-loves-preserved',createdAt:now()});return}if(/dream|goal|aspir|someday|want to|career|move to|learn/.test(words)){added+=addLegacy(state.growth.goals,`myloves-growth:${legacyId}`,{id:`myloves-growth:${legacyId}`,legacyId,title:titleOf(row),areaId:'',status:'future',targetDate:'',nextStep:text(row?.plan),notes:text(row?.notes||row?.important),source:'my-loves-preserved',createdAt:now()});return}const archiveId=`my-loves-preserved:${legacyId}`;if(!source.v4.archive.some(item=>item.id===archiveId)){source.v4.archive.push({id:archiveId,kind:'v4.people',originalId:legacyId,title:titleOf(row,'Preserved My Loves note'),data:clone(row),reason:'Sentimental or ambiguous My Loves information preserved during Pass 5.',archivedAt:now()});added++}});return added}
function migrate(source,state){let added=0;const movementRows=[...list(source?.movement?.sessions),...list(source?.movement?.logs),...list(source?.movement?.history)];movementRows.forEach((row,index)=>{const id=stableId('legacy-movement',row,index);added+=addLegacy(state.movement.activities,id,{id,legacyId:text(row?.id),title:titleOf(row,'Movement'),movementType:text(row?.movementType||row?.type)||'other',date:validDate(row?.date)?row.date:todayKey(),minutes:Number(row?.minutes||row?.duration)||0,intensity:text(row?.intensity)||'gentle',status:row?.skipped?'skipped':'completed',energy:text(row?.energy)||'medium',notes:text(row?.notes||row?.note),source:'legacy-movement',createdAt:text(row?.createdAt)||now()})});list(source?.movement?.routines).forEach((row,index)=>{const id=stableId('legacy-movement-plan',row,index);added+=addLegacy(state.movement.plans,id,{id,legacyId:text(row?.id),title:titleOf(row,'Movement plan'),movementType:text(row?.movementType||row?.type)||'other',minutes:Number(row?.minutes||row?.duration)||15,intensity:text(row?.intensity)||'gentle',energy:text(row?.energy)||'low',timeOfDay:text(row?.timeOfDay)||'anytime',status:'active',notes:text(row?.notes),source:'legacy-movement',createdAt:text(row?.createdAt)||now()})});list(source?.v4?.hobbies).forEach((row,index)=>{const id=stableId('legacy-hobby',row,index),legacyStatus=text(row?.status).toLowerCase(),status={playing:'current',current:'current',curious:'exploring',exploring:'exploring',shelf:'on-shelf',paused:'on-shelf',someday:'want-to-try'}[legacyStatus]||'on-shelf';added+=addLegacy(state.hobbies.items,id,{id,legacyId:text(row?.id),title:titleOf(row,'Hobby'),category:text(row?.category||row?.kind)||'other',status,energy:text(row?.energy).toLowerCase()||'low',minutes:Number(row?.minutes)||30,nextStep:text(row?.next||row?.nextStep),notes:text(row?.notes||row?.note),source:'legacy-hobby',createdAt:text(row?.createdAt)||now()})});list(source?.growth?.goals).forEach((row,index)=>{const id=stableId('legacy-growth-goal',row,index);added+=addLegacy(state.growth.goals,id,{id,legacyId:text(row?.id),title:titleOf(row,'Growth goal'),areaId:text(row?.areaId||row?.area),status:text(row?.status)||'active',targetDate:validDate(row?.targetDate||row?.dueDate)?text(row?.targetDate||row?.dueDate):'',nextStep:text(row?.next||row?.nextStep),notes:text(row?.notes||row?.why),source:'legacy-growth',createdAt:text(row?.createdAt)||now()})});list(source?.growth?.wins).forEach((row,index)=>{const id=stableId('legacy-growth-win',row,index);added+=addLegacy(state.growth.wins,id,{id,legacyId:text(row?.id),title:titleOf(row,'A win'),date:validDate(row?.date)?row.date:todayKey(),areaId:text(row?.areaId||row?.area),notes:text(row?.notes),source:'legacy-growth',createdAt:text(row?.createdAt)||now()})});added+=archivePeople(source,state);return added}

export function initializeLifestyle(source={},today=todayKey()){const next=clone(source),lifestyle=normalize(next);let changes=migrate(next,lifestyle);if(!lifestyle.migration.receipts.some(row=>row.key==='pass5-v1')){lifestyle.migration.receipts.push({key:'pass5-v1',at:now(),note:'Additive lifestyle migration; legacy Movement, Hobbies, Growth, and My Loves records retained.'});changes++}next.lifestyle=lifestyle;return{state:next,lifestyle,changed:changes>0,changes,today}}

export const getMovementPlans=source=>normalize(source).movement.plans.filter(active);
export const getMovementActivities=source=>normalize(source).movement.activities.filter(active);
export const getHobbies=source=>normalize(source).hobbies.items.filter(active);
export const getHobbyProjects=source=>normalize(source).hobbies.projects.filter(active);
export const getGrowthGoals=source=>normalize(source).growth.goals.filter(active);
export const getGrowthWins=source=>normalize(source).growth.wins.filter(active);
export function getMovementSummary(source,today=todayKey()){const rows=getMovementActivities(source),start=new Date(`${today}T12:00:00`);start.setDate(start.getDate()-((start.getDay()+6)%7));const from=todayKey(start),week=rows.filter(row=>row.date>=from&&row.date<=today&&row.status==='completed');return{weekCount:week.length,weekMinutes:week.reduce((sum,row)=>sum+(Number(row.minutes)||0),0),completed:rows.filter(row=>row.status==='completed').length,skipped:rows.filter(row=>row.status==='skipped').length}}
export function getRecommendedMovement(source,{energy='medium',minutes=30,timeOfDay='anytime'}={}){const rank={tiny:0,low:1,medium:2,high:3},limit=rank[text(energy).toLowerCase()]??2;return getMovementPlans(source).filter(row=>(rank[text(row.energy).toLowerCase()]??1)<=limit&&(Number(row.minutes)||0)<=Number(minutes||30)&&(row.timeOfDay==='anytime'||row.timeOfDay===timeOfDay)).sort((a,b)=>(Number(a.minutes)||0)-(Number(b.minutes)||0)||a.title.localeCompare(b.title))[0]||null}
export function getHobbyRecommendation(source,{mode='normal'}={}){const caps={tiny:[0,10],chill:[1,45],normal:[2,90],'locked-in':[3,999]},[energy,max]=caps[mode]||caps.normal,rank={tiny:0,low:1,medium:2,high:3};return getHobbies(source).filter(row=>['current','exploring','want-to-try'].includes(row.status)&&(rank[row.energy]??1)<=energy&&(Number(row.minutes)||30)<=max).sort((a,b)=>(Number(a.minutes)||30)-(Number(b.minutes)||30)||a.title.localeCompare(b.title))[0]||null}
export function getGrowthNextStep(source){return getGrowthGoals(source).filter(row=>row.status==='active').sort((a,b)=>(a.targetDate||'9999').localeCompare(b.targetDate||'9999')||a.title.localeCompare(b.title))[0]||null}
export function selectLifestyle(source={},today=todayKey()){const initialized=initializeLifestyle(source,today),state=initialized.state;return{...initialized,movement:{plans:getMovementPlans(state),activities:getMovementActivities(state),goals:normalize(state).movement.goals.filter(active),summary:getMovementSummary(state,today),recommendation:getRecommendedMovement(state,{energy:'low',minutes:20})},hobbies:{items:getHobbies(state),projects:getHobbyProjects(state),resources:normalize(state).hobbies.resources.filter(active),recommendation:getHobbyRecommendation(state,{mode:'normal'})},growth:{areas:normalize(state).growth.areas.filter(active),goals:getGrowthGoals(state),milestones:normalize(state).growth.milestones.filter(active),wins:getGrowthWins(state),reflections:normalize(state).growth.reflections.filter(active),nextStep:getGrowthNextStep(state)}}}

function collection(state,kind){const map={movementPlan:state.movement.plans,'movement-plan':state.movement.plans,movementActivity:state.movement.activities,'movement-activity':state.movement.activities,movementGoal:state.movement.goals,'movement-goal':state.movement.goals,hobby:state.hobbies.items,hobbyProject:state.hobbies.projects,'hobby-project':state.hobbies.projects,hobbyResource:state.hobbies.resources,'hobby-resource':state.hobbies.resources,growthArea:state.growth.areas,'growth-area':state.growth.areas,growthGoal:state.growth.goals,'growth-goal':state.growth.goals,growthMilestone:state.growth.milestones,'growth-milestone':state.growth.milestones,growthWin:state.growth.wins,'growth-win':state.growth.wins,growthReflection:state.growth.reflections,'growth-reflection':state.growth.reflections};return map[kind]}
function saveRow(rows,id,input,prefix){const existing=byId(rows,id),result=existing?{...existing,...input,id:existing.id,updatedAt:now()}:{id:makeId(prefix),...input,createdAt:now()};if(existing)rows[rows.indexOf(existing)]=result;else rows.push(result);return result}
function archive(state,kind,id){const rows=collection(state,kind),row=byId(rows,id);if(!row)return null;const result={...row,status:'archived',archivedAt:now(),updatedAt:now()};rows[rows.indexOf(row)]=result;return result}
export function applyLifestyleAction(source,action={},today=todayKey()){const initialized=initializeLifestyle(source,today),next=initialized.state,state=normalize(next),type=text(action.type);next.lifestyle=state;let result;
 if(type==='archive'){result=archive(state,action.kind,action.id);if(!result)return{ok:false,error:'That lifestyle record is no longer here.'};const paths={'movement-plan':'lifestyle.movement.plans','movement-activity':'lifestyle.movement.activities','movement-goal':'lifestyle.movement.goals',hobby:'lifestyle.hobbies.items','hobby-project':'lifestyle.hobbies.projects','hobby-resource':'lifestyle.hobbies.resources','growth-area':'lifestyle.growth.areas','growth-goal':'lifestyle.growth.goals','growth-milestone':'lifestyle.growth.milestones','growth-win':'lifestyle.growth.wins','growth-reflection':'lifestyle.growth.reflections'};next.v4=obj(next.v4);next.v4.archive=list(next.v4.archive);next.v4.archive.push({id:makeId('archive'),kind:paths[action.kind]||`lifestyle.${action.kind}`,originalId:result.id,title:titleOf(result),data:clone(result),archivedAt:now()});return{ok:true,state:next,result}}
 if(type==='movement-plan-save')result=saveRow(state.movement.plans,action.id,{title:text(action.title),movementType:text(action.movementType)||'other',minutes:Math.max(0,Number(action.minutes)||0),intensity:text(action.intensity)||'gentle',energy:text(action.energy)||'low',timeOfDay:text(action.timeOfDay)||'anytime',status:text(action.status)||'active',notes:text(action.notes)},'movement-plan');
 else if(type==='movement-activity-save')result=saveRow(state.movement.activities,action.id,{title:text(action.title),planId:text(action.planId),movementType:text(action.movementType)||'other',date:validDate(action.date)?action.date:today,minutes:Math.max(0,Number(action.minutes)||0),intensity:text(action.intensity)||'gentle',energy:text(action.energy)||'medium',status:text(action.status)||'planned',notes:text(action.notes)},'movement-activity');
 else if(type==='movement-goal-save')result=saveRow(state.movement.goals,action.id,{title:text(action.title),targetPerWeek:Math.max(0,Number(action.targetPerWeek)||0),status:text(action.status)||'active',notes:text(action.notes)},'movement-goal');
 else if(type==='hobby-save')result=saveRow(state.hobbies.items,action.id,{title:text(action.title),category:text(action.category)||'other',status:text(action.status)||'exploring',energy:text(action.energy)||'low',minutes:Math.max(0,Number(action.minutes)||0),nextStep:text(action.nextStep),notes:text(action.notes)},'hobby');
 else if(type==='hobby-project-save')result=saveRow(state.hobbies.projects,action.id,{title:text(action.title),hobbyId:text(action.hobbyId),status:text(action.status)||'active',targetDate:validDate(action.targetDate)?action.targetDate:'',nextStep:text(action.nextStep),notes:text(action.notes)},'hobby-project');
 else if(type==='hobby-resource-save')result=saveRow(state.hobbies.resources,action.id,{title:text(action.title),hobbyId:text(action.hobbyId),kind:text(action.resourceKind)||'supply',status:text(action.status)||'have',notes:text(action.notes)},'hobby-resource');
 else if(type==='growth-area-save')result=saveRow(state.growth.areas,action.id,{title:text(action.title),status:text(action.status)||'active',notes:text(action.notes)},'growth-area');
 else if(type==='growth-goal-save')result=saveRow(state.growth.goals,action.id,{title:text(action.title),areaId:text(action.areaId),status:text(action.status)||'active',targetDate:validDate(action.targetDate)?action.targetDate:'',nextStep:text(action.nextStep),notes:text(action.notes)},'growth-goal');
 else if(type==='growth-milestone-save')result=saveRow(state.growth.milestones,action.id,{title:text(action.title),goalId:text(action.goalId),status:text(action.status)||'active',targetDate:validDate(action.targetDate)?action.targetDate:'',notes:text(action.notes)},'growth-milestone');
 else if(type==='growth-win-save')result=saveRow(state.growth.wins,action.id,{title:text(action.title),areaId:text(action.areaId),date:validDate(action.date)?action.date:today,notes:text(action.notes)},'growth-win');
 else if(type==='growth-reflection-save')result=saveRow(state.growth.reflections,action.id,{title:text(action.title)||'Reflection',goalId:text(action.goalId),date:validDate(action.date)?action.date:today,notes:text(action.notes)},'growth-reflection');
 else if(type==='link-daily'){const rows=collection(state,action.kind),row=byId(rows,action.id);if(!row)return{ok:false,error:'That record is no longer here.'};const linked=applyDailyAction(next,{type:'ensure-linked',kind:'task',externalId:`lifestyle:${action.kind}:${row.id}`,title:action.kind==='movementActivity'?`Do ${titleOf(row)}`:`Next: ${text(row.nextStep)||titleOf(row)}`,date:validDate(row.date||row.targetDate)?text(row.date||row.targetDate):today,priority:'today',energy:row.energy||'low',duration:Number(row.minutes)||10,sourceId:row.id,sourceType:`lifestyle-${action.kind}`},today);return linked.ok?{...linked,lifestyleResult:row}:linked}
 else return{ok:false,error:'That lifestyle action is not available.'};
 if(!titleOf(result,''))return{ok:false,error:'Add a name first.'};return{ok:true,state:next,result}}
