import{snapshotV4,selectV5MoneyGig,getGigGoalProgress}from'./data.js?v=7.3.0-money-mission';
import{chooseTrackedGigGoal,buildGigGoalRunway}from'./gig-goal-runway.js?v=7.0.15-gig-goal-tracker';
import{buildShiftScorecards}from'./optimization-core.js?v=7.1.0-optimization-pass';
import{buildMoneyMission}from'./money-mission-core.js?v=7.3.4-account-goals';

const app=document.querySelector('#app'),list=value=>Array.isArray(value)?value:[],esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char])),money=value=>Number(value||0).toLocaleString([],{style:'currency',currency:'USD'}),cents=value=>Math.round(Number(value||0)*100)/100;
function trackedMission(){const snapshot=snapshotV4(),view=selectV5MoneyGig(snapshot.today),goal=chooseTrackedGigGoal(list(view.gig?.goals).filter(row=>!row.archivedAt&&row.active!==false),snapshot.today);if(!goal)return{snapshot,view,mission:null};const raw=getGigGoalProgress(snapshot.state,goal.id,snapshot.today)||{goal,earned:0,range:{from:goal.startDate,to:goal.endDate}},earned=Math.max(0,cents(Number(raw.earned||0)+Number(goal.progressAdjustment||0))),runway=buildGigGoalRunway({goal,progress:{...raw,earned},shifts:list(snapshot.state?.work?.gigShifts),platforms:view.gig?.platforms,today:snapshot.today}),scorecards=buildShiftScorecards(snapshot.state?.work?.gigShifts,view.gig?.orders),account=list(view.hq?.accounts).find(row=>String(row.id)===String(goal.linkedAccountId)),balance=account?view.accountBalances?.[account.id]?.posted:null,linkedAccount=account&&Number.isFinite(Number(balance))?{id:account.id,name:account.name,balance}:null;return{snapshot,view,mission:buildMoneyMission({runway,transactions:view.transactions,completedShifts:scorecards,today:snapshot.today,linkedAccount})}}
function markup(m){if(!m)return'';const rate=m.netHourly?`${money(m.netHourly)}/hr average net`:m.estimatedHours?'':'Log a completed shift to estimate hours',hours=m.estimatedHours?`About ${m.estimatedHours} more hour${m.estimatedHours===1?'':'s'} at your recent net rate`:`${money(m.dailyNeeded)} per remaining day`,account=m.linkedAccount,accountCard=account?`<div class="account"><small>IN ${esc(account.name).toUpperCase()}</small><b>${money(account.balance)}</b></div>`:'';
 return`<div class="money-mission ${account?'has-linked-account':''}" data-money-mission><div class="money-mission-status ${esc(m.status)}"><b>${esc(m.statusLabel)}</b><span>${m.daysLeft?`${m.daysLeft} day${m.daysLeft===1?'':'s'} left`:'Deadline reached'}</span></div><div class="money-mission-ledger"><div><small>GROSS EARNED</small><b>${money(m.grossEarned)}</b></div><div class="cost"><small>GIG COSTS</small><b>−${money(m.expenses.total)}</b></div><div class="net"><small>NET EARNED</small><b>${money(m.netEarned)}</b></div>${accountCard}<div><small>SCHEDULED</small><b>${money(m.planned)}</b></div><div><small>STILL NEEDED</small><b>${money(m.unplanned)}</b></div></div><div class="money-mission-bar" role="progressbar" aria-label="${account?'Money held and scheduled':'Net earned and scheduled'} mission progress" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${Math.round(m.coveredPercent)}"><i class="earned" style="width:${m.earnedPercent}%"></i><i class="planned" style="left:${m.earnedPercent}%;width:${m.plannedPercent}%"></i></div><div class="money-mission-foot"><span>${esc(hours)}</span><span>${esc(rate)}</span></div><p class="money-mission-rule">${account?`<b>${esc(account.name)}</b> is the source of truth for money you actually have toward this goal. Scheduled shifts stay separate until the money reaches that account.`:'Gas, tolls, parking, linked gig expenses, and <b>Shift Food</b> subtract automatically. Regular Food stays personal.'}</p><div class="money-mission-actions"><button type="button" class="btn soft" data-doordash-add>🚗 Plan DoorDash</button><button type="button" class="btn soft" data-flex-add>📦 Plan Flex</button></div></div>`}
function decorate(){const card=[...app.querySelectorAll('.money-card')].find(node=>/GIG GOAL TRACKER|MONEY MISSION|TODAY'S GOAL/i.test(node.querySelector('.ey')?.textContent||''));if(!card)return;const {mission}=trackedMission(),ey=card.querySelector('.ey'),copy=card.querySelector('.card-head p');if(ey)ey.textContent='🎯 MONEY MISSION';if(copy&&mission?.linkedAccount)copy.textContent=`${mission.linkedAccount.name} holds the real money. Earned and scheduled work stay visible without pretending they are cash.`;card.querySelector('[data-gig-goal-runway]')?.remove();card.querySelector('[data-money-mission]')?.remove();const anchor=card.querySelector('.money-progress.big')||card.querySelector('.card-head');anchor?.insertAdjacentHTML('afterend',markup(mission));const goalStat=app.querySelector('.stat-grid .stat:nth-child(2)');if(goalStat&&mission)goalStat.innerHTML=`<small>GOAL</small><b>${Math.round(mission.coveredPercent)}%</b><span>${money(mission.unplanned)} still needed${mission.linkedAccount?` · ${esc(mission.linkedAccount.name)} linked`:''}</span>`;const expense=[...app.querySelectorAll('[data-money-open="new-gig-expense"]')][0];if(expense)expense.textContent='⛽ Gig cost';decorateCategories()}
function decorateCategories(){const form=app.querySelector('[data-money-ledger-form], [data-money-form="quick-transaction"], [data-money-form="transaction-save"]');if(!form)return;const select=form.elements?.category;if(select?.tagName==='SELECT'){['Shift Food','Tolls','Parking'].forEach(value=>{if(![...select.options].some(option=>option.value===value))select.add(new Option(value,value))})}else if(select&&!select.list){const id='money-mission-categories',data=document.createElement('datalist');data.id=id;data.innerHTML=['Gas','Tolls','Parking','Shift Food','Food','Bills','Other'].map(value=>`<option value="${value}">`).join('');form.append(data);select.setAttribute('list',id)}if(select&&!form.querySelector('[data-gig-cost-help]'))select.closest('label,div')?.insertAdjacentHTML('afterend','<p class="money-mission-form-help" data-gig-cost-help>Choose <b>Shift Food</b> as the category—or write “Shift Food” in the description—for food bought during a gig shift. Gas, tolls, and parking reduce Money Mission too.</p>')}
window.addEventListener('katos:rendered',()=>queueMicrotask(decorate));
new MutationObserver(()=>{if(!app.querySelector('[data-money-mission]'))decorate();else decorateCategories()}).observe(app,{childList:true,subtree:true});
