import assert from'node:assert/strict';
import{applyMoneyGigAction,getAccountBalance,getBillInstances,getCashFlowSummary,getFinancialGoals,getGigEarningsSummary,getGigGoalProgress,getGigPlatformComparison,getLedgerTransactions,getMoneySummary,getPendingGigPayouts,getSubscriptions,initializeMoneyGig,selectMoneyGig}from'./money-gig.js';

const today='2026-09-03';
let state={schemaVersion:4,life:{tasks:[],reminders:[],routines:[],routineInstances:[]},work:{shifts:[],hq:{sessionPlans:[]}},money:{accounts:[],bills:[],subscriptions:[],savingsGoals:[],debts:[]},v4:{archive:[]}};
const run=action=>{const result=applyMoneyGigAction(state,action,today);assert.equal(result.ok,true,result.error);state=result.state;return result.result};

const initialized=initializeMoneyGig(state,today);
assert.equal(initialized.gig.platforms.some(row=>row.name==='Shipt'),true);
assert.equal(initialized.gig.platforms.some(row=>row.name==='DoorDash'),true);
const again=initializeMoneyGig(initialized.state,today);
assert.equal(again.changed,false,'Pass 4 initialization is idempotent');
assert.equal(again.gig.platforms.length,2,'platform seeds never duplicate');
state=again.state;

const checking=run({type:'account-save',name:'Everyday Checking',accountType:'checking',openingBalance:1000});
const savings=run({type:'account-save',name:'Savings',accountType:'savings',openingBalance:100});
const secondChecking=run({type:'account-save',name:'Travel Checking',accountType:'checking',openingBalance:20});
const card=run({type:'account-save',name:'Discover',accountType:'credit-card',openingBalance:0,creditLimit:2000});
run({type:'transaction-save',transactionType:'income',accountId:checking.id,amount:250,date:today,merchant:'Paycheck',status:'posted'});
const groceries=run({type:'transaction-save',transactionType:'expense',accountId:checking.id,amount:42,date:today,merchant:'Groceries',category:'Food',status:'posted'});
run({type:'transaction-save',transactionType:'expense',accountId:checking.id,amount:20,date:today,merchant:'Pending gas',status:'pending'});
run({type:'transaction-save',transactionType:'refund',accountId:checking.id,amount:10,date:today,merchant:'Grocery refund',refundOfId:groceries.id,status:'posted'});
run({type:'transaction-save',transactionType:'adjustment',accountId:checking.id,amount:5,signedAmount:5,date:today,merchant:'Reconciliation',status:'cleared'});
assert.equal(getAccountBalance(state,checking.id),1223,'posted balance derives from opening balance plus posted effects');
assert.equal(getAccountBalance(state,checking.id,{includePending:true}),1203,'projected balance includes pending effects');

run({type:'transaction-save',id:groceries.id,transactionType:'expense',accountId:checking.id,amount:45,date:today,merchant:'Groceries corrected',category:'Food',status:'posted'});
assert.equal(getLedgerTransactions(state).find(row=>row.id===groceries.id).amount,45,'transaction edits update the canonical row');
assert.equal(getLedgerTransactions(state).filter(row=>row.id===groceries.id).length,1,'transaction edits never duplicate');

run({type:'transaction-save',transactionType:'transfer',accountId:checking.id,toAccountId:savings.id,amount:200,date:today,merchant:'Move to savings',status:'posted',externalId:'transfer:test:savings'});
assert.equal(getAccountBalance(state,checking.id),1020);
assert.equal(getAccountBalance(state,savings.id),300,'checking to savings changes both balances');
run({type:'transaction-save',transactionType:'transfer',accountId:checking.id,toAccountId:secondChecking.id,amount:50,date:today,merchant:'Move between checking',status:'posted',externalId:'transfer:test:checking'});
assert.equal(getAccountBalance(state,secondChecking.id),70,'checking to checking is explicit account movement');
const transferCount=getLedgerTransactions(state).filter(row=>row.externalId==='transfer:test:checking').length;
run({type:'transaction-save',transactionType:'transfer',accountId:checking.id,toAccountId:secondChecking.id,amount:50,date:today,merchant:'Move between checking',status:'posted',externalId:'transfer:test:checking'});
assert.equal(getLedgerTransactions(state).filter(row=>row.externalId==='transfer:test:checking').length,transferCount,'stable transfer IDs deduplicate');
run({type:'transaction-save',transactionType:'expense',accountId:card.id,amount:50,date:today,merchant:'Card groceries',category:'Food',status:'posted'});
assert.equal(getAccountBalance(state,card.id),50,'credit-card purchase raises debt');
run({type:'transaction-save',transactionType:'payment',accountId:checking.id,toAccountId:card.id,amount:30,date:today,merchant:'Discover payment',status:'posted'});
assert.equal(getAccountBalance(state,card.id),20,'credit-card payment reduces debt');
const flow=getCashFlowSummary(state,{from:today,to:today});
assert.equal(flow.received,250);
assert.equal(flow.spent,85,'expenses count once, refunds reduce spending, and transfers/card payments are excluded');

const rent=run({type:'bill-save',name:'Rent',expectedAmount:700,amountType:'fixed',recurrence:'monthly',dueDay:5,accountId:checking.id});
const electric=run({type:'bill-save',name:'Electric',expectedAmount:80,amountType:'variable',recurrence:'monthly',dueDay:10,accountId:checking.id});
const weekly=run({type:'bill-save',name:'Weekly payment',expectedAmount:15,recurrence:'weekly',dueDate:today,accountId:checking.id});
const monthEndBill=run({type:'bill-save',name:'Month end',expectedAmount:25,recurrence:'monthly',dueDay:31,accountId:checking.id});
let instances=getBillInstances(state,{from:today,to:'2026-10-12',today});
assert.equal(instances.filter(row=>row.billId===rent.id).length,2,'monthly bill recurrence produces separate instances');
assert.equal(instances.filter(row=>row.billId===weekly.id).length,6,'weekly bill recurrence is supported');
const electricInstance=instances.find(row=>row.billId===electric.id);
run({type:'bill-instance-save',id:electricInstance.id,status:'changed',actualAmount:103.42,notes:'Actual statement'});
instances=getBillInstances(state,{from:today,to:'2026-09-15',today});
assert.equal(instances.find(row=>row.id===electricInstance.id).actualAmount,103.42,'variable amount applies to one occurrence');
const rentInstance=instances.find(row=>row.billId===rent.id);
run({type:'bill-instance-save',id:rentInstance.id,status:'paid'});
assert.equal(getBillInstances(state,{from:'2026-09-01',to:'2026-09-30',today}).find(row=>row.id===rentInstance.id).status,'paid','manual paid status is preserved even before a transaction is attached');
let activeBills=selectMoneyGig(state,today).bills;
assert.equal(activeBills.some(row=>row.id===rentInstance.id),false,'paid September instance does not reappear in the active September list');
assert.equal(activeBills.some(row=>row.billId===rent.id&&row.dueDate==='2026-10-05'),true,'the next monthly bill instance remains October');
run({type:'bill-record-payment',id:rentInstance.id,paymentType:'expense',accountId:checking.id,amount:700,date:'2026-09-05',merchant:'Rent'});
const paymentCount=getLedgerTransactions(state).filter(row=>row.billInstanceId===rentInstance.id).length;
run({type:'bill-record-payment',id:rentInstance.id,paymentType:'expense',accountId:checking.id,amount:700,date:'2026-09-05',merchant:'Rent corrected'});
assert.equal(getLedgerTransactions(state).filter(row=>row.billInstanceId===rentInstance.id).length,paymentCount,'bill payment linkage is idempotent');
assert.equal(getBillInstances(state,{from:'2026-09-05',to:'2026-09-05',today:'2026-09-06'})[0].status,'paid');
assert.equal(getBillInstances(state,{from:'2027-02-01',to:'2027-02-28',today:'2027-02-01'}).find(row=>row.billId===monthEndBill.id).dueDate,'2027-02-28','day 31 resolves to the final valid day in a short month');
const invalidBill=applyMoneyGigAction(state,{type:'bill-save',name:'Invalid day',expectedAmount:10,recurrence:'monthly',dueDay:32,accountId:checking.id},today);
assert.equal(invalidBill.ok,false,'monthly due day is constrained to 1 through 31');
run({type:'bill-link-daily',id:rentInstance.id});
run({type:'bill-link-daily',id:rentInstance.id});
assert.equal(state.life.tasks.filter(row=>row.externalId===`money:bill:${rentInstance.id}`).length,1,'bill Daily Shit action uses a stable occurrence ID');

const sophia=run({type:'subscription-save',name:'Sophia',amount:99,billingCycle:'monthly',nextRenewal:'2026-09-20',trialEnd:'2026-09-10',academicContext:'Study Nook',status:'active'});
assert.equal(getSubscriptions(state).find(row=>row.id===sophia.id).trialEnd,'2026-09-10','subscription trial end stays distinct from renewal');
run({type:'subscription-link-daily',id:sophia.id});
run({type:'subscription-link-daily',id:sophia.id});
assert.equal(state.life.tasks.filter(row=>row.externalId===`money:subscription:${sophia.id}`).length,1,'subscription Daily Shit link is idempotent');
run({type:'subscription-renew',id:sophia.id});
assert.equal(getSubscriptions(state).find(row=>row.id===sophia.id).nextRenewal,'2026-10-20','subscription renewal advances its cycle');
run({type:'subscription-save',id:sophia.id,name:'Sophia',amount:99,billingCycle:'monthly',nextRenewal:'2026-10-20',status:'canceled'});
assert.equal(getSubscriptions(state).find(row=>row.id===sophia.id).status,'canceled','canceled subscriptions remain preserved with an explicit state');

const linkedGoal=run({type:'goal-save',name:'Emergency Fund',targetAmount:1000,progressMethod:'linked-account',linkedAccountId:savings.id});
const manualGoal=run({type:'goal-save',name:'Trip',targetAmount:500,progressMethod:'manual',manualProgress:125});
const contributionGoal=run({type:'goal-save',name:'Move Fund',targetAmount:600,progressMethod:'contributions'});
run({type:'goal-contribute',id:contributionGoal.id,amount:50,date:today,externalId:'goal-transfer:one',linkedTransactionId:'transfer:test:savings'});
run({type:'goal-contribute',id:contributionGoal.id,amount:50,date:today,externalId:'goal-transfer:one',linkedTransactionId:'transfer:test:savings'});
const goalViews=selectMoneyGig(state,today).goals;
assert.equal(goalViews.find(row=>row.goal.id===linkedGoal.id).amount,300,'account-linked goal derives from the account balance');
assert.equal(goalViews.find(row=>row.goal.id===manualGoal.id).amount,125,'manual goal uses explicit progress');
assert.equal(goalViews.find(row=>row.goal.id===contributionGoal.id).amount,50,'linked contributions deduplicate and never create money movement');
assert.equal(getFinancialGoals(state).length,3);

const shipt=state.work.gig.platforms.find(row=>row.name==='Shipt'),doorDash=state.work.gig.platforms.find(row=>row.name==='DoorDash');
const shiptOrder=run({type:'order-save',platformId:shipt.id,date:today,basePay:18,tip:0,activeMinutes:60,onlineMinutes:90,mileage:12});
run({type:'order-save',id:shiptOrder.id,platformId:shipt.id,date:today,basePay:18,tip:27.93,activeMinutes:60,onlineMinutes:90,mileage:12});
const secondShipt=run({type:'order-save',platformId:shipt.id,date:today,basePay:15,tip:5,activeMinutes:30,onlineMinutes:40,mileage:5});
const doorOrder=run({type:'order-save',platformId:doorDash.id,date:today,basePay:24,promo:3,tip:8,activeMinutes:45,mileage:8});
const beforePayout=getAccountBalance(state,checking.id);
let gigSummary=getGigEarningsSummary(state,{from:today,to:today});
assert.equal(gigSummary.gross,100.93,'Shipt, DoorDash, and the late tip all count as earned once');
assert.equal(gigSummary.tips,40.93);
assert.equal(gigSummary.count,3);
assert.equal(gigSummary.mileage,25,'optional mileage rolls up only when recorded');
assert.notEqual(gigSummary.perActiveHour,null,'active-hour earnings appear only when time exists');
assert.equal(getGigPlatformComparison(state,{from:today,to:today}).length,2);
assert.equal(getAccountBalance(state,checking.id),beforePayout,'earned orders never change account balances');
const dailyGoal=run({type:'gig-goal-save',name:'Today 200',period:'day',targetAmount:200,startDate:today,endDate:today});
assert.equal(getGigGoalProgress(state,dailyGoal.id,today).remaining,99.07,'gig goal uses earned income');
assert.equal(selectMoneyGig(state,today).gigWeek.gross,100.93,'weekly gig total uses earned orders');
assert.equal(selectMoneyGig(state,today).gigMonth.gross,100.93,'monthly gig total uses earned orders');
run({type:'gig-link-daily',kind:'goal',id:dailyGoal.id,date:today});
run({type:'gig-link-daily',kind:'goal',id:dailyGoal.id,date:today});
assert.equal(state.life.tasks.filter(row=>row.externalId===`gig:goal:${dailyGoal.id}`).length,1,'gig Daily Shit action is idempotent');

const payout=run({type:'payout-save',platformId:shipt.id,orderIds:[shiptOrder.id,secondShipt.id],amount:'',status:'available',destinationAccountId:checking.id});
assert.equal(payout.orderIds.length,2,'one payout can group multiple orders from its platform');
assert.equal(payout.amount,65.93);
assert.equal(getPendingGigPayouts(state).length,1);
assert.equal(getAccountBalance(state,checking.id),beforePayout,'an available payout still is not bank money');
run({type:'payout-receive',id:payout.id,accountId:checking.id,date:'2026-09-04'});
const afterPayout=getAccountBalance(state,checking.id);
assert.equal(afterPayout,beforePayout+65.93,'received payout creates actual account income');
run({type:'payout-receive',id:payout.id,accountId:checking.id,date:'2026-09-04'});
assert.equal(getAccountBalance(state,checking.id),afterPayout,'repeating payout receipt does not double the deposit');
assert.equal(getLedgerTransactions(state).filter(row=>row.externalId===`gig-payout:${payout.id}`).length,1,'payout owns exactly one linked ledger transaction');
assert.equal(getPendingGigPayouts(state).length,0);
run({type:'gig-expense',accountId:checking.id,amount:10,date:today,merchant:'Parking',externalId:`gig-expense:${doorOrder.id}`});
run({type:'gig-expense',accountId:checking.id,amount:10,date:today,merchant:'Parking',externalId:`gig-expense:${doorOrder.id}`});
gigSummary=getGigEarningsSummary(state,{from:today,to:today});
assert.equal(gigSummary.linkedExpenses,10,'gig expenses reuse the canonical ledger and deduplicate');
assert.equal(gigSummary.simpleNet,90.93,'simple net is gross minus linked expenses, not tax-adjusted profit');

const balanceBeforeEstimate=getMoneySummary(state,today).posted;
run({type:'pay-rate-save',source:'ABA employer',hourlyRate:25,effectiveDate:'2026-09-01'});
state.work.shifts.push({id:'work-one',date:today,startTime:'09:00',endTime:'12:00'});
const selected=selectMoneyGig(state,today);
assert.equal(selected.estimatedWork.estimated,75);
assert.equal(selected.money.posted,balanceBeforeEstimate,'estimated Work HQ earnings do not affect balances');
assert.equal(selected.cashFlowToday.received,250,'today cash-flow selector is available');
assert.equal(selected.cashFlowWeek.net,selected.cashFlowMonth.net,'week/month selectors use the same canonical ledger for this fixture');

const legacy={life:{tasks:[]},work:{},money:{accounts:[{id:'old-checking',name:'Old checking',amount:400}],bills:[{id:'old-rent',name:'Old rent',amount:600,dueDay:1,paid:true,lastPaidDueDate:'2026-09-01'}],savingsGoals:[{id:'old-goal',name:'Old goal',current:20,target:200}],earnings:[{id:'old-gig',source:'Shipt',date:today,amount:30}],sourceBalances:{paycheck:150,gig:40},sourceBalancesInitializedAt:'2026-08-01T12:00:00Z',sourceSpending:[{id:'source-spend-1',bucket:'gig',amount:10,date:today,note:'Gas'}]},v4:{archive:[]}};
const migrated=initializeMoneyGig(legacy,today,{v5Ledger:[{id:'old-v5-ledger',kind:'expense',label:'Preserved expense',amount:12,date:today,account:'Old checking'}]});
const migratedAgain=initializeMoneyGig(migrated.state,today,{v5Ledger:[{id:'old-v5-ledger',kind:'expense',label:'Preserved expense',amount:12,date:today,account:'Old checking'}]});
assert.equal(migratedAgain.hq.accounts.length,migrated.hq.accounts.length);
assert.equal(migratedAgain.hq.transactions.length,migrated.hq.transactions.length);
assert.equal(migratedAgain.hq.billInstances.filter(row=>row.status==='paid').length,1,'legacy paid bill status becomes one preserved occurrence and stays idempotent');
assert.equal(migratedAgain.gig.orders.length,migrated.gig.orders.length,'legacy finance/gig migration is additive and idempotent');
assert.equal(migratedAgain.state.money.accounts.length,1,'legacy source collections remain preserved');
assert.equal(migratedAgain.hq.goals.find(row=>row.legacyId==='old-goal').manualProgress,20,'legacy savings progress preserves V4 current amounts');
assert.equal(migratedAgain.hq.legacyBuckets.filter(row=>row.meaning==='visual-allocation').length,2,'legacy paycheck/gig buckets remain preserved as allocations, not fake accounts');
assert.equal(migratedAgain.hq.legacyBuckets.some(row=>row.meaning==='visual-allocation-history'),true,'legacy bucket activity remains available without inventing ledger spending');

console.log('V5 Money Café + Gig Work behavior tests passed');
