import{selectV5MoneyGig}from'./data.js?v=5.6.0-final-integration';

const STORAGE_KEY='katos-v5-spending-budgets';
const DEFAULT_CATEGORIES=['Food','Groceries','Eating Out','Gas','Transportation','Fun','Shopping','Bills','Subscriptions','Work','Other'];
const app=document.getElementById('app');
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const money=value=>`$${Math.max(0,Number(value)||0).toFixed(2)}`;
const text=value=>String(value??'').trim();
const monthKey=date=>String(date||new Date().toISOString().slice(0,10)).slice(0,7);
const makeId=()=>`budget-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;

function loadBudgets(){try{const rows=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');return Array.isArray(rows)?rows:[]}catch{return[]}}
function saveBudgets(rows){localStorage.setItem(STORAGE_KEY,JSON.stringify(rows))}
function canonicalView(){try{return selectV5MoneyGig(new Date().toISOString().slice(0,10))}catch{return null}}
function currentMonthSpend(view,category){if(!view)return 0;const month=monthKey(view.today);return Math.max(0,view.transactions.filter(row=>String(row.date||'').startsWith(month)&&['posted','cleared'].includes(row.status)&&!['transfer','payment'].includes(row.type)&&String(row.category||'Other').toLowerCase()===String(category).toLowerCase()).reduce((sum,row)=>{if(row.type==='refund')return sum-(Number(row.amount)||0);if(['expense','fee','other'].includes(row.type))return sum+(Number(row.amount)||0);return sum},0))}
function progress(view,budget){const spent=currentMonthSpend(view,budget.category),limit=Math.max(0,Number(budget.limit)||0),remaining=Math.max(0,limit-spent),percent=limit?Math.min(100,Math.round(spent/limit*100)):0;return{spent,limit,remaining,percent,over:spent>limit,overBy:Math.max(0,spent-limit)}}
function categories(view){const fromLedger=(view?.transactions||[]).map(row=>text(row.category)).filter(Boolean);return[...new Set([...DEFAULT_CATEGORIES,...fromLedger])].sort((a,b)=>a.localeCompare(b))}
function budgetTitle(row){return text(row.name)||text(row.category)||'Spending budget'}

function modal(row={},view){const id=row.id||'',cats=categories(view),current=row.category||'Food';return`<div class="detail-modal-backdrop money-modal budget-modal" data-budget-modal><section class="detail-modal" role="dialog" aria-modal="true" aria-labelledby="budget-modal-title"><div class="detail-modal-head"><div><div class="ey">🍓 SPENDING BUDGET</div><h2 id="budget-modal-title">${esc(id?budgetTitle(row):'Add a spending budget')}</h2><p>KatOS compares this limit with posted ledger spending. It never creates fake money or transactions.</p></div><button type="button" class="detail-modal-close" data-budget-close aria-label="Close">×</button></div><form data-budget-form${id?` data-budget-id="${esc(id)}"`:''}><div class="room-detail-fields"><label class="daily-field"><span>Category</span><select name="category" required>${cats.map(category=>`<option value="${esc(category)}"${category===current?' selected':''}>${esc(category)}</option>`).join('')}</select></label><label class="daily-field"><span>Monthly limit</span><input name="limit" type="number" min="0.01" step="0.01" inputmode="decimal" value="${esc(row.limit||'')}" placeholder="0.00" required></label><label class="daily-field daily-field-wide"><span>Custom name · optional</span><input name="name" value="${esc(row.name||'')}" placeholder="Dining out, fun money…"></label><label class="daily-field daily-field-wide"><span>Notes · optional</span><textarea name="notes" rows="2" placeholder="Anything future Kat should know">${esc(row.notes||'')}</textarea></label></div><div class="button-row daily-actions"><button class="btn primary">🍓 Save budget</button>${id?'<button type="button" class="btn soft" data-budget-archive>📦 Archive</button>':''}<button type="button" class="btn soft" data-budget-close>Cancel</button></div></form></section></div>`}

function card(row,view){const p=progress(view,row);return`<article class="budget-row" data-budget-open="${esc(row.id)}" role="button" tabindex="0"><div class="budget-row-top"><div><b>${esc(budgetTitle(row))}</b><span>${esc(row.category)} · monthly</span></div><strong>${money(p.spent)} / ${money(p.limit)}</strong></div><div class="budget-progress" aria-label="${p.percent}% of budget used"><span style="width:${p.percent}%"></span></div><div class="budget-row-bottom"><span>${p.over?`${money(p.overBy)} over`:`${money(p.remaining)} left`}</span><span>${p.percent}%</span></div></article>`}

function section(view){const rows=loadBudgets().filter(row=>!row.archivedAt);return`<section class="card money-card spending-budget-card" data-spending-budgets><div class="card-head"><div><div class="ey">🍓 SPENDING BUDGETS</div><h2>Little fences for spending</h2><p>Monthly category limits, powered by the real ledger.</p></div><button type="button" class="btn tiny" data-budget-add>＋ Add budget</button></div><div class="budget-list">${rows.length?rows.map(row=>card(row,view)).join(''):'<div class="empty">No spending budgets yet. Add one for groceries, fun, gas, or whatever needs a tiny fence.</div>'}</div></section>`}

function decorateCategories(view){const budgets=loadBudgets().filter(row=>!row.archivedAt);document.querySelectorAll('.ledger-categories .category-list > div').forEach(row=>{const label=row.querySelector('span')?.textContent?.trim();if(!label||row.querySelector('.category-budget-note'))return;const budget=budgets.find(item=>String(item.category).toLowerCase()===label.toLowerCase());if(!budget)return;const p=progress(view,budget),note=document.createElement('small');note.className='category-budget-note';note.textContent=`${money(p.remaining)} left of ${money(p.limit)}`;row.append(note)})}

function enhance(){if(!app||!document.querySelector('.money-compact-grid')||document.querySelector('[data-spending-budgets]'))return;const view=canonicalView();if(!view)return;const ledger=document.querySelector('.money-ledger-card');if(!ledger)return;ledger.insertAdjacentHTML('afterend',section(view));decorateCategories(view)}
function openBudget(row){const view=canonicalView();document.querySelector('[data-budget-modal]')?.remove();app.insertAdjacentHTML('beforeend',modal(row,view));document.querySelector('[data-budget-modal] input, [data-budget-modal] select')?.focus()}

app?.addEventListener('click',event=>{const add=event.target.closest?.('[data-budget-add]');if(add){openBudget({});return}const open=event.target.closest?.('[data-budget-open]');if(open&&!event.target.closest('button,input,select,textarea,a')){const row=loadBudgets().find(item=>item.id===open.dataset.budgetOpen);if(row)openBudget(row);return}if(event.target.closest?.('[data-budget-close]')||event.target.matches?.('[data-budget-modal]')){document.querySelector('[data-budget-modal]')?.remove();return}const archive=event.target.closest?.('[data-budget-archive]');if(archive){const form=archive.closest('[data-budget-form]'),id=form?.dataset.budgetId;if(!id)return;saveBudgets(loadBudgets().map(row=>row.id===id?{...row,archivedAt:new Date().toISOString()}:row));document.querySelector('[data-budget-modal]')?.remove();document.querySelector('[data-spending-budgets]')?.remove();enhance();return}});

app?.addEventListener('submit',event=>{const form=event.target.closest?.('[data-budget-form]');if(!form)return;event.preventDefault();const data=Object.fromEntries(new FormData(form)),limit=Number(data.limit);if(!Number.isFinite(limit)||limit<=0)return;const rows=loadBudgets(),id=form.dataset.budgetId,existing=rows.find(row=>row.id===id),next={...existing,id:id||makeId(),name:text(data.name),category:text(data.category)||'Other',limit:Math.round(limit*100)/100,notes:text(data.notes),period:'monthly',updatedAt:new Date().toISOString(),createdAt:existing?.createdAt||new Date().toISOString()};saveBudgets(existing?rows.map(row=>row.id===id?next:row):[...rows,next]);document.querySelector('[data-budget-modal]')?.remove();document.querySelector('[data-spending-budgets]')?.remove();enhance()});

new MutationObserver(()=>queueMicrotask(enhance)).observe(app,{childList:true,subtree:true});
enhance();
