import{applyDailyAction}from'./daily-shit.js?v=5.4.0-money-gig';

const list=value=>Array.isArray(value)?value:[];
const obj=value=>value&&typeof value==='object'&&!Array.isArray(value)?value:{};
const text=value=>String(value??'').trim();
const cents=value=>Math.round((Number(value)||0)*100)/100;
const clone=value=>{try{return structuredClone(value)}catch{return JSON.parse(JSON.stringify(value||{}))}};
const now=()=>new Date().toISOString();
const makeId=prefix=>`${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;
const validDate=value=>/^\d{4}-\d{2}-\d{2}$/.test(text(value));
const dayKey=value=>validDate(value)?text(value):new Date(value||Date.now()).toISOString().slice(0,10);
const byId=(rows,id)=>list(rows).find(row=>String(row?.id)===String(id));
const active=row=>row?.active!==false&&!row?.archivedAt&&row?.status!=='archived';
const moneyTypes=['income','expense','transfer','refund','fee','adjustment','payment','other'];
const transactionStates=['pending','posted','cleared','voided'];
const accountTypes=['checking','savings','cash','credit-card','loan','prepaid','other'];
const normalizeAccountType=value=>{const kind=text(value).toLowerCase().replace(/[_\s]+/g,'-');if(['bank','bank-account'].includes(kind))return'checking';return accountTypes.includes(kind)?kind:'other'};
const payoutStates=['pending','available','processing','received'];
const startOfWeek=date=>{const d=new Date(`${dayKey(date)}T12:00:00`);d.setDate(d.getDate()-((d.getDay()+6)%7));return dayKey(d)};
const plusDays=(date,amount)=>{const d=new Date(`${dayKey(date)}T12:00:00`);d.setDate(d.getDate()+amount);return dayKey(d)};
const monthEnd=date=>{const d=new Date(`${dayKey(date)}T12:00:00`);return dayKey(new Date(d.getFullYear(),d.getMonth()+1,0,12))};
const monthStart=date=>`${dayKey(date).slice(0,7)}-01`;
const addMonths=(date,amount)=>{const original=new Date(`${dayKey(date)}T12:00:00`),day=original.getDate();original.setDate(1);original.setMonth(original.getMonth()+amount);original.setDate(Math.min(day,new Date(original.getFullYear(),original.getMonth()+1,0).getDate()));return dayKey(original)};

export const EMPTY_MONEY_HQ={version:1,accounts:[],transactions:[],bills:[],billInstances:[],subscriptions:[],goals:[],goalContributions:[],liabilities:[],payRates:[],legacyBuckets:[],migration:{version:1,receipts:[]}};
export const EMPTY_GIG_WORK={version:1,platforms:[],orders:[],payouts:[],goals:[],settings:{taxReservePercent:0},migration:{version:1,receipts:[]}};

function setMoney(state,hq){state.money=obj(state.money);state.money.hq=hq}
function setGig(state,gig){state.work=obj(state.work);state.work.gig=gig}
function normalizedMoney(source){const input=obj(source?.money?.hq),hq={...clone(EMPTY_MONEY_HQ),...clone(input)};for(const key of ['accounts','transactions','bills','billInstances','subscriptions','goals','goalContributions','liabilities','payRates','legacyBuckets'])hq[key]=list(hq[key]);hq.migration={...EMPTY_MONEY_HQ.migration,...obj(hq.migration),receipts:list(hq.migration?.receipts)};return hq}
function normalizedGig(source){const input=obj(source?.work?.gig),gig={...clone(EMPTY_GIG_WORK),...clone(input),settings:{...EMPTY_GIG_WORK.settings,...obj(input.settings)}};for(const key of ['platforms','orders','payouts','goals'])gig[key]=list(gig[key]);gig.migration={...EMPTY_GIG_WORK.migration,...obj(gig.migration),receipts:list(gig.migration?.receipts)};return gig}
const legacyId=(prefix,row,index)=>`${prefix}:${text(row?.id)||index}`;
const titleOf=row=>text(row?.name||row?.title||row?.label||row?.description);
function accountName(row){return titleOf(row)||text(row?.account)||'General'}
function ensureNamedAccount(hq,name,type='other'){
 const clean=text(name)||'General',existing=hq.accounts.find(row=>row.name.toLowerCase()===clean.toLowerCase());if(existing)return existing;
 const account={id:`legacy-account:name:${clean.toLowerCase().replace(/[^a-z0-9]+/g,'-')}`,name:clean,institution:'',type:normalizeAccountType(type),active:true,openingBalance:0,reconciledAt:'',creditLimit:0,apr:0,minimumPayment:0,dueDay:0,notes:'Created to preserve an existing transaction account label.',source:'v5-preservation',createdAt:now()};hq.accounts.push(account);return account;
}
function migrateAccounts(source,hq){let added=0;list(source?.money?.accounts).forEach((row,index)=>{const id=legacyId('legacy-account',row,index);if(hq.accounts.some(item=>item.id===id||text(item.legacyId)===text(row?.id)))return;hq.accounts.push({id,legacyId:text(row?.id),name:accountName(row),institution:text(row?.institution||row?.bank),type:normalizeAccountType(row?.type||'checking'),active:row?.active!==false&&!row?.archived,openingBalance:cents(row?.openingBalance??row?.reconciledBalance??row?.balance??row?.amount),reconciledAt:text(row?.reconciledAt||row?.updatedAt),creditLimit:cents(row?.creditLimit),apr:Number(row?.apr)||0,minimumPayment:cents(row?.minimumPayment),dueDay:Number(row?.dueDay)||0,notes:text(row?.notes||row?.note),source:'legacy-account',createdAt:text(row?.createdAt)||now()});added++});return added}
function normalizeLegacyTransaction(row,index,hq,{v5=false}={}){const raw=text(row?.kind||row?.type).toLowerCase(),type=raw==='spending'?'expense':moneyTypes.includes(raw)?raw:'expense',amount=Math.abs(Number(row?.amount??row?.actualAmount??row?.total)||0);if(!amount)return null;const account=ensureNamedAccount(hq,text(row?.account||row?.accountName)||'General'),toName=text(row?.toAccount||row?.toAccountName),toAccount=toName?ensureNamedAccount(hq,toName):null;return{id:text(row?.id)||legacyId(v5?'v5-ledger':'legacy-transaction',row,index),type,amount:cents(amount),signedAmount:type==='adjustment'?Number(row?.signedAmount??row?.adjustmentSigned??row?.amount)||0:null,date:validDate(row?.date)?row.date:dayKey(),merchant:text(row?.merchant||row?.source||row?.label||row?.name)||'Preserved transaction',category:text(row?.category)||'Other',accountId:account.id,toAccountId:toAccount?.id||'',status:transactionStates.includes(text(row?.status).toLowerCase())?text(row.status).toLowerCase():'posted',notes:text(row?.notes||row?.note),linkedTransferId:text(row?.linkedTransferId),externalId:`preserved:${text(row?.id)||index}`,source:v5?'v5-ledger-preservation':'legacy-money-history',affectsBalance:(v5&&type!=='transfer')||(v5&&type==='transfer'&&!!toAccount)||row?.affectsBalance===true,createdAt:text(row?.createdAt)||now()}}
function migrateTransactions(source,hq,v5Ledger=[]){let added=0;const imported=list(v5Ledger);if(imported.length){imported.forEach((row,index)=>{const next=normalizeLegacyTransaction(row,index,hq,{v5:true});if(next&&!hq.transactions.some(item=>item.id===next.id||item.externalId===next.externalId)){hq.transactions.push(next);added++}})}else if(!hq.transactions.length){const legacy=list(source?.money?.transactions).length?list(source.money.transactions):list(source?.money?.ledger);legacy.forEach((row,index)=>{const next=normalizeLegacyTransaction(row,index,hq);if(next&&!hq.transactions.some(item=>item.id===next.id||item.externalId===next.externalId)){hq.transactions.push(next);added++}})}return added}
function migrateNamedCollection(rows,target,prefix,mapper){let added=0;list(rows).forEach((row,index)=>{const id=legacyId(prefix,row,index);if(target.some(item=>item.id===id||text(item.legacyId)===text(row?.id)))return;target.push(mapper(row,id));added++});return added}
function migrateMoneyCollections(source,hq){let added=0;
 added+=migrateNamedCollection(source?.money?.bills,hq.bills,'legacy-bill',(row,id)=>({id,legacyId:text(row?.id),name:titleOf(row)||'Bill',expectedAmount:cents(row?.expectedAmount??row?.typicalAmount??row?.amount),amountType:text(row?.kind)==='variable'||row?.variable?'variable':'fixed',accountId:'',recurrence:text(row?.recurrence||row?.repeat).toLowerCase()||'monthly',dueDay:Number(row?.dueDay)||Number(String(row?.due||'').match(/\d+/)?.[0])||1,dueDate:validDate(row?.dueDate||row?.due)?text(row?.dueDate||row?.due):'',active:row?.active!==false&&!row?.archived,autopay:!!row?.autopay,category:text(row?.category)||'Bills',notes:text(row?.notes||row?.note),source:'legacy-bill',createdAt:text(row?.createdAt)||now()}));
 added+=migrateNamedCollection(source?.money?.subscriptions,hq.subscriptions,'legacy-subscription',(row,id)=>({id,legacyId:text(row?.id),name:titleOf(row)||'Subscription',amount:cents(row?.amount),billingCycle:text(row?.billingCycle||row?.frequency||row?.repeat).toLowerCase()||'monthly',nextRenewal:validDate(row?.nextRenewal||row?.renewalDate||row?.due)?text(row?.nextRenewal||row?.renewalDate||row?.due):'',accountId:'',category:text(row?.category)||'Subscriptions',trialEnd:validDate(row?.trialEnd||row?.trialEndDate)?text(row?.trialEnd||row?.trialEndDate):'',plannedCancellation:validDate(row?.plannedCancellation||row?.cancellationDate)?text(row?.plannedCancellation||row?.cancellationDate):'',status:text(row?.status).toLowerCase()||'active',active:row?.active!==false&&!row?.archived,academicContext:text(row?.academicContext),notes:text(row?.notes||row?.note),source:'legacy-subscription',createdAt:text(row?.createdAt)||now()}));
 added+=migrateNamedCollection(source?.money?.savingsGoals,hq.goals,'legacy-goal',(row,id)=>({id,legacyId:text(row?.id),name:titleOf(row)||'Savings goal',targetAmount:cents(row?.target??row?.targetAmount),targetDate:validDate(row?.targetDate)?row.targetDate:'',progressMethod:'manual',manualProgress:cents(row?.amount??row?.saved??row?.currentAmount??row?.current),linkedAccountId:'',status:row?.archived?'archived':'active',notes:text(row?.notes||row?.note),source:'legacy-goal',createdAt:text(row?.createdAt)||now()}));
 added+=migrateNamedCollection(source?.money?.debts,hq.liabilities,'legacy-liability',(row,id)=>({id,legacyId:text(row?.id),name:titleOf(row)||'Liability',type:normalizeAccountType(row?.type||'loan'),currentBalance:cents(row?.balance??row?.amount),limit:cents(row?.limit||row?.creditLimit),apr:Number(row?.apr)||0,minimum:cents(row?.minimum||row?.minimumPayment||row?.paymentAmount),dueDay:Number(row?.dueDay)||0,accountId:'',active:row?.active!==false&&!row?.archived,notes:text(row?.notes||row?.note),source:'legacy-liability',createdAt:text(row?.createdAt)||now()}));
 list(source?.money?.buckets||source?.money?.moneyBuckets||source?.money?.budgets).forEach((row,index)=>{const id=legacyId('legacy-bucket',row,index);if(hq.legacyBuckets.some(item=>item.id===id))return;hq.legacyBuckets.push({id,title:titleOf(row)||'Legacy money bucket',amount:cents(row?.amount??row?.saved),meaning:'ambiguous',original:clone(row),preservedAt:now()});added++});const sourceBalances=obj(source?.money?.sourceBalances);for(const bucket of ['paycheck','gig']){if(sourceBalances[bucket]==null)continue;const id=`legacy-bucket:source:${bucket}`;if(hq.legacyBuckets.some(item=>item.id===id))continue;hq.legacyBuckets.push({id,title:`${bucket==='gig'?'Gig':'Paycheck'} money allocation`,amount:cents(sourceBalances[bucket]),meaning:'visual-allocation',original:{bucket,amount:sourceBalances[bucket],initializedAt:text(source?.money?.sourceBalancesInitializedAt)},preservedAt:now()});added++}list(source?.money?.sourceSpending).forEach((row,index)=>{const id=legacyId('legacy-source-spending',row,index);if(hq.legacyBuckets.some(item=>item.id===id))return;hq.legacyBuckets.push({id,title:`Preserved ${text(row?.bucket)||'source'} allocation activity`,amount:-Math.abs(cents(row?.amount)),meaning:'visual-allocation-history',original:clone(row),preservedAt:now()});added++});return added
}
function platformHint(row){return text(row?.platform||row?.source||row?.app||row?.employer||row?.label)}
function migrateGig(source,gig){let added=0;['Shipt','DoorDash'].forEach(name=>{const id=`gig-platform:${name.toLowerCase()}`;if(!gig.platforms.some(row=>row.id===id||row.name.toLowerCase()===name.toLowerCase())){gig.platforms.push({id,name,icon:name==='Shipt'?'🛍️':'🚗',active:true,notes:'',createdAt:now()});added++}});
 list(source?.money?.earnings).forEach((row,index)=>{const platformName=platformHint(row);if(!/shipt|door\s*dash|uber|instacart|gig/i.test(platformName))return;const id=legacyId('legacy-gig-order',row,index);if(gig.orders.some(item=>item.id===id||text(item.legacyId)===text(row?.id)))return;const platform=gig.platforms.find(item=>platformName.toLowerCase().includes(item.name.toLowerCase()))||gig.platforms[0],total=Number(row?.earnedAmount??row?.actualAmount??row?.netAmount??row?.amount);if(!Number.isFinite(total)||total<=0)return;gig.orders.push({id,legacyId:text(row?.id),platformId:platform.id,date:validDate(row?.date||row?.earnedDate||row?.receivedDate)?text(row?.date||row?.earnedDate||row?.receivedDate):dayKey(),basePay:cents(total-Number(row?.tip||row?.tips||0)),promo:0,tip:cents(row?.tip||row?.tips),bonus:0,reimbursement:0,mileage:Number(row?.mileage||row?.miles)||0,activeMinutes:Number(row?.activeMinutes)||0,onlineMinutes:Number(row?.onlineMinutes)||0,status:'completed',notes:text(row?.notes||row?.note),source:'legacy-earned-gig',createdAt:text(row?.createdAt)||now()});added++});return added}

export function initializeMoneyGig(source={},today=dayKey(),options={}){const state=clone(source),hq=normalizedMoney(state),gig=normalizedGig(state);let changes=0;changes+=migrateAccounts(state,hq);changes+=migrateTransactions(state,hq,options.v5Ledger);changes+=migrateMoneyCollections(state,hq);changes+=migrateGig(state,gig);if(!hq.migration.receipts.some(row=>row.key==='pass4-v1')){hq.migration.receipts.push({key:'pass4-v1',at:now(),note:'Additive preservation migration; original finance collections retained.'});changes++}if(!gig.migration.receipts.some(row=>row.key==='pass4-v1')){gig.migration.receipts.push({key:'pass4-v1',at:now(),note:'Only clear earned gig records migrated; planned shifts retained separately.'});changes++}setMoney(state,hq);setGig(state,gig);return{state,hq,gig,changed:changes>0,today,changes}}

export function getAccounts(source,{includeArchived=false}={}){const rows=normalizedMoney(source).accounts;return includeArchived?rows:rows.filter(active)}
export function getLedgerTransactions(source,filters={}){let rows=normalizedMoney(source).transactions.filter(row=>!row.archivedAt);for(const [key,value]of Object.entries(filters)){if(value==null||value==='')continue;if(key==='from')rows=rows.filter(row=>row.date>=value);else if(key==='to')rows=rows.filter(row=>row.date<=value);else rows=rows.filter(row=>String(row[key])===String(value))}return rows.sort((a,b)=>`${b.date}${b.createdAt||''}`.localeCompare(`${a.date}${a.createdAt||''}`))}
const isLiability=account=>['credit-card','loan'].includes(account?.type);
const countsInBalance=(row,includePending)=>row.affectsBalance!==false&&!row.archivedAt&&row.status!=='voided'&&(['posted','cleared'].includes(row.status)||(includePending&&row.status==='pending'));
function transactionEffect(account,row){const amount=cents(row.amount),source=String(row.accountId)===String(account.id),destination=String(row.toAccountId)===String(account.id);if(row.type==='transfer'||row.type==='payment'){if(source)return isLiability(account)?amount:-amount;if(destination)return isLiability(account)?-amount:amount;return 0}if(!source)return 0;if(row.type==='adjustment')return Number(row.signedAmount??row.amount)||0;if(['expense','fee'].includes(row.type))return isLiability(account)?amount:-amount;if(row.type==='refund')return isLiability(account)?-amount:amount;if(row.type==='income')return isLiability(account)?-amount:amount;if(row.type==='other')return Number(row.signedAmount??-amount)||0;return 0}
export function getAccountBalance(source,id,{includePending=false}={}){const hq=normalizedMoney(source),account=byId(hq.accounts,id);if(!account)return null;return cents((Number(account.openingBalance)||0)+hq.transactions.filter(row=>countsInBalance(row,includePending)).reduce((sum,row)=>sum+transactionEffect(account,row),0))}
export function getCashFlowSummary(source,{from='0000-01-01',to='9999-12-31',includePending=false}={}){const rows=getLedgerTransactions(source,{from,to}).filter(row=>row.affectsBalance!==false&&row.status!=='voided'&&(['posted','cleared'].includes(row.status)||(includePending&&row.status==='pending')));let received=0,spent=0,refunds=0;rows.forEach(row=>{if(row.type==='income')received+=row.amount;else if(['expense','fee'].includes(row.type))spent+=row.amount;else if(row.type==='refund')refunds+=row.amount});spent=Math.max(0,cents(spent-refunds));return{received:cents(received),spent,refunds:cents(refunds),net:cents(received-spent),transactions:rows}}
export function getMoneySummary(source,today=dayKey()){const accounts=getAccounts(source),assets=accounts.filter(row=>!isLiability(row)),liabilities=accounts.filter(isLiability),posted=assets.reduce((sum,row)=>sum+(getAccountBalance(source,row.id)||0),0),projected=assets.reduce((sum,row)=>sum+(getAccountBalance(source,row.id,{includePending:true})||0),0),debt=liabilities.reduce((sum,row)=>sum+Math.max(0,getAccountBalance(source,row.id)||0),0),flow=getCashFlowSummary(source,{from:monthStart(today),to:monthEnd(today)});return{posted:cents(posted),projected:cents(projected),debt:cents(debt),flow,accounts,liabilities,upcomingObligations:getUpcomingBills(source,{from:today,to:plusDays(today,35)}).filter(row=>!['paid','skipped'].includes(row.status))}}

function dueForMonth(bill,month){const [year,monthNumber]=month.split('-').map(Number),last=new Date(year,monthNumber,0).getDate();return`${month}-${String(Math.min(last,Math.max(1,Number(bill.dueDay)||1))).padStart(2,'0')}`}
function monthsBetween(from,to){const out=[],cursor=new Date(`${from.slice(0,7)}-01T12:00:00`),end=new Date(`${to.slice(0,7)}-01T12:00:00`);while(cursor<=end){out.push(dayKey(cursor).slice(0,7));cursor.setMonth(cursor.getMonth()+1)}return out}
function billDates(bill,from,to){const recurrence=text(bill.recurrence).toLowerCase();if(['once','one-time'].includes(recurrence))return validDate(bill.dueDate)&&bill.dueDate>=from&&bill.dueDate<=to?[bill.dueDate]:[];if(recurrence==='weekly'){const anchor=new Date(`${validDate(bill.dueDate)?bill.dueDate:from}T12:00:00`),start=new Date(`${from}T12:00:00`);while(anchor<start)anchor.setDate(anchor.getDate()+7);const out=[];while(dayKey(anchor)<=to){out.push(dayKey(anchor));anchor.setDate(anchor.getDate()+7)}return out}if(recurrence==='yearly'){const anchor=validDate(bill.dueDate)?bill.dueDate:`${from.slice(0,4)}-01-01`;return monthsBetween(from,to).map(month=>month.endsWith(anchor.slice(5,7))?dueForMonth({...bill,dueDay:Number(anchor.slice(8,10))},month):'').filter(Boolean)}return monthsBetween(from,to).map(month=>dueForMonth(bill,month))}
export function getBillInstances(source,{from=dayKey(),to=plusDays(from,60),today=dayKey()}={}){const hq=normalizedMoney(source);return hq.bills.filter(active).flatMap(bill=>billDates(bill,from,to).map(dueDate=>{const id=`bill:${bill.id}:${dueDate}`,saved=byId(hq.billInstances,id)||{},payment=hq.transactions.find(row=>row.billInstanceId===id&&countsInBalance(row,false)),status=payment?'paid':saved.status||((dueDate<today)?'overdue':dueDate===today?'due':'upcoming');return{...saved,id,billId:bill.id,name:bill.name,dueDate,expectedAmount:cents(bill.expectedAmount),actualAmount:saved.actualAmount==null?null:cents(saved.actualAmount),status,paymentTransactionId:payment?.id||'',bill}})).sort((a,b)=>a.dueDate.localeCompare(b.dueDate)||a.name.localeCompare(b.name))}
export const getUpcomingBills=(source,range={})=>getBillInstances(source,range);
function billInstanceById(source,id,today){const due=text(id).slice(-10);return validDate(due)?getBillInstances(source,{from:due,to:due,today}).find(row=>row.id===id):null}
export function getSubscriptions(source){return normalizedMoney(source).subscriptions.filter(row=>!row.archivedAt)}
export function getFinancialGoals(source){return normalizedMoney(source).goals.filter(row=>row.status!=='archived'&&!row.archivedAt)}
export function getGoalProgress(source,id){const hq=normalizedMoney(source),goal=byId(hq.goals,id);if(!goal)return null;let amount=Number(goal.manualProgress)||0;if(goal.progressMethod==='linked-account')amount=Math.max(0,getAccountBalance(source,goal.linkedAccountId)||0);if(goal.progressMethod==='contributions')amount=hq.goalContributions.filter(row=>row.goalId===id&&!row.archivedAt).reduce((sum,row)=>sum+Number(row.amount||0),0);return{goal,amount:cents(amount),remaining:cents(Math.max(0,Number(goal.targetAmount||0)-amount)),percent:goal.targetAmount?Math.min(100,Math.round(amount/goal.targetAmount*100)):0}}
export function getGigPlatforms(source,{includeArchived=false}={}){const rows=normalizedGig(source).platforms;return includeArchived?rows:rows.filter(active)}
export function gigOrderTotal(order){return cents(['basePay','promo','tip','bonus','reimbursement','otherPay'].reduce((sum,key)=>sum+(Number(order?.[key])||0),0))}
export function getGigOrders(source,filters={}){let rows=normalizedGig(source).orders.filter(row=>!row.archivedAt);for(const [key,value]of Object.entries(filters)){if(value==null||value==='')continue;if(key==='from')rows=rows.filter(row=>row.date>=value);else if(key==='to')rows=rows.filter(row=>row.date<=value);else rows=rows.filter(row=>String(row[key])===String(value))}return rows.sort((a,b)=>`${b.date}${b.createdAt||''}`.localeCompare(`${a.date}${a.createdAt||''}`))}
export function getGigEarningsSummary(source,{from='0000-01-01',to='9999-12-31',platformId=''}={}){const orders=getGigOrders(source,{from,to}).filter(row=>row.status!=='canceled'&&(!platformId||row.platformId===platformId)),gross=cents(orders.reduce((sum,row)=>sum+gigOrderTotal(row),0)),tips=cents(orders.reduce((sum,row)=>sum+Number(row.tip||0),0)),activeMinutes=orders.reduce((sum,row)=>sum+Number(row.activeMinutes||0),0),onlineMinutes=orders.reduce((sum,row)=>sum+Number(row.onlineMinutes||0),0),mileage=cents(orders.reduce((sum,row)=>sum+Number(row.mileage||0),0)),expenses=getLedgerTransactions(source,{from,to}).filter(row=>row.gigExpense&&['expense','fee'].includes(row.type)&&countsInBalance(row,false)).reduce((sum,row)=>sum+Number(row.amount||0),0);return{orders,gross,tips,count:orders.length,activeMinutes,onlineMinutes,mileage,linkedExpenses:cents(expenses),simpleNet:cents(gross-expenses),averagePerOrder:orders.length?cents(gross/orders.length):null,perActiveHour:activeMinutes?cents(gross/(activeMinutes/60)):null,perOnlineHour:onlineMinutes?cents(gross/(onlineMinutes/60)):null,perMile:mileage?cents(gross/mileage):null}}
export function getGigPlatformComparison(source,range={}){return getGigPlatforms(source).map(platform=>({platform,...getGigEarningsSummary(source,{...range,platformId:platform.id})}))}
function goalRange(goal,today){if(validDate(goal.startDate)&&validDate(goal.endDate))return{from:goal.startDate,to:goal.endDate};if(goal.period==='week')return{from:startOfWeek(today),to:plusDays(startOfWeek(today),6)};if(goal.period==='month')return{from:monthStart(today),to:monthEnd(today)};return{from:today,to:today}}
export function getGigGoalProgress(source,id,today=dayKey()){const goal=byId(normalizedGig(source).goals,id);if(!goal)return null;const range=goalRange(goal,today),earned=getGigEarningsSummary(source,{...range,platformId:goal.platformId}).gross,target=Number(goal.targetAmount)||0;return{goal,range,earned,remaining:cents(Math.max(0,target-earned)),percent:target?Math.min(100,Math.round(earned/target*100)):0}}
export function getPendingGigPayouts(source){return normalizedGig(source).payouts.filter(row=>row.status!=='received'&&!row.archivedAt)}
export function getEstimatedWorkEarnings(source,{from='0000-01-01',to='9999-12-31'}={}){const hq=normalizedMoney(source),rates=hq.payRates.slice().sort((a,b)=>String(a.effectiveDate).localeCompare(String(b.effectiveDate))),records=[...list(source?.work?.shifts),...list(source?.work?.hq?.sessionPlans)].filter(row=>{const date=text(row.date);return validDate(date)&&date>=from&&date<=to});let estimated=0,minutes=0;records.forEach(row=>{const duration=Number(row.actualMinutes)||Number(row.minutes)||(()=>{const [sh,sm]=text(row.startTime).split(':').map(Number),[eh,em]=text(row.endTime).split(':').map(Number);return Number.isFinite(sh)&&Number.isFinite(eh)?Math.max(0,(eh*60+em)-(sh*60+sm)):0})();const rate=rates.filter(item=>item.effectiveDate<=row.date&&(!item.effectiveUntil||item.effectiveUntil>=row.date)).at(-1);minutes+=duration;if(rate)estimated+=(duration/60)*Number(rate.hourlyRate)});return{minutes,hours:cents(minutes/60),estimated:rates.length?cents(estimated):null,label:'Estimated work earnings — not deposited money'}}
export function selectMoneyGig(source={},today=dayKey(),options={}){const initialized=initializeMoneyGig(source,today,options),state=initialized.state,month={from:monthStart(today),to:monthEnd(today)},week={from:startOfWeek(today),to:plusDays(startOfWeek(today),6)},todayRange={from:today,to:today},money=getMoneySummary(state,today),hq=normalizedMoney(state),gigRaw=normalizedGig(state),gig={...gigRaw,orders:gigRaw.orders.map(row=>({...row,total:gigOrderTotal(row)}))},dailyGoal=gig.goals.find(row=>row.period==='day'&&goalRange(row,today).from===today),weekGoal=gig.goals.find(row=>row.period==='week'),monthGoal=gig.goals.find(row=>row.period==='month'),accountBalances=Object.fromEntries(hq.accounts.map(account=>[account.id,{posted:getAccountBalance(state,account.id),projected:getAccountBalance(state,account.id,{includePending:true})}]));return{...initialized,state,money,hq,gig,accountBalances,transactions:getLedgerTransactions(state),bills:getUpcomingBills(state,{from:today,to:plusDays(today,60),today}),subscriptions:getSubscriptions(state),goals:getFinancialGoals(state).map(row=>getGoalProgress(state,row.id)),cashFlowToday:getCashFlowSummary(state,todayRange),cashFlowWeek:getCashFlowSummary(state,week),cashFlowMonth:getCashFlowSummary(state,month),gigToday:getGigEarningsSummary(state,todayRange),gigWeek:getGigEarningsSummary(state,week),gigMonth:getGigEarningsSummary(state,month),gigComparison:getGigPlatformComparison(state,week),dailyGigGoal:dailyGoal?getGigGoalProgress(state,dailyGoal.id,today):null,weeklyGigGoal:weekGoal?getGigGoalProgress(state,weekGoal.id,today):null,monthlyGigGoal:monthGoal?getGigGoalProgress(state,monthGoal.id,today):null,pendingPayouts:getPendingGigPayouts(state),estimatedWork:getEstimatedWorkEarnings(state,week)}}

function fail(error){return{ok:false,error}}
function patch(rows,id,changes){const index=rows.findIndex(row=>String(row.id)===String(id));if(index<0)return null;const updated={...rows[index],...changes,id:rows[index].id,updatedAt:now()};rows[index]=updated;return updated}
function archiveToMemory(state,path,row){state.v4=obj(state.v4);state.v4.archive=list(state.v4.archive);state.v4.archive.push({id:makeId('archive'),kind:path,originalId:row.id,title:titleOf(row)||'Archived money record',data:clone(row),archivedAt:now()})}
function ensureDaily(state,{externalId,title,date,priority='today',energy='low',duration=10,sourceId,sourceType}){return applyDailyAction(state,{type:'ensure-linked',kind:'task',externalId,title,date:validDate(date)?date:dayKey(),priority,energy,duration,sourceId,sourceType},dayKey())}
function accountInput(action,old={}){return{...old,name:text(action.name)||old.name,institution:text(action.institution),type:normalizeAccountType(action.accountType||action.type||old.type||'checking'),active:action.active!==false&&action.active!=='false',openingBalance:cents(action.openingBalance??old.openingBalance),reconciledAt:text(action.reconciledAt||old.reconciledAt),creditLimit:cents(action.creditLimit),apr:Number(action.apr)||0,minimumPayment:cents(action.minimumPayment),dueDay:Number(action.dueDay)||0,notes:text(action.notes)}}
function transactionInput(action,old={}){const type=moneyTypes.includes(text(action.transactionType||action.kind||action.type))?text(action.transactionType||action.kind||action.type):(old.type||'expense');return{...old,type,amount:Math.abs(cents(action.amount??old.amount)),signedAmount:type==='adjustment'?Number(action.signedAmount??action.amount??old.signedAmount)||0:null,date:validDate(action.date)?action.date:(old.date||dayKey()),merchant:text(action.merchant||action.label)||old.merchant||'',category:text(action.category)||old.category||'Other',accountId:text(action.accountId)||old.accountId||'',toAccountId:['transfer','payment'].includes(type)?text(action.toAccountId)||old.toAccountId||'':'',status:transactionStates.includes(text(action.status))?text(action.status):(old.status||'posted'),notes:text(action.notes),refundOfId:text(action.refundOfId)||old.refundOfId||'',billInstanceId:text(action.billInstanceId)||old.billInstanceId||'',externalId:text(action.externalId)||old.externalId||'',gigExpense:action.gigExpense===true||action.gigExpense==='true'||old.gigExpense===true,affectsBalance:old.affectsBalance!==false}}

export function applyMoneyGigAction(source,action={},today=dayKey()){const initialized=initializeMoneyGig(source,today,{v5Ledger:action.v5Ledger}),state=initialized.state,hq=normalizedMoney(state),gig=normalizedGig(state),type=text(action.type);setMoney(state,hq);setGig(state,gig);
 if(type==='account-save'){const existing=byId(hq.accounts,action.id),input=accountInput(action,existing);if(!input.name)return fail('Give the account a name.');const result=existing?patch(hq.accounts,action.id,input):{id:makeId('account'),...input,createdAt:now()};if(!existing)hq.accounts.push(result);return{ok:true,state,result}}
 if(type==='account-reconcile'){const account=byId(hq.accounts,action.id);if(!account)return fail('That account is no longer here.');const actual=Number(action.actualBalance),current=getAccountBalance(state,account.id);if(!Number.isFinite(actual))return fail('Enter the real account balance.');const difference=cents(actual-current);if(Math.abs(difference)<.005)return{ok:true,state,result:null,reused:true};const result={id:makeId('transaction'),type:'adjustment',amount:Math.abs(difference),signedAmount:difference,date:today,merchant:'Balance reconciliation',category:'Adjustment',accountId:account.id,toAccountId:'',status:'cleared',notes:text(action.notes)||`Bank ${cents(actual)} · KatOS ${current}`,externalId:makeId(`reconcile:${account.id}`),source:'reconciliation',affectsBalance:true,createdAt:now()};hq.transactions.push(result);return{ok:true,state,result}}
 if(type==='transaction-save'){const existing=byId(hq.transactions,action.id),input=transactionInput(action,existing);if(!byId(hq.accounts,input.accountId))return fail('Choose an account.');if(['transfer','payment'].includes(input.type)&&(!byId(hq.accounts,input.toAccountId)||input.accountId===input.toAccountId))return fail('Choose two different accounts for the transfer.');if(!input.amount)return fail('Enter an amount.');let result;if(existing)result=patch(hq.transactions,action.id,input);else{const stable=text(action.externalId),same=stable&&hq.transactions.find(row=>row.externalId===stable);if(same){result=patch(hq.transactions,same.id,input);return{ok:true,state,result,reused:true}}result={id:makeId('transaction'),...input,linkedTransferId:['transfer','payment'].includes(input.type)?makeId('transfer'):'',source:'manual',createdAt:now()};hq.transactions.push(result)}return{ok:true,state,result}}
 if(type==='archive'){const maps={account:['money.hq.accounts',hq.accounts],transaction:['money.hq.transactions',hq.transactions],bill:['money.hq.bills',hq.bills],subscription:['money.hq.subscriptions',hq.subscriptions],goal:['money.hq.goals',hq.goals],liability:['money.hq.liabilities',hq.liabilities],platform:['work.gig.platforms',gig.platforms],order:['work.gig.orders',gig.orders],payout:['work.gig.payouts',gig.payouts]},entry=maps[action.kind];if(!entry)return fail('That record type cannot be archived here.');const row=byId(entry[1],action.id);if(!row||row.archivedAt)return fail('That record is no longer here.');archiveToMemory(state,entry[0],row);patch(entry[1],row.id,{archivedAt:now(),active:false});return{ok:true,state,result:row}}
 if(type==='bill-save'){const existing=byId(hq.bills,action.id),input={...existing,name:text(action.name)||existing?.name,expectedAmount:cents(action.expectedAmount),amountType:action.amountType==='variable'?'variable':'fixed',accountId:text(action.accountId),recurrence:['monthly','weekly','yearly','once'].includes(text(action.recurrence))?text(action.recurrence):'monthly',dueDay:Number(action.dueDay)||1,dueDate:validDate(action.dueDate)?action.dueDate:'',active:action.active!==false&&action.active!=='false',autopay:action.autopay===true||action.autopay==='true',category:text(action.category)||'Bills',notes:text(action.notes)};if(!input.name)return fail('Give the bill a name.');if(['weekly','yearly','once'].includes(input.recurrence)&&!input.dueDate)return fail('Choose the first due date for that recurrence.');const result=existing?patch(hq.bills,action.id,input):{id:makeId('bill'),...input,createdAt:now()};if(!existing)hq.bills.push(result);return{ok:true,state,result}}
 if(type==='bill-instance-save'){const generated=billInstanceById(state,action.id,today);if(!generated)return fail('That bill occurrence is no longer here.');if(text(action.status)==='paid'&&!generated.paymentTransactionId)return fail('Record the real payment below before marking this bill paid.');let saved=byId(hq.billInstances,action.id),changes={status:['upcoming','due','paid','overdue','skipped','changed'].includes(text(action.status))?text(action.status):generated.status,actualAmount:action.actualAmount===''?null:cents(action.actualAmount),notes:text(action.notes),updatedAt:now()};if(saved)saved=patch(hq.billInstances,action.id,changes);else{saved={id:action.id,billId:generated.billId,dueDate:generated.dueDate,...changes,createdAt:now()};hq.billInstances.push(saved)}return{ok:true,state,result:saved}}
 if(type==='bill-link-daily'){const instance=billInstanceById(state,action.id,today);if(!instance)return fail('That bill occurrence is no longer here.');const linked=ensureDaily(state,{externalId:`money:bill:${instance.id}`,title:`${instance.bill.amountType==='variable'?'Review':'Pay'} ${instance.name}`,date:instance.dueDate,sourceId:instance.id,sourceType:'money-bill'});return linked.ok?{...linked,moneyResult:instance}:linked}
 if(type==='bill-record-payment'){const instance=billInstanceById(state,action.id,today);if(!instance)return fail('That bill occurrence is no longer here.');const externalId=`bill-payment:${instance.id}`,existing=hq.transactions.find(row=>row.externalId===externalId),paymentType=text(action.paymentType)==='payment'?'payment':'expense',input=transactionInput({...action,type:paymentType,amount:action.amount||instance.actualAmount||instance.expectedAmount,billInstanceId:instance.id,externalId,status:'posted'},existing);if(!byId(hq.accounts,input.accountId))return fail('Choose the account used to pay.');if(paymentType==='payment'&&!byId(hq.accounts,input.toAccountId))return fail('Choose the liability account paid.');let result=existing?patch(hq.transactions,existing.id,input):{id:makeId('transaction'),...input,source:'bill-payment',createdAt:now()};if(!existing)hq.transactions.push(result);return{ok:true,state,result,reused:!!existing}}
 if(type==='subscription-save'){const existing=byId(hq.subscriptions,action.id),input={...existing,name:text(action.name)||existing?.name,amount:cents(action.amount),billingCycle:text(action.billingCycle)||'monthly',nextRenewal:validDate(action.nextRenewal)?action.nextRenewal:'',accountId:text(action.accountId),category:text(action.category)||'Subscriptions',trialEnd:validDate(action.trialEnd)?action.trialEnd:'',plannedCancellation:validDate(action.plannedCancellation)?action.plannedCancellation:'',status:['active','canceled','paused'].includes(text(action.status))?text(action.status):'active',active:text(action.status)!=='canceled',academicContext:text(action.academicContext),notes:text(action.notes)};if(!input.name)return fail('Give the subscription a name.');const result=existing?patch(hq.subscriptions,action.id,input):{id:makeId('subscription'),...input,createdAt:now()};if(!existing)hq.subscriptions.push(result);return{ok:true,state,result}}
 if(type==='subscription-renew'){const sub=byId(hq.subscriptions,action.id);if(!sub||!validDate(sub.nextRenewal))return fail('Add the current renewal date first.');const jumps={weekly:0,monthly:1,quarterly:3,yearly:12},next=sub.billingCycle==='weekly'?plusDays(sub.nextRenewal,7):addMonths(sub.nextRenewal,jumps[sub.billingCycle]||1),result=patch(hq.subscriptions,sub.id,{nextRenewal:next});return{ok:true,state,result}}
 if(type==='subscription-link-daily'){const sub=byId(hq.subscriptions,action.id);if(!sub)return fail('That subscription is no longer here.');const date=sub.trialEnd||sub.plannedCancellation||sub.nextRenewal||today,title=sub.plannedCancellation?`Cancel ${sub.name} before renewal`:`Review ${sub.name} before it renews`,linked=ensureDaily(state,{externalId:`money:subscription:${sub.id}`,title,date,sourceId:sub.id,sourceType:'money-subscription'});return linked.ok?{...linked,moneyResult:sub}:linked}
 if(type==='goal-save'){const existing=byId(hq.goals,action.id),input={...existing,name:text(action.name)||existing?.name,targetAmount:cents(action.targetAmount),targetDate:validDate(action.targetDate)?action.targetDate:'',progressMethod:['manual','linked-account','contributions'].includes(text(action.progressMethod))?text(action.progressMethod):'manual',manualProgress:cents(action.manualProgress),linkedAccountId:text(action.linkedAccountId),status:text(action.status)||'active',notes:text(action.notes)};if(!input.name)return fail('Give the goal a name.');const result=existing?patch(hq.goals,action.id,input):{id:makeId('goal'),...input,createdAt:now()};if(!existing)hq.goals.push(result);return{ok:true,state,result}}
 if(type==='goal-contribute'){const goal=byId(hq.goals,action.id),amount=Math.abs(cents(action.amount));if(!goal||!amount)return fail('Choose a goal and contribution amount.');const externalId=text(action.externalId),existing=externalId&&hq.goalContributions.find(row=>row.externalId===externalId);if(existing)return{ok:true,state,result:existing,reused:true};const result={id:makeId('goal-contribution'),goalId:goal.id,amount,date:validDate(action.date)?action.date:today,linkedTransactionId:text(action.linkedTransactionId),externalId,notes:text(action.notes),createdAt:now()};hq.goalContributions.push(result);return{ok:true,state,result}}
 if(type==='liability-save'){const existing=byId(hq.liabilities,action.id),input={...existing,name:text(action.name)||existing?.name,type:text(action.liabilityType)||'loan',currentBalance:cents(action.currentBalance),limit:cents(action.limit),apr:Number(action.apr)||0,minimum:cents(action.minimum),dueDay:Number(action.dueDay)||0,accountId:text(action.accountId),active:true,notes:text(action.notes)};if(!input.name)return fail('Give the liability a name.');const result=existing?patch(hq.liabilities,action.id,input):{id:makeId('liability'),...input,createdAt:now()};if(!existing)hq.liabilities.push(result);return{ok:true,state,result}}
 if(type==='pay-rate-save'){const rate=Number(action.hourlyRate);if(!Number.isFinite(rate)||rate<0)return fail('Enter a valid hourly rate.');const existing=byId(hq.payRates,action.id),input={...existing,source:text(action.source)||'ABA work',hourlyRate:cents(rate),effectiveDate:validDate(action.effectiveDate)?action.effectiveDate:today,effectiveUntil:validDate(action.effectiveUntil)?action.effectiveUntil:'',notes:text(action.notes)};const result=existing?patch(hq.payRates,action.id,input):{id:makeId('pay-rate'),...input,createdAt:now()};if(!existing)hq.payRates.push(result);return{ok:true,state,result}}
 if(type==='platform-save'){const existing=byId(gig.platforms,action.id),input={...existing,name:text(action.name)||existing?.name,icon:text(action.icon)||existing?.icon||'🛍️',active:action.active!==false&&action.active!=='false',notes:text(action.notes)};if(!input.name)return fail('Give the platform a name.');const result=existing?patch(gig.platforms,action.id,input):{id:makeId('gig-platform'),...input,createdAt:now()};if(!existing)gig.platforms.push(result);return{ok:true,state,result}}
 if(type==='order-save'){if(!byId(gig.platforms,action.platformId))return fail('Choose a gig platform.');const existing=byId(gig.orders,action.id),input={...existing,platformId:text(action.platformId),date:validDate(action.date)?action.date:today,basePay:cents(action.basePay),promo:cents(action.promo),tip:cents(action.tip),bonus:cents(action.bonus),reimbursement:cents(action.reimbursement),otherPay:cents(action.otherPay),mileage:Number(action.mileage)||0,activeMinutes:Number(action.activeMinutes)||0,onlineMinutes:Number(action.onlineMinutes)||0,status:text(action.status)||'completed',notes:text(action.notes)};const result=existing?patch(gig.orders,action.id,input):{id:makeId('gig-order'),...input,createdAt:now()};if(!existing)gig.orders.push(result);return{ok:true,state,result}}
 if(type==='gig-goal-save'){const existing=byId(gig.goals,action.id),period=['day','week','month','custom'].includes(text(action.period))?text(action.period):'day',input={...existing,name:text(action.name)||`${period[0].toUpperCase()+period.slice(1)} gig goal`,period,targetAmount:cents(action.targetAmount),startDate:validDate(action.startDate)?action.startDate:(period==='week'?startOfWeek(today):period==='month'?monthStart(today):today),endDate:validDate(action.endDate)?action.endDate:(period==='week'?plusDays(startOfWeek(today),6):period==='month'?monthEnd(today):today),platformId:text(action.platformId),notes:text(action.notes)};const result=existing?patch(gig.goals,action.id,input):{id:makeId('gig-goal'),...input,createdAt:now()};if(!existing)gig.goals.push(result);return{ok:true,state,result}}
 if(type==='payout-save'){if(!byId(gig.platforms,action.platformId))return fail('Choose a platform.');const orderIds=list(action.orderIds).filter(id=>byId(gig.orders,id)?.platformId===text(action.platformId)),amount=action.amount===''?orderIds.reduce((sum,id)=>sum+gigOrderTotal(byId(gig.orders,id)),0):Number(action.amount),existing=byId(gig.payouts,action.id),requested=payoutStates.includes(text(action.status))?text(action.status):'pending',status=requested==='received'&&!existing?.ledgerTransactionId?'processing':requested,input={...existing,platformId:text(action.platformId),orderIds,amount:cents(amount),status,availableDate:validDate(action.availableDate)?action.availableDate:'',destinationAccountId:text(action.destinationAccountId),depositDate:validDate(action.depositDate)?action.depositDate:'',notes:text(action.notes)};const result=existing?patch(gig.payouts,action.id,input):{id:makeId('gig-payout'),...input,createdAt:now()};if(!existing)gig.payouts.push(result);list(existing?.orderIds).filter(id=>!orderIds.includes(id)).forEach(id=>patch(gig.orders,id,{payoutId:''}));orderIds.forEach(id=>patch(gig.orders,id,{payoutId:result.id}));return{ok:true,state,result}}
 if(type==='payout-receive'){const payout=byId(gig.payouts,action.id),accountId=text(action.accountId||payout?.destinationAccountId),date=validDate(action.date)?action.date:today;if(!payout)return fail('That payout is no longer here.');if(!byId(hq.accounts,accountId))return fail('Choose the account receiving the payout.');const externalId=`gig-payout:${payout.id}`,existing=hq.transactions.find(row=>row.externalId===externalId),input=transactionInput({type:'income',amount:payout.amount,date,merchant:`${byId(gig.platforms,payout.platformId)?.name||'Gig'} payout`,category:'Gig income',accountId,status:'posted',externalId},existing);let transaction=existing?patch(hq.transactions,existing.id,input):{id:makeId('transaction'),...input,source:'gig-payout',gigPayoutId:payout.id,createdAt:now()};if(!existing)hq.transactions.push(transaction);patch(gig.payouts,payout.id,{status:'received',destinationAccountId:accountId,depositDate:date,ledgerTransactionId:transaction.id});payout.orderIds.forEach(id=>patch(gig.orders,id,{payoutStatus:'received'}));return{ok:true,state,result:transaction,reused:!!existing}}
 if(type==='gig-expense'){const externalId=text(action.externalId)||makeId('gig-expense'),existing=hq.transactions.find(row=>row.externalId===externalId),input=transactionInput({...action,type:'expense',status:action.status||'posted',externalId,gigExpense:true},existing);if(!byId(hq.accounts,input.accountId)||!input.amount)return fail('Choose an account and amount for the gig expense.');const result=existing?patch(hq.transactions,existing.id,input):{id:makeId('transaction'),...input,source:'gig-expense',createdAt:now()};if(!existing)hq.transactions.push(result);return{ok:true,state,result,reused:!!existing}}
 if(type==='gig-link-daily'){const kind=text(action.kind)||'goal',id=text(action.id)||today,title=kind==='payout'?'Cash out gig payout':kind==='mileage'?'Track gig mileage':kind==='review'?'Review weekly gig earnings':`Gig work toward today’s goal`,linked=ensureDaily(state,{externalId:`gig:${kind}:${id}`,title,date:validDate(action.date)?action.date:today,sourceId:id,sourceType:'gig-work'});return linked.ok?{...linked,gigResult:{kind,id}}:linked}
 if(type==='settings-save'){gig.settings={...gig.settings,taxReservePercent:Math.max(0,Math.min(100,Number(action.taxReservePercent)||0))};setGig(state,gig);return{ok:true,state,result:gig.settings}}
 return fail('That Money Café action is not available.')
}
