const V5_KEY='sm_v5_data';
const V4_KEY='sm_v4_beta';
const LOCK_KEY='sm_recovery_lock';
const RECOVERY_PREFIX='sm_recovery_before_restore_';
const PATHS=[
  'life.tasks','life.routines','life.routineInstances','life.events','life.reminders','life.threads',
  'money.earnings','money.accounts','money.bills','money.spending','money.ledger','money.transactions','money.savingsGoals','money.debts','money.subscriptions',
  'money.hq.accounts','money.hq.transactions','money.hq.bills','money.hq.billInstances','money.hq.subscriptions','money.hq.goals','money.hq.goalContributions','money.hq.liabilities','money.hq.payRates','money.hq.legacyBuckets',
  'work.gig.platforms','work.gig.orders','work.gig.payouts','work.gig.goals',
  'work.items','work.shifts','work.training','work.career',
  'work.hq.clients','work.hq.supervisors','work.hq.sessionPlans','work.hq.scheduleExceptions','work.hq.goalLibrary','work.hq.materialLibrary',
  'education.programs','education.providers','education.requirements','education.courses','education.items','education.sessions','education.reviews','education.transferEvaluations','education.transferResults','education.terms','education.importantDates',
  'insights.dayReviews','insights.activityLog','insights.observations','insights.experiments','movement.sessions',
  'v4.people','v4.hobbies','v4.admin','v4.shopping','v4.brainDump','v4.openDayPlans',
  'nourish.noms.foods','nourish.noms.recipes','nourish.noms.history','nourish.noms.groceries',
  'tasks','routines','events','reminders','habits','projects','goals','wins','courses','schoolTasks','workItems','brainNotes','priorities',
  'money.transactions','money.ledger'
];
const MONEY_PATHS=['money.hq.accounts','money.hq.transactions','money.hq.bills','money.hq.billInstances','money.hq.subscriptions','money.hq.goals','money.hq.goalContributions','money.hq.liabilities','money.hq.payRates','money.hq.legacyBuckets','money.accounts','money.transactions','money.ledger','money.bills','money.subscriptions','money.earnings','money.spending','money.savingsGoals','money.debts','work.gig.orders','work.gig.payouts'];
const get=(o,p)=>p.split('.').reduce((v,k)=>v?.[k],o);
const list=v=>Array.isArray(v)?v:[];
const unwrap=value=>{let v=value;for(let i=0;i<4;i++){if(v&&typeof v==='object'&&!Array.isArray(v)&&v.data&&typeof v.data==='object'&&!Array.isArray(v.data))v=v.data;else break}return v};
const parse=raw=>{try{const v=unwrap(JSON.parse(raw||'null'));return v&&typeof v==='object'&&!Array.isArray(v)?v:null}catch{return null}};
const count=(state,paths)=>paths.reduce((sum,p)=>sum+list(get(state,p)).length,0);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function candidateFromKey(key){const raw=localStorage.getItem(key)||'';const state=parse(raw);if(!state)return null;const total=count(state,PATHS),money=count(state,MONEY_PATHS);if(total<=0&&money<=0)return null;const updated=state?.meta?.updatedAt||state?.__smUpdatedAt||state?.updatedAt||'';return{key,raw,state,total,money,bytes:new Blob([raw]).size,updated};}
function scan(){const seen=new Map();for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(!key)continue;const row=candidateFromKey(key);if(!row)continue;const sig=`${row.total}|${row.money}|${row.bytes}|${row.raw.slice(0,80)}`;if(!seen.has(sig)||/backup|before|restore|recovery/i.test(row.key))seen.set(sig,row);}return [...seen.values()].sort((a,b)=>b.total-a.total||b.money-a.money||b.bytes-a.bytes);}
function restore(row){const stamp=Date.now();try{const cur5=localStorage.getItem(V5_KEY);if(cur5)localStorage.setItem(`${RECOVERY_PREFIX}${stamp}_v5`,cur5);const cur4=localStorage.getItem(V4_KEY);if(cur4)localStorage.setItem(`${RECOVERY_PREFIX}${stamp}_v4`,cur4);}catch{}
  localStorage.setItem(LOCK_KEY,'1');
  localStorage.setItem(V5_KEY,JSON.stringify(row.state));
  localStorage.setItem(V4_KEY,JSON.stringify({data:row.state,recoveredFrom:row.key,recoveredAt:new Date().toISOString()}));
  location.reload();
}
function styles(){if(document.getElementById('katos-recovery-vault-style'))return;const s=document.createElement('style');s.id='katos-recovery-vault-style';s.textContent=`.katos-recovery-banner{position:fixed;z-index:99999;left:12px;right:12px;bottom:12px;padding:12px 14px;border:1.5px solid #efb8cf;border-radius:18px;background:rgba(255,249,252,.97);box-shadow:0 10px 35px rgba(89,55,48,.18);display:flex;gap:10px;align-items:center;justify-content:space-between;color:#69483f;font:700 13px -apple-system,BlinkMacSystemFont,"SF Pro Display",sans-serif}.katos-recovery-banner button,.katos-recovery-vault button{border:0;border-radius:12px;padding:10px 12px;font:800 12px inherit;cursor:pointer;background:#e88eaf;color:white}.katos-recovery-vault{position:fixed;z-index:100000;inset:0;background:rgba(70,45,45,.32);padding:18px;overflow:auto}.katos-recovery-panel{max-width:760px;margin:24px auto;background:#fffafc;border:1.5px solid #efbfd2;border-radius:26px;padding:18px;box-shadow:0 20px 65px rgba(70,45,45,.22);color:#68483f;font-family:-apple-system,BlinkMacSystemFont,"SF Pro Display",sans-serif}.katos-recovery-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.katos-recovery-head h2{margin:3px 0 5px;font-family:Georgia,serif}.katos-recovery-close{background:#f8e7ee!important;color:#9e5b73!important}.katos-recovery-list{display:grid;gap:10px;margin-top:14px}.katos-recovery-row{border:1px solid #efd4df;border-radius:18px;padding:13px;background:white}.katos-recovery-row strong{display:block;margin-bottom:5px}.katos-recovery-meta{font-size:12px;color:#8b6c64;line-height:1.45}.katos-recovery-row.is-target{outline:3px solid #df8faf;background:#fff5f9}.katos-recovery-actions{display:flex;gap:8px;align-items:center;margin-top:9px}.katos-recovery-note{font-size:12px;line-height:1.5;color:#7e625b}`;document.head.appendChild(s)}
function openVault(){document.querySelector('.katos-recovery-vault')?.remove();const rows=scan();const target=rows.find(r=>r.total>=300||r.money>=28);const html=rows.slice(0,30).map((r,i)=>`<div class="katos-recovery-row ${r===target?'is-target':''}"><strong>${r===target?'🍓 POSSIBLE 315 COPY · ':''}${esc(r.key)}</strong><div class="katos-recovery-meta">Total records: <b>${r.total}</b> · Money-ish records: <b>${r.money}</b> · ${(r.bytes/1024).toFixed(1)} KB${r.updated?` · Updated ${esc(r.updated)}`:''}</div><div class="katos-recovery-actions"><button type="button" data-recovery-load="${i}">Load this copy locally</button></div></div>`).join('');const wrap=document.createElement('div');wrap.className='katos-recovery-vault';wrap.innerHTML=`<section class="katos-recovery-panel"><div class="katos-recovery-head"><div><div style="font-size:10px;font-weight:900;letter-spacing:.12em;color:#c96a8e">🍓 KATOS RECOVERY VAULT</div><h2>Search this device for the 315-record planner</h2><p class="katos-recovery-note">Cloud writes are frozen. This scans only this Safari/Home Screen container. A copy near 315 total records or ~30 money records is highlighted. Loading a candidate stays local and also backs up the current local state first.</p></div><button class="katos-recovery-close" data-recovery-close>Close</button></div><div class="katos-recovery-list">${html||'<p>No planner-like local backups were found in this container.</p>'}</div></section>`;document.body.appendChild(wrap);wrap.addEventListener('click',e=>{if(e.target.closest('[data-recovery-close]')||e.target===wrap){wrap.remove();return}const b=e.target.closest('[data-recovery-load]');if(!b)return;const row=rows[Number(b.dataset.recoveryLoad)];if(!row)return;if(confirm(`Load ${row.total} records from ${row.key}? This will NOT write to Supabase.`))restore(row);});}
function mount(){styles();document.querySelector('.katos-recovery-banner')?.remove();const rows=scan();const target=rows.find(r=>r.total>=300||r.money>=28);const b=document.createElement('div');b.className='katos-recovery-banner';b.innerHTML=`<span>🧰 Recovery vault: ${rows.length} local planner copies found.${target?` Possible match: <b>${target.total} records / ${target.money} money</b>.`:''}</span><button type="button" data-open-recovery-vault>Open vault</button>`;b.querySelector('button').addEventListener('click',openVault);document.body.appendChild(b);if(localStorage.getItem(LOCK_KEY)==='1')openVault();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(mount,250));else setTimeout(mount,250);
