const V5_KEY='sm_v5_data';
const V4_KEY='sm_v4_beta';
const LOCK_KEY='sm_recovery_lock';
const RECOVERY_PREFIX='sm_recovery_before_restore_';
const CLOUD_URL='https://sigjwmgekmrwehylvuvu.supabase.co';
const CLOUD_KEY='sb_publishable_CTqamiGR3_lXNW2mBx9wMA_ObemQMAC';
const SESSION_KEYS=['sm_v16_session','sb-sigjwmgekmrwehylvuvu-auth-token','sm_cloud_session'];
const PATHS=[
  'life.tasks','life.routines','life.routineInstances','life.events','life.reminders','life.threads',
  'money.earnings','money.accounts','money.bills','money.spending','money.ledger','money.transactions','money.savingsGoals','money.debts','money.subscriptions',
  'money.hq.accounts','money.hq.transactions','money.hq.bills','money.hq.billInstances','money.hq.subscriptions','money.hq.goals','money.hq.goalContributions','money.hq.liabilities','money.hq.payRates','money.hq.legacyBuckets',
  'work.gig.platforms','work.gig.orders','work.gig.payouts','work.gig.goals',
  'work.items','work.shifts','work.training','work.career',
  'work.hq.clients','work.hq.supervisors','work.hq.sessionPlans','work.hq.scheduleExceptions','work.hq.goalLibrary','work.hq.materialLibrary',
  'education.programs','education.providers','education.requirements','education.courses','education.items','education.sessions','education.reviews','education.transferEvaluations','education.transferResults','education.terms','education.importantDates',
  'insights.dayReviews','insights.activityLog','insights.observations','insights.experiments','movement.sessions',
  'v4.people','v4.hobbies','v4.admin','v4.shopping','v4.brainDump','v4.openDayPlans',
  'nourish.noms.foods','nourish.noms.recipes','nourish.noms.history','nourish.noms.groceries',
  'tasks','routines','events','reminders','habits','projects','goals','wins','courses','schoolTasks','workItems','brainNotes','priorities',
  'money.transactions','money.ledger'
];
const UNIQUE_PATHS=[...new Set(PATHS)];
const MONEY_PATHS=['money.hq.accounts','money.hq.transactions','money.hq.bills','money.hq.billInstances','money.hq.subscriptions','money.hq.goals','money.hq.goalContributions','money.hq.liabilities','money.hq.payRates','money.hq.legacyBuckets','money.accounts','money.transactions','money.ledger','money.bills','money.subscriptions','money.earnings','money.spending','money.savingsGoals','money.debts','work.gig.orders','work.gig.payouts'];
const get=(o,p)=>p.split('.').reduce((v,k)=>v?.[k],o);
const list=v=>Array.isArray(v)?v:[];
const clone=v=>{try{return structuredClone(v)}catch{return JSON.parse(JSON.stringify(v||{}))}};
const unwrap=value=>{let v=value;for(let i=0;i<4;i++){if(v&&typeof v==='object'&&!Array.isArray(v)&&v.data&&typeof v.data==='object'&&!Array.isArray(v.data))v=v.data;else break}return v};
const parse=raw=>{try{const v=unwrap(JSON.parse(raw||'null'));return v&&typeof v==='object'&&!Array.isArray(v)?v:null}catch{return null}};
const count=(state,paths)=>paths.reduce((sum,p)=>sum+list(get(state,p)).length,0);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
function set(state,path,value){const keys=path.split('.');let cursor=state;for(let i=0;i<keys.length-1;i++){const k=keys[i];if(!cursor[k]||typeof cursor[k]!=='object'||Array.isArray(cursor[k]))cursor[k]={};cursor=cursor[k]}cursor[keys.at(-1)]=value;}
function itemKey(item,index){if(!item||typeof item!=='object')return`primitive:${JSON.stringify(item)}`;for(const key of['id','uuid','key','recordId','transactionId','orderId','courseId'])if(item[key]!=null&&String(item[key]).trim())return`${key}:${String(item[key])}`;const bits=['date','day','title','name','text','label','type','kind','amount','dueDate','startTime'].map(k=>item[k]==null?'':String(item[k])).join('|');return bits.replaceAll('|','')?`shape:${bits}`:`json:${JSON.stringify(item)}:${index}`;}
function itemTime(item){const raw=item?.updatedAt||item?.updated_at||item?.modifiedAt||item?.createdAt||item?.created_at||item?.date||'';const n=Date.parse(raw);return Number.isFinite(n)?n:0;}
function mergeArray(sources,path){const found=new Map();for(const source of sources){for(const [index,item] of list(get(source.state,path)).entries()){const key=itemKey(item,index),prev=found.get(key);if(!prev||itemTime(item)>itemTime(prev))found.set(key,clone(item));}}return[...found.values()];}
function makeUnion(label,sources){if(!sources.length)return null;const base=clone([...sources].sort((a,b)=>b.total-a.total||b.bytes-a.bytes)[0].state);for(const path of UNIQUE_PATHS){const merged=mergeArray(sources,path);if(merged.length||sources.some(s=>Array.isArray(get(s.state,path))))set(base,path,merged);}const raw=JSON.stringify(base);return{key:label,raw,state:base,total:count(base,PATHS),money:count(base,MONEY_PATHS),bytes:new Blob([raw]).size,updated:'forensic merge',forensic:true,hqTx:list(get(base,'money.hq.transactions')).length};}
function candidateFromKey(key){const raw=localStorage.getItem(key)||'',state=parse(raw);if(!state)return null;const total=count(state,PATHS),money=count(state,MONEY_PATHS);if(total<=0&&money<=0)return null;const updated=state?.meta?.updatedAt||state?.__smUpdatedAt||state?.updatedAt||'';return{key,raw,state,total,money,bytes:new Blob([raw]).size,updated,hqTx:list(get(state,'money.hq.transactions')).length};}
function scan(){const seen=new Map();for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(!key)continue;const row=candidateFromKey(key);if(!row)continue;const sig=`${row.total}|${row.money}|${row.bytes}|${row.raw.slice(0,80)}`;if(!seen.has(sig)||/backup|before|restore|recovery/i.test(row.key))seen.set(sig,row);}return[...seen.values()].sort((a,b)=>b.total-a.total||b.money-a.money||b.bytes-a.bytes);}
function session(){for(const key of SESSION_KEYS){try{const p=JSON.parse(localStorage.getItem(key)||'null'),s=p?.currentSession||p?.session||p;if(s?.access_token&&s?.user?.id)return s}catch{}}return null;}
async function serverSources(){const s=session();if(!s)return[];const headers={apikey:CLOUD_KEY,Authorization:`Bearer ${s.access_token}`};try{const [curR,snapR]=await Promise.all([fetch(`${CLOUD_URL}/rest/v1/planner_data_v3?user_id=eq.${encodeURIComponent(s.user.id)}&select=data,revision,updated_at,last_device_id`,{headers}),fetch(`${CLOUD_URL}/rest/v1/planner_data_v3_snapshots?user_id=eq.${encodeURIComponent(s.user.id)}&select=data,revision,created_at,reason,device_id&order=created_at.desc&limit=20`,{headers})]);const cur=curR.ok?await curR.json():[],snaps=snapR.ok?await snapR.json():[];return[...list(cur).map(r=>({key:`SERVER current r${r.revision}`,state:unwrap(r.data),updated:r.updated_at||'',server:true})),...list(snaps).map(r=>({key:`SERVER snapshot r${r.revision} · ${r.reason||'snapshot'}`,state:unwrap(r.data),updated:r.created_at||'',server:true}))].filter(r=>r.state&&typeof r.state==='object').map(r=>({...r,raw:JSON.stringify(r.state),total:count(r.state,PATHS),money:count(r.state,MONEY_PATHS),bytes:new Blob([JSON.stringify(r.state)]).size,hqTx:list(get(r.state,'money.hq.transactions')).length}));}catch{return[];}}
function auxReport(){const rows=[];for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(!key)continue;try{const value=JSON.parse(localStorage.getItem(key)||'null');if(Array.isArray(value)&&(/daily|note|history/i.test(key)))rows.push({key,count:value.length,type:'array'});if(value&&typeof value==='object'&&Array.isArray(value.entries)&&(/ledger|money/i.test(key)))rows.push({key,count:value.entries.length,type:'ledger'});}catch{}}return rows.sort((a,b)=>b.count-a.count).slice(0,12);}
function restore(row){const stamp=Date.now();try{const cur5=localStorage.getItem(V5_KEY);if(cur5)localStorage.setItem(`${RECOVERY_PREFIX}${stamp}_v5`,cur5);const cur4=localStorage.getItem(V4_KEY);if(cur4)localStorage.setItem(`${RECOVERY_PREFIX}${stamp}_v4`,cur4);}catch{}localStorage.setItem(LOCK_KEY,'1');localStorage.setItem(V5_KEY,JSON.stringify(row.state));localStorage.setItem(V4_KEY,JSON.stringify({data:row.state,recoveredFrom:row.key,recoveredAt:new Date().toISOString()}));location.reload();}
function styles(){if(document.getElementById('katos-recovery-vault-style'))return;const s=document.createElement('style');s.id='katos-recovery-vault-style';s.textContent=`.katos-recovery-banner{position:fixed;z-index:99999;left:12px;right:12px;bottom:12px;padding:12px 14px;border:1.5px solid #efb8cf;border-radius:18px;background:rgba(255,249,252,.97);box-shadow:0 10px 35px rgba(89,55,48,.18);display:flex;gap:10px;align-items:center;justify-content:space-between;color:#69483f;font:700 13px -apple-system,BlinkMacSystemFont,"SF Pro Display",sans-serif}.katos-recovery-banner button,.katos-recovery-vault button{border:0;border-radius:12px;padding:10px 12px;font:800 12px inherit;cursor:pointer;background:#e88eaf;color:white}.katos-recovery-vault{position:fixed;z-index:100000;inset:0;background:rgba(70,45,45,.32);padding:18px;overflow:auto}.katos-recovery-panel{max-width:800px;margin:24px auto;background:#fffafc;border:1.5px solid #efbfd2;border-radius:26px;padding:18px;box-shadow:0 20px 65px rgba(70,45,45,.22);color:#68483f;font-family:-apple-system,BlinkMacSystemFont,"SF Pro Display",sans-serif}.katos-recovery-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.katos-recovery-head h2{margin:3px 0 5px;font-family:Georgia,serif}.katos-recovery-close{background:#f8e7ee!important;color:#9e5b73!important}.katos-recovery-list{display:grid;gap:10px;margin-top:14px}.katos-recovery-row{border:1px solid #efd4df;border-radius:18px;padding:13px;background:white}.katos-recovery-row strong{display:block;margin-bottom:5px}.katos-recovery-meta{font-size:12px;color:#8b6c64;line-height:1.5}.katos-recovery-row.is-target{outline:3px solid #df8faf;background:#fff5f9}.katos-recovery-row.is-forensic{background:#fff1f7;border-color:#df8faf}.katos-recovery-actions{display:flex;gap:8px;align-items:center;margin-top:9px}.katos-recovery-note{font-size:12px;line-height:1.5;color:#7e625b}.katos-recovery-aux{padding:10px 12px;border-radius:14px;background:#fff7fa;margin-top:12px;font-size:12px;line-height:1.55}`;document.head.appendChild(s)}
async function openVault(){document.querySelector('.katos-recovery-vault')?.remove();const local=scan(),server=await serverSources(),best=local[0];const conservative=best?makeUnion('🧬 FORENSIC UNION · best local + server snapshots',[best,...server]):null;const allUnion=local.length?makeUnion('🧬 WIDE UNION · all local backups + server snapshots',[...local,...server]):null;const rows=[conservative,allUnion,...local,...server].filter(Boolean);const target=rows.find(r=>r.total===315)||rows.find(r=>Math.abs(r.total-315)<=3)||rows.find(r=>r.total>=300&&r.total<=330);const aux=auxReport();const html=rows.slice(0,40).map((r,i)=>`<div class="katos-recovery-row ${r===target?'is-target':''} ${r.forensic?'is-forensic':''}"><strong>${r===target?'🍓 CLOSEST TO 315 · ':''}${esc(r.key)}</strong><div class="katos-recovery-meta">Settings-style records: <b>${r.total}</b> · Money HQ transactions: <b>${r.hqTx}</b> · Broad money arrays: ${r.money} · ${(r.bytes/1024).toFixed(1)} KB${r.updated?` · ${esc(r.updated)}`:''}</div><div class="katos-recovery-actions"><button type="button" data-recovery-load="${i}">Load this copy locally</button></div></div>`).join('');const auxHtml=aux.length?`<div class="katos-recovery-aux"><b>Separate V5 stores still on this device:</b><br>${aux.map(r=>`${esc(r.key)}: <b>${r.count}</b> ${r.type==='ledger'?'ledger entries':'items'}`).join('<br>')}</div>`:'';const wrap=document.createElement('div');wrap.className='katos-recovery-vault';wrap.innerHTML=`<section class="katos-recovery-panel"><div class="katos-recovery-head"><div><div style="font-size:10px;font-weight:900;letter-spacing:.12em;color:#c96a8e">🍓 KATOS FORENSIC RECOVERY</div><h2>Rebuild the 315-record planner from surviving pieces</h2><p class="katos-recovery-note">Cloud writes remain frozen. The first forensic card combines the richest local backup with every surviving server snapshot, deduplicated by record ID. Nothing is written to Supabase.</p>${auxHtml}</div><button class="katos-recovery-close" data-recovery-close>Close</button></div><div class="katos-recovery-list">${html||'<p>No planner-like recovery sources were found.</p>'}</div></section>`;document.body.appendChild(wrap);wrap.addEventListener('click',e=>{if(e.target.closest('[data-recovery-close]')||e.target===wrap){wrap.remove();return}const b=e.target.closest('[data-recovery-load]');if(!b)return;const row=rows[Number(b.dataset.recoveryLoad)];if(!row)return;if(confirm(`Load ${row.total} records from ${row.key}? This stays LOCAL and cloud writes remain frozen.`))restore(row);});}
function mount(){styles();document.querySelector('.katos-recovery-banner')?.remove();const rows=scan(),aux=auxReport();const b=document.createElement('div');b.className='katos-recovery-banner';b.innerHTML=`<span>🧰 Recovery vault: ${rows.length} local planner copies${aux[0]?` · separate store ${aux[0].count} items`:''}. <b>Forensic merge available.</b></span><button type="button" data-open-recovery-vault>Open vault</button>`;b.querySelector('button').addEventListener('click',openVault);document.body.appendChild(b);if(localStorage.getItem(LOCK_KEY)==='1')openVault();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(mount,250));else setTimeout(mount,250);
