import{snapshotV4,selectV5DailyShit,runV5DailyAction,runV5MochiniAction}from'./data.js?v=6.8.0-routine-builder';

const app=document.getElementById('app');
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const text=value=>String(value??'').trim();
const obj=value=>value&&typeof value==='object'&&!Array.isArray(value)?value:{};
let activePlayer=null;

function mode(){return document.body.classList.contains('mode-tiny')?'tiny':document.body.classList.contains('mode-power')?'power':'normal'}
function daily(){const snap=snapshotV4();return{snap,view:selectV5DailyShit(snap.today,{mode:mode()})}}
function routineById(id){const {snap,view}=daily();return{snap,routine:view.routineLibrary.find(row=>String(row.id)===String(id))||null}}
function statusFor(routine,step){return text(obj(routine?.instance?.steps)[step.id])||'open'}
function counts(routine){const values=routine.steps.map(step=>statusFor(routine,step));return{complete:values.filter(value=>value==='complete').length,skipped:values.filter(value=>value==='skipped').length,resolved:values.filter(value=>value==='complete'||value==='skipped').length,total:values.length}}
function isFinished(routine){return routine?.status==='complete'}
function iconFor(routine){if(text(routine?.icon))return text(routine.icon);const value=text(routine?.title).toLowerCase();if(/morning|wake|am\b/.test(value))return'☀️';if(/night|bed|sleep|pm\b/.test(value))return'🌙';if(/study|school|class/.test(value))return'📚';if(/work|client|shift/.test(value))return'💼';if(/clean|reset|tidy|room/.test(value))return'🧹';if(/skin|self|shower|care/.test(value))return'🚿';return'🍓'}
function totalMinutes(routine){return routine.steps.reduce((sum,step)=>sum+(Number(step.minutes)||5),0)}
function historyLabel(routine){const history=routine.history||{};if(history.weekCompleted)return`${history.weekCompleted} completed this week`;if(history.weekPartial)return`${history.weekPartial} partial this week · back at it 🌱`;return`${history.weekLogged||0} of ${history.weekPlanned||0} planned days logged`}
function statusLabel(status){return({'not-logged':'Not logged',running:'In progress',partial:'Partially completed',complete:'Completed',skipped:'Skipped'})[status]||'Not logged'}
function trail(routine){const pieces=routine.steps.map(step=>{const status=statusFor(routine,step),symbol=status==='complete'?'🍓':status==='skipped'?'◌':'○';return`<span class="rp-dot ${status}" title="${esc(step.label)}">${symbol}</span>`});return pieces.length?`<div class="rp-trail" aria-label="Routine progress">${pieces.join('<i>━</i>')}</div>`:'<div class="rp-trail empty">Add your first gentle step in the routine editor.</div>'}
function cardBody(routine){const c=counts(routine),done=isFinished(routine),tiny=mode()==='tiny',status=statusLabel(routine.status),mission=routine.tinyStart||routine.steps[0]?.label||'Choose one tiny beginning';if(tiny)return`<div class="rp-card-head"><div class="rp-card-icon">${esc(iconFor(routine))}</div><div class="rp-card-copy"><span class="rp-kicker">TINY MISSION</span><b>${esc(routine.title)}</b><small>${esc(mission)}</small></div></div><button type="button" class="btn primary rp-start" data-routine-player-open="${esc(routine.id)}"${done?' disabled':''}>${done?'✓ Counted today':routine.status==='partial'?'Continue tiny →':'Start tiny →'}</button>`;return`<div class="rp-card-head"><div class="rp-card-icon">${esc(iconFor(routine))}</div><div class="rp-card-copy"><span class="rp-kicker">${esc(status.toUpperCase())}</span><b>${esc(routine.title)}</b><small>${esc(routine.category)} · ${totalMinutes(routine)} min-ish · ${c.complete}/${c.total} done</small></div><span class="rp-status ${esc(routine.status)}">${esc(status)}</span></div><div class="rp-tiny-preview"><span>🌱 Tiny Start</span><b>${esc(mission)}</b></div>${trail(routine)}<div class="rp-week-copy">${esc(historyLabel(routine))}</div><div class="rp-card-actions">${routine.steps.length||routine.tinyStart?`<button type="button" class="btn primary rp-start" data-routine-player-open="${esc(routine.id)}"${done?' disabled':''}>${done?'✓ Completed':routine.status==='partial'||routine.status==='running'?'Continue →':'Start →'}</button>`:''}<button type="button" class="btn soft" data-daily-open="edit-routine-${esc(routine.id)}">Open routine</button>${!done?`<button type="button" class="btn tiny" data-routine-player-skip="${esc(routine.id)}">Not today</button>`:''}</div>`}
function mountCards(){if(!app)return;const {view}=daily();app.querySelectorAll('.daily-routine').forEach(card=>{const id=card.dataset.dailyId||card.querySelector('[data-daily-id]')?.dataset.dailyId;if(!id)return;const routine=view.routineLibrary.find(row=>String(row.id)===String(id));if(!routine)return;card.classList.add('routine-player-card');card.innerHTML=cardBody(routine)});mountDoneRoutines(view.routines)}
function mountDoneRoutines(routines){const completed=routines.filter(isFinished);if(!completed.length)return;const doneCard=[...app.querySelectorAll('.card')].find(card=>/DONE/i.test(card.querySelector('.ey')?.textContent||''));const details=doneCard?.querySelector('details.daily-done');if(!details||details.querySelector('[data-routine-done-list]'))return;const wrap=document.createElement('div');wrap.dataset.routineDoneList='1';wrap.className='rp-done-list';wrap.innerHTML=completed.map(routine=>`<div class="room-row rp-done-row"><div class="room-row-main"><b>${esc(iconFor(routine))} ${esc(routine.title)}</b><span>Routine completed today</span></div><span class="room-tag">Done</span></div>`).join('');details.append(wrap)}

function openingLine(routine){return routine.tinyStart?'We only need the beginning. The rest can wait.':'One little thing at a time. No giant checklist energy here. ♡'}
function mochiniLine(routine,lastAction=''){const c=counts(routine);if(routine.status==='complete')return'YOU DID ITTT. Tiny crown secured. 👑 :3';if(lastAction==='skip')return'Skipped is information, not a failure. The kingdom is okay. ♡';if(c.complete&&c.complete<c.total)return`${c.complete} step${c.complete===1?'':'s'} counted. Partial absolutely counts. 🌱`;return'We are only doing the next little thing together. 🍡'}
function fullStepList(routine,current){return routine.steps.map((step,index)=>{const status=statusFor(routine,step);return`<div class="rp-all-step ${status} ${index===current?'current':''}"><button type="button" class="rp-step-check" data-routine-player-step="${status==='complete'?'open':'complete'}" data-index="${index}" aria-label="${status==='complete'?'Uncheck':'Complete'} ${esc(step.label)}">${status==='complete'?'✓':status==='skipped'?'◌':index+1}</button><button type="button" class="rp-step-copy" data-routine-player-jump="${index}"><b>${esc(step.label)}</b><small>${Number(step.minutes)||5} min-ish</small></button><button type="button" class="btn tiny" data-routine-player-step="skipped" data-index="${index}">${status==='skipped'?'Undo':'Skip'}</button></div>`}).join('')}
function tinyGate(routine){return`<section class="rp-tiny-gate"><span class="rp-step-number">ONLY MISSION RIGHT NOW</span><div class="rp-mission-icon">${esc(iconFor(routine))}</div><h3>${esc(routine.tinyStart||routine.steps[0]?.label||'Pick one tiny beginning')}</h3><p>You do not have to agree to the whole routine yet.</p><div class="rp-step-actions"><button type="button" class="btn primary" data-routine-player-tiny-done>✓ Done</button><button type="button" class="btn soft" data-routine-player-show-full>Show full routine</button><button type="button" class="btn tiny" data-routine-player-close>Not right now</button></div></section>`}
function fullRoutine(routine){const c=counts(routine),idx=Math.max(0,Math.min(activePlayer?.index??0,Math.max(0,routine.steps.length-1))),step=routine.steps[idx],status=step?statusFor(routine,step):'open',hasProgress=c.complete>0||c.skipped>0||routine.tinyStartDone;return`<section class="rp-full"><div class="rp-progress-block">${trail(routine)}<div class="rp-progress-copy"><b>${c.complete} of ${c.total} completed</b><span>${c.skipped?`${c.skipped} skipped · `:''}${esc(statusLabel(routine.status))}</span></div></div>${step?`<section class="rp-spotlight"><span class="rp-step-number">STEP ${idx+1} OF ${routine.steps.length}</span><h3>${esc(step.label)}</h3><p>${Number(step.minutes)||5} min-ish · ${status==='complete'?'already counted ✓':status==='skipped'?'skipped for today':'only this step is in the spotlight'}</p><div class="rp-step-actions"><button type="button" class="btn primary" data-routine-player-step="complete" data-index="${idx}">✓ Done</button><button type="button" class="btn soft" data-routine-player-step="skipped" data-index="${idx}">Skip today</button></div></section>`:'<section class="rp-spotlight"><h3>No steps yet</h3><p>Open the routine editor to add gentle steps.</p></section>'}<div class="rp-nav"><button type="button" class="btn tiny" data-routine-player-prev${idx<=0?' disabled':''}>← Previous</button><button type="button" class="btn tiny" data-routine-player-next${idx>=routine.steps.length-1?' disabled':''}>Next →</button></div><div class="rp-all-list">${fullStepList(routine,idx)}</div><div class="rp-mochini"><span>🍡</span><div><b>Mochini</b><p>${esc(mochiniLine(routine,activePlayer?.lastAction))}</p></div></div><div class="rp-footer"><button type="button" class="btn soft" data-routine-player-close>Not right now</button><button type="button" class="btn primary" data-routine-player-log ${hasProgress?'':'disabled'}>${c.total&&c.complete===c.total?'🍓 Complete routine':'🌱 Save partial & close'}</button></div></section>`}
function playerShell(routine){const gate=activePlayer?.stage==='tiny'&&!routine.tinyStartDone;return`<div class="detail-modal-backdrop rp-backdrop" data-routine-player-modal><section class="detail-modal rp-modal" role="dialog" aria-modal="true" aria-labelledby="rp-title"><div class="rp-top"><div><div class="ey">${esc(iconFor(routine))} ROUTINE · ${mode().toUpperCase()}</div><h2 id="rp-title">${esc(routine.title)}</h2><p>${esc(openingLine(routine))}</p></div><button type="button" class="detail-modal-close" data-routine-player-close aria-label="Close routine">×</button></div>${gate?tinyGate(routine):fullRoutine(routine)}</section></div>`}
function openPlayer(id){const found=routineById(id);if(!found.routine)return;const routine=found.routine;if(!routine.instance||['not-logged','skipped'].includes(routine.status)){const result=runV5DailyAction({type:'routine-run',id:routine.id,date:found.snap.today});if(!result.ok)return;try{runV5MochiniAction({type:'focus'})}catch{}}const fresh=routineById(id);activePlayer={id,date:fresh.snap.today,index:0,stage:fresh.routine.tinyStart&&!fresh.routine.tinyStartDone?'tiny':'full',lastAction:''};app.querySelector('[data-routine-player-modal]')?.remove();app.insertAdjacentHTML('beforeend',playerShell(fresh.routine));app.querySelector('[data-routine-player-modal] button')?.focus()}
function redrawPlayer(){if(!activePlayer)return;const fresh=routineById(activePlayer.id);const old=app.querySelector('[data-routine-player-modal]');if(fresh.routine&&old)old.outerHTML=playerShell(fresh.routine)}
function resolveStep(status,index){if(!activePlayer)return;const routine=routineById(activePlayer.id).routine,current=routine?.steps?.[Number(index)],next=status==='skipped'&&current&&statusFor(routine,current)==='skipped'?'open':status;const result=runV5DailyAction({type:'routine-step',id:activePlayer.id,date:activePlayer.date,index,status:next});if(!result.ok){window.alert(result.error||'That routine step could not be saved.');return}activePlayer.lastAction=next==='skipped'?'skip':'done';const fresh=routineById(activePlayer.id).routine;if(fresh){const firstOpen=fresh.steps.findIndex(step=>!['complete','skipped'].includes(statusFor(fresh,step)));activePlayer.index=firstOpen>=0?firstOpen:Number(index)}redrawPlayer()}
function finishRoutine(){if(!activePlayer)return;const result=runV5DailyAction({type:'routine-complete',id:activePlayer.id,date:activePlayer.date});if(!result.ok){window.alert(result.error||'That progress could not be saved.');return}const fresh=routineById(activePlayer.id).routine;if(fresh?.status==='complete'){try{const reaction=runV5MochiniAction({type:'celebrate'});window.dispatchEvent(new CustomEvent('katos:mochini',{detail:reaction}));window.KatOSMochini?.nudge?.('proud')}catch{}}closeAndRefresh()}
function closeAndRefresh(){app.querySelector('[data-routine-player-modal]')?.remove();activePlayer=null;app.querySelector('[data-view="daily"]')?.click()}

app?.addEventListener('click',event=>{
 const rename=event.target.closest?.('.routine-edit-step>b');if(rename&&app.contains(rename)){const list=rename.closest('.routine-edit-steps'),row=rename.closest('.routine-edit-step'),modal=rename.closest('[data-daily-modal]'),id=modal?.querySelector('[data-daily-routine-edit]')?.dataset.dailyId,index=list?[...list.children].indexOf(row):-1,label=window.prompt('Rename this routine step:',rename.textContent.trim());if(label===null)return;const result=runV5DailyAction({type:'routine-update-step',id,index,label});if(!result.ok)window.alert(result.error||'That step could not be renamed.');app.querySelector('[data-view="daily"]')?.click();return}
 const preset=event.target.closest?.('[data-routine-shower-preset]');if(preset&&app.contains(preset)){const form=preset.closest('form');if(!form)return;const values={title:'Shower',icon:'🚿',category:'Self care',tinyStart:'Turn the shower water on.',effort:'medium',notes:'A gentle getting-ready routine. Partial completion always counts.',steps:'Get towel/clothes\nTurn shower water on\nGet undressed\nGet in shower\nWash body\nWash face\nHair step if needed\nGet out + dry off\nLotion/deodorant/skincare\nGet dressed'};Object.entries(values).forEach(([name,value])=>{const field=form.elements.namedItem(name);if(field)field.value=value});return}
 const open=event.target.closest?.('[data-routine-player-open]');if(open&&app.contains(open)){event.stopPropagation();openPlayer(open.dataset.routinePlayerOpen);return}
 const skip=event.target.closest?.('[data-routine-player-skip]');if(skip&&app.contains(skip)){event.stopPropagation();const snap=snapshotV4();runV5DailyAction({type:'routine-skip',id:skip.dataset.routinePlayerSkip,date:snap.today});app.querySelector('[data-view="daily"]')?.click();return}
 if(!event.target.closest?.('[data-routine-player-modal]'))return;
 if(event.target.closest('[data-routine-player-close]')){closeAndRefresh();return}
 if(event.target.closest('[data-routine-player-tiny-done]')){const result=runV5DailyAction({type:'routine-tiny-start',id:activePlayer.id,date:activePlayer.date});if(!result.ok){window.alert(result.error);return}activePlayer.stage='full';activePlayer.lastAction='done';redrawPlayer();return}
 if(event.target.closest('[data-routine-player-show-full]')){activePlayer.stage='full';redrawPlayer();return}
 const step=event.target.closest('[data-routine-player-step]');if(step){resolveStep(step.dataset.routinePlayerStep,step.dataset.index);return}
 if(event.target.closest('[data-routine-player-prev]')){activePlayer.index=Math.max(0,activePlayer.index-1);redrawPlayer();return}
 if(event.target.closest('[data-routine-player-next]')){const fresh=routineById(activePlayer.id).routine;if(fresh)activePlayer.index=Math.min(fresh.steps.length-1,activePlayer.index+1);redrawPlayer();return}
 const jump=event.target.closest('[data-routine-player-jump]');if(jump){activePlayer.index=Number(jump.dataset.routinePlayerJump)||0;redrawPlayer();return}
 if(event.target.closest('[data-routine-player-log]')){finishRoutine();return}
});

window.addEventListener('katos:rendered',mountCards);
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mountCards,{once:true});else mountCards();
