import assert from'node:assert/strict';
import{existsSync,readFileSync}from'node:fs';
import{dirname,resolve}from'node:path';
import{fileURLToPath}from'node:url';

const folder=dirname(fileURLToPath(import.meta.url));
const index=readFileSync(resolve(folder,'index.html'),'utf8');
const app=readFileSync(resolve(folder,'app.js'),'utf8');
const styles=readFileSync(resolve(folder,'styles.css'),'utf8');
const daily=readFileSync(resolve(folder,'daily-shit.js'),'utf8');
const dailyCss=readFileSync(resolve(folder,'daily-shit.css'),'utf8');
const boss=readFileSync(resolve(folder,'boss.js'),'utf8');
const bossCss=readFileSync(resolve(folder,'boss.css'),'utf8');
const work=readFileSync(resolve(folder,'work-hq.js'),'utf8');
const study=readFileSync(resolve(folder,'study.js'),'utf8');
const studyEngine=readFileSync(resolve(folder,'study-nook.js'),'utf8');
const studyCss=readFileSync(resolve(folder,'study.css'),'utf8');
const money=readFileSync(resolve(folder,'money.js'),'utf8');
const moneyEngine=readFileSync(resolve(folder,'money-gig.js'),'utf8');
const moneyCss=readFileSync(resolve(folder,'money.css'),'utf8');
const modalCss=readFileSync(resolve(folder,'detailed-rooms.css'),'utf8');

for(const href of [...index.matchAll(/href="\.\/([^"?]+)(?:\?[^\"]*)?"/g)].map(match=>match[1]))assert.equal(existsSync(resolve(folder,href)),true,`${href} should exist`);
assert.equal(index.includes('light-text.css'),false,'the orphaned stylesheet link should be gone');
for(const selector of ['.sidebar{','.topbar{','.mode-switch{','.detail-modal-backdrop{','body.mode-tiny','body.mode-power'])assert.equal(styles.includes(selector)||modalCss.includes(selector),true,`${selector} should remain in the V5 shell`);
for(const hook of ['data-mode="normal"','data-mode="tiny"','data-mode="power"','data-detail-open','data-detail-modal'])assert.equal(app.includes(hook),true,`${hook} should remain wired`);
assert.equal(/(?:from|href=)[^\n]*v17\//.test(`${index}\n${app}\n${styles}`),false,'V5 shell must not import the V17 presentation');
for(const hook of ['data-daily-open','data-daily-modal','data-daily-task-edit','data-daily-routine-edit'])assert.equal(`${app}\n${dailyCss}`.includes(hook),true,`${hook} should keep Daily Shit in V5 popups`);
assert.equal(dailyCss.includes('.daily-shit-row[data-daily-open]'),true,'Daily Shit rows should remain tappable V5 cards');
assert.equal(daily.includes('v17/'),false,'Daily Shit logic must not import the V17 presentation');
for(const hook of ['data-work-open','data-work-modal','data-work-form','data-work-close'])assert.equal(`${app}\n${boss}`.includes(hook),true,`${hook} should keep Work records in V5 popups`);
assert.equal(bossCss.includes('.work-open-card'),true,'saved Work cards remain visibly tappable');
assert.equal(modalCss.includes('max-height')&&modalCss.includes('overflow:auto'),true,'V5 modals remain viewport-bounded and scrollable');
assert.equal(`${boss}\n${bossCss}\n${work}`.includes('V5 • LIFE OS'),false,'the Codex-built V17 presentation shell is not copied into Work HQ');
assert.equal(/(?:from|url\(|href=)[^\n]*v17\//.test(`${boss}\n${bossCss}\n${work}`),false,'Work HQ must not import V17 presentation assets');
for(const label of ['BT / RLT','RBT exam','Use aliases/codes only'])assert.equal(boss.includes(label),true,`${label} should remain explicit in the Work HQ presentation`);
for(const hook of ['data-study-open','data-study-modal','data-study-form','data-study-close','data-study-program-switch'])assert.equal(`${app}\n${study}`.includes(hook),true,`${hook} should keep academic records in V5 popups`);
assert.equal(studyCss.includes('.study-open-card'),true,'saved Study Nook cards remain visibly tappable');
assert.equal(studyCss.includes('@media(max-width:780px)')&&studyCss.includes('font-size:16px'),true,'Study Nook popup controls remain reachable and mobile-safe');
assert.equal(index.includes('./study.css'),true,'the V5-native Study Nook stylesheet is loaded');
assert.equal(app.includes("ui.view==='study'?renderStudy"),true,'Study Nook evolves inside the authoritative V5 shell');
assert.equal(`${study}\n${studyCss}\n${studyEngine}`.includes('V5 • LIFE OS'),false,'the Codex-built V17 presentation shell is not copied into Study Nook');
assert.equal(/(?:from|url\(|href=)[^\n]*v17\//.test(`${study}\n${studyCss}\n${studyEngine}`),false,'Study Nook must not import V17 presentation assets');
for(const protectedHook of ['data-daily-open','data-work-open','data-mode="normal"','data-mode="tiny"','data-mode="power"'])assert.equal(app.includes(protectedHook),true,`${protectedHook} must survive Pass 3`);
for(const hook of ['data-money-open','data-money-modal','data-money-form','data-money-close','data-money-lane'])assert.equal(`${app}\n${money}`.includes(hook),true,`${hook} should keep Money and Gig records in V5-native popups`);
assert.equal(moneyCss.includes('.money-open-card')&&moneyCss.includes('.money-modal .detail-modal'),true,'saved finance and gig cards remain tappable and use the existing modal shell');
assert.equal(moneyCss.includes('@media(max-width:780px)')&&moneyCss.includes('font-size:16px'),true,'Money/Gig popup controls remain reachable and mobile-safe');
assert.equal(index.includes('./money.css'),true,'the V5-native Money Café stylesheet is loaded');
assert.equal(app.includes("ui.view==='money'?renderMoney"),true,'Money Café evolves inside the authoritative V5 shell');
assert.equal(app.includes("['review','🪷','Daily note']"),false,'Daily note should not appear as a separate sidebar destination');
assert.equal(app.includes("if(ui.view==='review')ui.view='time'"),true,'a previously saved Daily note view should return safely to Schedule');
assert.equal(moneyCss.includes('grid-template-columns:repeat(auto-fit,minmax(145px,1fr))'),true,'fast transaction controls should wrap instead of overflowing the iPad content area');
assert.equal(moneyCss.includes('font-weight:500'),true,'Money Café uses the lighter V5 text treatment');
assert.equal(`${money}\n${moneyCss}\n${moneyEngine}`.includes('V5 • LIFE OS'),false,'the Codex-built V17 presentation shell is not copied into Money Café');
assert.equal(/(?:from|url\(|href=)[^\n]*v17\//.test(`${money}\n${moneyCss}\n${moneyEngine}`),false,'Money Café must not import V17 presentation assets');
assert.equal(boss.includes('data-money-target="gig"'),true,'the protected Work gig lane links to the full V5-native Gig Work experience');
for(const protectedHook of ['data-daily-open','data-work-open','data-study-open','data-mode="normal"','data-mode="tiny"','data-mode="power"'])assert.equal(app.includes(protectedHook),true,`${protectedHook} must survive Pass 4`);

console.log('V5 shell preservation tests passed');
