import{applyDailyAction}from'./daily-shit.js?v=5.3.0-study-nook';

export const ACADEMIC_SCHEMA_VERSION=1;
export const PROGRAM_LEVELS=['certificate','associate','bachelors','masters','doctoral','other'];
export const REQUIREMENT_TYPES=['course','credit','capstone','practicum','field-experience','exam','portfolio','milestone','other'];
export const COURSE_STATUSES=['planned','next-up','in-progress','waiting','completed','dropped','archived'];
export const TRANSFER_STATUSES=['planning','taking-now','completed-externally','transcript-not-sent','transcript-sent','pending-evaluation','accepted','partially-accepted','rejected','appeal-pending','not-applicable'];
export const ASSIGNMENT_STATUSES=['not-started','drafting','submitted','grading','revision-needed','completed'];

const list=value=>Array.isArray(value)?value:[];
const obj=value=>value&&typeof value==='object'&&!Array.isArray(value)?value:{};
const text=value=>String(value??'').trim();
const clone=value=>{try{return structuredClone(value)}catch{return JSON.parse(JSON.stringify(value||{}))}};
const now=()=>new Date().toISOString();
const makeId=prefix=>`${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;
const validDate=value=>/^\d{4}-\d{2}-\d{2}$/.test(text(value));
const bool=value=>value===true||value==='true'||value==='on'||value==='yes';
const number=value=>Number.isFinite(Number(value))?Number(value):0;
const clamp=value=>Math.max(0,Math.min(100,number(value)));
const csv=value=>(Array.isArray(value)?value:String(value??'').split(',')).map(text).filter(Boolean);
const unique=values=>[...new Set(values.map(text).filter(Boolean))];
const pathValue=(source,path)=>path.split('.').reduce((value,key)=>value?.[key],source);
const setPath=(source,path,value)=>{const keys=path.split('.');let cursor=source;for(const key of keys.slice(0,-1)){cursor[key]=obj(cursor[key]);cursor=cursor[key]}cursor[keys.at(-1)]=value};
const replaceById=(rows,id,next)=>rows.some(row=>String(row?.id)===String(id))?rows.map(row=>String(row?.id)===String(id)?next:row):[...rows,next];
const titleOf=row=>text(row?.title||row?.name||row?.text||row?.label);
const normalizeToken=value=>text(value).toLowerCase().replace(/[ _]+/g,'-');
const programRank={active:0,preparing:1,future:2,planned:3,completed:4,archived:5};

function archiveRecord(state,path,item){
 const archived={id:makeId('archive'),kind:path,originalId:item.id,title:titleOf(item)||'Archived academic record',data:item,archivedAt:now()};
 setPath(state,'v4.archive',[...list(pathValue(state,'v4.archive')),archived]);return archived;
}
function statusOfCourse(row){
 const raw=normalizeToken(row?.status);if(COURSE_STATUSES.includes(raw))return raw;
 if(['active','taking','current'].includes(raw))return'in-progress';if(['transferred','complete','done'].includes(raw))return'completed';if(['not-started','queued'].includes(raw))return'planned';return'planned';
}
function statusOfAssignment(row){
 if(row?.done===true||row?.completed===true)return'completed';const raw=normalizeToken(row?.status);if(ASSIGNMENT_STATUSES.includes(raw))return raw;if(raw==='in-progress')return'drafting';return'not-started';
}
function transferStatusOf(row,providerName='',institutionName=''){
 const raw=normalizeToken(row?.transferStatus||row?.transcriptStatus||row?.evaluationStatus);if(TRANSFER_STATUSES.includes(raw))return raw;
 if(raw==='completed-external')return'completed-externally';if(raw==='partial')return'partially-accepted';
 return providerName&&institutionName&&providerName.toLowerCase()!==institutionName.toLowerCase()?'planning':'not-applicable';
}
function byId(rows,id){return list(rows).find(row=>String(row?.id)===String(id))||null}
function byName(rows,name){const key=text(name).toLowerCase();return list(rows).find(row=>text(row?.name).toLowerCase()===key)||null}
function ensureProvider(education,name,type='course-provider'){
 const label=text(name);if(!label)return null;const existing=byName(education.providers,label);if(existing){if(type==='degree-institution'&&existing.type!=='degree-institution')existing.type=type;return existing}
 const stable=label.toLowerCase()==='wgu'?'provider-wgu':label.toLowerCase()==='sophia'?'provider-sophia':makeId('provider'),provider={id:stable,name:label,type,active:true,createdAt:now()};education.providers.push(provider);return provider;
}
function findCourse(education,value){const raw=text(value),key=raw.toLowerCase();if(!key)return null;return education.courses.find(row=>String(row.id)===raw||titleOf(row).toLowerCase()===key||text(row.courseCode).toLowerCase()===key)||null}
function normalizeProgram(row,index,education){
 const title=titleOf(row)||`Academic Program ${index+1}`,institutionName=text(row.institution||row.institutionName||row.school)||(index===0?'WGU':''),provider=ensureProvider(education,institutionName,'degree-institution');
 return{...row,id:text(row.id)||makeId('program'),title,shortTitle:text(row.shortTitle)||title,level:PROGRAM_LEVELS.includes(normalizeToken(row.level))?normalizeToken(row.level):(title.toLowerCase().includes('master')?'masters':title.toLowerCase().includes('bachelor')?'bachelors':'other'),programType:text(row.programType)||'degree',institutionId:text(row.institutionId)||provider?.id||'',status:['active','preparing','future','planned','completed','archived'].includes(normalizeToken(row.status))?normalizeToken(row.status):(index===0?'active':'future'),totalCreditsRequired:Math.max(0,number(row.totalCreditsRequired||row.totalCredits)),officiallyConferred:row.officiallyConferred===true,completionDate:text(row.completionDate),createdAt:text(row.createdAt)||now()};
}
function normalizeCourse(row,index,education,programId,migrationKey=''){
 const program=byId(education.programs,text(row.programId)||programId),institution=byId(education.providers,program?.institutionId),providerName=text(row.provider||row.providerName||row.source||row.institution)||institution?.name||'',provider=ensureProvider(education,providerName,providerName&&institution&&providerName.toLowerCase()===institution.name.toLowerCase()?'degree-institution':'course-provider');
 return{...row,id:text(row.id)||makeId('course'),migrationKey:text(row.migrationKey)||migrationKey,title:titleOf(row)||`Course ${index+1}`,programId:text(row.programId)||programId,providerId:text(row.providerId)||provider?.id||'',termId:text(row.termId),courseCode:text(row.courseCode||row.code),credits:Math.max(0,number(row.credits||row.creditHours||row.competencyUnits)),status:statusOfCourse(row),progressPercent:clamp(row.progressPercent??row.progress),queueOrder:Number.isFinite(Number(row.queueOrder))?Number(row.queueOrder):index,pinned:row.pinned===true,completionDate:text(row.completionDate||row.completedAt).slice(0,10),targetDate:text(row.targetDate||row.officialDeadline),requirementIds:unique(csv(row.requirementIds||row.requirementId)),transferStatus:transferStatusOf(row,provider?.name,institution?.name),touchstones:Math.max(0,number(row.touchstones)),milestones:Math.max(0,number(row.milestones)),notes:text(row.notes||row.reflection?.overall),createdAt:text(row.createdAt)||now()};
}
function normalizeAssignment(row,index,education,programId,migrationKey=''){
 const course=findCourse(education,row.courseId||row.course||row.courseName),courseId=text(row.courseId)||course?.id||'',type=normalizeToken(row.type||row.kind||'assignment');
 return{...row,id:text(row.id)||makeId('assignment'),migrationKey:text(row.migrationKey)||migrationKey,title:titleOf(row)||`Academic item ${index+1}`,programId:text(row.programId)||course?.programId||programId,courseId,status:statusOfAssignment(row),type:text(type)||'assignment',progressPercent:clamp(row.progressPercent??(row.done?100:0)),dueDate:validDate(row.dueDate||row.due||row.date)?text(row.dueDate||row.due||row.date):'',dueTime:text(row.dueTime||row.time),hardDeadline:bool(row.hardDeadline)||normalizeToken(row.deadlineType)==='hard',order:Number.isFinite(Number(row.order))?Number(row.order):index,score:text(row.score||row.grade),notes:text(row.notes||row.note||row.nextStep),createdAt:text(row.createdAt)||now()};
}

export function initializeStudyNook(source={},today=new Date().toISOString().slice(0,10)){
 let state=clone(source),original=obj(state.education),education={...original,programs:list(original.programs),providers:list(original.providers),requirements:list(original.requirements),courses:list(original.courses),items:list(original.items),transferEvaluations:list(original.transferEvaluations),transferResults:list(original.transferResults),terms:list(original.terms),sessions:list(original.sessions),importantDates:list(original.importantDates),meta:{schemaVersion:ACADEMIC_SCHEMA_VERSION,...obj(original.meta)}};
 education.providers=education.providers.map(row=>({...row,id:text(row.id)||makeId('provider'),name:titleOf(row)||'Academic provider',type:text(row.type)||'course-provider'}));
 const initialPrograms=education.programs.slice();education.programs=[];initialPrograms.forEach((row,index)=>education.programs.push(normalizeProgram(row,index,education)));
 if(!education.programs.length){const wgu=ensureProvider(education,'WGU','degree-institution');education.programs.push({id:'study-program-bachelors',title:"Bachelor's Degree",shortTitle:"Bachelor's Degree",level:'bachelors',programType:'degree',institutionId:wgu.id,status:'active',totalCreditsRequired:0,officiallyConferred:false,completionDate:'',createdAt:now()})}
 const active=education.programs.find(row=>row.status==='active')||education.programs[0],programId=active.id;
 const currentCourses=education.courses.slice();education.courses=[];currentCourses.forEach((row,index)=>education.courses.push(normalizeCourse(row,index,education,programId)));
 const courseKeys=new Set(education.courses.map(row=>text(row.migrationKey))),courseIds=new Set(education.courses.map(row=>String(row.id)));
 list(state.courses).forEach((row,index)=>{const key=`legacy.courses:${text(row?.id)||index}`;if(!courseKeys.has(key)&&!courseIds.has(String(row?.id))){education.courses.push(normalizeCourse(row,education.courses.length,education,programId,key));courseKeys.add(key)}});
 const currentItems=education.items.slice();education.items=[];currentItems.forEach((row,index)=>education.items.push(normalizeAssignment(row,index,education,programId)));
 const itemKeys=new Set(education.items.map(row=>text(row.migrationKey))),itemIds=new Set(education.items.map(row=>String(row.id)));
 list(state.schoolTasks).forEach((row,index)=>{const key=`legacy.schoolTasks:${text(row?.id)||index}`;if(!itemKeys.has(key)&&!itemIds.has(String(row?.id))){education.items.push(normalizeAssignment(row,education.items.length,education,programId,key));itemKeys.add(key)}});
 education.sessions=education.sessions.map((row,index)=>({...row,id:text(row.id)||makeId('study-session'),programId:text(row.programId)||findCourse(education,row.courseId||row.course)?.programId||programId,courseId:text(row.courseId)||findCourse(education,row.course)?.id||'',targetMinutes:Math.max(0,number(row.targetMinutes||row.minutes)),actualMinutes:Math.max(0,number(row.actualMinutes||row.actualMinutesOptional||(row.completedAt?row.minutes:0))),goal:text(row.goal||row.title),status:text(row.status)||((row.completedAt||row.complete)?'completed':'planned'),date:validDate(row.date)?row.date:today,createdAt:text(row.createdAt)||now()}));
 education.requirements=education.requirements.map((row,index)=>({...row,id:text(row.id)||makeId('requirement'),programId:text(row.programId)||programId,title:titleOf(row)||`Requirement ${index+1}`,requirementType:REQUIREMENT_TYPES.includes(normalizeToken(row.requirementType||row.type))?normalizeToken(row.requirementType||row.type):'course',creditsRequired:Math.max(0,number(row.creditsRequired||row.credits)),status:['remaining','in-progress','satisfied','waived'].includes(normalizeToken(row.status))?normalizeToken(row.status):'remaining',order:Number.isFinite(Number(row.order))?Number(row.order):index}));
 education.terms=education.terms.map(row=>({...row,id:text(row.id)||makeId('term'),programId:text(row.programId)||programId,title:titleOf(row)||'Academic term',startDate:text(row.startDate),endDate:text(row.endDate),status:text(row.status)||'planned'}));
 education.importantDates=education.importantDates.map(row=>({...row,id:text(row.id)||makeId('academic-date'),programId:text(row.programId)||programId,title:titleOf(row)||'Academic date',date:text(row.date),kind:text(row.kind)||'other'}));
 education.transferEvaluations=education.transferEvaluations.map(row=>({...row,id:text(row.id)||makeId('evaluation'),programId:text(row.programId)||programId,evaluationDate:validDate(row.evaluationDate||row.date)?text(row.evaluationDate||row.date):today,status:text(row.status)||'valid',sourceLabel:text(row.sourceLabel||row.title)||'Official evaluation'}));
 education.transferResults=education.transferResults.map(row=>({...row,id:text(row.id)||makeId('transfer-result'),decision:normalizeToken(row.decision||row.status)||'pending',creditsAccepted:Math.max(0,number(row.creditsAccepted||row.credits))}));
 state.education=education;state.life={...obj(state.life),tasks:list(state?.life?.tasks),reminders:list(state?.life?.reminders),routines:list(state?.life?.routines),routineInstances:list(state?.life?.routineInstances)};state.v4={...obj(state.v4),archive:list(state?.v4?.archive)};
 for(const item of education.items.filter(row=>!row.courseId&&row.status!=='completed')){const linked=applyDailyAction(state,{type:'ensure-linked',kind:'task',externalId:`study-nook:legacy-item:${item.id}`,title:item.title,date:item.dueDate||today,priority:item.hardDeadline?'high':'today',energy:'medium',duration:item.minutes||15,deadlineType:item.hardDeadline?'hard':'soft',sourceId:item.id,sourceType:'study-legacy-action'},today);if(linked.ok)state=linked.state}
 state.education.meta={...education.meta,schemaVersion:ACADEMIC_SCHEMA_VERSION,selectedProgramId:education.programs.some(row=>row.id===education.meta.selectedProgramId)?education.meta.selectedProgramId:active.id,migration:{...obj(education.meta.migration),version:1,initializedAt:education.meta.migration?.initializedAt||now(),legacyCourses:education.courses.filter(row=>row.migrationKey?.startsWith('legacy.courses:')).length,legacyItems:education.items.filter(row=>row.migrationKey?.startsWith('legacy.schoolTasks:')).length}};
 return{state,education:state.education,changed:JSON.stringify(original)!==JSON.stringify(state.education),today};
}

function academic(source){return initializeStudyNook(source).education}
export const getAcademicPrograms=source=>academic(source).programs.slice().sort((a,b)=>(programRank[a.status]??9)-(programRank[b.status]??9));
export const getCompletedPrograms=source=>getAcademicPrograms(source).filter(row=>row.status==='completed'&&row.officiallyConferred===true);
export const getActiveCourses=(source,programId)=>academic(source).courses.filter(row=>row.programId===programId&&['next-up','in-progress','waiting'].includes(row.status)).sort((a,b)=>a.queueOrder-b.queueOrder);
export const getStudySessions=(source,{programId,from='0000-01-01',to='9999-12-31'}={})=>academic(source).sessions.filter(row=>(!programId||row.programId===programId)&&row.date>=from&&row.date<=to).sort((a,b)=>`${a.date}${a.createdAt}`.localeCompare(`${b.date}${b.createdAt}`));
export const getLatestTransferEvaluation=(source,programId)=>academic(source).transferEvaluations.filter(row=>row.programId===programId&&row.status!=='superseded'&&row.status!=='invalid').sort((a,b)=>`${b.evaluationDate}${b.createdAt||''}`.localeCompare(`${a.evaluationDate}${a.createdAt||''}`))[0]||null;
function degreeProvider(education,program){return byId(education.providers,program?.institutionId)}
function isInstitutionCourse(education,program,course){const provider=byId(education.providers,course.providerId),institution=degreeProvider(education,program);return!!(provider&&institution&&provider.id===institution.id)}
function latestTransferResults(source,programId){const education=academic(source),evaluation=getLatestTransferEvaluation(source,programId);return evaluation?education.transferResults.filter(row=>row.evaluationId===evaluation.id):[]}

export function getDegreeProgress(source,programId){
 const education=academic(source),program=byId(education.programs,programId);if(!program)return null;const requirements=education.requirements.filter(row=>row.programId===programId),courses=education.courses.filter(row=>row.programId===programId),results=latestTransferResults(source,programId),accepted=results.filter(row=>['accepted','partially-accepted'].includes(row.decision)&&number(row.creditsAccepted)>0),acceptedByRequirement=new Map(accepted.map(row=>[String(row.requirementId),row]));
 const transferSources=new Map();for(const result of accepted){const key=text(result.sourceCourseId)||result.id;transferSources.set(key,Math.max(transferSources.get(key)||0,number(result.creditsAccepted)))}
 const institutionCourses=new Map();for(const course of courses.filter(row=>row.status==='completed'&&isInstitutionCourse(education,program,row)))institutionCourses.set(course.id,number(course.credits));
 const transferredCredits=[...transferSources.values()].reduce((sum,value)=>sum+value,0),institutionCredits=[...institutionCourses.values()].reduce((sum,value)=>sum+value,0),totalCredits=number(program.totalCreditsRequired)||requirements.reduce((sum,row)=>sum+number(row.creditsRequired),0),officialSatisfiedCredits=Math.min(totalCredits||Infinity,transferredCredits+institutionCredits),satisfied=requirements.filter(requirement=>requirement.status==='satisfied'||requirement.status==='waived'||acceptedByRequirement.has(String(requirement.id))||courses.some(course=>course.status==='completed'&&isInstitutionCourse(education,program,course)&&course.requirementIds.includes(String(requirement.id)))),inProgress=requirements.filter(requirement=>requirement.status==='in-progress'||courses.some(course=>['in-progress','waiting'].includes(course.status)&&course.requirementIds.includes(String(requirement.id))&&!satisfied.includes(requirement)));
 return{program,totalCredits,officialSatisfiedCredits:Number.isFinite(officialSatisfiedCredits)?officialSatisfiedCredits:0,transferCredits:transferredCredits,institutionCredits,remainingCredits:Math.max(0,totalCredits-(Number.isFinite(officialSatisfiedCredits)?officialSatisfiedCredits:0)),percent:totalCredits?Math.min(100,Math.round(officialSatisfiedCredits/totalCredits*100)):0,completedRequirements:satisfied.length,inProgressRequirements:inProgress.length,remainingRequirements:Math.max(0,requirements.length-satisfied.length),totalRequirements:requirements.length};
}
export function getDegreeProgressByLevel(source,level){const program=getAcademicPrograms(source).filter(row=>row.level===level&&row.status!=='archived').sort((a,b)=>(programRank[a.status]??9)-(programRank[b.status]??9))[0];return program?getDegreeProgress(source,program.id):null}
export function getTransferSummary(source,programId){const education=academic(source),courses=education.courses.filter(row=>row.programId===programId),results=latestTransferResults(source,programId);return{planning:courses.filter(row=>['planning','taking-now'].includes(row.transferStatus)).length,completedExternally:courses.filter(row=>['completed-externally','transcript-not-sent','transcript-sent','pending-evaluation'].includes(row.transferStatus)).length,acceptedCredits:results.filter(row=>['accepted','partially-accepted'].includes(row.decision)).reduce((sum,row)=>sum+number(row.creditsAccepted),0),rejected:results.filter(row=>row.decision==='rejected').length,pending:results.filter(row=>row.decision==='pending').length,evaluation:getLatestTransferEvaluation(source,programId)} }
export function getCurrentFocusCourse(source,programId){const education=academic(source),courses=education.courses.filter(row=>row.programId===programId&&!['completed','dropped','archived'].includes(row.status)),items=education.items.filter(row=>row.programId===programId&&row.status!=='completed');return courses.find(row=>row.pinned)||courses.filter(course=>items.some(item=>item.courseId===course.id&&item.hardDeadline&&item.dueDate)).sort((a,b)=>String(items.find(item=>item.courseId===a.id&&item.hardDeadline)?.dueDate||'9999').localeCompare(String(items.find(item=>item.courseId===b.id&&item.hardDeadline)?.dueDate||'9999')))[0]||courses.filter(row=>row.status==='in-progress').sort((a,b)=>b.progressPercent-a.progressPercent)[0]||courses.filter(row=>row.progressPercent>0).sort((a,b)=>b.progressPercent-a.progressPercent)[0]||courses.sort((a,b)=>a.queueOrder-b.queueOrder)[0]||null}
export function getRecommendedAcademicNextStep(source,programId,today=new Date().toISOString().slice(0,10)){const education=academic(source),focus=getCurrentFocusCourse(source,programId),open=education.items.filter(row=>row.programId===programId&&row.status!=='completed'),hard=open.filter(row=>row.hardDeadline&&row.dueDate).sort((a,b)=>a.dueDate.localeCompare(b.dueDate))[0],current=open.filter(row=>row.courseId===focus?.id).sort((a,b)=>`${a.dueDate||'9999'}:${a.order}`.localeCompare(`${b.dueDate||'9999'}:${b.order}`))[0],transfer=education.courses.filter(row=>row.programId===programId&&['transcript-not-sent','transcript-sent','pending-evaluation','appeal-pending'].includes(row.transferStatus)).sort((a,b)=>a.queueOrder-b.queueOrder)[0],item=hard||current;if(item)return{kind:'assignment',id:item.id,title:item.title,courseId:item.courseId,date:item.dueDate,reason:hard?'Hard academic deadline':'Next item in Current Focus'};if(transfer)return{kind:'course',id:transfer.id,title:transfer.transferStatus==='transcript-not-sent'?`Send transcript for ${transfer.title}`:`Check transfer status for ${transfer.title}`,courseId:transfer.id,date:transfer.targetDate,reason:'Transfer step'};if(focus)return{kind:'course',id:focus.id,title:focus.title,courseId:focus.id,date:focus.targetDate,reason:focus.progressPercent>=75?'Nearly finished course':'Current academic focus'};return null}
export function getUpcomingAcademicDeadlines(source,{programId,from=new Date().toISOString().slice(0,10),to='9999-12-31'}={}){const education=academic(source),assignments=education.items.filter(row=>(!programId||row.programId===programId)&&row.status!=='completed'&&row.dueDate>=from&&row.dueDate<=to).map(row=>({...row,sourceType:'assignment'})),dates=education.importantDates.filter(row=>(!programId||row.programId===programId)&&row.date>=from&&row.date<=to).map(row=>({...row,dueDate:row.date,sourceType:'important-date'}));return[...assignments,...dates].sort((a,b)=>`${a.dueDate}${a.dueTime||''}`.localeCompare(`${b.dueDate}${b.dueTime||''}`))}

export function selectStudyNook(source={},today=new Date().toISOString().slice(0,10)){
 const initialized=initializeStudyNook(source,today),education=initialized.education,programs=getAcademicPrograms(initialized.state),selectedProgram=byId(programs,education.meta.selectedProgramId)||programs[0],programId=selectedProgram?.id||'',courses=education.courses.filter(row=>row.programId===programId),requirements=education.requirements.filter(row=>row.programId===programId).sort((a,b)=>a.order-b.order),assignments=education.items.filter(row=>row.programId===programId).sort((a,b)=>`${a.dueDate||'9999'}:${a.order}`.localeCompare(`${b.dueDate||'9999'}:${b.order}`)),terms=education.terms.filter(row=>row.programId===programId),sessions=education.sessions.filter(row=>row.programId===programId).sort((a,b)=>String(b.date).localeCompare(String(a.date))),importantDates=education.importantDates.filter(row=>row.programId===programId),evaluations=education.transferEvaluations.filter(row=>row.programId===programId).sort((a,b)=>String(b.evaluationDate).localeCompare(String(a.evaluationDate))),focus=getCurrentFocusCourse(initialized.state,programId),nextStep=getRecommendedAcademicNextStep(initialized.state,programId,today),progress=getDegreeProgress(initialized.state,programId),transfer=getTransferSummary(initialized.state,programId),deadlines=getUpcomingAcademicDeadlines(initialized.state,{programId,from:today}),completedPrograms=getCompletedPrograms(initialized.state);
 return{...initialized,programs,selectedProgram,programId,courses,requirements,assignments,terms,sessions,importantDates,evaluations,focus,nextStep,progress,transfer,deadlines,completedPrograms};
}

function fail(error){return{ok:false,error}}
function cleanDate(value){return validDate(value)?text(value):''}
function programFor(education,id){return byId(education.programs,id)||education.programs[0]}
function saveProvider(education,name,type){return ensureProvider(education,name,type)?.id||''}
function reorderCourses(education,programId){education.courses.filter(row=>row.programId===programId&&!['completed','archived'].includes(row.status)).sort((a,b)=>a.queueOrder-b.queueOrder).forEach((row,index)=>row.queueOrder=index)}

export function applyStudyAction(source={},action={},today=new Date().toISOString().slice(0,10)){
 const initialized=initializeStudyNook(source,today),state=initialized.state,education=state.education,type=text(action.type),stamp=now(),program=programFor(education,text(action.programId)||education.meta.selectedProgramId),programId=program?.id||'';
 if(type==='initialize')return{ok:true,state,result:education};
 if(type==='select-program'){if(!byId(education.programs,action.id))return fail('That academic program is no longer available.');education.meta.selectedProgramId=action.id;return{ok:true,state,result:byId(education.programs,action.id)}}
 if(type==='program-save'){const title=text(action.title),level=PROGRAM_LEVELS.includes(normalizeToken(action.level))?normalizeToken(action.level):'other';if(!title)return fail('Name the academic program first.');const old=byId(education.programs,action.id),id=old?.id||makeId('program'),institutionId=saveProvider(education,action.institution||byId(education.providers,old?.institutionId)?.name,'degree-institution'),status=old?.officiallyConferred?'completed':(['active','preparing','future','planned'].includes(normalizeToken(action.status))?normalizeToken(action.status):(old?.status||'future')),item={...old,id,title,shortTitle:text(action.shortTitle)||title,level,programType:text(action.programType)||'degree',institutionId,status,totalCreditsRequired:Math.max(0,number(action.totalCreditsRequired)),officiallyConferred:old?.officiallyConferred===true,completionDate:text(old?.completionDate),notes:text(action.notes),createdAt:old?.createdAt||stamp,updatedAt:stamp};education.programs=replaceById(education.programs,id,item);if(!old)education.meta.selectedProgramId=id;return{ok:true,state,result:item}}
 if(type==='program-confer'){const item=byId(education.programs,action.id);if(!item)return fail('That academic program is no longer available.');if(action.confirmed!==true)return fail('Confirm that the degree or program was officially conferred first.');const next={...item,status:'completed',officiallyConferred:true,completionDate:cleanDate(action.completionDate)||today,updatedAt:stamp};education.programs=replaceById(education.programs,item.id,next);const nextActive=education.programs.find(row=>row.status==='active'&&row.id!==item.id)||education.programs.find(row=>row.id!==item.id&&row.status!=='archived');education.meta.selectedProgramId=nextActive?.id||item.id;return{ok:true,state,result:next}}
 if(type==='program-archive'){const item=byId(education.programs,action.id);if(!item)return fail('That academic program is no longer available.');if(item.officiallyConferred)return fail('Completed programs stay on the Academic Shelf.');education.programs=education.programs.filter(row=>row.id!==item.id);const archived=archiveRecord(state,'education.programs',item);education.meta.selectedProgramId=education.programs[0]?.id||'';return{ok:true,state,result:archived}}
 if(type==='requirement-save'){const title=text(action.title);if(!programId||!title)return fail('Choose a program and name the requirement.');const old=byId(education.requirements,action.id),id=old?.id||makeId('requirement'),item={...old,id,programId,title,requirementType:REQUIREMENT_TYPES.includes(normalizeToken(action.requirementType))?normalizeToken(action.requirementType):'course',creditsRequired:Math.max(0,number(action.creditsRequired)),status:['remaining','in-progress','satisfied','waived'].includes(normalizeToken(action.status))?normalizeToken(action.status):'remaining',order:Number.isFinite(Number(action.order))?Number(action.order):(old?.order??education.requirements.filter(row=>row.programId===programId).length),notes:text(action.notes),createdAt:old?.createdAt||stamp,updatedAt:stamp};education.requirements=replaceById(education.requirements,id,item);return{ok:true,state,result:item}}
 if(type==='course-save'){const title=text(action.title);if(!programId||!title)return fail('Choose a program and name the course.');const old=byId(education.courses,action.id),id=old?.id||makeId('course'),institution=degreeProvider(education,program),providerId=saveProvider(education,action.provider||byId(education.providers,old?.providerId)?.name||institution?.name,(text(action.provider)||institution?.name).toLowerCase()===text(institution?.name).toLowerCase()?'degree-institution':'course-provider'),item={...old,id,programId,providerId,termId:text(action.termId),title,courseCode:text(action.courseCode),credits:Math.max(0,number(action.credits)),status:COURSE_STATUSES.includes(normalizeToken(action.status))?normalizeToken(action.status):'planned',progressPercent:clamp(action.progressPercent),queueOrder:Number.isFinite(Number(old?.queueOrder))?old.queueOrder:education.courses.filter(row=>row.programId===programId).length,pinned:old?.pinned===true,completionDate:cleanDate(action.completionDate),targetDate:cleanDate(action.targetDate),requirementIds:unique(csv(action.requirementIds)),transferStatus:TRANSFER_STATUSES.includes(normalizeToken(action.transferStatus))?normalizeToken(action.transferStatus):'not-applicable',touchstones:Math.max(0,number(action.touchstones)),milestones:Math.max(0,number(action.milestones)),notes:text(action.notes),createdAt:old?.createdAt||stamp,updatedAt:stamp};education.courses=replaceById(education.courses,id,item);reorderCourses(education,programId);return{ok:true,state,result:item}}
 if(type==='course-focus'){const item=byId(education.courses,action.id);if(!item)return fail('That course is no longer available.');education.courses=education.courses.map(row=>row.programId===item.programId?{...row,pinned:row.id===item.id,updatedAt:stamp}:row);return{ok:true,state,result:{...item,pinned:true}}}
 if(type==='course-move'){const item=byId(education.courses,action.id),direction=action.direction==='down'?1:-1;if(!item)return fail('That course is no longer available.');const queue=education.courses.filter(row=>row.programId===item.programId&&!['completed','archived'].includes(row.status)).sort((a,b)=>a.queueOrder-b.queueOrder),index=queue.findIndex(row=>row.id===item.id),swap=queue[index+direction];if(!swap)return{ok:true,state,result:item,reused:true};const currentOrder=item.queueOrder;item.queueOrder=swap.queueOrder;swap.queueOrder=currentOrder;reorderCourses(education,item.programId);return{ok:true,state,result:item}}
 if(type==='assignment-save'){const title=text(action.title),course=byId(education.courses,action.courseId);if(!programId||!title)return fail('Name the academic item first.');const old=byId(education.items,action.id),id=old?.id||makeId('assignment'),status=ASSIGNMENT_STATUSES.includes(normalizeToken(action.status))?normalizeToken(action.status):'not-started',item={...old,id,programId:course?.programId||programId,courseId:course?.id||'',title,type:normalizeToken(action.assignmentType)||'assignment',status,progressPercent:status==='completed'?100:clamp(action.progressPercent),dueDate:cleanDate(action.dueDate),dueTime:text(action.dueTime),hardDeadline:bool(action.hardDeadline),order:Number.isFinite(Number(action.order))?Number(action.order):(old?.order??education.items.filter(row=>row.courseId===course?.id).length),score:text(action.score),notes:text(action.notes),completedAt:status==='completed'?(old?.completedAt||stamp):'',createdAt:old?.createdAt||stamp,updatedAt:stamp};education.items=replaceById(education.items,id,item);return{ok:true,state,result:item}}
 if(type==='evaluation-save'){if(!programId)return fail('Choose an academic program first.');const old=byId(education.transferEvaluations,action.id),id=old?.id||makeId('evaluation'),item={...old,id,programId,evaluationDate:cleanDate(action.evaluationDate)||today,status:['valid','superseded','invalid'].includes(normalizeToken(action.status))?normalizeToken(action.status):'valid',sourceLabel:text(action.sourceLabel)||'Official transfer evaluation',totalCreditsAccepted:Math.max(0,number(action.totalCreditsAccepted)),notes:text(action.notes),createdAt:old?.createdAt||stamp,updatedAt:stamp};education.transferEvaluations=replaceById(education.transferEvaluations,id,item);return{ok:true,state,result:item}}
 if(type==='transfer-result-save'){const evaluation=byId(education.transferEvaluations,action.evaluationId),requirement=byId(education.requirements,action.requirementId);if(!evaluation||!requirement)return fail('Choose an evaluation and degree requirement.');const old=byId(education.transferResults,action.id),id=old?.id||makeId('transfer-result'),decision=['pending','accepted','partially-accepted','rejected','appeal-pending'].includes(normalizeToken(action.decision))?normalizeToken(action.decision):'pending',item={...old,id,evaluationId:evaluation.id,requirementId:requirement.id,sourceCourseId:text(action.sourceCourseId),decision,creditsAccepted:['accepted','partially-accepted'].includes(decision)?Math.max(0,number(action.creditsAccepted)):0,notes:text(action.notes),createdAt:old?.createdAt||stamp,updatedAt:stamp};education.transferResults=replaceById(education.transferResults,id,item);return{ok:true,state,result:item}}
 if(type==='session-save'){if(!programId)return fail('Choose an academic program first.');const old=byId(education.sessions,action.id),id=old?.id||makeId('study-session'),item={...old,id,programId,courseId:text(action.courseId),date:cleanDate(action.date)||today,targetMinutes:Math.max(0,number(action.targetMinutes)),actualMinutes:Math.max(0,number(action.actualMinutes)),goal:text(action.goal),status:['planned','in-progress','completed','skipped'].includes(normalizeToken(action.status))?normalizeToken(action.status):'planned',notes:text(action.notes),createdAt:old?.createdAt||stamp,updatedAt:stamp};education.sessions=replaceById(education.sessions,id,item);return{ok:true,state,result:item}}
 if(type==='term-save'){if(!programId)return fail('Choose an academic program first.');const title=text(action.title);if(!title)return fail('Name the academic term first.');const old=byId(education.terms,action.id),id=old?.id||makeId('term'),item={...old,id,programId,title,startDate:cleanDate(action.startDate),endDate:cleanDate(action.endDate),status:text(action.status)||'planned',targetUnits:Math.max(0,number(action.targetUnits)),notes:text(action.notes),createdAt:old?.createdAt||stamp,updatedAt:stamp};education.terms=replaceById(education.terms,id,item);return{ok:true,state,result:item}}
 if(type==='date-save'){if(!programId)return fail('Choose an academic program first.');const title=text(action.title),date=cleanDate(action.date);if(!title||!date)return fail('Name the academic date and choose a date.');const old=byId(education.importantDates,action.id),id=old?.id||makeId('academic-date'),item={...old,id,programId,title,date,kind:text(action.kind)||'other',hardDeadline:bool(action.hardDeadline),notes:text(action.notes),createdAt:old?.createdAt||stamp,updatedAt:stamp};education.importantDates=replaceById(education.importantDates,id,item);return{ok:true,state,result:item}}
 if(type==='archive'){const paths={requirement:'requirements',course:'courses',assignment:'items',session:'sessions',term:'terms',date:'importantDates'},key=paths[action.kind],item=key&&byId(education[key],action.id);if(!item)return fail('That academic record is no longer available.');education[key]=education[key].filter(row=>row.id!==item.id);return{ok:true,state,result:archiveRecord(state,`education.${key}`,item)}}
 if(type==='link-daily'){let item,title,date,deadlineType='soft',duration=30,sourceType;if(action.kind==='assignment'){item=byId(education.items,action.id);title=item?.title;date=item?.dueDate;deadlineType=item?.hardDeadline?'hard':'soft';sourceType='study-assignment'}else if(action.kind==='session'){item=byId(education.sessions,action.id);title=item?.goal||`Study ${titleOf(byId(education.courses,item?.courseId))||'course'}`;date=item?.date;duration=item?.targetMinutes||30;sourceType='study-session'}else if(action.kind==='date'){item=byId(education.importantDates,action.id);title=item?.title;date=item?.date;deadlineType=item?.hardDeadline?'hard':'soft';sourceType='academic-date'}else{item=byId(education.courses,action.id);title=action.title||`Study ${item?.title||'course'}`;date=item?.targetDate||today;sourceType='study-course'}if(!item)return fail('That academic record is no longer available.');const linked=applyDailyAction(state,{type:'ensure-linked',kind:'task',externalId:`study-nook:${action.kind}:${item.id}`,title,date:cleanDate(date)||today,priority:deadlineType==='hard'?'high':'today',energy:'medium',duration,deadlineType,sourceId:item.id,sourceType},today);return linked.ok?{...linked,studyResult:item}:linked}
 return fail('That Study Nook action is not available.');
}
