import{snapshotV4,selectV5MoneyGig}from'./data.js?v=7.3.0-money-mission';
import{buildWeeklyMirror}from'./money-mission-core.js?v=7.3.0-money-mission';

const app=document.querySelector('#app'),KEY='sm_v5_weekly_mirror',list=value=>Array.isArray(value)?value:[],text=value=>String(value??'').trim(),esc=value=>text(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char])),money=value=>Number(value||0).toLocaleString([],{style:'currency',currency:'USD'});
function saved(){try{return list(JSON.parse(localStorage.getItem(KEY)||'[]'))}catch{return[]}}
function rows(state,path){return path.split('.').reduce((value,key)=>value?.[key],state)||[]}
function summary(){const snapshot=snapshotV4(),view=selectV5MoneyGig(snapshot.today),state=snapshot.state||{},routineSources=[...list(rows(state,'life.routineInstances')),...list(rows(state,'life.routines'))];return{snapshot,value:buildWeeklyMirror({today:snapshot.today,transactions:view.transactions,orders:view.gig?.orders,shifts:rows(state,'work.gigShifts'),tasks:rows(state,'life.tasks'),routines:routineSources,medicationLogs:rows(state,'health.medicationLogs'),studySessions:rows(state,'education.sessions')})}}
function label(date){return new Date(`${date}T12:00:00`).toLocaleDateString([],{month:'short',day:'numeric'})}
function cardMarkup(value){const old=saved().find(row=>row.from===value.range.from),done=Boolean(old);return`<section class="card full weekly-mirror-card ${value.range.isSunday?'sunday':''}" data-weekly-mirror><div class="card-head"><div><div class="ey">🪞 WEEKLY MIRROR</div><h2>${done?'Your last week is tucked in safely':'Look back, then choose one thing'}</h2><p>${label(value.range.from)}–${label(value.range.to)} · numbers first, judgment never.</p></div><button type="button" class="btn ${done?'soft':'primary'}" data-weekly-mirror-open>${done?'Open review':'Review my week'}</button></div><div class="weekly-mirror-strip"><span><small>GIG NET</small><b>${money(value.net)}</b></span><span><small>ACTUAL HOURS</small><b>${value.actualHours}h</b></span><span><small>TASKS DONE</small><b>${value.tasksDone}</b></span><span><small>MEDS LOGGED</small><b>${value.medsTaken}</b></span></div>${done?`<p class="weekly-mirror-next"><b>One thing for this week:</b> ${esc(old.nextStep||'Keep it realistic.')}</p>`:''}</section>`}
function modalMarkup(value){const old=saved().find(row=>row.from===value.range.from)||{};return`<div class="modal-backdrop weekly-mirror-modal" data-weekly-mirror-modal><section class="modal-sheet" role="dialog" aria-modal="true" aria-labelledby="weekly-mirror-title"><button type="button" class="modal-x" data-weekly-mirror-close aria-label="Close">×</button><div class="ey">🪞 WEEKLY MIRROR</div><h2 id="weekly-mirror-title">${label(value.range.from)}–${label(value.range.to)}</h2><p>A factual check-in. You are allowed to learn from a week without grading yourself.</p><div class="weekly-mirror-metrics"><div><small>Gig gross</small><b>${money(value.gross)}</b></div><div><small>Gig costs</small><b>−${money(value.gigCosts)}</b></div><div><small>Gig net</small><b>${money(value.net)}</b></div><div><small>Planned / actual</small><b>${value.plannedHours}h / ${value.actualHours}h</b></div><div><small>Tasks done</small><b>${value.tasksDone}</b></div><div><small>Study</small><b>${value.studyMinutes} min</b></div></div><form data-weekly-mirror-form><label><span>What worked?</span><textarea name="win" rows="2" placeholder="One win counts.">${esc(old.win)}</textarea></label><label><span>What got in the way?</span><select name="friction"><option value="">Choose if useful</option>${['Too much planned','Low energy','Time disappeared','Money pressure','Health or meds','Plans changed','Something else'].map(option=>`<option${old.friction===option?' selected':''}>${option}</option>`).join('')}</select></label><label><span>One realistic thing for this week</span><input name="nextStep" value="${esc(old.nextStep)}" placeholder="Example: plan one Flex block" required></label><div class="weekly-mirror-actions"><button class="btn primary">Save weekly mirror</button><button type="button" class="btn soft" data-route-view="money" data-route-lane="gig">Open Money Mission</button></div></form></section></div>`}
function decorate(){const hero=[...app.querySelectorAll('.hero')].find(node=>/HOME · V5/i.test(node.querySelector('.ey')?.textContent||''));if(hero&&!app.querySelector('[data-weekly-mirror]')){const {value}=summary();hero.insertAdjacentHTML('afterend',cardMarkup(value))}const memory=[...app.querySelectorAll('.hero')].find(node=>/MEMORY BOX · V5/i.test(node.querySelector('.ey')?.textContent||''));if(memory&&!app.querySelector('[data-weekly-mirror-history]')){const history=saved().slice().reverse();memory.insertAdjacentHTML('afterend',`<section class="card full weekly-mirror-history" data-weekly-mirror-history><div class="card-head"><div><div class="ey">🪞 WEEKLY MIRRORS</div><h2>Past check-ins</h2></div></div>${history.length?history.map(row=>`<div class="weekly-mirror-history-row"><b>${esc(label(row.from))}–${esc(label(row.to))}</b><span>${esc(row.nextStep||row.win||'Review saved')}</span></div>`).join(''):'<p>No weekly mirrors saved yet.</p>'}</section>`}}
app.addEventListener('click',event=>{if(event.target.closest('[data-weekly-mirror-open]')){const {value}=summary();app.insertAdjacentHTML('beforeend',modalMarkup(value));app.querySelector('[data-weekly-mirror-modal] textarea,input,select')?.focus()}if(event.target.closest('[data-weekly-mirror-close]')||event.target.matches('[data-weekly-mirror-modal]'))event.target.closest('[data-weekly-mirror-modal]')?.remove()});
app.addEventListener('submit',event=>{const form=event.target.closest('[data-weekly-mirror-form]');if(!form)return;event.preventDefault();const {value}=summary(),record={from:value.range.from,to:value.range.to,savedAt:new Date().toISOString(),win:text(form.elements.win.value),friction:text(form.elements.friction.value),nextStep:text(form.elements.nextStep.value),summary:value},history=saved().filter(row=>row.from!==record.from);localStorage.setItem(KEY,JSON.stringify([...history,record].slice(-52)));app.querySelector('[data-weekly-mirror-modal]')?.remove();app.querySelector('[data-weekly-mirror]')?.remove();decorate()});
window.addEventListener('katos:rendered',()=>queueMicrotask(decorate));
