export const GROWTH_VERSION=1;
const list=v=>Array.isArray(v)?v:[];const object=v=>v&&typeof v==='object'&&!Array.isArray(v)?v:{};const text=v=>String(v??'').trim();const makeId=p=>`${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;
export function normalizeMilestone(v,i=0){v=object(v);return{id:text(v.id)||`milestone-${i}`,label:text(v.label||v.title)||`Milestone ${i+1}`,done:v.done===true,completedAt:text(v.completedAt)}}
export function normalizeGoal(v,i=0){v=object(v);return{id:text(v.id)||`goal-${i}`,title:text(v.title)||'Goal',kind:['dream','outcome','practice'].includes(v.kind)?v.kind:'outcome',status:['moving','paused','complete'].includes(v.status)?v.status:'moving',why:text(v.why),targetDate:text(v.targetDate),milestones:list(v.milestones).map(normalizeMilestone),createdAt:text(v.createdAt)||new Date().toISOString(),completedAt:text(v.completedAt)}}
export function normalizeExperimentAttempt(v,i=0){v=object(v);return{id:text(v.id)||`attempt-${i}`,date:text(v.date)||new Date().toISOString().slice(0,10),result:['worked','mixed','did-not-work','skipped'].includes(v.result)?v.result:'mixed',note:text(v.note),createdAt:text(v.createdAt)||new Date().toISOString()}}
export function normalizeExperiment(v,i=0){v=object(v);return{id:text(v.id)||`experiment-${i}`,title:text(v.title)||'Experiment',hypothesis:text(v.hypothesis),behavior:text(v.behavior),status:['active','paused','complete'].includes(v.status)?v.status:'active',attempts:list(v.attempts).map(normalizeExperimentAttempt),createdAt:text(v.createdAt)||new Date().toISOString()}}
export function normalizeWin(v,i=0){v=object(v);return{id:text(v.id)||`win-${i}`,title:text(v.title)||'Win',date:text(v.date)||new Date().toISOString().slice(0,10),note:text(v.note),source:text(v.source)||'manual',sourceEventId:text(v.sourceEventId),createdAt:text(v.createdAt)||new Date().toISOString()}}
export const DEFAULT_GROWTH={goals:[],wins:[],experiments:[]};
export function normalizeGrowth(value){const v=object(value);return{goals:list(v.goals).map(normalizeGoal),wins:list(v.wins).map(normalizeWin),experiments:list(v.experiments).map(normalizeExperiment)}}
export function addGoal(growth,input={}){const g=normalizeGrowth(growth),item=normalizeGoal({...input,id:makeId('goal')});return{...g,goals:[...g.goals,item]}}
export function updateGoal(growth,id,patch={}){const g=normalizeGrowth(growth);return{...g,goals:g.goals.map(x=>x.id===String(id)?normalizeGoal({...x,...patch,id:x.id,createdAt:x.createdAt}):x)}}
export function toggleMilestone(growth,goalId,milestoneId){const g=normalizeGrowth(growth),goal=g.goals.find(x=>x.id===String(goalId));if(!goal)return g;const milestones=goal.milestones.map(m=>m.id===String(milestoneId)?{...m,done:!m.done,completedAt:!m.done?new Date().toISOString():''}:m),all=milestones.length&&milestones.every(m=>m.done);return updateGoal(g,goalId,{milestones,status:all?'complete':goal.status==='complete'?'moving':goal.status,completedAt:all?new Date().toISOString():''})}
export function addWin(growth,input={}){const g=normalizeGrowth(growth),item=normalizeWin({...input,id:makeId('win')});return{...g,wins:[...g.wins,item]}}
export function addExperiment(growth,input={}){const g=normalizeGrowth(growth),item=normalizeExperiment({...input,id:makeId('experiment')});return{...g,experiments:[...g.experiments,item]}}
export function addExperimentAttempt(growth,id,input={}){const g=normalizeGrowth(growth),exp=g.experiments.find(x=>x.id===String(id));if(!exp)return g;const attempt=normalizeExperimentAttempt({...input,id:makeId('attempt')});return{...g,experiments:g.experiments.map(x=>x.id===String(id)?{...x,attempts:[...x.attempts,attempt]}:x)}}
export function goalProgress(goal){const g=normalizeGoal(goal),total=g.milestones.length,done=g.milestones.filter(m=>m.done).length;return{done,total,percent:total?Math.round(done/total*100):(g.status==='complete'?100:0)}}
export function experimentSummary(exp){const e=normalizeExperiment(exp),count=e.attempts.length,worked=e.attempts.filter(a=>a.result==='worked').length,mixed=e.attempts.filter(a=>a.result==='mixed').length;return{count,worked,mixed,workedPercent:count?Math.round(worked/count*100):0}}
export function derivedWins(state={}){const log=list(state?.insights?.activityLog),seen=new Set(),wins=[];const labels={'routine.completed':'Finished a routine','study.item.completed':'Finished a study item','study.session.completed':'Finished a study session','goal.completed':'Completed a goal'};for(const event of log){const title=labels[event.type];if(!title||seen.has(event.id))continue;seen.add(event.id);wins.push(normalizeWin({id:`derived-${event.id}`,title:event.detail?.title||title,date:String(event.timestamp||'').slice(0,10),note:event.detail?.note||'',source:'activity',sourceEventId:event.id,createdAt:event.timestamp}))}return wins}
