import{normalizeV3State,V3_BUILD,V3_SCHEMA_VERSION}from'./schema.js';
export const MIGRATION_VERSION=1;
export const LEGACY_KEYS=['sm_v16','sm_v16_backup'];
export const LEGACY_CAPSULE_KEY='sm_v3_legacy_capsule';
export const MIGRATION_RECEIPT_KEY='sm_v3_migration_receipt';
const list=v=>Array.isArray(v)?v:[];
const obj=v=>v&&typeof v==='object'&&!Array.isArray(v)?v:{};
const text=v=>String(v??'').trim();
const num=v=>Number(v)||0;
const asList=v=>Array.isArray(v)?v:(v&&typeof v==='object'?Object.entries(v).map(([name,item])=>({name,...(item&&typeof item==='object'?item:{amount:item})})):[]);
const safeId=(kind,id,index)=>`legacy-${kind}-${String(id??index).replace(/[^a-z0-9_-]/gi,'-')}`;
const iso=v=>text(v)||new Date().toISOString();
const nearestMinutes=v=>{const n=Math.max(0,Number(v)||15),choices=[5,15,30,60];return choices.reduce((a,b)=>Math.abs(b-n)<Math.abs(a-n)?b:a,15)};
const effort=v=>{const s=text(v).toLowerCase();return s==='low'?'low':s==='high'?'high':'medium'};
const mergeUnique=(current,incoming)=>{const seen=new Set(list(current).map(x=>String(x?.id||'')));return[...list(current),...list(incoming).filter(x=>!seen.has(String(x?.id||'')))];};
function parseRaw(raw){if(!raw)return null;try{const p=JSON.parse(raw),data=p?.data||p;return data&&typeof data==='object'?data:null}catch{return null}}
export function readLegacySnapshot(storage=localStorage){const candidates=LEGACY_KEYS.map(key=>{let raw='';try{raw=storage.getItem(key)||''}catch{}const data=parseRaw(raw);return{key,raw,data,stamp:Date.parse(data?.__smUpdatedAt||'')||0}}).filter(x=>x.data);candidates.sort((a,b)=>b.stamp-a.stamp||(a.key==='sm_v16'?-1:1));return candidates[0]||null}
export function legacySummary(v2={}){const d=obj(v2),money=obj(d.money),noms=obj(d.noms);return{tasks:list(d.tasks).length,reminders:list(d.reminders).length,events:list(d.events).length,routines:list(d.routines).length+list(d.guidedRoutines).length,goals:list(d.goals).length+list(d.schoolGoals).length,wins:list(d.wins).length,courses:list(d.courses).length,schoolItems:list(d.schoolTasks).length,projects:list(d.projects).length+list(d.parkedProjects).length,workItems:list(d.workItems).length,money:asList(money.bills).length+asList(money.subscriptions).length+asList(money.income).length+asList(money.debts).length+asList(money.savings).length,noms:list(noms.foods).length+list(noms.recipes).length+list(noms.emergencyNoms).length,lab:list(d.labObservations).length+list(d.labFindings).length+list(d.labExperiments).length,archive:list(d.archive).length};}
export function scanLegacy(v2={}){const summary=legacySummary(v2),review=[];const d=obj(v2),noms=obj(d.noms);if(Object.keys(obj(d.days)).length)review.push('Daily mood/energy/notes will be preserved as V3 activity history instead of recreating the V2 day journal.');if(list(d.guidedRoutines).length)review.push('Task-based V2 guided routines will become standalone V3 routine steps. They will no longer depend on Sweet To-Dos.');if(list(noms.pantry).length)review.push('V2 pantry records are preserved in the legacy capsule; V3 uses saved Noms + availability instead of a second pantry database.');if(list(noms.groceries).length)review.push('V2 grocery-list records are preserved in the legacy capsule for review.');if(list(noms.mealPlan).length)review.push('V2 meal-plan records are preserved in the legacy capsule for review.');if(obj(d.financeWorkflow)&&Object.keys(d.financeWorkflow).length)review.push('V2 Finance Friday workflow state is preserved in the capsule; Money Café replaces the old workflow UI.');return{summary,review,total:Object.values(summary).reduce((a,b)=>a+b,0)}}
function mapTasks(v2){return list(v2.tasks).map((x,i)=>({id:safeId('task',x.id,i),text:text(x.text||x.title)||'Migrated task',done:x.done===true,date:text(x.date),protected:x.isProtected===true||x.hardBoundary===true,energy:effort(x.effort),initiation:Number(x.timesDeferred)>1?'sticky':'easy',mode:'any',minutes:nearestMinutes(x.durationMin||x.minutes),createdAt:iso(x.createdAt),completedAt:text(x.completedAt),source:'v2-migration',legacySourceId:text(x.id)}))}
function mapReminders(v2){return list(v2.reminders).map((x,i)=>({id:safeId('ping',x.id,i),title:text(x.title||x.name)||'Migrated reminder',date:text(x.date),time:text(x.time),timing:x.timing==='before_bed'?'before_bed':'specific',completed:x.completed===true,repeat:text(x.repeat),createdAt:iso(x.createdAt),completedAt:text(x.completedAt),source:'v2-migration'}))}
function mapEvents(v2){return list(v2.events).map((x,i)=>({id:safeId('event',x.id,i),title:text(x.title||x.name)||'Migrated event',type:'event',date:text(x.date),startTime:text(x.start||x.startTime||x.time),endTime:text(x.end||x.endTime),allDay:!text(x.start||x.startTime||x.time),protected:x.protected===true,location:text(x.location),notes:text(x.notes||x.note),createdAt:iso(x.createdAt)}))}
function routineParts(v2){const templates=[],instances=[],taskById=new Map(list(v2.tasks).map(x=>[String(x.id),x]));list(v2.routines).forEach((r,ri)=>{const rid=safeId('routine',r.id,ri),steps=list(r.steps).map((s,si)=>({id:`${rid}-step-${si}`,label:text(s?.label||s?.text||s)||`Step ${si+1}`,minutes:5,optional:s?.optional===true}));templates.push({id:rid,name:text(r.name||r.title)||'Migrated routine',icon:'🎀',daypart:'any',targetTime:text(r.targetTime),recurrence:'daily',days:[],steps,archived:r.archived===true,createdAt:iso(r.createdAt)});Object.entries(obj(r.checks)).forEach(([date,checks])=>{const states=Object.fromEntries(steps.map((s,si)=>[s.id,!!obj(checks)[si]])),done=steps.length>0&&steps.every((_,si)=>!!obj(checks)[si]);instances.push({id:`${rid}-instance-${date}`,routineId:rid,date,status:done?'completed':'active',stepStates:states,completedAt:done?`${date}T23:59:00.000Z`:'',updatedAt:new Date().toISOString()})})});list(v2.guidedRoutines).forEach((r,ri)=>{const rid=safeId('guided-routine',r.id,ri),labels=list(r.taskIds).map(id=>taskById.get(String(id))).filter(Boolean).map(x=>text(x.text||x.title)).filter(Boolean);if(!labels.length)return;templates.push({id:rid,name:text(r.name)||'Migrated guided routine',icon:'🌷',daypart:'any',recurrence:'manual',days:[],steps:labels.map((label,si)=>({id:`${rid}-step-${si}`,label,minutes:5,optional:false})),archived:false,createdAt:new Date().toISOString()})});return{templates,instances}}
function mapGrowth(v2){const goals=[...list(v2.goals),...list(v2.schoolGoals)].map((x,i)=>({id:safeId('goal',x.id,i),title:text(x.title||x.name||x.text)||'Migrated goal',kind:'outcome',status:x.done===true||String(x.status).toLowerCase()==='complete'?'complete':String(x.status).toLowerCase()==='paused'?'paused':'moving',why:text(x.why||x.note),targetDate:text(x.targetDate||x.dueDate||x.date),milestones:list(x.milestones||x.steps).map((m,mi)=>({id:`${safeId('goal',x.id,i)}-milestone-${mi}`,label:text(m?.label||m?.title||m?.text||m)||`Milestone ${mi+1}`,done:m?.done===true,completedAt:text(m?.completedAt)})),createdAt:iso(x.createdAt),completedAt:text(x.completedAt)}));const wins=list(v2.wins).map((x,i)=>({id:safeId('win',x.id,i),title:text(x.title||x.text||x.name)||'Migrated win',date:text(x.date)||String(x.createdAt||'').slice(0,10),note:text(x.note||x.description),source:'v2-migration',createdAt:iso(x.createdAt)}));const experiments=[...list(v2.habits).map((x,i)=>({id:safeId('habit-experiment',x.id,i),title:text(x.title||x.name)||'Migrated habit experiment',hypothesis:'Migrated from a V2 habit so KatOS can treat it as an experiment instead of a streak obligation.',behavior:text(x.behavior||x.title||x.name),status:x.paused?'paused':'active',attempts:[],createdAt:iso(x.createdAt)})),...list(v2.labExperiments).map((x,i)=>({id:safeId('lab-experiment',x.id,i),title:text(x.title||x.name)||'Migrated experiment',hypothesis:text(x.hypothesis||x.question),behavior:text(x.behavior||x.plan||x.description),status:String(x.status).toLowerCase()==='completed'?'complete':String(x.status).toLowerCase()==='planned'?'paused':'active',attempts:[],createdAt:iso(x.createdAt)}))];return{goals,wins,experiments}}
function mapEducation(v2){const courses=list(v2.courses).map((x,i)=>({id:safeId('course',x.id,i),programId:'legacy-program',title:text(x.title||x.name)||'Migrated course',code:text(x.code),status:x.done===true?'complete':'active',progress:Math.max(0,Math.min(100,Number(x.progress||x.percent)||0)),createdAt:iso(x.createdAt)}));const programs=courses.length?[{id:'legacy-program',name:'Migrated Education',status:'active',targetDate:'',createdAt:new Date().toISOString()}]:[];const items=list(v2.schoolTasks).map((x,i)=>({id:safeId('study-item',x.id,i),courseId:text(x.courseId)?safeId('course',x.courseId,0):courses[0]?.id||'',title:text(x.title||x.text)||'Migrated study item',type:String(x.type||'assignment').toLowerCase().includes('exam')?'exam':'assignment',dueDate:text(x.dueDate||x.date),dueTime:text(x.dueTime||x.time),minutes:nearestMinutes(x.minutes||x.durationMin),energy:effort(x.effort),initiation:Number(x.timesDeferred)>1?'sticky':'easy',difficulty:'medium',protected:x.isProtected===true,done:x.done===true,notes:text(x.notes||x.note),createdAt:iso(x.createdAt),completedAt:text(x.completedAt)}));return{programs,courses,items,sessions:[]}}
function mapThreads(v2){return[...list(v2.projects).map((x,i)=>({...x,__parked:false,__i:i})),...list(v2.parkedProjects).map((x,i)=>({...x,__parked:true,__i:i}))].map(x=>({id:safeId('thread',x.id,x.__i),title:text(x.title||x.name)||'Migrated Thread',icon:'🧵',summary:text(x.summary||x.description||x.currentObjective),status:x.__parked?'paused':String(x.status).toLowerCase()==='complete'?'complete':'active',deadline:text(x.deadline||x.dueDate),notes:text(x.notes||x.note)?[{id:`${safeId('thread',x.id,x.__i)}-note`,text:text(x.notes||x.note),createdAt:iso(x.updatedAt||x.createdAt)}]:[],resources:[],links:{taskIds:[],reminderIds:[],eventIds:[],courseIds:[],workItemIds:[],routineIds:[],goalIds:[]},createdAt:iso(x.createdAt),updatedAt:iso(x.updatedAt||x.createdAt)}))}
function mapWork(v2){const items=list(v2.workItems).map((x,i)=>({id:safeId('work-item',x.id,i),text:text(x.text||x.title)||'Migrated work item',area:String(x.type).toLowerCase().includes('admin')?'admin':'work',dueDate:text(x.dueDate||x.date),minutes:nearestMinutes(x.minutes||x.durationMin),done:x.done===true,protected:x.isProtected===true,createdAt:iso(x.createdAt)}));return{items,schedule:{...obj(v2.workSchedule),migratedFromV2:true},shifts:[],training:[],career:[],focus:{active:false,itemId:'',label:'',minutes:0,startedAt:'',endsAt:''}}}
function mapMoney(v2){const m=obj(v2.money),accounts=[],bills=[],earnings=[],debts=[],savingsGoals=[];const onHand=m.onHand?.amount??m.cash?.amount??m.cash;if(onHand!==undefined&&onHand!==null)accounts.push({id:'legacy-money-on-hand',name:'Migrated money on hand',type:'checking',balance:num(onHand),createdAt:new Date().toISOString()});[...asList(m.bills),...asList(m.subscriptions)].forEach((x,i)=>bills.push({id:safeId('bill',x.id,i),name:text(x.name)||'Migrated bill',amount:Math.max(0,num(x.typicalAmount??x.amount)),dueDate:/^\d{4}-\d{2}-\d{2}$/.test(text(x.due))?text(x.due):'',recurring:String(x.repeat||'Monthly')!=='One-time',paid:x.paid===true,createdAt:iso(x.createdAt)}));asList(m.income).forEach((x,i)=>earnings.push({id:safeId('earning',x.id,i),kind:'paycheck',label:text(x.name)||'Migrated income',employer:text(x.employer),estimatedGross:Math.max(0,num(x.amount)),expectedDate:/^\d{4}-\d{2}-\d{2}$/.test(text(x.date))?text(x.date):'',status:'expected',note:`Migrated V2 income schedule${x.repeat?` · ${x.repeat}`:''}`,createdAt:iso(x.createdAt)}));asList(m.debts).forEach((x,i)=>debts.push({id:safeId('debt',x.id,i),name:text(x.name)||'Migrated debt',balance:Math.max(0,num(x.balance??x.amount)),apr:Math.max(0,num(x.apr)),minimum:Math.max(0,num(x.minimum)),dueDate:text(x.dueDate||x.due),createdAt:iso(x.createdAt)}));asList(m.savings).forEach((x,i)=>savingsGoals.push({id:safeId('savings',x.id,i),name:text(x.name)||'Migrated savings',current:Math.max(0,num(x.current??x.amount)),target:Math.max(0,num(x.target)),createdAt:iso(x.createdAt)}));return{earnings,accounts,bills,spending:[],savingsGoals,debts}}
function mapNoms(v2){const n=obj(v2.noms),foods=[...list(n.foods).map((x,i)=>({id:safeId('food',x.id,i),name:text(x.name||x.title)||'Migrated food',kind:text(x.kind)||'other',tags:Array.isArray(x.tags)?x.tags:[],effort:'low',prepMinutes:Number(x.prepMinutes)||0,available:x.available!==false,favorite:x.favorite===true,notes:text(x.notes||x.note),createdAt:iso(x.createdAt)})),...list(n.emergencyNoms).map((x,i)=>({id:safeId('emergency-food',x.id,i),name:text(x.name||x.title||x)||'Emergency Nom',kind:'other',tags:['emergency','safe'],effort:'zero',prepMinutes:0,available:true,favorite:false,notes:'Migrated from V2 Emergency Noms',createdAt:new Date().toISOString()}))];const recipes=list(n.recipes).map((x,i)=>({id:safeId('recipe',x.id,i),name:text(x.name||x.title)||'Migrated recipe',kind:text(x.kind)||'meal',tags:Array.isArray(x.tags)?x.tags:[],effort:'medium',prepMinutes:Number(x.prepMinutes)||15,ingredients:list(x.ingredients).map(text).filter(Boolean),notes:text(x.notes||x.note),available:x.available!==false,favorite:x.favorite===true,createdAt:iso(x.createdAt)}));return{foods,recipes,history:[],currentNom:null}}
function legacyActivity(v2){const out=[];Object.entries(obj(v2.days)).forEach(([date,day],i)=>{const d=obj(day);if(text(d.notes))out.push({id:`legacy-day-note-${date}`,type:'legacy.day-note',targetId:date,timestamp:`${date}T12:00:00.000Z`,context:{},detail:{title:`Day note · ${date}`,note:text(d.notes),mood:text(d.mood),energy:text(d.energy)},source:'v2-migration'});if(text(d.movement))out.push({id:`legacy-movement-note-${date}`,type:'legacy.movement-note',targetId:date,timestamp:`${date}T12:00:00.000Z`,context:{},detail:{title:`Movement note · ${date}`,note:text(d.movement)},source:'v2-migration'})});list(v2.archive).forEach((x,i)=>out.push({id:safeId('archive',x.id,i),type:'legacy.archive',targetId:text(x.id),timestamp:iso(x.completedAt||x.updatedAt||x.createdAt),context:{},detail:{title:text(x.title||x.text||x.name)||'Legacy archive record',note:text(x.note||x.description)},source:'v2-migration'}));return out}
export function buildMigration(v2,currentV3){const before=normalizeV3State(currentV3),next=structuredClone(before),routines=routineParts(v2),growth=mapGrowth(v2),ed=mapEducation(v2),work=mapWork(v2),money=mapMoney(v2),noms=mapNoms(v2);next.life.tasks=mergeUnique(next.life.tasks,mapTasks(v2));next.life.reminders=mergeUnique(next.life.reminders,mapReminders(v2));next.life.events=mergeUnique(next.life.events,mapEvents(v2));next.life.routines=mergeUnique(next.life.routines,routines.templates);next.life.routineInstances=mergeUnique(next.life.routineInstances,routines.instances);next.life.threads=mergeUnique(next.life.threads,mapThreads(v2));next.growth={goals:mergeUnique(next.growth.goals,growth.goals),wins:mergeUnique(next.growth.wins,growth.wins),experiments:mergeUnique(next.growth.experiments,growth.experiments)};next.education={...next.education,programs:mergeUnique(next.education.programs,ed.programs),courses:mergeUnique(next.education.courses,ed.courses),items:mergeUnique(next.education.items,ed.items)};next.work={...next.work,items:mergeUnique(next.work.items,work.items),schedule:Object.keys(next.work.schedule||{}).length?next.work.schedule:work.schedule};next.money={...next.money,earnings:mergeUnique(next.money.earnings,money.earnings),accounts:mergeUnique(next.money.accounts,money.accounts),bills:mergeUnique(next.money.bills,money.bills),savingsGoals:mergeUnique(next.money.savingsGoals,money.savingsGoals),debts:mergeUnique(next.money.debts,money.debts)};next.nourish={...next.nourish,noms:{...next.nourish.noms,foods:mergeUnique(next.nourish.noms.foods,noms.foods),recipes:mergeUnique(next.nourish.noms.recipes,noms.recipes)}};const obs=[...list(v2.labObservations),...list(v2.labFindings),...list(v2.labArchivedObservations),...list(v2.brainNotes)].map((x,i)=>typeof x==='string'?{id:`legacy-observation-${i}`,text:x,source:'v2-migration'}:{...x,id:x.id||`legacy-observation-${i}`,source:'v2-migration'});next.insights={...next.insights,observations:mergeUnique(next.insights.observations,obs),activityLog:mergeUnique(next.insights.activityLog,legacyActivity(v2))};const normalized=normalizeV3State(next),scan=scanLegacy(v2),after=legacySummary(v2);return{state:normalized,report:{migrationVersion:MIGRATION_VERSION,build:V3_BUILD,schemaVersion:V3_SCHEMA_VERSION,createdAt:new Date().toISOString(),sourceSummary:scan.summary,review:scan.review,accountedFor:after,totalSourceRecords:scan.total,notes:['Existing V3 records are preserved.','Imported IDs are deterministic, so repeating the migration does not duplicate the same legacy records.','The original V2 snapshot is stored separately as a rollback/review capsule.']}}}
export function saveLegacyCapsule(source,storage=localStorage){if(!source?.raw)return false;storage.setItem(LEGACY_CAPSULE_KEY,JSON.stringify({savedAt:new Date().toISOString(),sourceKey:source.key,raw:source.raw}));return true}
export function saveMigrationReceipt(report,storage=localStorage){storage.setItem(MIGRATION_RECEIPT_KEY,JSON.stringify(report));return report}
export function loadMigrationReceipt(storage=localStorage){try{return JSON.parse(storage.getItem(MIGRATION_RECEIPT_KEY)||'null')}catch{return null}}
