import{DEFAULT_CONSTITUTION,normalizeConstitution}from'./constitution.js';
import{DEFAULT_KAT_MODEL,DEFAULT_PATTERNS,normalizeKatModel,normalizePatterns}from'./kat-model.js';
import{DEFAULT_CONTEXT,normalizeContext}from'./context.js';
import{normalizeTasks}from'./tasks.js';
import{normalizeReminders}from'./reminders.js';
import{normalizeSips}from'./sips.js';
import{normalizeMovement}from'./motion.js';
import{normalizeNoms}from'./noms.js?v=3.0.0-alpha.16-stockguard';
import{normalizeWork}from'./work.js';
import{normalizeMoney}from'./money.js';
import{normalizeRoutines,normalizeRoutineInstances}from'./routines.js';
import{normalizeTimeEvents}from'./time.js';
import{normalizeEducation}from'./study.js';
import{normalizeThreads}from'./threads.js';
import{normalizeGrowth}from'./growth.js';
import{normalizeActivityLog}from'./activity.js';
import{normalizeResetSessions}from'./soft-reset.js';
import{normalizeDayReviews}from'./day-review.js?v=1';

export const V3_SCHEMA_VERSION=8;
export const V3_STORAGE_KEY='sm_v3_beta';
export const V3_BUILD='3.0.0-alpha.16.5';
const clone=v=>structuredClone(v),object=v=>v&&typeof v==='object'&&!Array.isArray(v)?v:{},list=v=>Array.isArray(v)?v:[];
export const DEFAULT_V3_STATE={schemaVersion:V3_SCHEMA_VERSION,profile:{constitution:clone(DEFAULT_CONSTITUTION),katModel:clone(DEFAULT_KAT_MODEL),preferences:{},patterns:clone(DEFAULT_PATTERNS)},context:clone(DEFAULT_CONTEXT),life:{inbox:[],tasks:[],reminders:[],routines:normalizeRoutines([]),routineInstances:normalizeRoutineInstances([]),events:normalizeTimeEvents([]),threads:normalizeThreads([])},nourish:{noms:normalizeNoms({foods:[],recipes:[],history:[]}),sips:normalizeSips({fridge:[],history:[]})},movement:normalizeMovement({sessions:[],routines:[],videos:[],weighIns:[]}),education:normalizeEducation({}),work:normalizeWork({items:[],schedule:{}}),money:normalizeMoney({}),growth:normalizeGrowth({}),insights:{activityLog:normalizeActivityLog([]),observations:[],experiments:[],resetSessions:normalizeResetSessions([]),legacyNotes:[],dayReviews:normalizeDayReviews([])},mochini:{conversation:[],pendingProposal:null,lastProposal:null,lastContextInference:null},meta:{build:V3_BUILD,createdAt:'',updatedAt:'',legacyMigration:{}}};
export function createInitialV3State(){const now=new Date().toISOString(),s=clone(DEFAULT_V3_STATE);s.meta.createdAt=now;s.meta.updatedAt=now;s.context.updatedAt=now;return s}
export function normalizeV3State(value){const saved=object(value),profile=object(saved.profile),life=object(saved.life),nourish=object(saved.nourish),insights=object(saved.insights),mochini=object(saved.mochini),meta=object(saved.meta),fallback=createInitialV3State(),growthSource=Object.keys(object(saved.growth)).length?saved.growth:{experiments:list(insights.experiments)};return{schemaVersion:V3_SCHEMA_VERSION,profile:{constitution:normalizeConstitution(profile.constitution),katModel:normalizeKatModel(profile.katModel),preferences:object(profile.preferences),patterns:normalizePatterns(profile.patterns)},context:normalizeContext(saved.context),life:{inbox:list(life.inbox),tasks:normalizeTasks(life.tasks),reminders:normalizeReminders(life.reminders),routines:normalizeRoutines(life.routines),routineInstances:normalizeRoutineInstances(life.routineInstances),events:normalizeTimeEvents(life.events),threads:normalizeThreads(life.threads)},nourish:{noms:normalizeNoms(nourish.noms),sips:normalizeSips(nourish.sips)},movement:normalizeMovement(saved.movement),education:normalizeEducation(saved.education),work:normalizeWork(saved.work),money:normalizeMoney(saved.money),growth:normalizeGrowth(growthSource),insights:{activityLog:normalizeActivityLog(insights.activityLog),observations:list(insights.observations),experiments:list(insights.experiments),resetSessions:normalizeResetSessions(insights.resetSessions),legacyNotes:list(insights.legacyNotes),dayReviews:normalizeDayReviews(insights.dayReviews)},mochini:{conversation:list(mochini.conversation).slice(-80),pendingProposal:mochini.pendingProposal&&typeof mochini.pendingProposal==='object'?mochini.pendingProposal:null,lastProposal:mochini.lastProposal&&typeof mochini.lastProposal==='object'?mochini.lastProposal:null,lastContextInference:mochini.lastContextInference&&typeof mochini.lastContextInference==='object'?mochini.lastContextInference:null},meta:{build:V3_BUILD,createdAt:String(meta.createdAt||fallback.meta.createdAt),updatedAt:String(meta.updatedAt||fallback.meta.updatedAt),legacyMigration:object(meta.legacyMigration)}}}
function rawStoredState(storage){try{const raw=storage.getItem(V3_STORAGE_KEY);if(!raw)return{};const parsed=JSON.parse(raw);return object(parsed?.data||parsed)}catch{return{}}}
function preserveNewerState(incoming,storage){const current=rawStoredState(storage),currentAt=Date.parse(current?.meta?.updatedAt||'')||0,incomingAt=Date.parse(incoming?.meta?.updatedAt||'')||0;if(!currentAt||incomingAt>=currentAt)return incoming;const currentNoms=object(current?.nourish?.noms),currentFoods=list(currentNoms.foods),byId=new Map(currentFoods.map(item=>[String(item?.id||''),item])),next=clone(incoming),nourish=object(next.nourish),noms=object(nourish.noms);noms.foods=list(noms.foods).map(item=>{const newer=byId.get(String(item?.id||''));if(!newer)return item;return{...item,trackQuantity:newer.trackQuantity===true,quantity:newer.quantity,lowAt:newer.lowAt,available:newer.available}});const history=list(noms.history),historyIds=new Set(history.map(item=>String(item?.id||'')));for(const entry of list(currentNoms.history)){const entryAt=Date.parse(entry?.loggedAt||entry?.createdAt||'')||0,id=String(entry?.id||'');if(id&&entryAt>=incomingAt&&!historyIds.has(id)){history.push(entry);historyIds.add(id)}}noms.history=history;const currentNom=currentNoms.currentNom,currentNomAt=Date.parse(currentNom?.loggedAt||currentNom?.createdAt||'')||0;if(currentNom&&currentNomAt>=incomingAt)noms.currentNom=currentNom;next.nourish={...nourish,noms};const nextInsights=object(next.insights),reviews=new Map(normalizeDayReviews(nextInsights.dayReviews).map(item=>[item.date,item]));for(const review of normalizeDayReviews(current?.insights?.dayReviews)){const reviewAt=Date.parse(review.updatedAt||review.createdAt||'')||0,existing=reviews.get(review.date),existingAt=Date.parse(existing?.updatedAt||existing?.createdAt||'')||0;if(reviewAt>=Math.max(incomingAt,existingAt))reviews.set(review.date,review)}next.insights={...nextInsights,dayReviews:[...reviews.values()]};return next}
export function loadV3State(storage=localStorage){try{const raw=storage.getItem(V3_STORAGE_KEY);if(!raw)return createInitialV3State();const parsed=JSON.parse(raw);return normalizeV3State(parsed?.data||parsed)}catch{return createInitialV3State()}}
export function saveV3State(state,storage=localStorage){const guarded=preserveNewerState(object(state),storage),next=normalizeV3State({...guarded,meta:{...guarded?.meta,updatedAt:new Date().toISOString()}});storage.setItem(V3_STORAGE_KEY,JSON.stringify({data:next}));return next}
export function resetV3State(storage=localStorage){const next=createInitialV3State();storage.setItem(V3_STORAGE_KEY,JSON.stringify({data:next}));return next}
