export const STUDY_VERSION=2;
const list=v=>Array.isArray(v)?v:[];const object=v=>v&&typeof v==='object'&&!Array.isArray(v)?v:{};const text=v=>String(v??'').trim();const num=v=>Math.max(0,Number(v)||0);const makeId=p=>`${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;const pad=v=>String(v).padStart(2,'0');export const localDateKey=(value=new Date())=>{const d=value instanceof Date?value:new Date(value);return`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`};
export const STUDY_ITEM_TYPES=['assignment','exam','reading','video','study','other'];
export const COURSE_FEELINGS=[
 {value:'rough',icon:'😭',label:'Rough'},
 {value:'confused',icon:'😵‍💫',label:'Confused'},
 {value:'meh',icon:'😐',label:'Meh'},
 {value:'okay',icon:'🙂',label:'Okay'},
 {value:'good',icon:'😎',label:'Good'}
];
export function normalizeProgram(v,i=0){v=object(v);return{id:text(v.id)||`program-${i}`,name:text(v.name)||'Program',status:['active','paused','complete'].includes(v.status)?v.status:'active',targetDate:text(v.targetDate),createdAt:text(v.createdAt)||new Date().toISOString()}}
export function normalizeCourse(v,i=0){v=object(v);return{id:text(v.id)||`course-${i}`,programId:text(v.programId),title:text(v.title||v.name)||'Course',code:text(v.code),status:['active','paused','complete'].includes(v.status)?v.status:'active',progress:Math.max(0,Math.min(100,Number(v.progress)||0)),createdAt:text(v.createdAt)||new Date().toISOString()}}
export function normalizeStudyItem(v,i=0){v=object(v);return{id:text(v.id)||`study-item-${i}`,courseId:text(v.courseId),title:text(v.title)||'Study item',type:STUDY_ITEM_TYPES.includes(v.type)?v.type:'assignment',dueDate:text(v.dueDate),dueTime:text(v.dueTime),minutes:num(v.minutes)||15,energy:['low','medium','high'].includes(v.energy)?v.energy:'medium',initiation:['easy','sticky'].includes(v.initiation)?v.initiation:'easy',difficulty:['easy','medium','hard'].includes(v.difficulty)?v.difficulty:'medium',protected:v.protected===true,done:v.done===true,notes:text(v.notes),createdAt:text(v.createdAt)||new Date().toISOString(),completedAt:text(v.completedAt)}}
export function normalizeStudySession(v,i=0){v=object(v);return{id:text(v.id)||`study-session-${i}`,courseId:text(v.courseId),itemId:text(v.itemId),date:text(v.date)||localDateKey(),minutes:num(v.minutes),note:text(v.note),completedAt:text(v.completedAt)||new Date().toISOString(),context:object(v.context)}}
export function normalizeStudyFocus(v){v=object(v);return{active:v.active===true,courseId:text(v.courseId),itemId:text(v.itemId),label:text(v.label),minutes:num(v.minutes),startedAt:text(v.startedAt),endsAt:text(v.endsAt)}}
export function normalizeCourseReview(v,i=0){v=object(v);return{id:text(v.id)||`course-review-${i}`,courseId:text(v.courseId),date:text(v.date)||localDateKey(),feeling:COURSE_FEELINGS.some(x=>x.value===v.feeling)?v.feeling:'okay',confidence:Math.max(1,Math.min(5,Number(v.confidence)||3)),goingWell:text(v.goingWell),hardParts:text(v.hardParts),needsWork:text(v.needsWork),focusNext:text(v.focusNext),support:text(v.support),note:text(v.note),createdAt:text(v.createdAt)||new Date().toISOString(),updatedAt:text(v.updatedAt)||new Date().toISOString()}}
export const DEFAULT_EDUCATION={programs:[],courses:[],items:[],sessions:[],reviews:[],focus:normalizeStudyFocus({})};
export function normalizeEducation(value){const v=object(value);return{programs:list(v.programs).map(normalizeProgram),courses:list(v.courses).map(normalizeCourse),items:list(v.items||v.tasks).map(normalizeStudyItem),sessions:list(v.sessions).map(normalizeStudySession),reviews:list(v.reviews).map(normalizeCourseReview),focus:normalizeStudyFocus(v.focus)}}
export function addProgram(ed,input={}){const e=normalizeEducation(ed),item=normalizeProgram({...input,id:makeId('program')});return{...e,programs:[...e.programs,item]}}
export function addCourse(ed,input={}){const e=normalizeEducation(ed),item=normalizeCourse({...input,id:makeId('course')});return{...e,courses:[...e.courses,item]}}
export function updateCourse(ed,id,patch={}){const e=normalizeEducation(ed);return{...e,courses:e.courses.map(x=>x.id===String(id)?normalizeCourse({...x,...patch,id:x.id,createdAt:x.createdAt}):x)}}
export function addStudyItem(ed,input={}){const e=normalizeEducation(ed),item=normalizeStudyItem({...input,id:makeId('study-item')});return{...e,items:[...e.items,item]}}
export function toggleStudyItem(ed,id){const e=normalizeEducation(ed);return{...e,items:e.items.map(x=>x.id===String(id)?{...x,done:!x.done,completedAt:!x.done?new Date().toISOString():''}:x)}}
export function deleteStudyItem(ed,id){const e=normalizeEducation(ed);return{...e,items:e.items.filter(x=>x.id!==String(id))}}
export function courseProgress(ed,courseId){const e=normalizeEducation(ed),course=e.courses.find(x=>x.id===String(courseId)),items=e.items.filter(x=>x.courseId===String(courseId));if(items.length)return Math.round(items.filter(x=>x.done).length/items.length*100);return course?.progress||0}
export function saveCourseReview(ed,input={}){const e=normalizeEducation(ed),now=new Date().toISOString(),review=normalizeCourseReview({...input,id:input.id||makeId('course-review'),updatedAt:now,createdAt:input.createdAt||now});const existing=e.reviews.findIndex(x=>x.id===review.id);return{...e,reviews:existing>=0?e.reviews.map((x,i)=>i===existing?review:x):[...e.reviews,review]}}
export function deleteCourseReview(ed,id){const e=normalizeEducation(ed);return{...e,reviews:e.reviews.filter(x=>x.id!==String(id))}}
export function courseReviews(ed,courseId){const e=normalizeEducation(ed);return e.reviews.filter(x=>x.courseId===String(courseId)).sort((a,b)=>String(b.date||b.updatedAt).localeCompare(String(a.date||a.updatedAt)))}
export function latestCourseReview(ed,courseId){return courseReviews(ed,courseId)[0]||null}
export function startStudyFocus(ed,input={},nowValue=new Date()){const e=normalizeEducation(ed),now=nowValue instanceof Date?nowValue:new Date(nowValue),minutes=Math.max(5,Math.min(180,Number(input.minutes)||15)),ends=new Date(now.getTime()+minutes*60000);return{...e,focus:normalizeStudyFocus({active:true,courseId:input.courseId,itemId:input.itemId,label:input.label||'Study focus',minutes,startedAt:now.toISOString(),endsAt:ends.toISOString()})}}
export function finishStudyFocus(ed,note='',nowValue=new Date(),context={}){const e=normalizeEducation(ed),f=e.focus;if(!f.active)return{education:e,session:null};const now=nowValue instanceof Date?nowValue:new Date(nowValue),elapsed=f.startedAt?Math.max(1,Math.round((now-new Date(f.startedAt))/60000)):f.minutes,session=normalizeStudySession({id:makeId('study-session'),courseId:f.courseId,itemId:f.itemId,date:localDateKey(now),minutes:Math.min(f.minutes||elapsed,elapsed),note,completedAt:now.toISOString(),context});return{education:{...e,sessions:[...e.sessions,session],focus:normalizeStudyFocus({})},session}}
export function recommendStudy(ed,policy={},availableMinutes=120,today=localDateKey()){
 const e=normalizeEducation(ed),energy=policy?.context?.energy||'okay',ceiling=policy?.taskEnergyCeiling||'medium',rank={low:0,medium:1,high:2},limit=Math.max(5,Number(availableMinutes)||120);
 return e.items.filter(x=>!x.done&&x.minutes<=limit).map(item=>{let score=0;const reasons=[];if(item.protected){score+=60;reasons.push('protected')}if(item.dueDate&&item.dueDate<today){score+=50;reasons.push('overdue')}else if(item.dueDate===today){score+=40;reasons.push('due today')}else if(item.dueDate){const diff=(new Date(`${item.dueDate}T12:00:00`)-new Date(`${today}T12:00:00`))/86400000;if(diff<=3){score+=25;reasons.push('due soon')}}if(item.minutes<=15){score+=18;reasons.push('short fit')}if(item.initiation==='easy')score+=8;if(policy?.singleNext&&item.initiation==='easy')score+=12;if(energy==='drained'&&item.energy==='low')score+=22;if(energy==='energized'&&item.energy==='high')score+=16;if(rank[item.energy]>rank[ceiling])score-=35;return{item,score,reasons}}).sort((a,b)=>b.score-a.score||a.item.minutes-b.item.minutes).slice(0,Math.max(1,Math.min(3,Number(policy?.choiceCount)||3)));
}
