import{loadV3State}from'./app/schema.js?v=3.0.0-alpha.16.5-dayreview';
import{searchArchive,archiveSummary}from'./app/archive.js?v=3.0.0-alpha.16-dayreview';
let query='',kind='all';
const app=document.getElementById('app'),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const multi=v=>esc(v).replace(/\n/g,'<br>');
const label=v=>String(v||'').replaceAll('-',' ').replace(/^./,c=>c.toUpperCase());
function detailMarkup(x){const d=x.detail||{};if(x.kind==='day-review'){const bits=[d.mood&&`Mood: ${label(d.mood)}`,d.energy&&`Energy: ${label(d.energy)}`].filter(Boolean).join(' · '),rows=[['What happened',d.happened],['What helped',d.helped],['What was hard',d.hard],['Proud of',d.proud],['Tomorrow-Kat',d.tomorrow]].filter(([,v])=>String(v||'').trim());const s=d.snapshot||{},trail=[s.tasks&&`${Number(s.tasks.done)||0} tasks done`,s.routines&&`${Number(s.routines.completed)||0} routines finished`,s.movement&&`${Number(s.movement.minutes)||0}m movement`,s.nourish&&`${Number(s.nourish.noms)||0} Noms · ${Number(s.nourish.sips)||0} Sips`].filter(Boolean).join(' · ');return`<div class="note" style="margin-top:9px"><b>🌙 ${esc(bits||'Day reflection')}</b>${trail?`<small style="display:block;margin-top:4px">${esc(trail)}</small>`:''}${rows.map(([k,v])=>`<p style="margin:8px 0 0"><b>${esc(k)}:</b> ${multi(v)}</p>`).join('')}</div>`}if(x.kind==='legacy'&&d.content){return`<div class="note" style="margin-top:9px"><b>${d.area==='day-review'?'🌙 Migrated V2 Day Review':'📦 Migrated V2 memory'}</b><p style="margin:7px 0 0">${multi(d.content)}</p>${d.reason?`<small style="display:block;margin-top:6px">${esc(d.reason)}</small>`:''}</div>`}return''}
function render(){const state=loadV3State(),s=archiveSummary(state),entries=searchArchive(state,{query,kind}),preferred=['all','day-review','legacy','task','thread','goal','win','study','movement','reset','activity'],available=Object.keys(s.byKind),kinds=preferred.filter(x=>x==='all'||available.includes(x));for(const x of available)if(!kinds.includes(x))kinds.push(x);if(kind!=='all'&&!available.includes(kind))kind='all';app.innerHTML=`<main class="shell"><a class="back" href="../">← Back to KatOS V3</a><section class="hero"><div class="ey">📦 MEMORY BOX</div><h1>Past things can leave the desk without disappearing.</h1><p>Completed work, sessions, Day Reviews, and migrated history stay searchable here. The source modules still own the records.</p><div class="stats"><article class="stat"><small>SEARCHABLE</small><b>${s.total}</b></article><article class="stat"><small>KINDS</small><b>${Object.keys(s.byKind).length}</b></article></div></section><section class="card full"><div class="fields"><label class="field wide"><span>Search memory</span><input id="archiveSearch" value="${esc(query)}"></label><label class="field"><span>Kind</span><select id="archiveKind">${kinds.map(x=>`<option value="${esc(x)}" ${x===kind?'selected':''}>${esc(label(x))}</option>`).join('')}</select></label></div><div class="stack">${entries.slice(0,150).map(x=>`<article class="panel"><b>${esc(x.title)}</b><small>${esc(label(x.kind))} · ${esc(x.status)}${x.date?` · ${new Date(x.date).toLocaleString()}`:''}</small>${detailMarkup(x)}</article>`).join('')||'<div class="empty">📦 Nothing matches.</div>'}</div></section></main>`;document.getElementById('archiveSearch').oninput=e=>{query=e.target.value;render()};document.getElementById('archiveKind').onchange=e=>{kind=e.target.value;render()}}
render();
