import{loadV3State,saveV3State,V3_BUILD}from'./app/schema.js?v=3.0.0-alpha.12';
import{CONTEXT_OPTIONS,updateContext}from'./app/context.js?v=3.0.0-alpha.12';
import{normalizePatterns}from'./app/kat-model.js?v=3.0.0-alpha.12';
import{RESET_ACTIONS,startSoftReset,toggleResetAction,finishSoftReset,normalizeResetSessions,resetImproved}from'./app/soft-reset.js?v=3.0.0-alpha.12';
import{derivePatternCandidates,patternPreference}from'./app/patterns.js?v=3.0.0-alpha.12';
import{addActivityEvent}from'./app/activity.js?v=3.0.0-alpha.12';
let state=loadV3State();state={...state,insights:{...state.insights,resetSessions:normalizeResetSessions(state.insights?.resetSessions)}};let status='Reset Lab is ready.';const app=document.getElementById('app');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function activity(type,id,detail={}){state={...state,insights:{...state.insights,activityLog:addActivityEvent(state.insights?.activityLog,type,id,state.context,detail,'reset-lab')}}}
function persist(msg){state=saveV3State(state);status=`✓ ${msg} · ${V3_BUILD}`;window.__katOSV3=state;render()}
function activeReset(){return state.insights.resetSessions.slice().reverse().find(x=>!x.completedAt)||null}
function contextSelect(key,value){return`<label class="field"><span>${key}</span><select data-after="${key}">${CONTEXT_OPTIONS[key].map(x=>`<option value="${x.value}" ${x.value===value?'selected':''}>${x.icon} ${esc(x.label)}</option>`).join('')}</select></label>`}
function renderReset(){const active=activeReset(),history=state.insights.resetSessions.filter(x=>x.completedAt);if(!active)return`<section class="card"><div class="head"><div><div class="ey">🌸 SOFT RESET</div><h2>Change the state, not your worth</h2><p>KatOS picks a tiny reset menu from Current Context. Nothing becomes a task or obligation.</p></div><div class="count">${history.length}</div></div><div class="focus-box"><span class="big-icon">🌸</span><b>Need a reset?</b><p>We’ll offer up to three low-response-effort actions, then you can tell KatOS what actually changed.</p><button class="btn primary" id="startReset">Start Soft Reset</button></div><div class="stack">${history.slice(-4).reverse().map(s=>`<article class="panel"><b>${resetImproved(s)?'🌱 State shifted':'🌙 Reset completed'}</b><small>${new Date(s.completedAt).toLocaleString()} · ${s.completedActions.length} action${s.completedActions.length===1?'':'s'} tried</small></article>`).join('')}</div></section>`;const actions=active.suggestions.map(id=>RESET_ACTIONS[id]).filter(Boolean);return`<section class="card"><div class="head"><div><div class="ey">🌸 SOFT RESET · ACTIVE</div><h2>Just enough to change the weather</h2><p>Tap what you actually do. Partial reset still counts.</p></div><div class="count">${active.completedActions.length}/${actions.length}</div></div><div class="reset-actions">${actions.map(a=>`<button class="reset-action ${active.completedActions.includes(a.id)?'done':''}" data-reset-action="${a.id}"><span class="big-icon">${a.icon}</span>${esc(a.label)}<small>${a.minutes} min-ish</small></button>`).join('')}</div><div class="note"><b>After check:</b> nothing here assumes the reset “worked.” You report the result.</div><div class="fields">${contextSelect('brain',state.context.brain)}${contextSelect('energy',state.context.energy)}${contextSelect('capacity',state.context.capacity)}${contextSelect('pressure',state.context.pressure)}<label class="field wide"><span>Note · optional</span><input id="resetNote" placeholder="What changed, if anything?"></label></div><div class="actions"><button class="btn primary" id="finishReset">✓ Finish reset</button></div></section>`}
function upsertPattern(candidate,statusValue){const now=new Date().toISOString(),current=normalizePatterns(state.profile.patterns),found=current.find(x=>x.id===candidate.id),entry={id:candidate.id,label:candidate.label,description:candidate.description,confidence:candidate.confidence,evidenceCount:candidate.evidenceCount,status:statusValue,createdAt:found?.createdAt||now,updatedAt:now};state={...state,profile:{...state.profile,patterns:normalizePatterns([...current.filter(x=>x.id!==candidate.id),entry])}}}
function renderPatterns(){const candidates=derivePatternCandidates(state),stored=normalizePatterns(state.profile.patterns),prefs=Array.isArray(state.profile.preferences?.patternPreferences)?state.profile.preferences.patternPreferences:[];return`<section class="card"><div class="head"><div><div class="ey">🔬 PATTERN LAB</div><h2>Observations stay observations</h2><p>Patterns are transparent, evidence-counted, and separate from rules. KatOS never turns one into an obligation on its own.</p></div><div class="count">${candidates.length}</div></div><div class="stack">${candidates.length?candidates.map(c=>{const saved=stored.find(x=>x.id===c.id),pref=prefs.some(x=>x.id===c.id);return`<article class="pattern-card"><b>${esc(c.label)} ${pref?'<span class="chip">💗 preference</span>':saved?`<span class="chip">${esc(saved.status)}</span>`:''}</b><small>${esc(c.description)} · evidence ${c.evidenceCount} · confidence ${Math.round(c.confidence*100)}%</small><div class="confidence"><i style="width:${Math.round(c.confidence*100)}%"></i></div><div class="pattern-actions"><button class="btn tiny" data-pattern-observe="${esc(c.id)}">🔎 Keep observing</button><button class="btn tiny" data-pattern-dismiss="${esc(c.id)}">Not useful</button><button class="btn primary tiny" data-pattern-preference="${esc(c.id)}">💗 Make preference</button></div></article>`}).join(''):'<div class="empty">🔬 Not enough repeated evidence yet. Pattern Lab needs at least two matching observations before it says anything.</div>'}</div><div class="note"><b>Promotion law:</b> “Make preference” is an explicit Kat action. Even then, it becomes a preference, not a Constitution rule.</div></section>`}
function render(){app.innerHTML=`<main class="shell"><a class="back" href="./?v=3.0.0-alpha.12">← Back to KatOS V3</a><section class="hero"><div class="ey">🌸 KATOS V3 · ALPHA 11+12 MERGED · RESET LAB</div><h1>Recover, observe, learn. No silent rules.</h1><p>Soft Reset helps shift Current Context with tiny actions. Pattern Lab shows what KatOS has enough evidence to notice and leaves the interpretation in your hands.</p><div class="note">${esc(status)}</div></section><div class="grid">${renderReset()}${renderPatterns()}</div></main>`;bind()}
function bind(){document.getElementById('startReset')?.addEventListener('click',()=>{const session=startSoftReset(state);state={...state,insights:{...state.insights,resetSessions:[...state.insights.resetSessions,session]}};activity('soft-reset.started',session.id,{suggestions:session.suggestions});persist('Soft Reset started')});document.querySelectorAll('[data-reset-action]').forEach(b=>b.onclick=()=>{const active=activeReset();state={...state,insights:{...state.insights,resetSessions:state.insights.resetSessions.map(x=>x.id===active.id?toggleResetAction(x,b.dataset.resetAction):x)}};persist('Reset action updated')});document.getElementById('finishReset')?.addEventListener('click',()=>{const active=activeReset(),patch={};document.querySelectorAll('[data-after]').forEach(x=>patch[x.dataset.after]=x.value);const nextContext=updateContext(state.context,patch),finished=finishSoftReset(active,nextContext,document.getElementById('resetNote')?.value||'');state={...state,context:nextContext,insights:{...state.insights,resetSessions:state.insights.resetSessions.map(x=>x.id===active.id?finished:x)}};activity('soft-reset.completed',finished.id,{improved:resetImproved(finished),actions:finished.completedActions.length});persist('Soft Reset finished and Current Context updated')});const candidates=derivePatternCandidates(state);document.querySelectorAll('[data-pattern-observe]').forEach(b=>b.onclick=()=>{const c=candidates.find(x=>x.id===b.dataset.patternObserve);if(c)upsertPattern(c,'observed');persist('Pattern kept visible')});document.querySelectorAll('[data-pattern-dismiss]').forEach(b=>b.onclick=()=>{const c=candidates.find(x=>x.id===b.dataset.patternDismiss);if(c)upsertPattern(c,'dismissed');persist('Pattern marked not useful')});document.querySelectorAll('[data-pattern-preference]').forEach(b=>b.onclick=()=>{const c=candidates.find(x=>x.id===b.dataset.patternPreference);if(!c)return;upsertPattern(c,'observed');const current=Array.isArray(state.profile.preferences?.patternPreferences)?state.profile.preferences.patternPreferences:[],next=[...current.filter(x=>x.id!==c.id),patternPreference(c)];state={...state,profile:{...state.profile,preferences:{...state.profile.preferences,patternPreferences:next}}};activity('pattern.promoted',c.id,{label:c.label});persist('Pattern promoted to an explicit preference')})}
render();