import{loadV3State,saveV3State,V3_STORAGE_KEY,V3_BUILD}from'./app/schema.js?v=3.0.0-alpha.9';
import{normalizeMoney,addAccount,deleteAccount,addBill,toggleBillPaid,deleteBill,addSpending,deleteSpending,addSavingsGoal,deleteSavingsGoal,addDebt,deleteDebt,markEarningReceived,deleteEarning,earningAmount,gigNetBeforeTax,moneyCafeSnapshot,localDateKey}from'./app/money.js?v=3.0.0-alpha.9';

let state=loadV3State();state={...state,money:normalizeMoney(state.money)};
let statusText='Fresh pot. Money data is ready.';
const app=document.getElementById('app');
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const cash=value=>`${Number(value||0)<0?'−':''}$${Math.abs(Number(value||0)).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const dateLabel=value=>{if(!value)return'No date';const d=new Date(`${value}T12:00:00`);return Number.isNaN(d.getTime())?value:d.toLocaleDateString([],{weekday:'short',month:'short',day:'numeric'})};
function persist(message){state=saveV3State({...state,money:normalizeMoney(state.money)});statusText=`✓ ${message} · ${V3_BUILD}`;window.__katOSV3=state;render()}
function replaceMoney(patch){state={...state,money:normalizeMoney({...state.money,...patch})}}

function renderReceipt(){
  const s=moneyCafeSnapshot(state.money),next=s.nextPayday;
  const verdict=state.money.accounts.length===0?'Add your actual account balances so the Café can calculate cash available.':s.safeToUse>=0?(s.dueBeforePayday?`You're covered through ${next?'the next expected payday':'the current bill window'} based on the balances you entered.`:'No unpaid bills are currently in the receipt window.'):'Bills in the current window are larger than the cash balances entered.';
  return `<section class="receipt"><div class="receipt-title"><div class="ey">☕ TODAY'S CAFÉ RECEIPT</div><b>What does the money actually look like?</b><span>Expected income stays separate from received cash.</span></div><div class="receipt-grid"><article class="receipt-item"><small>💳 IN THE TILL</small><b>${cash(s.totalCash)}</b><span>entered account balances</span></article><article class="receipt-item"><small>☕ NEXT PAYDAY</small><b>${next?cash(next.estimatedGross):'Not set'}</b><span>${next?`estimated · ${dateLabel(next.expectedDate)}`:'no expected paycheck'}</span></article><article class="receipt-item"><small>🧾 DUE BEFORE PAY</small><b>${cash(s.dueBeforePayday)}</b><span>${s.billsBefore.length} unpaid bill${s.billsBefore.length===1?'':'s'} in window</span></article><article class="receipt-item"><small>💸 SIDE QUESTS PENDING</small><b>${cash(s.pendingEarned)}</b><span>earned, not deposited</span></article></div><div class="safe-line"><div><div class="ey">AVAILABLE AFTER CURRENT BILL WINDOW</div><span>${esc(verdict)}</span></div><b>${state.money.accounts.length?cash(s.safeToUse):'Add balances'}</b></div></section>`;
}

function renderIncome(){
  const earnings=state.money.earnings.slice().sort((a,b)=>String(b.receivedDate||b.expectedDate||b.date).localeCompare(String(a.receivedDate||a.expectedDate||a.date)));
  const received=earnings.filter(x=>x.status==='received').reduce((s,x)=>s+earningAmount(x),0),pending=earnings.filter(x=>x.kind==='gig'&&x.status==='earned').reduce((s,x)=>s+x.grossEarned,0),expected=earnings.filter(x=>x.kind==='paycheck'&&x.status==='expected').reduce((s,x)=>s+x.estimatedGross,0);
  return `<section class="card full"><div class="head"><div><div class="ey">💵 PAYDAY COUNTER</div><h2>One earnings ledger, two views</h2><p>Anything created in Boss Bitch appears here automatically. Expected, waiting payout, and received stay visibly different.</p></div><div class="count">${earnings.length}</div></div><div class="small-grid"><article class="mini"><small>RECEIVED</small><b>${cash(received)}</b></article><article class="mini"><small>EXPECTED PAYCHECKS</small><b>${cash(expected)}</b></article><article class="mini"><small>SIDE QUESTS WAITING</small><b>${cash(pending)}</b></article></div><div class="income-grid">${earnings.length?earnings.map(item=>{const isReceived=item.status==='received',name=item.kind==='gig'?(item.platform||'Side Quest'):(item.employer||'Paycheck'),amount=earningAmount(item),detail=item.kind==='gig'?`${dateLabel(item.date)} · ${item.hours?`${item.hours} hr · `:''}${item.expenses?`${cash(item.expenses)} tracked expenses · `:''}${cash(gigNetBeforeTax(item))} net before tax/other deductions`:`${item.hours} hr × ${cash(item.hourlyRate)} · ${item.expectedDate?`expected ${dateLabel(item.expectedDate)}`:''}`;return `<article class="income-card ${isReceived?'received':''}"><b>${item.kind==='gig'?'💸':'💼'} ${esc(name)} · ${cash(amount)} <span class="status ${isReceived?'received':''}">${isReceived?'received':item.kind==='gig'?'waiting payout':'expected'}</span></b><small>${esc(detail)}${isReceived&&item.receivedDate?` · landed ${dateLabel(item.receivedDate)}`:''}</small>${!isReceived?`<div class="earning-actions"><input class="money-input" type="number" min="0" step="0.01" value="${item.kind==='gig'?item.grossEarned:''}" placeholder="deposit" data-income-value="${esc(item.id)}"><button class="btn tiny primary" data-income-land="${esc(item.id)}">🏦 Mark received</button><button class="delete" data-income-delete="${esc(item.id)}">×</button></div>`:`<div class="earning-actions"><button class="delete" data-income-delete="${esc(item.id)}">×</button></div>`}</article>`}).join(''):'<div class="empty">☕ No earnings yet. Boss Bitch payroll and Side Quests will appear here automatically.</div>'}</div></section>`;
}

function renderAccounts(){
  const accounts=state.money.accounts;
  return `<section class="card"><div class="head"><div><div class="ey">💰 IN THE TILL</div><h2>Money you can actually see</h2><p>These balances drive the Café Receipt. Receiving income does not silently guess which account changed.</p></div><div class="count">${cash(accounts.reduce((s,x)=>s+x.balance,0))}</div></div><form id="accountForm"><div class="fields"><label class="field"><span>Account</span><input id="accountName" required placeholder="Checking"></label><label class="field"><span>Type</span><select id="accountType"><option value="checking">Checking</option><option value="savings">Savings</option><option value="cash">Cash</option><option value="other">Other</option></select></label><label class="field wide"><span>Current balance</span><input id="accountBalance" type="number" min="0" step="0.01" required></label></div><div class="form-actions"><button class="btn primary">＋ Add account</button></div></form><div class="list">${accounts.length?accounts.map(item=>`<article class="row"><div class="row-icon">${item.type==='savings'?'🫙':item.type==='cash'?'💵':'💳'}</div><div><b>${esc(item.name)}</b><small>${esc(item.type)} · <input class="money-input" type="number" min="0" step="0.01" value="${item.balance}" data-account-value="${esc(item.id)}"> <button class="btn tiny" data-account-save="${esc(item.id)}">Update balance</button></small></div><button class="delete" data-account-delete="${esc(item.id)}">×</button></article>`).join(''):'<div class="empty">💳 Add the accounts you want included in available cash.</div>'}</div></section>`;
}

function renderBills(){
  const bills=state.money.bills.slice().sort((a,b)=>String(a.dueDate||'9999').localeCompare(String(b.dueDate||'9999')));
  return `<section class="card"><div class="head"><div><div class="ey">🧾 ON THE TAB</div><h2>Bills coming up</h2><p>Clear dates, clear amounts, no financial jump scares.</p></div><div class="count">${bills.filter(x=>!x.paid).length}</div></div><form id="billForm"><div class="fields"><label class="field"><span>Bill</span><input id="billName" required placeholder="Rent"></label><label class="field"><span>Amount</span><input id="billAmount" type="number" min="0" step="0.01" required></label><label class="field wide"><span>Due date</span><input id="billDue" type="date" required></label></div><div class="form-actions"><button class="btn primary">＋ Add bill</button></div></form><div class="list">${bills.length?bills.map(item=>`<article class="row ${item.paid?'done':''}"><button class="check" data-bill-toggle="${esc(item.id)}">${item.paid?'✓':'○'}</button><div><b>${esc(item.name)} · ${cash(item.amount)}</b><small>Due ${dateLabel(item.dueDate)}${item.paid?' · paid':''}</small></div><button class="delete" data-bill-delete="${esc(item.id)}">×</button></article>`).join(''):'<div class="empty">🧾 Nothing on the tab yet.</div>'}</div></section>`;
}

function renderSpending(){
  const today=localDateKey(),items=state.money.spending.slice().sort((a,b)=>String(b.loggedAt).localeCompare(String(a.loggedAt))).slice(0,12),todayTotal=state.money.spending.filter(x=>x.date===today).reduce((s,x)=>s+x.amount,0);
  return `<section class="card"><div class="head"><div><div class="ey">🍓 SPENDING TRAY</div><h2>What left the table</h2><p>Information, not a courtroom.</p></div><div class="count">${cash(todayTotal)}</div></div><form id="spendForm"><div class="fields"><label class="field"><span>What</span><input id="spendDescription" required placeholder="Groceries"></label><label class="field"><span>Amount</span><input id="spendAmount" type="number" min="0" step="0.01" required></label><label class="field"><span>Category</span><input id="spendCategory" placeholder="Food"></label><label class="field"><span>Date</span><input id="spendDate" type="date" value="${today}"></label></div><div class="form-actions"><button class="btn primary">＋ Log spending</button></div></form><div class="list">${items.length?items.map(item=>`<article class="row"><div class="row-icon">🍓</div><div><b>${esc(item.description)} · ${cash(item.amount)}</b><small>${esc(item.category)} · ${dateLabel(item.date)}</small></div><button class="delete" data-spend-delete="${esc(item.id)}">×</button></article>`).join(''):'<div class="empty">🍓 No spending logged yet.</div>'}</div></section>`;
}

function renderSavings(){
  const goals=state.money.savingsGoals;
  return `<section class="card"><div class="head"><div><div class="ey">🫙 TIP JARS</div><h2>Save toward something, or just save</h2><p>A target is optional. The jar does not need to yell a percentage at you.</p></div><div class="count">${goals.length}</div></div><form id="goalForm"><div class="fields"><label class="field"><span>Jar name</span><input id="goalName" required placeholder="Future Home"></label><label class="field"><span>Saved now</span><input id="goalCurrent" type="number" min="0" step="0.01" value="0"></label><label class="field wide"><span>Target · optional</span><input id="goalTarget" type="number" min="0" step="0.01"></label></div><div class="form-actions"><button class="btn primary">＋ Add Tip Jar</button></div></form><div class="jar-grid">${goals.length?goals.map(item=>{const pct=item.target?Math.min(100,item.current/item.target*100):0;return `<article class="jar"><b>🫙 ${esc(item.name)}</b><small>${cash(item.current)}${item.target?` / ${cash(item.target)}`:' saved · no target'}</small>${item.target?`<div class="jar-track"><i style="width:${pct}%"></i></div>`:''}<div class="earning-actions"><input class="money-input" type="number" min="0" step="0.01" value="${item.current}" data-goal-value="${esc(item.id)}"><button class="btn tiny" data-goal-save="${esc(item.id)}">Update</button><button class="delete" data-goal-delete="${esc(item.id)}">×</button></div></article>`}).join(''):'<div class="empty">🫙 No Tip Jars yet.</div>'}</div></section>`;
}

function renderDebts(){
  const debts=state.money.debts;
  return `<section class="card"><div class="head"><div><div class="ey">💳 BALANCE DUE</div><h2>Debt needs clarity, not confetti</h2><p>Balance, APR, minimum, date. Cute enough to look at, serious enough to understand.</p></div><div class="count">${cash(debts.reduce((s,x)=>s+x.balance,0))}</div></div><form id="debtForm"><div class="fields"><label class="field"><span>Debt</span><input id="debtName" required placeholder="Credit card"></label><label class="field"><span>Balance</span><input id="debtBalance" type="number" min="0" step="0.01" required></label><label class="field"><span>APR %</span><input id="debtApr" type="number" min="0" step="0.01"></label><label class="field"><span>Minimum</span><input id="debtMinimum" type="number" min="0" step="0.01"></label><label class="field wide"><span>Due date</span><input id="debtDue" type="date"></label></div><div class="form-actions"><button class="btn primary">＋ Add debt</button></div></form><div class="list">${debts.length?debts.map(item=>`<article class="debt-card"><b>${esc(item.name)} · ${cash(item.balance)}</b><small>${item.apr?`${item.apr}% APR · `:''}${item.minimum?`${cash(item.minimum)} minimum · `:''}${item.dueDate?`due ${dateLabel(item.dueDate)}`:'no due date'}</small><div class="earning-actions"><button class="delete" data-debt-delete="${esc(item.id)}">×</button></div></article>`).join(''):'<div class="empty">💳 No debt records added.</div>'}</div></section>`;
}

function render(){app.innerHTML=`<main class="shell"><a class="back" href="./?v=3.0.0-alpha.9">← Back to KatOS V3</a><section class="hero"><div class="ey">☕ KATOS V3 · ALPHA 9 · MONEY CAFÉ</div><h1>Your money, currently brewing.</h1><p>Paychecks and Side Quest payouts flow in from Boss Bitch automatically. The Café keeps expected money separate from landed money, then puts bills, cash, spending, savings, and debt into one calmer view.</p><div class="hero-actions"><a class="btn primary" href="./boss.html?v=3.0.0-alpha.9">💼 Open Boss Bitch</a></div></section>${renderReceipt()}<div class="grid">${renderIncome()}${renderAccounts()}${renderBills()}${renderSpending()}${renderSavings()}${renderDebts()}</div><div class="cafe-note"><b>${esc(statusText)}</b><br>The Café Receipt uses balances and bills you enter here. Income history does not automatically alter an account balance because KatOS does not guess which account received a deposit.</div></main>`;bind()}

function bind(){
  document.querySelectorAll('[data-income-land]').forEach(b=>b.addEventListener('click',()=>{const input=document.querySelector(`[data-income-value="${CSS.escape(b.dataset.incomeLand)}"]`),amount=Number(input?.value);if(!amount)return;state={...state,money:markEarningReceived(state.money,b.dataset.incomeLand,amount)};persist('Income marked received; Boss Bitch sees the same record')}));
  document.querySelectorAll('[data-income-delete]').forEach(b=>b.addEventListener('click',()=>{state={...state,money:deleteEarning(state.money,b.dataset.incomeDelete)};persist('Earning removed from both views')}));
  document.getElementById('accountForm')?.addEventListener('submit',e=>{e.preventDefault();state={...state,money:addAccount(state.money,{name:document.getElementById('accountName').value,type:document.getElementById('accountType').value,balance:Number(document.getElementById('accountBalance').value)})};persist('Account added to the till')});
  document.querySelectorAll('[data-account-save]').forEach(b=>b.addEventListener('click',()=>{const input=document.querySelector(`[data-account-value="${CSS.escape(b.dataset.accountSave)}"]`),accounts=state.money.accounts.map(x=>x.id===b.dataset.accountSave?{...x,balance:Number(input?.value)||0}:x);replaceMoney({accounts});persist('Account balance updated')}));
  document.querySelectorAll('[data-account-delete]').forEach(b=>b.addEventListener('click',()=>{state={...state,money:deleteAccount(state.money,b.dataset.accountDelete)};persist('Account removed')}));
  document.getElementById('billForm')?.addEventListener('submit',e=>{e.preventDefault();state={...state,money:addBill(state.money,{name:document.getElementById('billName').value,amount:Number(document.getElementById('billAmount').value),dueDate:document.getElementById('billDue').value})};persist('Bill added to the tab')});
  document.querySelectorAll('[data-bill-toggle]').forEach(b=>b.addEventListener('click',()=>{state={...state,money:toggleBillPaid(state.money,b.dataset.billToggle)};persist('Bill status updated')}));
  document.querySelectorAll('[data-bill-delete]').forEach(b=>b.addEventListener('click',()=>{state={...state,money:deleteBill(state.money,b.dataset.billDelete)};persist('Bill removed')}));
  document.getElementById('spendForm')?.addEventListener('submit',e=>{e.preventDefault();state={...state,money:addSpending(state.money,{description:document.getElementById('spendDescription').value,amount:Number(document.getElementById('spendAmount').value),category:document.getElementById('spendCategory').value,date:document.getElementById('spendDate').value})};persist('Spending logged')}));
  document.querySelectorAll('[data-spend-delete]').forEach(b=>b.addEventListener('click',()=>{state={...state,money:deleteSpending(state.money,b.dataset.spendDelete)};persist('Spending entry removed')}));
  document.getElementById('goalForm')?.addEventListener('submit',e=>{e.preventDefault();state={...state,money:addSavingsGoal(state.money,{name:document.getElementById('goalName').value,current:Number(document.getElementById('goalCurrent').value),target:Number(document.getElementById('goalTarget').value)})};persist('Tip Jar added')}));
  document.querySelectorAll('[data-goal-save]').forEach(b=>b.addEventListener('click',()=>{const input=document.querySelector(`[data-goal-value="${CSS.escape(b.dataset.goalSave)}"]`),savingsGoals=state.money.savingsGoals.map(x=>x.id===b.dataset.goalSave?{...x,current:Number(input?.value)||0}:x);replaceMoney({savingsGoals});persist('Tip Jar updated')}));
  document.querySelectorAll('[data-goal-delete]').forEach(b=>b.addEventListener('click',()=>{state={...state,money:deleteSavingsGoal(state.money,b.dataset.goalDelete)};persist('Tip Jar removed')}));
  document.getElementById('debtForm')?.addEventListener('submit',e=>{e.preventDefault();state={...state,money:addDebt(state.money,{name:document.getElementById('debtName').value,balance:Number(document.getElementById('debtBalance').value),apr:Number(document.getElementById('debtApr').value),minimum:Number(document.getElementById('debtMinimum').value),dueDate:document.getElementById('debtDue').value})};persist('Debt added')}));
  document.querySelectorAll('[data-debt-delete]').forEach(b=>b.addEventListener('click',()=>{state={...state,money:deleteDebt(state.money,b.dataset.debtDelete)};persist('Debt removed')}));
}
render();try{localStorage.setItem(V3_STORAGE_KEY,JSON.stringify({data:state}))}catch{}
