import{loadV3State,saveV3State,V3_STORAGE_KEY}from'./app/schema.js?v=3.0.0-alpha.7';
import{evaluateStateBrain}from'./app/brain.js?v=3.0.0-alpha.7';
import{ensureBehaviorSupport,evaluateBehaviorSupport}from'./app/behavior-support.js?v=3.0.0-alpha.7';
import{MOTION_TYPES,motionTypeMeta,normalizeMovement,addMotionSession,deleteMotionSession,motionTotals,movementWinMessage,weekMotionBreakdown,addMotionRecipe,deleteMotionRecipe,addMotionVideo,deleteMotionVideo,addWeighIn,deleteWeighIn,latestWeighIn,recommendMovement}from'./app/motion.js?v=3.0.0-alpha.7';

let state=ensureBehaviorSupport(loadV3State());
state={...state,movement:normalizeMovement(state.movement)};
let lastWin='';
const app=document.getElementById('app');
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const time=value=>{const d=new Date(value);return Number.isNaN(d.getTime())?'':d.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})};
const dateLabel=value=>{const d=new Date(`${value}T12:00:00`);return Number.isNaN(d.getTime())?value:d.toLocaleDateString([],{month:'short',day:'numeric'})};
const safeUrl=value=>/^https?:\/\//i.test(String(value||''))?String(value):'';

function persist(message){state=saveV3State({...state,movement:normalizeMovement(state.movement)});window.__katOSV3=state;render(message)}
function sessionMeta(session){const bits=[`${session.minutes} min`,`${session.effort} effort`];if(session.distanceMiles)bits.push(`${session.distanceMiles} mi`);if(session.speedMph)bits.push(`${session.speedMph} mph`);if(session.inclinePct)bits.push(`${session.inclinePct}% incline`);if(session.calories)bits.push(`${session.calories} cal`);if(session.pairedWith)bits.push(`paired with ${session.pairedWith}`);return bits.join(' · ')}
function itemName(item){return item.name||item.title||motionTypeMeta(item.type).label}

function renderRecommendations(policy){
  const picks=recommendMovement(state.movement,policy);
  return `<section class="card full recommend"><div class="head"><div><div class="ey">🧠 BRAIN-POWERED FIT</div><h2>What movement fits right now?</h2><p>These are options, not assignments. KatOS uses current energy, capacity, mode, and your saved movement library.</p></div><div class="count">${picks.length}</div></div><div class="recommend-grid">${picks.map(entry=>{const item=entry.item,meta=motionTypeMeta(item.type);return `<article class="recommend-card"><div class="bigicon">${meta.icon}</div><small>${entry.kind==='video'?'VIDEO SHELF':entry.kind==='recipe'?'MOVEMENT RECIPE':'QUICK OPTION'}</small><b>${esc(itemName(item))}</b><span>${item.minutes} min · ${esc(item.effort)} effort</span>${item.pairedWith?`<span>Pairs with: ${esc(item.pairedWith)}</span>`:''}<button class="btn" data-load-motion="${esc(item.id)}" data-load-kind="${entry.kind}">Load into log</button></article>`}).join('')}</div><div class="brain-note">${esc(policy.headline)} · ${policy.choiceCount} visible choice${policy.choiceCount===1?'':'s'} · ${esc(policy.taskEnergyCeiling)} effort ceiling</div></section>`;
}

function renderProgress(){
  const totals=motionTotals(state.movement),days=weekMotionBreakdown(state.movement),max=Math.max(10,...days.map(d=>d.minutes)),latest=latestWeighIn(state.movement);
  return `<section class="card full"><div class="head"><div><div class="ey">🌷 GENTLE PROGRESS</div><h2>What happened, not what you “should” have done</h2><p>Minutes and sessions are the movement headline. Weight and calories remain optional context.</p></div><div class="count">${totals.todayMinutes}</div></div><div class="stats"><article class="stat"><small>TODAY</small><b>${totals.todayMinutes}</b><span>minutes moved</span></article><article class="stat"><small>TODAY</small><b>${totals.todaySessions}</b><span>session${totals.todaySessions===1?'':'s'}</span></article><article class="stat"><small>THIS WEEK</small><b>${totals.weekMinutes}</b><span>minutes moved</span></article><article class="stat"><small>CHECK-IN</small><b>${latest?latest.weightLb:'♡'}</b><span>${latest?'lb · optional':'weight optional'}</span></article></div><div class="week-bars">${days.map(day=>`<article><div class="week-bar"><i style="height:${Math.max(3,(day.minutes/max)*100)}%"></i></div><b>${esc(day.label)}</b><span>${day.minutes}m</span></article>`).join('')}</div>${lastWin?`<div class="win">${esc(lastWin)}</div>`:''}</section>`;
}

function renderLog(){
  return `<section class="card"><div class="head"><div><div class="ey">＋ LOG MOVEMENT</div><h2>Tiny entry, useful history</h2><p>Only movement type and minutes are required.</p></div><div class="count">＋</div></div><div class="quick"><button class="chipbtn" data-minutes="5">5 min</button><button class="chipbtn" data-minutes="10">10 min</button><button class="chipbtn" data-minutes="15">15 min</button><button class="chipbtn" data-minutes="20">20 min</button></div><form id="motionForm"><div class="fields"><label class="field"><span>Movement</span><select id="motionType">${MOTION_TYPES.map(type=>`<option value="${type.value}">${type.icon} ${esc(type.label)}</option>`).join('')}</select></label><label class="field"><span>Minutes</span><input id="motionMinutes" type="number" min="1" max="600" required placeholder="10"></label><label class="field"><span>Effort</span><select id="motionEffort"><option value="low">Low</option><option value="medium" selected>Medium</option><option value="high">High</option></select></label><label class="field"><span>Paired with · optional</span><input id="motionPaired" placeholder="work videos, TV, music"></label><label class="field"><span>Distance miles · optional</span><input id="motionDistance" type="number" min="0" step="0.01"></label><label class="field"><span>Speed mph · optional</span><input id="motionSpeed" type="number" min="0" step="0.1"></label><label class="field"><span>Incline % · optional</span><input id="motionIncline" type="number" min="0" step="0.5"></label><label class="field"><span>Calories · optional context</span><input id="motionCalories" type="number" min="0" step="1"></label><label class="field wide"><span>Notes · optional</span><textarea id="motionNotes" placeholder="How it felt, anything Future Kat should know"></textarea></label><input id="motionRecipeId" type="hidden"><input id="motionVideoId" type="hidden"></div><div class="form-actions"><button class="btn primary" type="submit">🌿 Log movement</button></div></form></section>`;
}

function renderSupport(){const support=evaluateBehaviorSupport(state);return `<section class="card"><div class="head"><div><div class="ey">🧠 BEHAVIOR SUPPORT</div><h2>How KatOS helps today</h2><p>Support tactics, not a behavior grade.</p></div><div class="count">🌷</div></div><div class="support">${support.tactics.slice(0,5).map(item=>`<article class="support-item"><b>${esc(item.icon)} ${esc(item.label)}</b>${esc(item.reason||item.description)}</article>`).join('')}</div></section>`}

function renderRecipes(){
  const recipes=state.movement.routines.filter(x=>!x.archived);
  return `<section class="card"><div class="head"><div><div class="ey">🎀 MOVEMENT RECIPES</div><h2>Save versions that are easy to repeat</h2><p>A recipe remembers the setup so starting later takes fewer decisions.</p></div><div class="count">${recipes.length}</div></div><form id="recipeForm"><div class="fields"><label class="field wide"><span>Name</span><input id="recipeName" required placeholder="Work-video treadmill walk"></label><label class="field"><span>Type</span><select id="recipeType">${MOTION_TYPES.map(type=>`<option value="${type.value}">${type.icon} ${esc(type.label)}</option>`).join('')}</select></label><label class="field"><span>Minutes</span><input id="recipeMinutes" type="number" min="1" value="10" required></label><label class="field"><span>Effort</span><select id="recipeEffort"><option value="low">Low</option><option value="medium" selected>Medium</option><option value="high">High</option></select></label><label class="field"><span>Pair with · optional</span><input id="recipePair" placeholder="work videos"></label><label class="field wide"><span>Tags · comma separated</span><input id="recipeTags" placeholder="easy, work, low energy"></label></div><div class="form-actions"><button class="btn primary">＋ Save recipe</button></div></form><div class="library">${recipes.length?recipes.map(item=>`<article class="library-item"><div class="bigicon">${motionTypeMeta(item.type).icon}</div><div><b>${esc(item.name)}</b><small>${item.minutes} min · ${esc(item.effort)}${item.tags.length?` · ${esc(item.tags.join(', '))}`:''}</small></div><button class="btn tiny" data-load-motion="${esc(item.id)}" data-load-kind="recipe">Load</button><button class="delete" data-recipe-delete="${esc(item.id)}">×</button></article>`).join(''):'<div class="empty">🎀 No recipes yet.</div>'}</div></section>`;
}

function renderVideos(){
  const videos=state.movement.videos;
  return `<section class="card"><div class="head"><div><div class="ey">📺 VIDEO SHELF</div><h2>Keep movement videos where movement happens</h2><p>Save links with enough context for the Brain to recommend them later.</p></div><div class="count">${videos.length}</div></div><form id="videoForm"><div class="fields"><label class="field wide"><span>Title</span><input id="videoTitle" required placeholder="15-minute beginner Pilates"></label><label class="field wide"><span>URL</span><input id="videoUrl" type="url" placeholder="https://..."></label><label class="field"><span>Type</span><select id="videoType">${MOTION_TYPES.map(type=>`<option value="${type.value}">${type.icon} ${esc(type.label)}</option>`).join('')}</select></label><label class="field"><span>Minutes</span><input id="videoMinutes" type="number" min="1" value="15" required></label><label class="field"><span>Effort</span><select id="videoEffort"><option value="low">Low</option><option value="medium" selected>Medium</option><option value="high">High</option></select></label><label class="field"><span>Tags</span><input id="videoTags" placeholder="beginner, gentle"></label></div><div class="form-actions"><button class="btn primary">＋ Save video</button></div></form><div class="library">${videos.length?videos.map(item=>{const url=safeUrl(item.url);return `<article class="library-item"><div class="bigicon">${motionTypeMeta(item.type).icon}</div><div><b>${esc(item.title)}</b><small>${item.minutes} min · ${esc(item.effort)}${item.tags.length?` · ${esc(item.tags.join(', '))}`:''}</small></div>${url?`<a class="btn tiny" target="_blank" rel="noopener" href="${esc(url)}">Watch</a>`:''}<button class="btn tiny" data-load-motion="${esc(item.id)}" data-load-kind="video">Load</button><button class="delete" data-video-delete="${esc(item.id)}">×</button></article>`}).join(''):'<div class="empty">📺 No saved movement videos yet.</div>'}</div></section>`;
}

function renderCheckIns(){
  const entries=state.movement.weighIns.slice().sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,6),latest=latestWeighIn(state.movement);
  return `<section class="card"><div class="head"><div><div class="ey">⚖️ OPTIONAL CHECK-IN</div><h2>Weight can be data without being the grade</h2><p>Use this if you want a Sunday or occasional weigh-in. Motion progress does not depend on it.</p></div><div class="count">${latest?latest.weightLb:'♡'}</div></div><form id="weighForm"><div class="fields"><label class="field"><span>Weight · lb</span><input id="weighWeight" type="number" min="1" step="0.1" required placeholder="200.8"></label><label class="field"><span>Date</span><input id="weighDate" type="date"></label><label class="field wide"><span>Note · optional</span><input id="weighNote" placeholder="Sunday check-in"></label></div><div class="form-actions"><button class="btn primary">＋ Log check-in</button></div></form><div class="checkins">${entries.map(item=>`<article><b>${item.weightLb} lb</b><span>${esc(dateLabel(item.date))}${item.note?` · ${esc(item.note)}`:''}</span><button class="delete" data-weigh-delete="${esc(item.id)}">×</button></article>`).join('')||'<div class="empty">⚖️ No check-ins logged.</div>'}</div></section>`;
}

function renderToday(){const today=motionTotals(state.movement).today.slice().reverse();return `<section class="card full"><div class="head"><div><div class="ey">📓 TODAY'S MOVEMENT LOG</div><h2>Every session gets to exist</h2><p>Short sessions are not hidden, rounded down, or labeled incomplete.</p></div><div class="count">${today.length}</div></div><div class="sessions">${today.length?today.map(session=>`<article class="session"><div class="session-icon">${motionTypeMeta(session.type).icon}</div><div><b>${esc(session.label)}</b><small>${esc(sessionMeta(session))}${session.notes?` · ${esc(session.notes)}`:''}</small></div><button class="delete" data-motion-delete="${esc(session.id)}">×</button></article>`).join(''):'<div class="empty">🌱 No movement logged today yet. Even five minutes belongs here.</div>'}</div></section>`}

function render(message=''){
  const policy=evaluateStateBrain(state);
  app.innerHTML=`<main class="shell"><a class="back" href="./?v=3.0.0-alpha.7">← Back to KatOS V3</a><section class="hero"><div class="ey">🌿 KATOS V3 · ALPHA 7 · MOTION MEADOW V1 COMPLETE</div><h1>Movement gets support, not pressure.</h1><p>Log what happened, save repeatable movement recipes and videos, get Brain-fit options, see gentle weekly progress, and keep weight as an optional check-in instead of the scoreboard.</p>${message?`<div class="win">✓ ${esc(message)}</div>`:''}</section><div class="grid">${renderRecommendations(policy)}${renderProgress()}${renderLog()}${renderSupport()}${renderRecipes()}${renderVideos()}${renderCheckIns()}${renderToday()}</div><div class="note"><b>Motion Meadow V1 rule:</b> initiation and useful approximations count. Minutes are the primary movement signal. Calories, distance, speed, and weight are optional context, never mandatory goals.</div></main>`;
  bind();
}

function findLibraryItem(kind,id){if(kind==='recipe')return state.movement.routines.find(x=>x.id===id);if(kind==='video')return state.movement.videos.find(x=>x.id===id);return recommendMovement(state.movement,evaluateStateBrain(state)).find(x=>x.item.id===id)?.item||null}
function loadIntoForm(item){if(!item)return;document.getElementById('motionType').value=item.type;document.getElementById('motionMinutes').value=item.minutes;document.getElementById('motionEffort').value=item.effort||'medium';document.getElementById('motionPaired').value=item.pairedWith||'';document.getElementById('motionRecipeId').value=state.movement.routines.some(x=>x.id===item.id)?item.id:'';document.getElementById('motionVideoId').value=state.movement.videos.some(x=>x.id===item.id)?item.id:'';document.getElementById('motionMinutes').focus();document.getElementById('motionForm').scrollIntoView({behavior:'smooth',block:'center'})}

function bind(){
  document.querySelectorAll('[data-minutes]').forEach(button=>button.addEventListener('click',()=>{document.getElementById('motionMinutes').value=button.dataset.minutes;document.getElementById('motionMinutes').focus()}));
  document.querySelectorAll('[data-load-motion]').forEach(button=>button.addEventListener('click',()=>loadIntoForm(findLibraryItem(button.dataset.loadKind,button.dataset.loadMotion))));
  document.getElementById('motionForm')?.addEventListener('submit',event=>{event.preventDefault();const type=document.getElementById('motionType').value,minutes=Number(document.getElementById('motionMinutes').value);const next=addMotionSession(state.movement,{type,minutes,effort:document.getElementById('motionEffort').value,pairedWith:document.getElementById('motionPaired').value,distanceMiles:Number(document.getElementById('motionDistance').value)||0,speedMph:Number(document.getElementById('motionSpeed').value)||0,inclinePct:Number(document.getElementById('motionIncline').value)||0,calories:Number(document.getElementById('motionCalories').value)||0,notes:document.getElementById('motionNotes').value,recipeId:document.getElementById('motionRecipeId').value,videoId:document.getElementById('motionVideoId').value,source:'manual'});const created=next.sessions.at(-1);state={...state,movement:next};lastWin=movementWinMessage(created);persist(`${minutes} minutes movement logged · ${lastWin}`)});
  document.querySelectorAll('[data-motion-delete]').forEach(button=>button.addEventListener('click',()=>{state={...state,movement:deleteMotionSession(state.movement,button.dataset.motionDelete)};lastWin='';persist('Movement entry removed')}));
  document.getElementById('recipeForm')?.addEventListener('submit',event=>{event.preventDefault();state={...state,movement:addMotionRecipe(state.movement,{name:document.getElementById('recipeName').value,type:document.getElementById('recipeType').value,minutes:Number(document.getElementById('recipeMinutes').value),effort:document.getElementById('recipeEffort').value,pairedWith:document.getElementById('recipePair').value,tags:document.getElementById('recipeTags').value})};persist('Movement recipe saved')});
  document.querySelectorAll('[data-recipe-delete]').forEach(button=>button.addEventListener('click',()=>{state={...state,movement:deleteMotionRecipe(state.movement,button.dataset.recipeDelete)};persist('Movement recipe removed')}));
  document.getElementById('videoForm')?.addEventListener('submit',event=>{event.preventDefault();state={...state,movement:addMotionVideo(state.movement,{title:document.getElementById('videoTitle').value,url:document.getElementById('videoUrl').value,type:document.getElementById('videoType').value,minutes:Number(document.getElementById('videoMinutes').value),effort:document.getElementById('videoEffort').value,tags:document.getElementById('videoTags').value})};persist('Movement video saved')});
  document.querySelectorAll('[data-video-delete]').forEach(button=>button.addEventListener('click',()=>{state={...state,movement:deleteMotionVideo(state.movement,button.dataset.videoDelete)};persist('Movement video removed')}));
  document.getElementById('weighForm')?.addEventListener('submit',event=>{event.preventDefault();state={...state,movement:addWeighIn(state.movement,{weightLb:Number(document.getElementById('weighWeight').value),date:document.getElementById('weighDate').value,note:document.getElementById('weighNote').value,source:'manual'})};persist('Optional check-in logged')});
  document.querySelectorAll('[data-weigh-delete]').forEach(button=>button.addEventListener('click',()=>{state={...state,movement:deleteWeighIn(state.movement,button.dataset.weighDelete)};persist('Check-in removed')}));
}

render();
try{localStorage.setItem(V3_STORAGE_KEY,JSON.stringify({data:state}))}catch{}
