import{loadV3State,saveV3State,V3_STORAGE_KEY}from'./app/schema.js?v=3.0.0-alpha.8';
import{evaluateStateBrain}from'./app/brain.js?v=3.0.0-alpha.8';
import{NOM_KINDS,nomKindMeta,normalizeNoms,addFood,deleteFood,toggleFoodAvailable,addRecipe,deleteRecipe,toggleRecipeAvailable,logNom,clearCurrentNom,deleteNomLog,todayNomLogs,recommendNoms,nomRecommendationMessage}from'./app/noms.js?v=3.0.0-alpha.8';

let state=loadV3State();
state={...state,nourish:{...state.nourish,noms:normalizeNoms(state.nourish?.noms)}};
let requestedTags=[];
let status='';
const app=document.getElementById('app');
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const time=value=>{const d=new Date(value);return Number.isNaN(d.getTime())?'':d.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})};
const parseTags=value=>String(value||'').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean);

function persist(message){state=saveV3State({...state,nourish:{...state.nourish,noms:normalizeNoms(state.nourish?.noms)}});window.__katOSV3=state;status=message;render()}
function itemMeta(item){const bits=[nomKindMeta(item.kind).label,item.effort==='zero'?'zero prep effort':`${item.effort} effort`];if(item.prepMinutes)bits.push(`${item.prepMinutes} min`);if(item.tags.length)bits.push(item.tags.join(', '));return bits.join(' · ')}
function getSource(type,id){const noms=normalizeNoms(state.nourish?.noms);return type==='food'?noms.foods.find(x=>x.id===id):noms.recipes.find(x=>x.id===id)}
function eatSaved(type,id){const item=getSource(type,id);if(!item)return;state={...state,nourish:{...state.nourish,noms:logNom(state.nourish.noms,{name:item.name,sourceType:type,sourceId:item.id,kind:item.kind,tags:item.tags})}};persist(`Logged ${item.name} in Nom Diary`)}

function renderRecommendations(){
  const policy=evaluateStateBrain(state),picks=recommendNoms(state.nourish.noms,policy,requestedTags),message=nomRecommendationMessage(state.nourish.noms,policy,requestedTags);
  return `<section class="card full recommend"><div class="head"><div><div class="ey">🧠 BRAIN + YOUR SAVED NOMS</div><h2>What sounds doable right now?</h2><p>Recommendations only come from foods and recipes you saved and marked available. Tag requests are strict.</p></div><div class="count">${picks.length}</div></div><div class="query-row"><input class="tag-query" id="nomTagQuery" value="${esc(requestedTags.join(', '))}" placeholder="Optional tags: sweet, easy, salty"><button class="btn" id="applyNomTags">Filter tags</button><button class="btn" id="clearNomTags">Clear</button></div><div class="recommend-grid">${picks.length?picks.map(entry=>{const item=entry.item,meta=nomKindMeta(item.kind);return `<article class="pick"><div class="icon">${meta.icon}</div><small>${entry.sourceType==='recipe'?'RECIPE':'MY NOMS'}</small><b>${esc(item.name)}</b><span>${esc(itemMeta(item))}</span><button class="btn primary" data-eat-type="${entry.sourceType}" data-eat-id="${esc(item.id)}">🍱 Log this Nom</button></article>`}).join(''):'<div class="empty">🍓 No matching saved Nom.</div>'}</div><div class="explain">${esc(message)} · Brain says: ${esc(policy.headline)}</div></section>`;
}

function renderCurrent(){const current=state.nourish.noms.currentNom;return `<section class="card"><div class="head"><div><div class="ey">🍽 CURRENT NOM</div><h2>What you most recently logged</h2><p>Logging something new never deletes the diary trail.</p></div><div class="count">${current?nomKindMeta(current.kind).icon:'♡'}</div></div>${current?`<div class="current"><b>${esc(current.name)}</b><span>${esc(nomKindMeta(current.kind).label)} · ${esc(time(current.loggedAt))}</span><div class="form-actions"><button class="btn" id="clearCurrentNom">Clear current only</button></div></div>`:'<div class="empty">🍱 Nothing current right now.</div>'}</section>`}

function renderFoods(){
  const foods=state.nourish.noms.foods;
  return `<section class="card"><div class="head"><div><div class="ey">🍓 MY NOMS</div><h2>Food that actually exists</h2><p>Availability lets KatOS know what is realistically an option right now.</p></div><div class="count">${foods.filter(x=>x.available).length}</div></div><form id="foodForm"><div class="fields"><label class="field wide"><span>Name</span><input id="foodName" required placeholder="Greek yogurt, salmon, crackers"></label><label class="field"><span>Kind</span><select id="foodKind">${NOM_KINDS.map(k=>`<option value="${k.value}">${k.icon} ${esc(k.label)}</option>`).join('')}</select></label><label class="field"><span>Effort</span><select id="foodEffort"><option value="zero">Zero prep</option><option value="low" selected>Low</option><option value="medium">Medium</option><option value="high">High</option></select></label><label class="field"><span>Prep minutes</span><input id="foodMinutes" type="number" min="0" max="240" value="0"></label><label class="field"><span>Tags</span><input id="foodTags" placeholder="easy, sweet, safe"></label><label class="field wide"><span>Notes · optional</span><input id="foodNotes" placeholder="Any useful detail"></label></div><div class="form-actions"><button class="btn primary">＋ Add to My Noms</button></div></form><div class="library">${foods.length?foods.map(item=>`<article class="item ${item.available?'':'off'}"><div class="icon">${nomKindMeta(item.kind).icon}</div><div><b>${esc(item.name)}</b><small>${esc(itemMeta(item))}</small></div><button class="btn tiny" data-eat-type="food" data-eat-id="${esc(item.id)}">Log</button><button class="toggle" data-food-toggle="${esc(item.id)}">${item.available?'Available':'Unavailable'}</button><button class="delete" data-food-delete="${esc(item.id)}">×</button></article>`).join(''):'<div class="empty">🍓 Save foods you actually keep around.</div>'}</div></section>`;
}

function renderRecipes(){
  const recipes=state.nourish.noms.recipes;
  return `<section class="card"><div class="head"><div><div class="ey">📖 RECIPES</div><h2>Meals Future Kat can repeat</h2><p>Tags and effort make recipes Brain-readable without turning cooking into a database internship.</p></div><div class="count">${recipes.filter(x=>x.available).length}</div></div><form id="recipeForm"><div class="fields"><label class="field wide"><span>Name</span><input id="nomRecipeName" required placeholder="Korean ground turkey"></label><label class="field"><span>Kind</span><select id="nomRecipeKind">${NOM_KINDS.map(k=>`<option value="${k.value}">${k.icon} ${esc(k.label)}</option>`).join('')}</select></label><label class="field"><span>Effort</span><select id="nomRecipeEffort"><option value="low">Low</option><option value="medium" selected>Medium</option><option value="high">High</option></select></label><label class="field"><span>Prep minutes</span><input id="nomRecipeMinutes" type="number" min="0" max="360" value="20"></label><label class="field"><span>Tags</span><input id="nomRecipeTags" placeholder="savory, comfort, easy"></label><label class="field wide"><span>Ingredients · comma separated</span><input id="nomRecipeIngredients" placeholder="ground turkey, rice, soy sauce"></label></div><div class="form-actions"><button class="btn primary">＋ Save recipe</button></div></form><div class="library">${recipes.length?recipes.map(item=>`<article class="item ${item.available?'':'off'}"><div class="icon">${nomKindMeta(item.kind).icon}</div><div><b>${esc(item.name)}</b><small>${esc(itemMeta(item))}</small></div><button class="btn tiny" data-eat-type="recipe" data-eat-id="${esc(item.id)}">Log</button><button class="toggle" data-recipe-toggle="${esc(item.id)}">${item.available?'Available':'Unavailable'}</button><button class="delete" data-recipe-delete="${esc(item.id)}">×</button></article>`).join(''):'<div class="empty">📖 No recipes saved yet.</div>'}</div></section>`;
}

function renderQuickLog(){return `<section class="card"><div class="head"><div><div class="ey">＋ QUICK LOG</div><h2>For something not saved yet</h2><p>Manual logging is allowed. It does not automatically become a recommendation option.</p></div><div class="count">＋</div></div><form id="manualNomForm"><div class="fields"><label class="field wide"><span>What did you have?</span><input id="manualNomName" required placeholder="Whatever actually happened"></label><label class="field"><span>Kind</span><select id="manualNomKind">${NOM_KINDS.map(k=>`<option value="${k.value}">${k.icon} ${esc(k.label)}</option>`).join('')}</select></label><label class="field"><span>Tags · optional</span><input id="manualNomTags" placeholder="sweet, snack"></label><label class="field wide"><span>Note · optional</span><input id="manualNomNote"></label></div><div class="form-actions"><button class="btn primary">🍱 Log Nom</button></div></form></section>`}

function renderDiary(){const entries=todayNomLogs(state.nourish.noms).slice().reverse();return `<section class="card full"><div class="head"><div><div class="ey">📓 NOM DIARY</div><h2>Today’s food trail</h2><p>Changing Current Nom never erases history.</p></div><div class="count">${entries.length}</div></div><div class="diary">${entries.length?entries.map(item=>`<article class="diary-entry"><div class="icon">${nomKindMeta(item.kind).icon}</div><div><b>${esc(item.name)}</b><small>${esc(nomKindMeta(item.kind).label)} · ${esc(time(item.loggedAt))}${item.tags.length?` · ${esc(item.tags.join(', '))}`:''}</small></div><button class="delete" data-diary-delete="${esc(item.id)}">×</button></article>`).join(''):'<div class="empty">📓 Nothing logged today yet.</div>'}</div></section>`}

function render(){app.innerHTML=`<main class="shell"><a class="back" href="./?v=3.0.0-alpha.8">← Back to KatOS V3</a><section class="hero"><div class="ey">🍱 KATOS V3 · ALPHA 8 · NOMS NOOK V1</div><h1>Recommendations from your food, not imaginary food.</h1><p>Save what actually exists, tag it in ways that matter to you, mark availability, and let the Brain favor lower-effort options when today-Kat needs that.</p>${status?`<div class="explain">✓ ${esc(status)}</div>`:''}</section><div class="grid">${renderRecommendations()}${renderCurrent()}${renderQuickLog()}${renderFoods()}${renderRecipes()}${renderDiary()}</div><div class="note"><b>Noms V1 rule:</b> recommendation tags are strict and recommendations only come from saved, available My Noms or Recipes. Nom Diary records what happened without assigning a food score.</div></main>`;bind()}

function bind(){
  document.getElementById('applyNomTags')?.addEventListener('click',()=>{requestedTags=parseTags(document.getElementById('nomTagQuery').value);render()});
  document.getElementById('clearNomTags')?.addEventListener('click',()=>{requestedTags=[];render()});
  document.querySelectorAll('[data-eat-type]').forEach(btn=>btn.addEventListener('click',()=>eatSaved(btn.dataset.eatType,btn.dataset.eatId)));
  document.getElementById('clearCurrentNom')?.addEventListener('click',()=>{state={...state,nourish:{...state.nourish,noms:clearCurrentNom(state.nourish.noms)}};persist('Current Nom cleared; diary kept')});
  document.getElementById('foodForm')?.addEventListener('submit',event=>{event.preventDefault();state={...state,nourish:{...state.nourish,noms:addFood(state.nourish.noms,{name:document.getElementById('foodName').value,kind:document.getElementById('foodKind').value,effort:document.getElementById('foodEffort').value,prepMinutes:Number(document.getElementById('foodMinutes').value)||0,tags:document.getElementById('foodTags').value,notes:document.getElementById('foodNotes').value})}};persist('Added to My Noms')});
  document.querySelectorAll('[data-food-toggle]').forEach(btn=>btn.addEventListener('click',()=>{state={...state,nourish:{...state.nourish,noms:toggleFoodAvailable(state.nourish.noms,btn.dataset.foodToggle)}};persist('Food availability updated')}));
  document.querySelectorAll('[data-food-delete]').forEach(btn=>btn.addEventListener('click',()=>{state={...state,nourish:{...state.nourish,noms:deleteFood(state.nourish.noms,btn.dataset.foodDelete)}};persist('Food removed from My Noms')}));
  document.getElementById('recipeForm')?.addEventListener('submit',event=>{event.preventDefault();state={...state,nourish:{...state.nourish,noms:addRecipe(state.nourish.noms,{name:document.getElementById('nomRecipeName').value,kind:document.getElementById('nomRecipeKind').value,effort:document.getElementById('nomRecipeEffort').value,prepMinutes:Number(document.getElementById('nomRecipeMinutes').value)||0,tags:document.getElementById('nomRecipeTags').value,ingredients:document.getElementById('nomRecipeIngredients').value})}};persist('Recipe saved')});
  document.querySelectorAll('[data-recipe-toggle]').forEach(btn=>btn.addEventListener('click',()=>{state={...state,nourish:{...state.nourish,noms:toggleRecipeAvailable(state.nourish.noms,btn.dataset.recipeToggle)}};persist('Recipe availability updated')}));
  document.querySelectorAll('[data-recipe-delete]').forEach(btn=>btn.addEventListener('click',()=>{state={...state,nourish:{...state.nourish,noms:deleteRecipe(state.nourish.noms,btn.dataset.recipeDelete)}};persist('Recipe removed')}));
  document.getElementById('manualNomForm')?.addEventListener('submit',event=>{event.preventDefault();state={...state,nourish:{...state.nourish,noms:logNom(state.nourish.noms,{name:document.getElementById('manualNomName').value,sourceType:'manual',kind:document.getElementById('manualNomKind').value,tags:parseTags(document.getElementById('manualNomTags').value),note:document.getElementById('manualNomNote').value})}};persist('Nom logged')});
  document.querySelectorAll('[data-diary-delete]').forEach(btn=>btn.addEventListener('click',()=>{state={...state,nourish:{...state.nourish,noms:deleteNomLog(state.nourish.noms,btn.dataset.diaryDelete)}};persist('Nom Diary entry removed')}));
}
render();
try{localStorage.setItem(V3_STORAGE_KEY,JSON.stringify({data:state}))}catch{}
