import{loadV3State,saveV3State,V3_STORAGE_KEY,V3_BUILD}from'./app/schema.js?v=3.0.0-alpha.10';
import{ROUTINE_DAYPARTS,localDateKey,normalizeRoutines,normalizeRoutineInstances,addRoutine,archiveRoutine,deleteRoutine,ensureRoutineInstance,toggleRoutineStep,finishRoutineToday,skipRoutineDay,deferRoutineDay,reactivateRoutineDay,skipRoutineTomorrow,routineSummary,routinesForDate}from'./app/routines.js?v=3.0.0-alpha.10';

let state=loadV3State();
state={...state,life:{...state.life,routines:normalizeRoutines(state.life?.routines),routineInstances:normalizeRoutineInstances(state.life?.routineInstances)}};
let statusText='Routines V3 is ready.';
const app=document.getElementById('app');
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const dayNames=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];
const daypartMeta=value=>ROUTINE_DAYPARTS.find(item=>item.value===value)||ROUTINE_DAYPARTS.at(-1);

function activity(type,targetId,detail={}){const entry={id:`activity-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,6)}`,type,targetId:String(targetId||''),timestamp:new Date().toISOString(),context:{brain:state.context?.brain,energy:state.context?.energy,capacity:state.context?.capacity,mode:state.context?.mode},detail};state={...state,insights:{...state.insights,activityLog:[...(state.insights?.activityLog||[]),entry]}}}
function persist(message){state=saveV3State({...state,life:{...state.life,routines:normalizeRoutines(state.life.routines),routineInstances:normalizeRoutineInstances(state.life.routineInstances)}});window.__katOSV3=state;statusText=`✓ ${message} · ${V3_BUILD}`;render()}
function recurrenceLabel(item){if(item.recurrence==='daily')return'Every day';if(item.recurrence==='weekdays')return'Weekdays';if(item.recurrence==='weekends')return'Weekends';if(item.recurrence==='manual')return'Manual';return item.days.map(day=>dayNames[day]).join(', ')||'Selected days'}
function parseSteps(value){return String(value||'').split('\n').map(line=>line.trim()).filter(Boolean).map(line=>{const parts=line.split('|'),minutes=Math.max(1,Number(parts[1])||5);return{label:parts[0].trim(),minutes}})}

function renderToday(){
  const today=localDateKey(),summary=routineSummary(state.life.routines,state.life.routineInstances,today),rows=summary.rows;
  return `<section class="card full"><div class="head"><div><div class="ey">🌷 TODAY'S ROUTINES</div><h2>Today's copy can have its own day</h2><p>Complete, partial, skipped, and deferred belong to this date only. Tomorrow's template stays clean.</p></div><div class="count">${summary.percent}%</div></div><div class="stats"><article class="stat"><small>TODAY</small><b>${summary.total}</b><span>routine${summary.total===1?'':'s'} due</span></article><article class="stat"><small>STEPS</small><b>${summary.doneSteps}/${summary.totalSteps}</b><span>completed today</span></article><article class="stat"><small>FINISHED</small><b>${summary.completed}</b><span>routine${summary.completed===1?'':'s'}</span></article><article class="stat"><small>SKIPPED / DEFERRED</small><b>${summary.skipped+summary.deferred}</b><span>without template damage</span></article></div><div class="routine-list" style="margin-top:12px">${rows.length?rows.map(row=>renderRoutineCard(row)).join(''):'<div class="empty">🎀 No recurring routines are due today. Manual routines can be started from the template shelf.</div>'}</div></section>`;
}

function renderRoutineCard(row){
  const {template,instance,progress}=row,meta=daypartMeta(template.daypart),status=progress.status,nextStatus=['skipped','deferred'].includes(status)?'paused':status;
  return `<article class="routine-card"><div class="routine-title"><div class="routine-icon">${esc(template.icon)}</div><div><b>${esc(template.name)} <span class="status ${esc(status)}">${esc(status)}</span></b><small>${meta.icon} ${esc(meta.label)}${template.targetTime?` · ${esc(template.targetTime)}`:''} · ${esc(recurrenceLabel(template))}</small></div><span class="time-pill">${progress.done}/${progress.total}</span></div><div class="progress"><i style="width:${progress.percent}%"></i></div><div class="steps">${template.steps.length?template.steps.map(step=>`<div class="step ${instance?.stepStates?.[step.id]?'done':''}"><button type="button" data-step-toggle="${esc(template.id)}" data-step-id="${esc(step.id)}" ${status==='skipped'?'disabled':''}>${instance?.stepStates?.[step.id]?'✓':'○'}</button><span>${esc(step.label)}${step.optional?' · optional':''}</span><small>${step.minutes}m</small></div>`).join(''):'<div class="empty">No steps saved in this routine.</div>'}</div><div class="actions">${status==='completed'?'<span class="chip">✨ Finished today</span>':status==='skipped'||status==='deferred'?`<button class="btn" data-routine-reactivate="${esc(template.id)}">↩ Bring back today</button>`:`<button class="btn primary" data-routine-finish="${esc(template.id)}">✓ Finish today</button><button class="btn warn" data-routine-defer="${esc(template.id)}">↷ Defer today</button><button class="btn" data-routine-skip="${esc(template.id)}">Skip today</button>`}<button class="btn" data-routine-skip-tomorrow="${esc(template.id)}">Skip tomorrow</button></div><small style="display:block;color:var(--muted);font-size:8px;margin-top:5px">${nextStatus==='active'&&progress.done>0?'🌱 Partial progress counts.':''}</small></article>`;
}

function renderCreate(){
  return `<section class="card"><div class="head"><div><div class="ey">＋ NEW ROUTINE</div><h2>Build steps, not duplicate tasks</h2><p>Each line becomes a native routine step. Add “| minutes” if you want a step estimate.</p></div><div class="count">🎀</div></div><form id="routineForm"><div class="fields"><label class="field"><span>Name</span><input id="routineName" required placeholder="Night landing"></label><label class="field"><span>Icon</span><input id="routineIcon" maxlength="4" value="🌙"></label><label class="field"><span>Daypart</span><select id="routineDaypart">${ROUTINE_DAYPARTS.map(item=>`<option value="${item.value}">${item.icon} ${esc(item.label)}</option>`).join('')}</select></label><label class="field"><span>Target time · optional</span><input id="routineTime" type="time"></label><label class="field wide"><span>Repeats</span><select id="routineRepeat"><option value="daily">Every day</option><option value="weekdays">Weekdays</option><option value="weekends">Weekends</option><option value="selected">Selected days</option><option value="manual">Manual only</option></select></label><div class="field wide"><span>Selected days · used when repeat = Selected days</span><div class="days">${dayNames.map((name,index)=>`<label class="daycheck"><input type="checkbox" data-routine-day="${index}"> ${name}</label>`).join('')}</div></div><label class="field wide"><span>Steps · one per line</span><textarea id="routineSteps" required placeholder="Brush teeth | 3\nSkincare | 5\nFill water | 2"></textarea></label></div><div class="form-actions"><button class="btn primary">🎀 Create routine</button></div></form></section>`;
}

function renderTemplates(){
  const routines=state.life.routines.filter(item=>!item.archived);
  return `<section class="card"><div class="head"><div><div class="ey">🧺 ROUTINE SHELF</div><h2>Your reusable templates</h2><p>Manual routines live here until you start one. Recurring routines generate dated instances as needed.</p></div><div class="count">${routines.length}</div></div><div class="template-list">${routines.length?routines.map(item=>{const meta=daypartMeta(item.daypart);return `<article class="template-row"><div><b>${esc(item.icon)} ${esc(item.name)}</b><small>${meta.icon} ${esc(meta.label)} · ${esc(recurrenceLabel(item))} · ${item.steps.length} step${item.steps.length===1?'':'s'}</small></div><div class="actions" style="margin:0"><button class="btn tiny" data-routine-start="${esc(item.id)}">Start today</button><button class="btn tiny" data-routine-archive="${esc(item.id)}">Archive</button><button class="delete" data-routine-delete="${esc(item.id)}">×</button></div></article>`}).join(''):'<div class="empty">🎀 No routine templates yet.</div>'}</div></section>`;
}

function renderTomorrow(){
  const d=new Date();d.setDate(d.getDate()+1);const date=localDateKey(d),rows=routinesForDate(state.life.routines,state.life.routineInstances,date);
  return `<section class="card full"><div class="head"><div><div class="ey">🔮 TOMORROW</div><h2>Preview without touching today</h2><p>Tomorrow's instances are separate records. A “skip tomorrow” choice stays over there.</p></div><div class="count">${rows.length}</div></div><div class="template-list">${rows.length?rows.map(row=>`<article class="template-row"><div><b>${esc(row.template.icon)} ${esc(row.template.name)}</b><small>${row.progress.status==='skipped'?'⏭️ Already skipped for tomorrow':`${row.progress.total} steps · ${esc(recurrenceLabel(row.template))}`}</small></div><span class="status ${esc(row.progress.status)}">${esc(row.progress.status)}</span></article>`).join(''):'<div class="empty">🌱 Nothing scheduled for tomorrow.</div>'}</div></section>`;
}

function render(){app.innerHTML=`<main class="shell"><a class="back" href="./?v=3.0.0-alpha.10">← Back to KatOS V3</a><section class="hero"><div class="ey">🔁 KATOS V3 · ALPHA 10 · ROUTINES V3</div><h1>A rhythm is not a pile of tasks.</h1><p>Templates describe the routine. Dated instances record what actually happened. Partial progress counts, skipped days stay local to that day, and routine steps never raid Sweet To-Dos for ingredients.</p>${statusText?`<div class="note">${esc(statusText)}</div>`:''}</section><div class="grid">${renderToday()}${renderCreate()}${renderTemplates()}${renderTomorrow()}</div><div class="notice"><b>Routines V3 law:</b> completing, skipping, deferring, or partially doing today's routine changes today's instance only. The reusable template remains tomorrow-ready.</div></main>`;bind()}

function templateById(id){return state.life.routines.find(item=>item.id===String(id))}
function setInstances(next){state={...state,life:{...state.life,routineInstances:next}}}
function bind(){
  document.getElementById('routineForm')?.addEventListener('submit',event=>{event.preventDefault();const days=[...document.querySelectorAll('[data-routine-day]:checked')].map(input=>Number(input.dataset.routineDay));const input={name:document.getElementById('routineName').value,icon:document.getElementById('routineIcon').value,daypart:document.getElementById('routineDaypart').value,targetTime:document.getElementById('routineTime').value,recurrence:document.getElementById('routineRepeat').value,days,steps:parseSteps(document.getElementById('routineSteps').value)};state={...state,life:{...state.life,routines:addRoutine(state.life.routines,input)}};const created=state.life.routines.at(-1);activity('routine.created',created?.id,{name:created?.name});persist('Routine template created')});
  document.querySelectorAll('[data-step-toggle]').forEach(button=>button.addEventListener('click',()=>{const template=templateById(button.dataset.stepToggle);if(!template)return;setInstances(toggleRoutineStep(state.life.routineInstances,template,localDateKey(),button.dataset.stepId));activity('routine.step.toggled',template.id,{stepId:button.dataset.stepId,date:localDateKey()});persist('Routine step updated')}));
  document.querySelectorAll('[data-routine-finish]').forEach(button=>button.addEventListener('click',()=>{const template=templateById(button.dataset.routineFinish);setInstances(finishRoutineToday(state.life.routineInstances,template));activity('routine.completed',template.id,{date:localDateKey()});persist('Routine finished for today')}));
  document.querySelectorAll('[data-routine-skip]').forEach(button=>button.addEventListener('click',()=>{const template=templateById(button.dataset.routineSkip);setInstances(skipRoutineDay(state.life.routineInstances,template));activity('routine.skipped',template.id,{date:localDateKey()});persist('Routine skipped for today only')}));
  document.querySelectorAll('[data-routine-defer]').forEach(button=>button.addEventListener('click',()=>{const template=templateById(button.dataset.routineDefer);setInstances(deferRoutineDay(state.life.routineInstances,template));activity('routine.deferred',template.id,{date:localDateKey()});persist('Routine deferred for today')}));
  document.querySelectorAll('[data-routine-reactivate]').forEach(button=>button.addEventListener('click',()=>{const template=templateById(button.dataset.routineReactivate);setInstances(reactivateRoutineDay(state.life.routineInstances,template));activity('routine.reactivated',template.id,{date:localDateKey()});persist('Routine brought back today')}));
  document.querySelectorAll('[data-routine-skip-tomorrow]').forEach(button=>button.addEventListener('click',()=>{const template=templateById(button.dataset.routineSkipTomorrow);setInstances(skipRoutineTomorrow(state.life.routineInstances,template));activity('routine.skipped',template.id,{date:'tomorrow'});persist('Tomorrow skipped without touching the template')}));
  document.querySelectorAll('[data-routine-start]').forEach(button=>button.addEventListener('click',()=>{const template=templateById(button.dataset.routineStart),ensured=ensureRoutineInstance(state.life.routineInstances,template,localDateKey());setInstances(ensured.instances);activity('routine.started',template.id,{date:localDateKey()});persist('Routine started for today')}));
  document.querySelectorAll('[data-routine-archive]').forEach(button=>button.addEventListener('click',()=>{state={...state,life:{...state.life,routines:archiveRoutine(state.life.routines,button.dataset.routineArchive)}};activity('routine.archived',button.dataset.routineArchive);persist('Routine archived')}));
  document.querySelectorAll('[data-routine-delete]').forEach(button=>button.addEventListener('click',()=>{const id=button.dataset.routineDelete;state={...state,life:{...state.life,routines:deleteRoutine(state.life.routines,id),routineInstances:state.life.routineInstances.filter(item=>item.routineId!==id)}};activity('routine.deleted',id);persist('Routine and its dated instances removed')}));
}

render();
try{localStorage.setItem(V3_STORAGE_KEY,JSON.stringify({data:state}))}catch{}
