import assert from'node:assert/strict';
import{readFileSync}from'node:fs';
import{createWorkoutScaffold,feedMeRecommendation,goalZone,normalizeJourney,progressionFromFeedback,roadTo10kStatus}from'./journey.js';
import{processMochini}from'./mochini.js';
import{normalizeState}from'./store.js';

const state={nourish:{noms:{foods:[{id:'a',name:'Pasta',available:true,prepMinutes:25,effort:'medium'},{id:'b',name:'Yogurt',available:true,prepMinutes:0,effort:'low'}],journey:{mealPrep:[{id:'prep',name:'Ready burrito bowl',ready:true,prepMinutes:4,effort:'low'}]}}},movement:{roadTo10k:{goalSteps:10000,logs:[{date:'2026-08-26',steps:4200}]}}};
assert.equal(feedMeRecommendation(state,{lowEnergy:true}).name,'Yogurt');
assert.equal(feedMeRecommendation({...state,nourish:{noms:{...state.nourish.noms,foods:[]}}}).name,'Ready burrito bowl');
assert.deepEqual(goalZone(normalizeJourney({goalWeight:145,goalZone:5})),{center:145,low:140,high:150});
assert.deepEqual(roadTo10kStatus(state.movement,'2026-08-26'),{steps:4200,goal:10000,remaining:5800,percent:42});
assert.equal(createWorkoutScaffold([]).length,12);
assert.equal(progressionFromFeedback([{date:'2026-08-26',feedback:'tough'}]).action,'repeat-gentler');
assert.equal(progressionFromFeedback([{date:'2026-08-26',feedback:'easy'}]).action,'optional-advance');
assert.equal(progressionFromFeedback([]).action,'choose-baseline');
const normalized=normalizeState({unknownLegacyField:{keep:true},nourish:{noms:{foods:[]}},movement:{}});
assert.equal(normalized.unknownLegacyField.keep,true);
assert.deepEqual(normalized.nourish.noms.journey.mealPrep,[]);
assert.equal(normalized.nourish.noms.journey.goalWeight,145);
assert.equal(normalized.movement.roadTo10k.goalSteps,10000);
assert.deepEqual(normalized.movement.workoutPlan.months,[]);
const mochiniState={...state,life:{tasks:[],events:[],routines:[],routineInstances:[]},context:{energy:'okay',capacity:'normal'},v4:{archive:[],brainDump:[]},mochini:{conversation:[],life:{},lore:{}}};
assert.equal(processMochini(mochiniState,'Mochini, feed me').intent,'feed_me');
assert.match(processMochini(mochiniState,'what can I eat?').reply,/Yogurt/);
const nav=readFileSync(new URL('./parts/app-01.txt',import.meta.url),'utf8');
const views=readFileSync(new URL('./parts/app-06.txt',import.meta.url),'utf8');
const wellness=readFileSync(new URL('./parts/app-03.txt',import.meta.url),'utf8');
assert.doesNotMatch(nav,/\['journey','🍓','Food \+ Journey'\]/);
assert.doesNotMatch(views,/journey:foodJourneyView/);
assert.match(wellness,/nomsJourneyPanel/);
assert.match(wellness,/movementJourneyPanel/);
console.log('journey tests passed');
