import{ACTIVITIES,DIALOGUE,IDLE_EVENTS,OBSESSIONS}from'./mochini-dialogue.js';
const DAY=86400000,HOUR=3600000,MOODS=new Set(['content','happy','excited','sleepy','bored','proud','grumpy','chaotic','curious']);
const obj=v=>v&&typeof v==='object'&&!Array.isArray(v)?v:{};const num=(v,f)=>Number.isFinite(Number(v))?Number(v):f;export const clamp=(v,min=0,max=100)=>Math.min(max,Math.max(min,num(v,min)));export const dayKey=(v=new Date())=>{const d=new Date(v);return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};const weekKey=v=>{const d=new Date(v),start=new Date(d.getFullYear(),0,1);return`${d.getFullYear()}-W${String(Math.ceil((Math.floor((d-start)/DAY)+start.getDay()+1)/7)).padStart(2,'0')}`};
export const DEFAULT_LIFE={mood:'content',energy:70,affection:50,chaos:30,lastInteractionAt:null,lastSeenAt:null,lastEnergyAt:null,interactionsToday:0,ignoredCount:0,berriesFedToday:0,berriesFedTotal:0,currentActivity:null,activityChangedAt:null,currentObsession:null,obsessionStartedAt:null,currentLine:null,dialogueHistory:[],recentVisits:[],lastEvent:null,lastEventAt:null,lastPokeAt:null,pokeCount:0,dailyKey:null,weeklyKey:null,dailyFlags:{},weeklyFlags:{},permanentFlags:{}};
export function normalizeLife(value={},now=new Date()){const x=obj(value),today=dayKey(now),week=weekKey(now);return{...DEFAULT_LIFE,...x,mood:MOODS.has(x.mood)?x.mood:'content',energy:clamp(num(x.energy,70)),affection:clamp(num(x.affection,50)),chaos:clamp(num(x.chaos,30)),interactionsToday:x.dailyKey===today?Math.max(0,Math.floor(num(x.interactionsToday,0))):0,berriesFedToday:x.dailyKey===today?Math.max(0,Math.floor(num(x.berriesFedToday,0))):0,berriesFedTotal:Math.max(0,Math.floor(num(x.berriesFedTotal,0))),dialogueHistory:Array.isArray(x.dialogueHistory)?x.dialogueHistory.filter(v=>typeof v==='string').slice(-6):[],recentVisits:Array.isArray(x.recentVisits)?x.recentVisits.slice(-8):[],dailyKey:today,weeklyKey:week,dailyFlags:x.dailyKey===today?obj(x.dailyFlags):{},weeklyFlags:x.weeklyKey===week?obj(x.weeklyFlags):{},permanentFlags:obj(x.permanentFlags)}}
export function elapsedEnergy(value={},now=new Date()){const life=normalizeLife(value,now),previous=Date.parse(life.lastEnergyAt||life.lastSeenAt||'');if(!Number.isFinite(previous))return{...life,lastEnergyAt:now.toISOString()};const hours=Math.min(72,Math.max(0,now-previous)/HOUR),delta=hours>=7?Math.min(24,hours*1.8):-Math.min(18,hours*.45);return{...life,energy:clamp(life.energy+delta),lastEnergyAt:now.toISOString()}}
export function mood(value={},context={},now=new Date()){const l=normalizeLife(value,now),hour=now.getHours(),recent=now-Date.parse(l.lastInteractionAt||0)<2*HOUR;if((hour>=23||hour<6)&&l.energy<55)return'sleepy';if(context.recentCompletions>=2||l.dailyFlags.celebratedAllTasks)return'proud';if(l.chaos>=65&&context.randomEvent)return'chaotic';if(l.ignoredCount>=3||l.recentVisits.length>=4&&!recent)return'bored';if(l.interactionsToday>=4&&recent)return'happy';if(l.energy<25)return'sleepy';if(context.berryFed||context.funInteraction)return'excited';if(hour>=12&&hour<19)return'curious';return'content'}
const pick=(pool,l,random)=>{const usable=pool.filter(x=>!l.dialogueHistory.slice(-3).includes(x));return(usable.length?usable:pool)[Math.floor(random()*(usable.length||pool.length))]||'Tiny bean noises.'};export function dialogue(category,value={},random=Math.random,replace={}){const l=normalizeLife(value),template=pick(DIALOGUE[category]||DIALOGUE.idle,l,random),line=template.replace(/\{(\w+)\}/g,(_,k)=>replace[k]||l.currentObsession||'tiny mysteries');return{line,life:{...l,currentLine:line,dialogueHistory:[...l.dialogueHistory,line].slice(-6)}}}
export function refresh(value={},now=new Date(),random=Math.random){let l=elapsedEnergy(value,now),activityAge=now-Date.parse(l.activityChangedAt||0);if(!l.currentActivity||activityAge>=6*HOUR)l={...l,currentActivity:ACTIVITIES[Math.floor(random()*ACTIVITIES.length)%ACTIVITIES.length],activityChangedAt:now.toISOString()};const started=Date.parse(l.obsessionStartedAt||0),age=now-started;if(l.currentObsession&&Number.isFinite(started)&&age>=7*DAY)l={...l,currentObsession:null,obsessionStartedAt:null,dailyFlags:{...l.dailyFlags,obsessionConcluded:true}};else if(!l.currentObsession&&random()<.18){l={...l,currentObsession:OBSESSIONS[Math.floor(random()*OBSESSIONS.length)],obsessionStartedAt:now.toISOString()}};return l}
export function poke(value={},now=new Date(),random=Math.random){let l=normalizeLife(value,now);l={...l,lastPokeAt:now.toISOString(),pokeCount:l.pokeCount+1,lastInteractionAt:now.toISOString(),interactionsToday:l.interactionsToday+1,ignoredCount:0,energy:clamp(l.energy+1),affection:clamp(l.affection+1)};const p=dialogue('poke',l,()=>Math.min(.999,(l.pokeCount-1)/DIALOGUE.poke.length),{});return{life:{...p.life,mood:mood(p.life,{funInteraction:true},now)},line:p.line,local:true,requiresAI:false}}
export function berry(value={},now=new Date(),random=Math.random){let l=normalizeLife(value,now),accepted=l.berriesFedToday<6; l={...l,berriesFedToday:l.berriesFedToday+(accepted?1:0),berriesFedTotal:l.berriesFedTotal+(accepted?1:0),energy:clamp(l.energy+(accepted?(l.berriesFedToday>=3?1:5):0)),affection:clamp(l.affection+(accepted?(l.berriesFedToday>=3?1:3):0)),lastInteractionAt:now.toISOString(),interactionsToday:l.interactionsToday+1};const p=dialogue(accepted?'berries':'berryLimit',l,random);return{life:{...p.life,mood:mood(p.life,{berryFed:accepted},now)},line:p.line,accepted,local:true,requiresAI:false}}
export function react(value={},event,now=new Date(),random=Math.random){const category=event==='routineComplete'?'routineComplete':event==='taskComplete'?(value?.dailyFlags?.celebratedAllTasks?'allTasksComplete':'taskComplete'):'idle',p=dialogue(category,value,random);const l={...p.life,lastEvent:event,lastEventAt:now.toISOString(),dailyFlags:{...p.life.dailyFlags,[event==='routineComplete'?'celebratedRoutine':category==='allTasksComplete'?'celebratedAllTasks':'celebratedTask']:true},mood:mood(p.life,{recentCompletions:event==='taskComplete'?1:2},now)};return{life:l,line:p.line,local:true,requiresAI:false}}
export function idle(value={},now=new Date(),random=Math.random){const l=normalizeLife(value,now);if(now-Date.parse(l.lastEventAt||0)<12*HOUR||random()>=.08)return{life:l,event:null};const event=IDLE_EVENTS[Math.floor(random()*IDLE_EVENTS.length)%IDLE_EVENTS.length];return{life:{...l,lastEvent:event,lastEventAt:now.toISOString(),currentLine:event},event}}
export const requiresMochiniAI=intent=>['complex','unknown','planning','reasoning','emotional_support','open_conversation'].includes(typeof intent==='string'?intent:intent?.intent);export const getMochiniLifeDebugState=(value={},now=new Date())=>{const l=normalizeLife(value,now);return{...l,calculatedMood:mood(l,{},now),localOnly:true}}
