const obj=v=>v&&typeof v==='object'&&!Array.isArray(v)?v:{};const list=v=>Array.isArray(v)?v:[];const cats=['tinyFurniture','hats','spoons','stickers','mysteryBoxes','wormStuff','tinyBeverages','importantBeanDocuments','miscellaneousTinyObjects'];
export const DEFAULT_LORE={era:null,canonSeedVersion:0,storagePhysics:'questionable',hoard:Object.fromEntries(cats.map(k=>[k,[]])),specialPossessions:[],activeScandals:[],resolvedScandals:[],rivals:[],organizations:[{id:'bean-enterprises',name:'Bean Enterprises',status:'active',purpose:'unclear'}],permanentFlags:{},recentLoreLines:[],loreEvents:[]};
const CANON={tinyFurniture:[['chair-pink','tiny pink chair'],['chair-folding','suspicious folding chair']],spoons:[['spoon-important','Important Spoon'],['spoon-emergency','Emergency Spoon']],mysteryBoxes:[['box-important','box labeled IMPORTANT']],wormStuff:[['worm-logistics','Worm Logistics paperwork']]};
export function seedCanonicalLore(value={}){const l=normalizeMochiniLore(value);if(l.canonSeedVersion>=1)return l;const hoard={...l.hoard};for(const[k,items]of Object.entries(CANON))hoard[k]=[...hoard[k],...items.map(([id,name])=>({id,name}))];return{...l,canonSeedVersion:1,hoard,activeScandals:l.activeScandals.length?l.activeScandals:[{id:'alarm-coup',name:'Alarm Clock Coup',status:'active',summary:'The Clock attempted a hostile morning takeover.'}],resolvedScandals:l.resolvedScandals.length?l.resolvedScandals:[{id:'strawberry-incident',name:'The Strawberry Incident',status:'resolved'}]}}
export function normalizeMochiniLore(value={}){const x=obj(value),hoard={...DEFAULT_LORE.hoard,...obj(x.hoard)};return{...DEFAULT_LORE,...x,storagePhysics:'questionable',hoard:Object.fromEntries(cats.map(k=>[k,list(hoard[k]).filter(v=>v&&typeof v==='object').map(v=>({...v}))])),specialPossessions:list(x.specialPossessions).map(v=>({...obj(v)})),activeScandals:list(x.activeScandals).map(v=>({...obj(v)})),resolvedScandals:list(x.resolvedScandals).map(v=>({...obj(v)})),rivals:list(x.rivals).map(v=>({...obj(v)})),organizations:list(x.organizations).map(v=>({...obj(v)})),permanentFlags:obj(x.permanentFlags),recentLoreLines:list(x.recentLoreLines).filter(v=>typeof v==='string').slice(-6),loreEvents:list(x.loreEvents).map(v=>({...obj(v)})).slice(-50)}}
export function addHoardItem(value,category,item){const l=normalizeMochiniLore(value);if(!cats.includes(category)||!item?.id)return l;if(l.hoard[category].some(x=>x.id===item.id))return l;return{...l,hoard:{...l.hoard,[category]:[...l.hoard[category],{...item}]}}}
export function removeHoardItem(value,category,id){const l=normalizeMochiniLore(value);if(!cats.includes(category))return l;return{...l,hoard:{...l.hoard,[category]:l.hoard[category].filter(x=>x.id!==id)}}}
export function recordLoreEvent(value,event){const l=normalizeMochiniLore(value);return{...l,loreEvents:[...l.loreEvents,{...event,at:event.at||new Date().toISOString()}].slice(-50)}}
export function startScandal(value,scandal){const l=normalizeMochiniLore(value);if(!scandal?.id||l.activeScandals.some(x=>x.id===scandal.id))return l;return{...l,activeScandals:[...l.activeScandals,{...scandal,status:'active',startedAt:scandal.startedAt||new Date().toISOString()}]}}
export function resolveScandal(value,id,now=new Date()){const l=normalizeMochiniLore(value),found=l.activeScandals.find(x=>x.id===id);if(!found)return l;const resolved={...found,status:'resolved',resolvedAt:now.toISOString()};return{...l,activeScandals:l.activeScandals.filter(x=>x.id!==id),resolvedScandals:[...l.resolvedScandals,resolved]}}
export function setEra(value,era){return{...normalizeMochiniLore(value),era:era||null}}
export function getHoardSummary(value){const l=normalizeMochiniLore(value);return Object.entries(l.hoard).flatMap(([category,items])=>items.map(item=>({category,...item})))}
export function getLoreResponse(value,life={},question=''){const l=normalizeMochiniLore(value),q=String(question).toLowerCase();const all=getHoardSummary(l);if(/spoon/.test(q))return l.hoard.spoons.length?`The spoon collection contains ${l.hoard.spoons.length}. The situation is under control.`:'No spoons are currently documented. This is not an admission.';if(/chair|furniture|where did .*come from|where do you keep getting|who gave you/.test(q)){const items=l.hoard.tinyFurniture;if(!items.length)return'There is no furniture currently on the official record. Bean Enterprises may have paperwork.';return`I have ${items.length} furniture item${items.length===1?'':'s'}: ${items.map(x=>x.name||'unnamed chair').join(', ')}. Incorrect. There is vertical space.`}if(/what do you have in your corner|how much stuff|are you a hoarder/.test(q)){if(!all.length)return'Her corner is currently suspiciously tidy. The storage physics remain questionable.';return`My corner contains ${all.length} documented tiny object${all.length===1?'':'s'} across ${new Set(all.map(x=>x.category)).size} categories. This is an organized system.`}if(/bean enterprises/.test(q))return'Bean Enterprises provided it. That is all I am authorized to say.';if(/clock|alarm/.test(q))return'The Clock is an authoritarian concept. I remain professionally opposed.';if(/scandal|strawberr|hat black/.test(q)){const s=[...l.activeScandals,...l.resolvedScandals];if(!s.length)return'There are no scandals on the official record. The paperwork is unusually quiet.';return s.length===1?`${s[0].name}: ${s[0].mochiniStatement||s[0].summary||'The matter is under review.'}`:`The official record lists ${s.length} scandals. The spoon situation is under control.`}if(/box/.test(q)){const b=l.hoard.mysteryBoxes;if(!b.length)return'There are no mystery boxes currently on the record. This is temporary, probably.';return`There ${b.length===1?'is':'are'} ${b.length} mystery box${b.length===1?'':'es'}. Their contents are classified as mysterious.`}if(/worm/.test(q)&&/worm/i.test(life.currentObsession||''))return'The Worm Era is pending. The paperwork is moving slower than expected.';return''}
