import assert from'node:assert/strict';
import{movementLoggerPrefill,normalizeMovementRecipe,removeMovementRecipe,upsertMovementRecipe}from'./movement-recipes.js';
import{normalizeMovement}from'./journey.js';
import{readFileSync}from'node:fs';

let rows=[];
rows=upsertMovementRecipe(rows,{name:'Pilates reset',type:'Pilates',minutes:20,effort:'easy',instructions:'Roll down\nHundred',notes:'Gentle core',lowEnergyVersion:'Ten minutes of breathing + mobility'},{id:'recipe-1',now:'2026-08-26T00:00:00.000Z'});
assert.equal(rows.length,1);
assert.equal(rows[0].instructions,'Roll down\nHundred');
assert.equal(rows[0].lowEnergyVersion,'Ten minutes of breathing + mobility');
rows=upsertMovementRecipe(rows,{id:'recipe-1',name:'Pilates reset',type:'Pilates',minutes:25,effort:'medium'},{now:'2026-08-27T00:00:00.000Z'});
assert.equal(rows.length,1);
assert.equal(rows[0].minutes,25);
assert.equal(rows[0].instructions,'Roll down\nHundred');
assert.deepEqual(movementLoggerPrefill(rows[0]),{type:'pilates',minutes:25,effort:'medium'});
assert.deepEqual(movementLoggerPrefill({type:'Recovery',minutes:8,effort:'easy'}),{type:'stretch',minutes:8,effort:'easy'});
const persisted=normalizeMovement({routines:rows,unknownMovementField:{keep:true}});
assert.equal(persisted.routines[0].instructions,'Roll down\nHundred');
assert.deepEqual(persisted.unknownMovementField,{keep:true});
rows=upsertMovementRecipe(rows,{name:'Walk outside',type:'Walking',minutes:15,effort:'easy'},{id:'recipe-2'});
const afterDelete=removeMovementRecipe(rows,'recipe-1');
assert.equal(afterDelete.length,1);
assert.equal(afterDelete[0].id,'recipe-2');
const legacy=normalizeMovementRecipe({id:'legacy',name:'Walk',type:'Walking',minutes:'15',effort:'hard',instructions:'Outside'});
assert.equal(legacy.minutes,15);
assert.equal(legacy.type,'Walking');
const ui=readFileSync(new URL('./movement-recipes-ui.js',import.meta.url),'utf8');
assert.match(ui,/Add movement recipe/);
assert.match(ui,/name="instructions"/);
assert.match(ui,/name="lowEnergyVersion"/);
assert.match(ui,/movement-recipe-start/);
const loader=readFileSync(new URL('./loader.js',import.meta.url),'utf8');
assert.match(loader,/movement-recipes-ui\.js/);
console.log('movement recipe tests passed');
