const list=v=>Array.isArray(v)?v:(v&&typeof v==='object'?Object.values(v):[]);
const id=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function renderArchive({root,store}){
 let search='';
 const draw=()=>{const d=store.get(),items=list(d.archive),filtered=items.filter(x=>!search||JSON.stringify(x).toLowerCase().includes(search.toLowerCase()));root.innerHTML=`<section class="v17-card"><div class="v17-home-hero"><div class="v17-eyebrow">🍓 STRAWBERRY MOCHA • ARCHIVE</div><div class="v17-home-heading"><div><h1>🗄 Archive</h1><p>A quiet little shelf for things you're done with, but not ready to forget.</p></div><div class="v17-hero-berry">🗄️</div></div></div><section class="v17-card"><header><div><h2>🗂 Archived Items</h2><p class="v17-muted">${filtered.length} item${filtered.length===1?'':'s'}</p></div><input id="archiveSearch" placeholder="Search archive…" value="${esc(search)}"></header>${filtered.map(x=>`<article class="v17-win-row"><div class="v17-win-icon">${esc(x.emoji||'🗂️')}</div><div><b>${esc(x.title||x.name||x.text||'Archived item')}</b><small>${esc(x.type||'Archived')} ${x.date?'• '+esc(x.date):''}</small>${x.note?`<p>${esc(x.note)}</p>`:''}</div><button data-restore="${esc(x.id)}">↩ Restore</button><button data-delete="${esc(x.id)}">×</button></article>`).join('')||'<div class="v17-empty">🗄️ Nothing is archived yet.</div>'}</section></section>`;
 root.querySelector('#archiveSearch')?.addEventListener('input',e=>{search=e.target.value;draw()});root.querySelectorAll('[data-restore]').forEach(b=>b.onclick=()=>{const key=b.dataset.restore;store.update(s=>{const a=list(s.archive),item=a.find(x=>String(x.id)===String(key));if(!item)return s;const target=item.sourceKey||'tasks';const copy={...item};delete copy.sourceKey;delete copy.id;return {...s,archive:a.filter(x=>String(x.id)!==String(key)),[target]:[...list(s[target]),{...copy,id:id()}]}})});root.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{const key=b.dataset.delete;store.update(s=>({...s,archive:list(s.archive).filter(x=>String(x.id)!==String(key))}))});
 };store.subscribe(draw);draw();
}
export{renderArchive};