import{CATCH_ALL_DESTINATIONS,catchAllItems,routeCatchAllCapture,sortedCaptures,undoCatchAllRoute}from'../app/catch-all.js?v=22.2.0-20260818';

const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const makeId=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8);
const list=value=>Array.isArray(value)?value:(value&&typeof value==='object'?Object.values(value):[]);
const titleFor=text=>String(text||'').trim().replace(/\s+/g,' ').slice(0,64)||'Brain note';
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const isBrainNote=note=>note?.source!=='catch-all'&&!['inbox','sorted'].includes(note?.captureStatus);

const css=`.sm-brain-layout{display:grid;gap:14px}.sm-inbox-head,.sm-note-head{display:flex;justify-content:space-between;align-items:flex-start;gap:12px}.sm-inbox-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin-top:12px}.sm-inbox-card{padding:14px;border:1px solid #ead6de;border-radius:18px;background:linear-gradient(145deg,#fff,#fff8fb)}.sm-inbox-card h3{margin:0 0 7px}.sm-inbox-card p{color:var(--v21-muted,#9f8179);line-height:1.45;margin:0}.sm-inbox-card footer{display:flex;justify-content:space-between;align-items:center;gap:8px;margin-top:12px}.sm-sorter{margin-top:12px;padding:14px;border:2px dashed #e8b4c8;border-radius:20px;background:linear-gradient(145deg,#fff2f7,#fffdfb)}.sm-sorter-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.sm-sorter label{display:grid;gap:5px;font-size:11px;font-weight:900;color:#a36b7b}.sm-sorter input,.sm-sorter select,.sm-sorter textarea{width:100%;min-height:42px;padding:9px 10px;border:1px solid #e8bdd0;border-radius:12px;background:#fff;color:#674941}.sm-sorter textarea{min-height:76px;resize:vertical}.sm-sorter-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:10px}.sm-sorted-list{display:grid;gap:8px;margin-top:10px}.sm-sorted-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;align-items:center;padding:10px 12px;border:1px solid #e5dfdc;border-radius:15px;background:#fbfaf8}.sm-sorted-row small{display:block;color:#9f8179;margin-top:3px}.sm-note-layout{display:grid;grid-template-columns:minmax(300px,.9fr) minmax(0,1.1fr);gap:14px;align-items:start}.sm-note-compose{position:sticky;top:18px;padding:14px;border:1px solid #efd6df;border-radius:20px;background:linear-gradient(145deg,#fff6fa,#fffdfb)}.sm-note-compose textarea{width:100%;min-height:240px;padding:13px;resize:vertical}.sm-note-list{display:grid;gap:9px}.sm-note-card{padding:13px;border:1px solid #ead6de;border-radius:17px;background:#fffafc}.sm-note-card b,.sm-note-card small{display:block}.sm-note-card small{margin-top:5px;color:#9f8179}.sm-note-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:9px}@media(max-width:800px){.sm-inbox-grid{grid-template-columns:1fr}.sm-note-layout{grid-template-columns:1fr}.sm-note-compose{position:static}.sm-sorter-grid{grid-template-columns:1fr}}`;
function install(){if(document.getElementById('sm-brain-inbox-style'))return;const style=document.createElement('style');style.id='sm-brain-inbox-style';style.textContent=css;document.head.appendChild(style)}

function sortFields(destination,capture){
 const title=esc(capture.title||capture.text||'');
 if(destination==='task')return `<div class="sm-sorter-grid"><label>Task<input name="text" value="${title}"></label><label>Date<input name="date" type="date" value="${today()}"></label><label>Category<input name="category" placeholder="Optional"></label><label>Effort<select name="effort"><option value="">Flexible</option><option>Low</option><option>Medium</option><option>High</option></select></label><label>Minutes<input name="durationMin" type="number" min="0" placeholder="Optional"></label></div>`;
 if(destination==='event')return `<div class="sm-sorter-grid"><label>Event<input name="title" value="${title}"></label><label>Date<input name="date" type="date" value="${today()}"></label><label>Start<input name="start" type="time"></label><label>End<input name="end" type="time"></label></div><label>Notes<textarea name="notes">${esc(capture.text||'')}</textarea></label>`;
 if(destination==='nom')return `<div class="sm-sorter-grid"><label>Nom name<input name="name" value="${title}"></label><label>Type<input name="type" placeholder="Meal, snack…"></label><label>Effort<select name="effort"><option value="">Any</option><option value="no-prep">No prep</option><option value="easy">Easy</option><option value="medium">Medium</option><option value="involved">Involved</option></select></label></div><label>Notes<textarea name="notes">${esc(capture.text||'')}</textarea></label>`;
 if(destination==='grocery')return `<div class="sm-sorter-grid"><label>Grocery item<input name="name" value="${title}"></label><label>Quantity<input name="quantity" placeholder="Optional"></label></div><label>Notes<textarea name="notes">${esc(capture.text||'')}</textarea></label>`;
 if(destination==='project')return `<div class="sm-sorter-grid"><label>Project name<input name="name" value="${title}"></label><label>Next step<input name="nextStep" placeholder="One concrete next step"></label></div><label>Goal<textarea name="goal">${esc(capture.text||'')}</textarea></label>`;
 if(destination==='school_task')return `<div class="sm-sorter-grid"><label>School task<input name="name" value="${title}"></label><label>Due<input name="due" type="date"></label><label>Course<input name="course" placeholder="Optional"></label></div>`;
 if(destination==='reminder')return `<div class="sm-sorter-grid"><label>Reminder<input name="title" value="${title}"></label><label>Date<input name="date" type="date"></label><label>Time<input name="time" type="time"></label><label>Repeat<select name="repeat"><option value="">Doesn't repeat</option><option>Daily</option><option>Weekly</option><option>Monthly</option></select></label></div>`;
 if(destination==='lab_observation')return `<label>Observation<textarea name="text">${esc(capture.text||'')}</textarea></label><label>Tags<input name="tags" placeholder="Focus, Planning, Routines"></label>`;
 return `<label>Brain note<textarea name="text">${esc(capture.text||'')}</textarea></label>`;
}

function formInput(form){const data=new FormData(form),input=Object.fromEntries(data.entries());if(input.tags)input.tags=String(input.tags).split(',').map(value=>value.trim()).filter(Boolean);return input}

function renderBrain({root,store}){
 install();let sortingId=null,destination='task',editingNote=null,notice='';
 const draw=()=>{
  const state=store.get(),inbox=catchAllItems(state),sorted=sortedCaptures(state,12),notes=list(state.brainNotes).filter(isBrainNote),capture=sortingId?inbox.find(item=>String(item.id)===String(sortingId)):null,activeNote=editingNote?notes.find(item=>String(item.id)===String(editingNote)):null;
  root.innerHTML=`<div class="sm-polished sm-brain-layout"><section class="v17-card"><div class="v17-home-hero"><div class="v17-eyebrow">🍓 KATOS • BRAIN + INBOX</div><div class="v17-home-heading"><div><h1>🧠 Brain & Catch-All</h1><p>Capture first. Decide what it is later. Then route it where it actually belongs. ♡</p></div><div class="v17-hero-berry">🧺</div></div></div></section>
  <section class="v17-card"><div class="sm-inbox-head"><div><small>🧺 CATCH-ALL INBOX</small><h2>${inbox.length} waiting to be sorted</h2><p class="v17-muted">Nothing moves until you choose a destination and save it.</p></div><span class="v17-pill">Unsorted ${inbox.length}</span></div>${notice?`<p class="sm-noms-note" role="status">${esc(notice)}</p>`:''}<div class="sm-inbox-grid">${inbox.map(item=>`<article class="sm-inbox-card"><h3>${esc(item.title||'Quick capture')}</h3><p>${esc(item.text||'')}</p><footer><small>${item.createdAt?new Date(item.createdAt).toLocaleDateString():''}</small><button class="primary" data-sort="${esc(item.id)}">Sort →</button></footer></article>`).join('')||'<div class="v17-empty">✨ Catch-All is clear. Every loose thought has a home.</div>'}</div>${capture?`<form class="sm-sorter" data-sort-form><input type="hidden" name="captureId" value="${esc(capture.id)}"><header><div><small>SORTING</small><h3>${esc(capture.title)}</h3></div><button type="button" data-cancel-sort>×</button></header><label>Send to<select name="destination" data-destination>${Object.entries(CATCH_ALL_DESTINATIONS).map(([key,label])=>`<option value="${key}" ${key===destination?'selected':''}>${esc(label)}</option>`).join('')}</select></label><div data-sort-fields>${sortFields(destination,capture)}</div><div class="sm-sorter-actions"><button type="button" data-cancel-sort>Cancel</button><button class="primary" type="submit">Sort into ${esc(CATCH_ALL_DESTINATIONS[destination])}</button></div></form>`:''}</section>
  <details class="v17-card" ${sorted.length?'':'open'}><summary>📦 Recently sorted · ${sorted.length}</summary><div class="sm-sorted-list">${sorted.map(item=>`<div class="sm-sorted-row"><span><b>${esc(item.title||'Capture')}</b><small>→ ${esc(CATCH_ALL_DESTINATIONS[item.routedTo?.type]||item.routedTo?.type||'KatOS')} ${item.sortedAt?`• ${new Date(item.sortedAt).toLocaleDateString()}`:''}</small></span><button data-undo-sort="${esc(item.id)}">Undo sort</button></div>`).join('')||'<div class="v17-empty">Nothing sorted yet.</div>'}</div></details>
  <section class="v17-card"><div class="sm-note-head"><div><small>📝 BRAIN NOTES</small><h2>Notes that are meant to stay notes</h2><p class="v17-muted">This is separate from Catch-All now. Older notes can be moved into the inbox manually if they were really captures.</p></div><span class="v17-pill">${notes.length} notes</span></div><div class="sm-note-layout"><div class="sm-note-compose"><textarea data-note-text placeholder="Write a note that belongs in Brain…">${esc(activeNote?.text||'')}</textarea><div class="sm-note-actions"><button class="primary" data-save-note>${activeNote?'Save changes':'Save Brain note'}</button>${activeNote?'<button data-new-note>New note</button>':''}</div></div><div class="sm-note-list">${[...notes].sort((a,b)=>String(b.updatedAt||b.createdAt||'').localeCompare(String(a.updatedAt||a.createdAt||''))).map(note=>`<article class="sm-note-card"><b>${esc(note.title||'Brain note')}</b><small>${esc(note.text||'')}</small><div class="sm-note-actions"><button data-note-to-inbox="${esc(note.id)}">🧺 Move to Catch-All</button><button data-edit-note="${esc(note.id)}">Edit</button><button data-archive-note="${esc(note.id)}">Archive</button></div></article>`).join('')||'<div class="v17-empty">No Brain notes yet.</div>'}</div></div></section></div>`;
  root.querySelectorAll('[data-sort]').forEach(button=>button.onclick=()=>{sortingId=button.dataset.sort;destination='task';notice='';draw()});
  root.querySelectorAll('[data-cancel-sort]').forEach(button=>button.onclick=()=>{sortingId=null;notice='';draw()});
  root.querySelector('[data-destination]')?.addEventListener('change',event=>{destination=event.target.value;draw()});
  root.querySelector('[data-sort-form]')?.addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget,input=formInput(form),target=input.destination;delete input.destination;delete input.captureId;const result=routeCatchAllCapture(store,capture.id,target,input);if(result.ok){notice=`Sorted into ${CATCH_ALL_DESTINATIONS[target]}. 🍓`;sortingId=null}else notice=result.error;draw()});
  root.querySelectorAll('[data-undo-sort]').forEach(button=>button.onclick=()=>{const item=sorted.find(capture=>String(capture.id)===String(button.dataset.undoSort));if(!item)return;if(!confirm(`Undo this sort? KatOS will remove the exact ${CATCH_ALL_DESTINATIONS[item.routedTo?.type]||'destination item'} it created and return the capture to the inbox.`))return;const result=undoCatchAllRoute(store,item.id);notice=result.ok?'Sort undone. The original capture is back in Catch-All. 🌷':result.error;draw()});
  root.querySelectorAll('[data-note-to-inbox]').forEach(button=>button.onclick=()=>{const id=String(button.dataset.noteToInbox),note=notes.find(item=>String(item.id)===id);if(!note)return;if(!confirm(`Move “${note.title||'this note'}” into Catch-All so it can be sorted?`))return;store.update(current=>({...current,brainNotes:list(current.brainNotes).map(item=>String(item.id)===id?{...item,source:'catch-all',captureStatus:'inbox',updatedAt:new Date().toISOString()}:item)}));if(editingNote===id)editingNote=null;notice='Moved into Catch-All. 🧺'});
  root.querySelector('[data-save-note]')?.addEventListener('click',()=>{const text=root.querySelector('[data-note-text]').value.trim();if(!text)return;const now=new Date().toISOString();store.update(current=>{const entries=list(current.brainNotes),item={id:activeNote?.id||makeId(),title:activeNote?.title||titleFor(text),text,source:'brain',createdAt:activeNote?.createdAt||now,updatedAt:now};return{...current,brainNotes:activeNote?entries.map(note=>String(note.id)===String(activeNote.id)?item:note):[...entries,item]}});editingNote=null});
  root.querySelector('[data-new-note]')?.addEventListener('click',()=>{editingNote=null;draw()});
  root.querySelectorAll('[data-edit-note]').forEach(button=>button.onclick=()=>{editingNote=button.dataset.editNote;draw()});
  root.querySelectorAll('[data-archive-note]').forEach(button=>button.onclick=()=>{const id=String(button.dataset.archiveNote);store.update(current=>{const entries=list(current.brainNotes),item=entries.find(note=>String(note.id)===id);if(!item)return current;return{...current,brainNotes:entries.filter(note=>String(note.id)!==id),archive:[...list(current.archive),{...item,type:'Brain note',sourceKey:'brainNotes',archivedAt:new Date().toISOString()}]}});if(editingNote===id)editingNote=null});
 };
 store.subscribe(draw);draw();
}
export{renderBrain};
