const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const makeId=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8);
const list=v=>Array.isArray(v)?v:(v&&typeof v==='object'?Object.values(v):[]);
function renderBrain({root,store}){
 let adding=false,editing=null;
 const draw=()=>{const d=store.get(),notes=list(d.brainNotes),brainText=typeof d.brain==='string'?d.brain:'';const edit=editing?notes.find(x=>String(x.id)===String(editing)):null;
 root.innerHTML=`<section class="v17-card"><div class="v17-home-hero"><div class="v17-eyebrow">🍓 STRAWBERRY MOCHA • BRAIN</div><div class="v17-home-heading"><div><h1>🧠 Brain Dump</h1><p>Get it out of your head. Sort it later. ♡</p></div><div class="v17-hero-berry">🧠</div></div></div><section class="v17-card"><header><div><h2>📝 Quick Capture</h2><p class="v17-muted">A safe place for thoughts, ideas, reminders, and random brain tabs.</p></div><button class="primary" id="saveBrain">♡ Save brain dump</button></header><textarea id="brainText" style="min-height:220px" placeholder="Dump it all here...">${esc(brainText)}</textarea></section><section class="v17-card"><header><div><h2>📚 Brain Notes</h2><p class="v17-muted">Turn important thoughts into little notes you can find again.</p></div><button class="primary" id="toggleNote">${adding?'× Close':'＋ Note'}</button></header>${notes.map(n=>`<article class="v17-brain-note"><div><b>${esc(n.title||'Untitled note')}</b><small>${esc(n.text||'')}</small></div><button data-edit="${esc(n.id)}">✎</button><button data-delete="${esc(n.id)}">×</button></article>`).join('')||'<div class="v17-empty">🌱 No saved notes yet.</div>'}${(adding||edit)?`<div class="v17-school-form"><input id="noteTitle" placeholder="Note title" value="${esc(edit?.title||'')}"><textarea id="noteText" placeholder="Write it down...">${esc(edit?.text||'')}</textarea><button class="primary" id="saveNote">♡ ${edit?'Save changes':'Save note'}</button></div>`:''}</section></section>`;
 root.querySelector('#saveBrain')?.addEventListener('click',()=>store.update(x=>({...x,brain:root.querySelector('#brainText').value})));
 root.querySelector('#toggleNote')?.addEventListener('click',()=>{adding=!adding;editing=null;draw()});root.querySelector('#saveNote')?.addEventListener('click',()=>{const title=root.querySelector('#noteTitle').value.trim()||'Untitled note',text=root.querySelector('#noteText').value;if(!text.trim())return;store.update(x=>({...x,brainNotes:edit?notes.map(n=>String(n.id)===String(edit.id)?{...n,title,text}:n):[...notes,{id:makeId(),title,text,createdAt:new Date().toISOString()}]}));adding=false;editing=null});root.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{editing=b.dataset.edit;adding=false;draw()});root.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{const id=b.dataset.delete;store.update(x=>({...x,brainNotes:list(x.brainNotes).filter(n=>String(n.id)!==id)}))});
 };store.subscribe(draw);draw();
}
export{renderBrain};