const q=(root,sel)=>root?.querySelector?.(sel)||null;

const css=`
.sm-course-corner-backdrop{position:fixed;inset:0;z-index:970;display:flex;align-items:center;justify-content:center;padding:24px;background:rgba(103,73,65,.26);backdrop-filter:blur(7px)}
.sm-course-corner{width:min(900px,100%);max-height:min(90vh,920px);overflow:auto;margin:0!important;padding:0!important;background:linear-gradient(150deg,#fffafd 0%,#fffdf9 52%,#f5faef 100%)!important;border:2px solid #efc3d5!important;border-radius:34px!important;box-shadow:0 30px 90px rgba(103,73,65,.28)!important;color:#674941}
.sm-course-corner>.sm-row:first-child{position:sticky;top:0;z-index:4;padding:20px 22px 17px;margin:0;background:linear-gradient(135deg,rgba(255,239,247,.97),rgba(255,253,250,.97) 62%,rgba(240,248,235,.97));border-bottom:1px solid #efd7df;backdrop-filter:blur(14px)}
.sm-course-corner>.sm-row:first-child h2{font-size:28px!important;line-height:1.08;margin:4px 0 5px!important;color:#5f4037!important}.sm-course-corner>.sm-row:first-child .sm-muted{font-size:0}.sm-course-corner>.sm-row:first-child .sm-muted:after{content:'📚 Study Nook • Course Corner';font-size:10px;font-weight:950;letter-spacing:.12em;text-transform:uppercase;color:#bd6b87}
.sm-course-corner #closeCourse{width:38px;height:38px;padding:0;border-radius:50%;font-size:20px;background:#fff;border:1px solid #e9ccd6;color:#8f6570}
.sm-cc-body{padding:20px 22px 8px}.sm-cc-section{margin:0 0 19px}.sm-cc-section-head{display:flex;align-items:center;gap:8px;margin:0 0 9px}.sm-cc-section-head small{font-size:10px;font-weight:950;letter-spacing:.12em;color:#bd6b87;text-transform:uppercase}.sm-cc-section-head:after{content:'';height:1px;flex:1;background:linear-gradient(90deg,#efcad7,transparent)}
.sm-cc-overview{display:grid;grid-template-columns:1fr 1fr 1fr 1fr;gap:10px}.sm-cc-field{display:grid;gap:6px;min-width:0;padding:11px 12px;border:1px solid #edd8df;border-radius:18px;background:rgba(255,255,255,.82);color:#674941}.sm-cc-field.wide{grid-column:span 2}.sm-cc-field>span{font-size:9px;font-weight:950;letter-spacing:.055em;text-transform:uppercase;color:#b66d86}.sm-cc-field .sm-input,.sm-cc-field .sm-select,.sm-cc-field .sm-area{width:100%;box-sizing:border-box;margin:0;border-radius:12px;background:#fff}.sm-cc-field .sm-area{min-height:84px}
.sm-cc-statusbar{display:flex;align-items:center;gap:9px}.sm-cc-statusbar input{width:78px}.sm-cc-mini-bar{height:9px;flex:1;min-width:48px;border-radius:99px;background:#f0e4e7;overflow:hidden}.sm-cc-mini-bar i{display:block;height:100%;background:linear-gradient(90deg,#e99ab7,#cfe0b8);border-radius:99px}.sm-cc-badge{display:inline-flex;align-items:center;width:max-content;padding:5px 8px;border-radius:999px;background:#fff0f5;color:#aa617d;font-size:9px;font-weight:900}
.sm-cc-action{display:grid;grid-template-columns:1fr 1fr;gap:10px;padding:14px;border:1px solid #ead4dc;border-radius:22px;background:linear-gradient(135deg,#fff1f7,#fffdf9 55%,#f1f8ec)}.sm-cc-action .sm-cc-field{background:rgba(255,255,255,.9)}.sm-cc-task-wrap{display:grid;gap:8px}.sm-cc-task-wrap #sendCourseTask{justify-self:start;border-radius:14px;padding:10px 15px;box-shadow:0 8px 20px rgba(219,132,165,.16)}
.sm-cc-reflect{display:grid;grid-template-columns:1fr 1fr;gap:10px}.sm-cc-reflect .sm-cc-field.full{grid-column:1/-1}.sm-cc-reflect .sm-area{min-height:92px}.sm-cc-reflect .full .sm-area{min-height:112px}
.sm-cc-footer{position:sticky;bottom:0;z-index:4;display:flex!important;justify-content:space-between!important;gap:10px!important;margin:0!important;padding:14px 22px!important;background:linear-gradient(90deg,rgba(255,249,252,.97),rgba(250,252,246,.97));border-top:1px solid #efd7df;backdrop-filter:blur(14px)}.sm-cc-footer .sm-btn{min-width:145px;border-radius:15px;padding:11px 15px}
.sm-course-corner>h3,.sm-course-corner>.sm-two,.sm-course-corner>.sm-form,.sm-course-corner>.sm-reflect{display:none!important}
@media(max-width:800px){.sm-course-corner-backdrop{padding:12px}.sm-course-corner{max-height:92vh;border-radius:28px!important}.sm-cc-overview{grid-template-columns:1fr 1fr}.sm-cc-field.wide{grid-column:span 1}.sm-cc-action,.sm-cc-reflect{grid-template-columns:1fr}.sm-cc-reflect .sm-cc-field.full{grid-column:auto}.sm-cc-body{padding:16px 18px 6px}.sm-course-corner>.sm-row:first-child{padding:17px 18px 15px}.sm-cc-footer{padding:13px 18px!important}}
@media(max-width:520px){.sm-cc-overview{grid-template-columns:1fr}.sm-course-corner>.sm-row:first-child h2{font-size:23px!important}.sm-cc-footer .sm-btn{min-width:0;flex:1}.sm-cc-statusbar{align-items:stretch;flex-direction:column}.sm-cc-statusbar input{width:100%}}
`;

function style(){if(document.getElementById('sm-course-corner-style'))return;const el=document.createElement('style');el.id='sm-course-corner-style';el.textContent=css;document.head.appendChild(el)}
function field(title,node,{wide=false,full=false,badge=''}={}){if(!node)return null;const label=document.createElement('label');label.className=`sm-cc-field${wide?' wide':''}${full?' full':''}`;const head=document.createElement('span');head.textContent=title;label.appendChild(head);if(badge){const b=document.createElement('small');b.className='sm-cc-badge';b.textContent=badge;label.appendChild(b)}label.appendChild(node);return label}
function section(icon,title,cls){const sec=document.createElement('section');sec.className='sm-cc-section';sec.innerHTML=`<div class="sm-cc-section-head"><span>${icon}</span><small>${title}</small></div>`;const body=document.createElement('div');body.className=cls;sec.appendChild(body);return{sec,body}}
function textareaFrom(root,id){return q(root,id)}

function transform(root){
 const close=q(root,'#closeCourse');if(!close)return;const card=close.closest('.sm-card');if(!card||card.classList.contains('sm-course-corner'))return;
 const backdrop=document.createElement('div');backdrop.className='sm-course-corner-backdrop';card.before(backdrop);backdrop.appendChild(card);card.classList.add('sm-course-corner');
 const footer=q(card,':scope > .sm-row:last-child');if(footer&&q(footer,'#saveCourse'))footer.classList.add('sm-cc-footer');
 const body=document.createElement('div');body.className='sm-cc-body';const header=q(card,':scope > .sm-row:first-child');header?.insertAdjacentElement('afterend',body);
 const overview=section('📌','Overview','sm-cc-overview');body.appendChild(overview.sec);
 const progress=q(card,'#editProgress'),status=q(card,'#editStatus'),objective=q(card,'#courseObjective'),milestone=q(card,'#courseMilestone'),deadline=q(card,'#courseDeadline'),target=q(card,'#courseTarget');
 if(progress){const label=document.createElement('label');label.className='sm-cc-field';label.innerHTML='<span>Progress</span>';const statusbar=document.createElement('div');statusbar.className='sm-cc-statusbar';const old=Number(progress.value)||0;statusbar.appendChild(progress);const mini=document.createElement('div');mini.className='sm-cc-mini-bar';mini.innerHTML=`<i style="width:${Math.max(0,Math.min(100,old))}%"></i>`;statusbar.appendChild(mini);label.appendChild(statusbar);progress.addEventListener('input',()=>{const i=q(label,'.sm-cc-mini-bar i');if(i)i.style.width=`${Math.max(0,Math.min(100,Number(progress.value)||0))}%`});overview.body.appendChild(label)}
 const entries=[field('Status',status),field('Official Deadline',deadline),field('My Target Date',target),field('🎯 Current Objective',objective,{wide:true}),field('🌱 Next Milestone',milestone,{wide:true})];entries.filter(Boolean).forEach(el=>overview.body.appendChild(el));
 const action=section('✨','Next Move','sm-cc-action');body.appendChild(action.sec);const done=q(card,'#courseDoneWhen'),next=q(card,'#courseNextTask'),send=q(card,'#sendCourseTask');const doneField=field('✅ Done When…',done);if(doneField)action.body.appendChild(doneField);if(next){const wrap=document.createElement('div');wrap.className='sm-cc-task-wrap';const taskField=field('📝 Assignment / Next Task',next);if(taskField)wrap.appendChild(taskField);if(send)wrap.appendChild(send);action.body.appendChild(wrap)}
 const reflect=section('💭','Reflection','sm-cc-reflect');body.appendChild(reflect.sec);const reflectionFields=[['📚 What did I learn?','#rLearn'],['❔ What was confusing?','#rHard'],['🌟 What am I proud of?','#rProud'],['🌱 What should I work on?','#rWork'],['📝 Overall Thoughts','#rOverall']];reflectionFields.forEach(([title,sel],index)=>{const node=textareaFrom(card,sel);const f=field(title,node,{full:index===4});if(f)reflect.body.appendChild(f)});
 if(footer)card.appendChild(footer);
 backdrop.addEventListener('click',e=>{if(e.target===backdrop)close.dispatchEvent(new MouseEvent('click',{bubbles:true}))});
}

export function installCourseCorner({root}){style();let queued=false;const run=()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;transform(root)})};new MutationObserver(run).observe(root,{childList:true,subtree:true});run()}
