import{completeTask}from'../app/task-actions.js?v=22.1.27-20260818';

const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const localDateKey=()=>{const date=new Date();return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`};
const title=task=>task?.text||task?.title||'Untitled task';
const isOpen=task=>task&&!task.done&&!task.parked&&!task.archived;
const isForToday=(task,day)=>!task.date||task.date===day;
const routineProgress=(routine,day)=>{const steps=Array.isArray(routine?.steps)?routine.steps:[],checks=routine?.checks?.[day]||{},done=steps.filter((_,index)=>checks[index]===true||checks[index]==='complete').length;return{done,total:steps.length}};

const subscribed=new WeakSet();

function renderDaily({root,store,router}){
 const draw=()=>{
  const data=store.get()||{},day=localDateKey(),open=(data.tasks||[]).filter(task=>isOpen(task)&&isForToday(task,day)),protectedTasks=open.filter(task=>task.isProtected),regular=open.filter(task=>!task.isProtected),now=protectedTasks[0]||regular[0]||null,next=(protectedTasks[0]&&regular[0])?regular[0]:open.find(task=>String(task.id)!==String(now?.id))||null;
  const routines=(data.routines||[]).filter(routine=>routine.repeat!=='manual'||routine.triggerType).slice(0,2);
  const guided=(data.guidedRoutines||[]).slice(0,1);
  const routineCards=[...routines.map(routine=>({name:routine.name||'Routine',meta:(()=>{const progress=routineProgress(routine,day);return progress.total?`${progress.done}/${progress.total} steps today`:'Ready when you are'})()})),...guided.map(routine=>({name:routine.name||'Guided routine',meta:`${(routine.taskIds||[]).length} tiny steps`}))].slice(0,2);
  const pings=(data.reminders||[]).filter(item=>!item.done&&!item.completed).filter(item=>!item.date||item.date===day).length;
  const events=(data.events||[]).filter(event=>event.date===day).sort((a,b)=>String(a.start||'').localeCompare(String(b.start||'')));
  const mirrorRow=(label,task,kind)=>task?`<div class="v5-mirror-row"><small>${label}</small><span><b>${esc(title(task))}</b><small>${task.isProtected?'Protected commitment':task.durationMin?`${task.durationMin} min`:'A tiny next move is enough'}</small></span><button type="button" data-complete="${esc(task.id)}" aria-label="Complete ${esc(title(task))}">✓</button></div>`:`<div class="v5-mirror-row"><small>${label}</small><span><b>${kind==='now'?'Choose gently':'Nothing queued yet'}</b><small>${kind==='now'?'Open Tasks or ask Mochini for a next move.':'That is completely okay.'}</small></span><button type="button" data-go="tasks" aria-label="Open Tasks">→</button></div>`;
  root.innerHTML=`<main class="v5-daily-flow"><section class="v5-daily-hero"><div><p class="v5-daily-kicker">KATOS V5 • DAILY FLOW</p><h1>Your day, Kat</h1><p>One gentle starting point—then only open the room you need.</p></div><div class="v5-daily-hero-icon">🪞</div></section><section class="v5-daily-grid"><section class="v5-daily-card v5-mirror"><h2>Now & Next</h2><p>Protected things stay visible. Everything else can wait its turn.</p><div class="v5-mirror-list">${mirrorRow('NOW',now,'now')}${mirrorRow('NEXT',next,'next')}</div><div class="v5-room-actions"><button class="primary" type="button" data-go="tasks">Open tasks</button><button type="button" data-go="mochini">Ask Mochini</button></div></section><section class="v5-daily-card v5-protected"><h2>Protected today</h2><p>Keep only the commitments that should not get lost.</p><div class="v5-protected-list">${protectedTasks.slice(0,3).map(task=>`<div class="v5-protected-item"><span class="v5-protected-dot">🛡</span><span>${esc(title(task))}</span></div>`).join('')||'<div class="v5-empty">No protected task set. You can make one in Tasks whenever something truly matters.</div>'}</div><div class="v5-room-actions"><button type="button" data-go="tasks">Edit protection</button></div></section></section><section class="v5-daily-grid"><section class="v5-daily-card v5-routine-card"><h2>Routine garden</h2><p>Start, resume, skip, or stop. No guilt math.</p>${routineCards.map(routine=>`<div class="v5-routine-line"><span><b>🌷 ${esc(routine.name)}</b><small>${esc(routine.meta)}</small></span><button type="button" data-go="tasks">Open</button></div>`).join('')||'<div class="v5-empty">No routine is asking for anything right now. Add one only when it will make life easier.</div>'}<div class="v5-room-actions"><button type="button" data-go="rituals">Open routines</button></div></section><section class="v5-status-grid"><section class="v5-status-card" data-tone="blue"><h2>Today’s map</h2><p>${events.length?esc(events[0].title||'Next event')+(events[0].start?` • ${esc(events[0].start)}`:''):'No fixed event is next.'}</p><div class="v5-room-actions"><button type="button" data-go="planner">Plan my day</button></div></section><section class="v5-status-card" data-tone="lavender"><h2>Little Pings</h2><p>${pings?pings+' to check today.':'Nothing urgent is waiting.'}</p><div class="v5-room-actions"><button type="button" data-go="reminders">Open Pings</button></div></section></section></section><section class="v5-daily-card"><h2>Pick a room</h2><p>Use the smallest room that solves the problem.</p><div class="v5-room-actions"><button type="button" data-go="tasks">📝 Tasks</button><button type="button" data-go="planner">📅 Planner</button><button type="button" data-go="mochini">🍡 Mochini</button><button type="button" data-go="brain">🧠 Brain dump</button></div></section></main>`;
  root.querySelectorAll('[data-go]').forEach(button=>button.addEventListener('click',()=>router.go(button.dataset.go)));
  root.querySelectorAll('[data-complete]').forEach(button=>button.addEventListener('click',()=>completeTask(store,String(button.dataset.complete))));
 };
 if(!subscribed.has(store)){subscribed.add(store);store.subscribe(draw)}
 draw();
}
export{renderDaily};
