const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const id=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8);
const list=v=>Array.isArray(v)?v:(v&&typeof v==='object'?Object.values(v):[]);
function renderGoals({root,store}){
 let mode=false,editing=null;
 const draw=()=>{
  const all=list(store.get().goals),active=all.filter(x=>!x.archived),done=active.filter(x=>Number(x.progress||0)>=100),selected=editing?all.find(x=>String(x.id)===String(editing)):null;
  root.innerHTML=`<section class="v17-card sm-goals"><div class="v17-home-hero"><div class="v17-eyebrow">🍓 STRAWBERRY MOCHA • DREAMSCAPE</div><h1>🌙 Dreamscape</h1><p>Big dreams, tiny next steps, zero perfection requirement. ♡</p></div><div class="v17-columns"><div class="v17-card"><small>DREAMS IN MOTION</small><h2>${active.filter(x=>Number(x.progress||0)<100).length}</h2></div><div class="v17-card"><small>ACHIEVED</small><h2>${done.length}</h2></div></div><section class="v17-card"><header><div><h2>💭 Dreams in Motion</h2><p class="v17-muted">Keep the next little step visible.</p></div><button class="primary" id="addGoal">${mode?'× Close':'＋ Dream'}</button></header>${active.filter(x=>Number(x.progress||0)<100).map(card).join('')||'<div class="v17-empty">💭 Your dream space is waiting for its first little dream.</div>'}</section><section class="v17-card"><header><h2>✨ Achieved</h2><span class="v17-pill">${done.length}</span></header>${done.map(x=>card(x,true)).join('')||'<div class="v17-empty">🌙 Your first dream is waiting to come true.</div>'}</section>${mode||selected?form(selected):''}</section>`;
  root.querySelector('#addGoal')?.addEventListener('click',()=>{mode=!mode;editing=null;draw()});
  root.querySelector('#closeGoal')?.addEventListener('click',()=>{mode=false;editing=null;draw()});
  root.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{editing=b.dataset.edit;mode=false;draw()});
  root.querySelectorAll('[data-archive]').forEach(b=>b.onclick=()=>store.update(d=>({...d,goals:list(d.goals).map(x=>String(x.id)===String(b.dataset.archive)?{...x,archived:true}:x)})));
  root.querySelector('#progress')?.addEventListener('input',e=>root.querySelector('#pv').textContent=e.target.value+'%');
  root.querySelector('#saveGoal')?.addEventListener('click',()=>{const title=root.querySelector('#title').value.trim();if(!title)return;const item={id:editing||id(),title,why:root.querySelector('#why').value,category:root.querySelector('#cat').value||'Personal',date:root.querySelector('#date').value,progress:Number(root.querySelector('#progress').value)||0,archived:false};store.update(d=>({...d,goals:editing?list(d.goals).map(x=>String(x.id)===String(editing)?{...x,...item}:x):[...list(d.goals),item]}));mode=false;editing=null});
 };
 const card=(x,complete=false)=>`<article class="v17-goal-row"><div class="v17-goal-icon">${complete?'✨':Number(x.progress||0)>=75?'🌙':'💭'}</div><div class="v17-goal-main"><div><b>${esc(x.title||'Untitled dream')}</b><span>${esc(x.category||'Personal')}</span></div><small>${esc(x.why||'One little step at a time.')}</small><div class="v17-goal-progress"><i style="width:${Math.max(0,Math.min(100,Number(x.progress)||0))}%"></i></div><small>${Number(x.progress||0)}%${x.date?' • target '+esc(x.date):''}</small></div><button data-edit="${esc(x.id)}">✎</button><button data-archive="${esc(x.id)}">🗄</button></article>`;
 const form=x=>`<section class="v17-card"><header><h2>${x?'✎ Edit Dream':'＋ New Dream'}</h2><button id="closeGoal">×</button></header><div class="v17-money-form"><label>Dream<input id="title" placeholder="What are you working toward?" value="${esc(x?.title||'')}"></label><label>Why does this matter?<textarea id="why">${esc(x?.why||'')}</textarea></label><label>Category<input id="cat" value="${esc(x?.category||'')}"></label><label>Target date<input id="date" type="date" value="${esc(x?.date||'')}"></label><label>Progress <span id="pv">${Number(x?.progress||0)}%</span><input id="progress" type="range" min="0" max="100" step="5" value="${Number(x?.progress||0)}"></label><button class="primary" id="saveGoal">♡ ${x?'Save changes':'Save Dream'}</button></div></section>`;
 store.subscribe(draw);draw()
}
export{renderGoals};