const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const makeId=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8);
const list=v=>Array.isArray(v)?v:(v&&typeof v==='object'?Object.values(v):[]);
function renderGoals({root,store}){
 let mode=null,editing=null;
 const getGoals=()=>list(store.get().goals);
 const saveGoals=goals=>store.update(d=>({...d,goals}));
 const draw=()=>{
  const goals=getGoals(),selected=editing?goals.find(x=>String(x.id)===String(editing)):null;
  const active=goals.filter(x=>!x.archived),done=active.filter(x=>Number(x.progress||0)>=100),inProgress=active.filter(x=>Number(x.progress||0)<100);
  const form=mode||selected?`<section class="v17-card"><header><h2>${selected?'✎ Edit Goal':'＋ New Goal'}</h2><button type="button" data-action="close">×</button></header><div class="v17-money-form"><label>Goal<input id="gTitle" placeholder="What are you working toward?" value="${esc(selected?.title||'')}"></label><label>Why does this matter to me?<textarea id="gWhy" placeholder="Give this goal a reason that actually matters to you.">${esc(selected?.why||'')}</textarea></label><label>Category<input id="gCategory" placeholder="School, money, health, personal..." value="${esc(selected?.category||'')}"></label><label>Target date<input id="gDate" type="date" value="${esc(selected?.date||'')}"></label><label>Progress: <span id="gProgressValue">${Number(selected?.progress||0)}%</span><input id="gProgress" type="range" min="0" max="100" step="5" value="${Number(selected?.progress||0)}"></label><button type="button" class="primary" data-action="save">♡ ${selected?'Save changes':'Save goal'}</button></div></section>`:'';
  root.innerHTML=`<section class="v17-card"><div class="v17-home-hero"><div class="v17-eyebrow">🍓 STRAWBERRY MOCHA • GOALS</div><div class="v17-home-heading"><div><h1>✨ Goals</h1><p>Small steps count. Your goal does not need to be perfect to be real. ♡</p></div><div class="v17-hero-berry">🌷</div></div></div><section class="v17-card"><header><div><h2>🌱 Goal Garden</h2><p class="v17-muted">${done.length} blooming • ${inProgress.length} growing</p></div><button type="button" class="primary" data-action="add">${mode?'× Close':'＋ Goal'}</button></header>${inProgress.map(x=>`<article class="v17-goal-row"><div class="v17-goal-icon">${Number(x.progress||0)>=75?'🌸':Number(x.progress||0)>=40?'🌷':'🌱'}</div><div class="v17-goal-main"><div><b>${esc(x.title||'Untitled goal')}</b><span>${esc(x.category||'Personal')}</span></div><small>${esc(x.why||'No reason added yet.')}</small><div class="v17-goal-progress"><i style="width:${Math.max(0,Math.min(100,Number(x.progress)||0))}%"></i></div><small>${Number(x.progress||0)}%${x.date?' • target '+esc(x.date):''}</small></div><button type="button" data-action="edit" data-id="${esc(x.id)}">✎</button><button type="button" data-action="archive" data-id="${esc(x.id)}">🗄</button></article>`).join('')||'<div class="v17-empty">🌱 No active goals yet. Plant one.</div>'}</section><section class="v17-card"><header><h2>🌸 Blooming</h2><span class="v17-pill">${done.length}</span></header>${done.map(x=>`<article class="v17-goal-row completed"><div class="v17-goal-icon">🌸</div><div class="v17-goal-main"><b>${esc(x.title||'Goal')}</b><small>${esc(x.why||'')}</small><div class="v17-goal-progress"><i style="width:100%"></i></div><small>100% complete</small></div><button type="button" data-action="edit" data-id="${esc(x.id)}">✎</button><button type="button" data-action="archive" data-id="${esc(x.id)}">🗄</button></article>`).join('')||'<div class="v17-empty">🌷 Your first bloom is waiting.</div>'}</section>${form}</section>`;
  root.querySelector('#gProgress')?.addEventListener('input',e=>{const out=root.querySelector('#gProgressValue');if(out)out.textContent=e.target.value+'%'});
 };
 root.onclick=e=>{const b=e.target.closest('[data-action]');if(!b||!root.contains(b))return;const a=b.dataset.action,id=b.dataset.id;if(a==='add'){editing=null;mode=mode?null:'add';draw();return}if(a==='close'){mode=null;editing=null;draw();return}if(a==='edit'){editing=id;mode=null;draw();return}if(a==='archive'){saveGoals(getGoals().map(x=>String(x.id)===String(id)?{...x,archived:true}:x));return}if(a==='save'){const item={id:editing||makeId(),title:root.querySelector('#gTitle')?.value.trim()||'',why:root.querySelector('#gWhy')?.value.trim()||'',category:root.querySelector('#gCategory')?.value.trim()||'Personal',date:root.querySelector('#gDate')?.value||'',progress:Number(root.querySelector('#gProgress')?.value)||0,archived:false};if(!item.title)return;const goals=getGoals();saveGoals(editing?goals.map(x=>String(x.id)===String(editing)?{...x,...item,archived:x.archived}:x):[...goals,item]);mode=null;editing=null}};
 store.subscribe(draw);draw();
}
export{renderGoals};