const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const makeId=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8);
const list=v=>Array.isArray(v)?v:(v&&typeof v==='object'?Object.values(v):[]);
function renderGoals({root,store}){
 let mode=false,editing=null;
 const normalizeGoals=()=>{const raw=list(store.get().goals);let changed=false;const out=raw.map(x=>{if(x?.id)return x;changed=true;return{...(x||{}),id:makeId()}});if(changed)store.update(d=>({...d,goals:out}));return out};
 const goals=()=>normalizeGoals();
 const updateGoals=next=>store.update(d=>({...d,goals:next}));
 const draw=()=>{
  const all=goals(),active=all.filter(x=>!x.archived),done=active.filter(x=>Number(x.progress||0)>=100),growing=active.filter(x=>Number(x.progress||0)<100),selected=editing?all.find(x=>String(x.id)===String(editing)):null;
  root.innerHTML=`<section class="v17-card"><div class="v17-home-hero"><div class="v17-eyebrow">🍓 STRAWBERRY MOCHA • GOALS</div><div class="v17-home-heading"><div><h1>✨ Goals</h1><p>Small steps count. Your goal does not need to be perfect to be real. ♡</p></div><div class="v17-hero-berry">🌷</div></div></div><section class="v17-card"><header><div><h2>🌱 Goal Garden</h2><p class="v17-muted">${done.length} blooming • ${growing.length} growing</p></div><button type="button" class="primary" id="addGoal">${mode?'× Close':'＋ Goal'}</button></header>${growing.map(x=>card(x)).join('')||'<div class="v17-empty">🌱 No active goals yet. Plant one.</div>'}</section><section class="v17-card"><header><h2>🌸 Blooming</h2><span class="v17-pill">${done.length}</span></header>${done.map(x=>card(x,true)).join('')||'<div class="v17-empty">🌷 Your first bloom is waiting.</div>'}</section>${(mode||selected)?form(selected):''}</section>`;
  root.querySelector('#addGoal')?.addEventListener('click',()=>{mode=!mode;editing=null;draw()});
  root.querySelector('#closeGoal')?.addEventListener('click',()=>{mode=false;editing=null;draw()});
  root.querySelectorAll('[data-edit-goal]').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.editGoal;if(!id)return;editing=id;mode=false;draw()}));
  root.querySelectorAll('[data-archive-goal]').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.archiveGoal;if(!id)return;updateGoals(goals().map(x=>String(x.id)===String(id)?{...x,archived:true}:x))}));
  root.querySelector('#gProgress')?.addEventListener('input',e=>{const out=root.querySelector('#gProgressValue');if(out)out.textContent=e.target.value+'%'});
  root.querySelector('#saveGoal')?.addEventListener('click',()=>{const title=root.querySelector('#gTitle')?.value.trim();if(!title)return;const item={id:editing||makeId(),title,why:root.querySelector('#gWhy')?.value.trim()||'',category:root.querySelector('#gCategory')?.value.trim()||'Personal',date:root.querySelector('#gDate')?.value||'',progress:Number(root.querySelector('#gProgress')?.value)||0};const current=goals();updateGoals(editing?current.map(x=>String(x.id)===String(editing)?{...x,...item}:x):[...current,{...item,archived:false}]);mode=false;editing=null});
 };
 const card=(x,complete=false)=>`<article class="v17-goal-row${complete?' completed':''}"><div class="v17-goal-icon">${complete?'🌸':Number(x.progress||0)>=75?'🌸':Number(x.progress||0)>=40?'🌷':'🌱'}</div><div class="v17-goal-main"><div><b>${esc(x.title||'Untitled goal')}</b><span>${esc(x.category||'Personal')}</span></div><small>${esc(x.why||'No reason added yet.')}</small><div class="v17-goal-progress"><i style="width:${Math.max(0,Math.min(100,Number(x.progress)||0))}%"></i></div><small>${Number(x.progress||0)}%${x.date?' • target '+esc(x.date):''}</small></div><button type="button" data-edit-goal="${esc(x.id)}">✎</button><button type="button" data-archive-goal="${esc(x.id)}">🗄</button></article>`;
 const form=x=>`<section class="v17-card"><header><h2>${x?'✎ Edit Goal':'＋ New Goal'}</h2><button type="button" id="closeGoal">×</button></header><div class="v17-money-form"><label>Goal<input id="gTitle" placeholder="What are you working toward?" value="${esc(x?.title||'')}"></label><label>Why does this matter to me?<textarea id="gWhy" placeholder="Give this goal a reason that actually matters to you.">${esc(x?.why||'')}</textarea></label><label>Category<input id="gCategory" placeholder="School, money, personal..." value="${esc(x?.category||'')}"></label><label>Target date<input id="gDate" type="date" value="${esc(x?.date||'')}"></label><label>Progress: <span id="gProgressValue">${Number(x?.progress||0)}%</span><input id="gProgress" type="range" min="0" max="100" step="5" value="${Number(x?.progress||0)}"></label><button type="button" class="primary" id="saveGoal">♡ ${x?'Save changes':'Save goal'}</button></div></section>`;
 store.subscribe(draw);draw();
}
export{renderGoals};