import{buildBigMochiRequest,buildMochiniPresentation}from'../app/mochini.js?v=22.1.16-20260817';

const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const time=value=>value?new Date(`2000-01-01T${value}`).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}):'Any time';
function installStyle(){if(document.getElementById('sm-mochini-style'))return;const style=document.createElement('style');style.id='sm-mochini-style';style.textContent=`.sm-mochini{color:#674941}.sm-mochini-hero{background:linear-gradient(135deg,#ffe5f0,#fffaf6 55%,#edf7e8);border:1px solid #edcfdb;border-radius:28px;padding:24px;position:relative;overflow:hidden}.sm-mochini-hero:after{content:'🍓  ✦  🍡  ✦';position:absolute;right:20px;bottom:14px;opacity:.7}.sm-mochini-grid{display:grid;grid-template-columns:1.25fr .75fr;gap:12px;margin-top:12px}.sm-mochini-message{background:#fffdfb;border:1px solid #eadbd6;border-radius:22px;padding:18px}.sm-mochini-message h2{margin:0 0 7px}.sm-mochini-notice{margin:8px 0;padding:9px 11px;border-radius:13px;background:#fff0f5;color:#7a5047;font-size:13px}.sm-mochini-reasons{margin:10px 0;padding-left:19px}.sm-mochini-reasons li{margin:5px 0}.sm-mochini-context{display:grid;gap:8px}.sm-mochini-context div{padding:12px;border:1px solid #eadbd6;border-radius:16px;background:#fffaf6}.sm-mochini-context small{display:block;color:#9a817b;font-weight:800;letter-spacing:.06em}.sm-mochini-request{width:100%;min-height:300px;border:1px solid #e8bdd0;border-radius:18px;padding:13px;background:#fffdfb;color:#674941;font:12px/1.45 ui-monospace,SFMono-Regular,Consolas,monospace;resize:vertical}@media(max-width:780px){.sm-mochini-grid{grid-template-columns:1fr}.sm-mochini-hero{padding:19px}}`;document.head.appendChild(style)}

function renderMochini({root,store}){installStyle();let request='';const draw=()=>{const evaluation=store.evaluateToday({}),state=store.get(),view=buildMochiniPresentation(evaluation,state),next=state.events?.find(event=>String(event.id)===String(evaluation.state.nextFixedEventId));root.innerHTML=`<section class="v17-card sm-mochini"><section class="sm-mochini-hero"><div class="v17-eyebrow">🍓 KATOS RESIDENT • DETERMINISTIC COMPANION</div><h1>🍡 Mochini</h1><p>Tiny bean verdicts from your actual planner data.</p><button data-refresh>↻ Re-evaluate</button></section><div class="sm-mochini-grid"><section class="sm-mochini-message"><small>MOCHINI SAYS</small><h2>${esc(view.headline)}</h2><p>${esc(view.message)}</p>${view.notices.map(notice=>`<p class="sm-mochini-notice">${esc(notice)}</p>`).join('')}${view.reasonLines.length?`<details open><summary>Why this?</summary><ul class="sm-mochini-reasons">${view.reasonLines.map(line=>`<li>${esc(line)}</li>`).join('')}</ul></details>`:''}${view.finance.applicable?`<p class="sm-mochini-notice">💰 Available: $${Number(view.finance.summary.available||0).toFixed(2)} • Unpaid bills: $${Number(view.finance.summary.unpaidBills||0).toFixed(2)}</p>`:''}${view.showBigMochi?`<button class="primary" data-make-request>🍓 Make Big Mochi Request</button>`:''}</section><aside class="sm-mochini-context"><div><small>TODAY</small><b>${evaluation.state.openTaskCount} open task${evaluation.state.openTaskCount===1?'':'s'} • ${esc(evaluation.state.capacity)} capacity</b></div><div><small>NEXT FIXED EVENT</small><b>${next?`${esc(next.title||'Scheduled event')} • ${esc(time(next.start))}`:'Nothing fixed next'}</b></div><div><small>ROUTINES</small><b>${evaluation.routines.completed}/${evaluation.routines.total} complete</b></div>${evaluation.deadlines[0]?`<div><small>CLOSEST DEADLINE</small><b>${esc(evaluation.deadlines[0].title)} • ${esc(evaluation.deadlines[0].urgency)}</b></div>`:''}</aside></div>${request?`<section class="v17-card"><header><div><h2>🍓 Big Mochi Request</h2><p class="v17-muted">Nothing was sent. Copy this into ChatGPT when you want deeper help.</p></div><button data-close-request>×</button></header><textarea class="sm-mochini-request" readonly>${esc(request)}</textarea><button class="primary" data-copy-request>Copy Big Mochi Request</button><p data-copy-status class="v17-muted" role="status"></p></section>`:''}</section>`;
 root.querySelector('[data-refresh]')?.addEventListener('click',draw);root.querySelector('[data-make-request]')?.addEventListener('click',()=>{request=buildBigMochiRequest(evaluation,state);draw()});root.querySelector('[data-close-request]')?.addEventListener('click',()=>{request='';draw()});root.querySelector('[data-copy-request]')?.addEventListener('click',async()=>{const status=root.querySelector('[data-copy-status]');try{await navigator.clipboard.writeText(request);status.textContent='Copied. Go summon Big Mochi. 🍓'}catch{const area=root.querySelector('.sm-mochini-request');area.focus();area.select();document.execCommand('copy');status.textContent='Copied. Go summon Big Mochi. 🍓'}});
 };draw()}
export{renderMochini};
