import{buildBigMochiRequest,buildMochiniPresentation}from'../app/mochini.js?v=22.1.34-20260818';
import{answerMochiniIntent,matchMochiniIntent}from'../app/mochini-intents.js?v=22.1.34-20260818';
import{routeMochiniCapability}from'../app/mochini-capabilities.js?v=22.10.0-20260819';
import{appendConversation,clearConversation,conversationEvidence,conversationSession}from'../app/mochini-conversation.js?v=22.1.20-20260817';
import{protectTaskFromMochini,protectionProposal}from'../app/mochini-actions.js?v=22.2.0-20260818';

const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const time=value=>value?new Date(`2000-01-01T${value}`).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}):'Any time';
const choiceLabels={ask_tasks:'Tasks',ask_next_event:'Schedule',ask_deadlines:'Deadlines'};

function installStyle(){if(document.getElementById('sm-mochini-style'))return;const style=document.createElement('style');style.id='sm-mochini-style';style.textContent=`.sm-mochini{color:#674941}.sm-mochini-hero{background:linear-gradient(135deg,#ffe5f0,#fffaf6 55%,#edf7e8);border:1px solid #edcfdb;border-radius:28px;padding:24px;position:relative;overflow:hidden}.sm-mochini-hero:after{content:'🍓  ✦  🍡  ✦';position:absolute;right:20px;bottom:14px;opacity:.7}.sm-mochini-grid{display:grid;grid-template-columns:1.25fr .75fr;gap:12px;margin-top:12px}.sm-mochini-message,.sm-mochini-chat{background:#fffdfb;border:1px solid #eadbd6;border-radius:22px;padding:18px}.sm-mochini-message h2{margin:0 0 7px}.sm-mochini-notice{margin:8px 0;padding:9px 11px;border-radius:13px;background:#fff0f5;color:#7a5047;font-size:13px}.sm-mochini-reasons{margin:10px 0;padding-left:19px}.sm-mochini-reasons li{margin:5px 0}.sm-mochini-context{display:grid;gap:8px}.sm-mochini-context div{padding:12px;border:1px solid #eadbd6;border-radius:16px;background:#fffaf6}.sm-mochini-context small{display:block;color:#9a817b;font-weight:800;letter-spacing:.06em}.sm-mochini-request{width:100%;min-height:260px;border:1px solid #e8bdd0;border-radius:18px;padding:13px;background:#fffdfb;color:#674941;font:12px/1.45 ui-monospace,SFMono-Regular,Consolas,monospace;resize:vertical}.sm-mochini-chat{margin-top:12px}.sm-mochini-chat header{display:flex;justify-content:space-between;gap:12px;align-items:baseline}.sm-mochini-chat h2{margin:0}.sm-mochini-history{display:grid;gap:9px;max-height:280px;overflow:auto;margin:12px 0}.sm-mochini-turn{padding:10px 12px;border-radius:15px;background:#fff6f9;border:1px solid #f2d6e0}.sm-mochini-turn.mochini{background:#f7fbf1}.sm-mochini-turn small{display:block;font-weight:900;letter-spacing:.07em;color:#a36b7b}.sm-mochini-turn p{margin:4px 0 0}.sm-mochini-ask{display:flex;gap:8px}.sm-mochini-ask input{flex:1;min-width:0;border:1px solid #e8bdd0;border-radius:15px;padding:12px 13px;color:#674941;background:#fff}.sm-mochini-choices{display:flex;gap:7px;flex-wrap:wrap;margin-top:9px}.sm-mochini-choices button{padding:7px 10px;border-radius:12px}@media(max-width:780px){.sm-mochini-grid{grid-template-columns:1fr}.sm-mochini-hero{padding:19px}.sm-mochini-ask{flex-direction:column}.sm-mochini-ask button{width:100%}}`;document.head.appendChild(style)}

function renderMochini({root,store}){
 installStyle();let request='',requestQuestion='',proposal=null,actionMessage='';const declinedTaskIds=new Set();
 const draw=()=>{
  const evaluation=store.evaluateToday({}),state=store.get(),history=store.getMochini().conversation,session=conversationSession(state),view=buildMochiniPresentation(evaluation,state),next=state.events?.find(event=>String(event.id)===String(evaluation.state.nextFixedEventId));
  const proposedTask=proposal?(state.tasks||[]).find(task=>String(task?.id)===String(proposal.taskId)):null;if(proposal&&(!proposedTask||proposedTask.isProtected))proposal=null;
  const historyHtml=history.length?history.map(turn=>`<article class="sm-mochini-turn ${turn.role==='mochini'?'mochini':''}"><small>${turn.role==='mochini'?'🍡 MOCHINI':'KAT'}</small><p>${esc(turn.text)}</p>${turn.choices?.length?`<div class="sm-mochini-choices">${turn.choices.map(choice=>`<button type="button" data-choice="${esc(choice)}">${esc(choiceLabels[choice]||choice)}</button>`).join('')}</div>`:''}${turn.escalation?`<button class="primary" type="button" data-conversation-request="${esc(turn.id)}">🍓 Make Big Mochi Request</button>`:''}</article>`).join(''):'<p class="v17-muted">Ask about anything KatOS knows: tasks, Noms, Sip Fridge, Motion Meadow, work, routines, projects, Kat Labs, Catch-All, deadlines, capacity, or today.</p>';
  const actionMarkup=proposedTask?`<section class="v17-card sm-mochini-action"><small>🍓 MOCHINI ACTION SUGGESTION</small><h2>Protect ${esc(proposedTask.text||proposedTask.title||'this task')}?</h2><p>${esc(proposal.reason)} Nothing changes unless you choose Protect it.</p><button class="primary" data-approve-protection="${esc(proposedTask.id)}">Protect it</button><button type="button" data-decline-protection="${esc(proposedTask.id)}">No thanks</button></section>`:actionMessage?`<p class="sm-mochini-notice" role="status">${esc(actionMessage)}</p>`:'';
  root.innerHTML=`<section class="v17-card sm-mochini"><section class="sm-mochini-hero"><div class="v17-eyebrow">🍓 KATOS RESIDENT • DETERMINISTIC COMPANION</div><h1>🍡 Mochini</h1><p>Tiny bean verdicts from your actual planner data.</p><button data-refresh>↻ Re-evaluate</button></section><div class="sm-mochini-grid"><section class="sm-mochini-message"><small>MOCHINI SAYS</small><h2>${esc(view.headline)}</h2><p>${esc(view.message)}</p>${view.notices.map(notice=>`<p class="sm-mochini-notice">${esc(notice)}</p>`).join('')}${view.reasonLines.length?`<details open><summary>Why this?</summary><ul class="sm-mochini-reasons">${view.reasonLines.map(line=>`<li>${esc(line)}</li>`).join('')}</ul></details>`:''}${view.finance.applicable?`<p class="sm-mochini-notice">💰 Available: $${Number(view.finance.summary.available||0).toFixed(2)} • Unpaid bills: $${Number(view.finance.summary.unpaidBills||0).toFixed(2)}</p>`:''}${view.showBigMochi?`<button class="primary" data-make-request>🍓 Make Big Mochi Request</button>`:''}</section><aside class="sm-mochini-context"><div><small>TODAY</small><b>${evaluation.state.openTaskCount} open task${evaluation.state.openTaskCount===1?'':'s'} • ${esc(evaluation.state.capacity)} capacity</b></div><div><small>NEXT FIXED EVENT</small><b>${next?`${esc(next.title||'Scheduled event')} • ${esc(time(next.start))}`:'Nothing fixed next'}</b></div><div><small>ROUTINES</small><b>${evaluation.routines.completed}/${evaluation.routines.total} complete</b></div>${evaluation.deadlines[0]?`<div><small>CLOSEST DEADLINE</small><b>${esc(evaluation.deadlines[0].title)} • ${esc(evaluation.deadlines[0].urgency)}</b></div>`:''}</aside></div>${actionMarkup}<section class="sm-mochini-chat"><header><div><small>🍓 LITTLE CONVERSATION</small><h2>Ask Mochini</h2></div><div><small>Connected to KatOS • Conversation saved</small><button type="button" data-clear-conversation>Clear conversation</button></div></header><div class="sm-mochini-history" aria-live="polite">${historyHtml}</div><form class="sm-mochini-ask" data-ask-form><input name="question" aria-label="Ask Mochini something" placeholder="What should I do?" autocomplete="off"><button class="primary" type="submit">Ask 🍡</button></form></section>${request?`<section class="v17-card"><header><div><h2>🍓 Big Mochi Request</h2><p class="v17-muted">Nothing was sent. Copy this into ChatGPT when you want deeper help.</p></div><button data-close-request>×</button></header><textarea class="sm-mochini-request" readonly>${esc(request)}</textarea><button class="primary" data-copy-request>Copy Big Mochi Request</button><p data-copy-status class="v17-muted" role="status"></p></section>`:''}</section>`;
  const recordResult=(result,question='')=>{appendConversation(store,{role:'mochini',text:result.answer,intent:result.intent,evidence:conversationEvidence(result),choices:result.choices,escalation:result.escalation});proposal=protectionProposal({intent:result.intent,recommendation:result.recommendation,evaluation,declinedTaskIds:[...declinedTaskIds]});if(result.escalation)requestQuestion=question;draw()};
  const answer=(intentResult,question='')=>recordResult(answerMochiniIntent(intentResult,{state,evaluation,session}),question);
  root.querySelector('[data-refresh]')?.addEventListener('click',draw);
  root.querySelector('[data-approve-protection]')?.addEventListener('click',event=>{const result=protectTaskFromMochini(store,String(event.currentTarget.dataset.approveProtection));proposal=null;actionMessage=result.ok?(result.alreadyProtected?'That task is already protected. You can still edit or unprotect it anytime. 🌷':'Protected. I’ll treat this as something we should not casually push aside. 🍓'):result.error;draw()});
  root.querySelector('[data-decline-protection]')?.addEventListener('click',event=>{declinedTaskIds.add(String(event.currentTarget.dataset.declineProtection));proposal=null;actionMessage='Okay. We’ll leave that task flexible.';draw()});
  const openRequest=(question,options={})=>{requestQuestion=question;request=buildBigMochiRequest(evaluation,state,question,{topic:'general',recentConversation:history,...options});draw()};
  root.querySelector('[data-make-request]')?.addEventListener('click',()=>openRequest(session.lastUserQuestion||'Please help me decide what to do next and explain why.',{topic:'task_ambiguity'}));
  const askQuestion=question=>{question=String(question||'').trim();if(!question)return;const routed=routeMochiniCapability(question,{state,evaluation,session}),legacy=routed?null:matchMochiniIntent(question),intent=routed?.intent||legacy?.intent||'unknown';appendConversation(store,{role:'kat',text:question,intent});if(routed)return recordResult(routed,question);answer(legacy,question)};
  const askForm=root.querySelector('[data-ask-form]'),askInput=root.querySelector('[name="question"]');
  askForm?.addEventListener('submit',event=>{event.preventDefault();askQuestion(new FormData(event.currentTarget).get('question'))});
  askInput?.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();askQuestion(event.currentTarget.value)}});
  root.querySelectorAll('[data-choice]').forEach(button=>button.addEventListener('click',()=>answer({intent:button.dataset.choice,confidence:'exact',parameters:{}},session.lastUserQuestion||'')));
  root.querySelectorAll('[data-conversation-request]').forEach(button=>button.addEventListener('click',()=>{const index=history.findIndex(turn=>String(turn.id)===String(button.dataset.conversationRequest)),turn=index>=0?history[index]:null,priorKat=[...history.slice(0,Math.max(0,index))].reverse().find(entry=>entry.role==='kat'),question=priorKat?.text||requestQuestion||session.lastUserQuestion||'Please help me decide what to do next and explain why.';openRequest(question,{reason:turn?.evidence?.reason||'This question cannot be answered reliably using deterministic KatOS rules.'})}));
  root.querySelector('[data-clear-conversation]')?.addEventListener('click',()=>{if(confirm('Clear Mochini’s saved conversation? Your planner data will stay exactly as it is.'))clearConversation(store)});
  root.querySelector('[data-close-request]')?.addEventListener('click',()=>{request='';draw()});
  root.querySelector('[data-copy-request]')?.addEventListener('click',async()=>{const status=root.querySelector('[data-copy-status]');try{if(!navigator.clipboard?.writeText)throw new Error('Clipboard unavailable');await navigator.clipboard.writeText(request);status.textContent='Copied. Go summon Big Mochi. 🍓'}catch{const area=root.querySelector('.sm-mochini-request');area.focus();area.select();status.textContent=document.execCommand('copy')?'Copied. Go summon Big Mochi. 🍓':'Select the request above, then copy it. 🍓'}});
 };
 draw();
}
export{renderMochini};
