const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const id=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8);
const money=n=>'$'+Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
const list=(v,k)=>Array.isArray(v)?v:(v&&typeof v==='object'?Object.entries(v).map(([n,x])=>({id:x?.id||id(),name:x?.name||n,...(x&&typeof x==='object'?x:{amount:Number(x)||0})})):[]);
const repeats=['One-time','Weekly','Biweekly','Monthly','Quarterly','Yearly'];
const css=()=>{if(document.getElementById('sm-money-style'))return;const s=document.createElement('style');s.id='sm-money-style';s.textContent='.sm-money{color:#674941}.sm-money .v17-card{border-radius:21px;border-color:#eadbd6;background:linear-gradient(135deg,#fffdfb,#fff7fa)}.sm-money .sm-total{background:linear-gradient(105deg,#f5c3d4,#dcebcf);border-radius:22px;padding:18px}.sm-money .sm-total h1{font-size:34px;margin:4px 0}.sm-money .v17-money-row{border-radius:15px!important;background:#fffaf6!important;margin:6px 0;padding:10px!important}.sm-money .primary{background:linear-gradient(105deg,#e99ab7,#cfe0b8)!important;border:0!important}.sm-money .v17-progress{border-radius:99px;overflow:hidden}';document.head.appendChild(s)};
function renderMoney({root,store}){
 css();let adding=null;
 const draw=()=>{
  const m=store.get().money||{},income=list(m.income,'income'),expenses=list(m.expenses,'expenses'),bills=list(m.bills,'bills'),debts=list(m.debts,'debts'),savings=list(m.savings,'savings');
  const inc=income.reduce((a,x)=>a+Number(x.amount||0),0),spent=expenses.reduce((a,x)=>a+Number(x.amount||0),0),unpaid=bills.filter(x=>!x.paid).reduce((a,x)=>a+Number(x.amount||0),0),left=inc-spent-unpaid,debt=debts.reduce((a,x)=>a+Number(x.balance??(x.amount||0)),0),saved=savings.reduce((a,x)=>a+Number(x.current??(x.amount||0)),0);
  const rows=(arr,type,extra=null)=>arr.map(x=>`<div class="v17-money-row"><span><b>${esc(x.name||type)}</b><small>${esc(x.repeat&&x.repeat!=='One-time'?`${x.repeat}${x.due?` • due ${x.due}`:''}`:x.frequency||x.category||x.due||'')}</small></span><strong>${money(x.balance??x.current??x.amount)}</strong>${extra?extra(x):''}<button data-del="${type}:${esc(x.id)}">×</button></div>`).join('')||'<div class="v17-empty">Nothing here yet. ♡</div>';
  const recurring=bills.filter(bill=>bill.repeat&&bill.repeat!=='One-time');
  root.innerHTML=`<div class="sm-money"><section class="v17-card"><div class="v17-home-hero"><div class="v17-eyebrow">🍓 STRAWBERRY MOCHA • MONEY CAFÉ</div><h1>☕ Money Café</h1><p>Know what is available, what is planned, and what deserves your attention next. ♡</p></div><div class="sm-total"><small>AVAILABLE RIGHT NOW</small><h1>${money(left)}</h1><span>Income ${money(inc)} • Spent ${money(spent)} • Bills ${money(unpaid)}</span></div><div class="v17-columns"><section class="v17-card"><header><h2>💵 Income</h2><button class="primary" data-add="income">＋</button></header>${rows(income,'income')}</section><section class="v17-card"><header><h2>🧾 Spending</h2><button class="primary" data-add="expenses">＋</button></header>${rows(expenses,'expenses')}</section></div><section class="v17-card"><header><div><h2>📅 Bills</h2><p class="v17-muted">Mark bills paid so the available number stays honest.</p></div><button class="primary" data-add="bills">＋ Bill</button></header>${rows(bills,'bills',x=>`<button data-paid="${esc(x.id)}">${x.paid?'✓ Paid':'○ Unpaid'}</button>`)}</section><section class="v17-card"><header><div><h2>🔁 Recurring bills</h2><p class="v17-muted">Your repeating monthly and scheduled commitments.</p></div><span class="v17-pill">${recurring.length}</span></header>${rows(recurring,'bills')}</section><div class="v17-columns"><section class="v17-card"><header><h2>💳 Debt</h2><button class="primary" data-add="debts">＋</button></header><h2>${money(debt)}</h2>${rows(debts,'debts')}</section><section class="v17-card"><header><h2>🌷 Savings</h2><button class="primary" data-add="savings">＋</button></header><h2>${money(saved)}</h2>${rows(savings,'savings',x=>{const p=Math.min(100,Math.round(Number(x.current||0)/Math.max(1,Number(x.target||0))*100));return `<span class="v17-pill">${p}%</span>`})}</section></div>${adding?`<section class="v17-card"><header><h2>＋ Add ${esc(adding)}</h2><button id="closeAdd">×</button></header><div class="v17-money-form"><input id="mName" placeholder="Name"><input id="mAmount" type="number" min="0" step="0.01" placeholder="Amount">${adding==='income'||adding==='bills'?`<select id="mRepeat">${repeats.map(repeat=>`<option value="${repeat}" ${repeat===`${adding==='income'?'Monthly':'One-time'}`?'selected':''}>${repeat}</option>`).join('')}</select>`:''}<input id="mExtra" placeholder="${adding==='bills'?'Due date (e.g. 1st of month)':adding==='savings'?'Target amount':adding==='income'?'Income source':'Category'}"><button class="primary" id="saveMoney">♡ Save</button></div></section>`:''}</section></div>`;
  root.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{adding=b.dataset.add;draw()});
  root.querySelector('#closeAdd')?.addEventListener('click',()=>{adding=null;draw()});
  root.querySelector('#saveMoney')?.addEventListener('click',()=>{const type=adding,name=root.querySelector('#mName').value.trim(),amount=Number(root.querySelector('#mAmount').value)||0,extra=root.querySelector('#mExtra').value,repeat=root.querySelector('#mRepeat')?.value||'One-time';if(!name)return;const item={id:id(),name,amount};if(type==='bills'){item.due=extra;item.repeat=repeat;item.paid=false}else if(type==='savings'){item.current=amount;item.target=Number(extra)||0;delete item.amount}else if(type==='debts'){item.balance=amount;item.minimum=0;delete item.amount}else if(type==='income'){item.repeat=repeat;item.frequency=extra||repeat}else item.category=extra;store.update(x=>({...x,money:{...(x.money||{}),[type]:[...list(x.money?.[type],type),item]}}));adding=null;draw()});
  root.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{const[t,i]=b.dataset.del.split(':');store.update(x=>({...x,money:{...(x.money||{}),[t]:list(x.money?.[t],t).filter(v=>String(v.id)!==i)}}))});
  root.querySelectorAll('[data-paid]').forEach(b=>b.onclick=()=>store.update(x=>({...x,money:{...(x.money||{}),bills:list(x.money?.bills,'bills').map(v=>String(v.id)===b.dataset.paid?{...v,paid:!v.paid}:v)}})));
 };
 store.subscribe(draw);draw();
}
export{renderMoney};
