import{createTask,moveTask}from'../app/task-actions.js?v=22.1.13-20260817';
import{shiftsForDate,shiftLabel,shiftMinutes}from'../app/work-schedule.js?v=22.1.14-20260817';
const pad=n=>String(n).padStart(2,'0');
const key=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const parse=s=>{const [y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d,12)};
const monthName=d=>d.toLocaleDateString(undefined,{month:'long',year:'numeric'});
const dayName=d=>d.toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'});
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2);
const money=n=>'$'+Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
const MOODS=['Loved','Happy','Calm','Tender','Excited','Confident','Okay','Meh','Blank','Sleepy','Drained','Overwhelmed','Sad','Sensitive','Frustrated','Irritated','Overloaded','Hopeful','Focused','Feeling cute'];
const moodEmoji={Loved:'🥰',Happy:'😊',Calm:'😌',Tender:'🥹',Excited:'🤩',Confident:'😎',Okay:'🙂',Meh:'😐',Blank:'😶',Sleepy:'😴',Drained:'🥱',Overwhelmed:'😮‍💨',Sad:'😔',Sensitive:'🥺',Frustrated:'😣',Irritated:'😤',Overloaded:'🤯',Hopeful:'🌱',Focused:'🧠','Feeling cute':'🎀'};
const list=value=>Array.isArray(value)?value:(value&&typeof value==='object'?Object.values(value):[]);
const dueInfo=bill=>{const raw=String(bill?.due||'').trim(),dated=/^(\d{4})-(\d{2})-(\d{2})$/.exec(raw);if(dated)return{date:new Date(Number(dated[1]),Number(dated[2])-1,Number(dated[3]),12),day:Number(dated[3])};const day=/\b([1-9]|[12]\d|3[01])(?:st|nd|rd|th)?\b/i.exec(raw);return day?{date:null,day:Number(day[1])}:null};
const billsForDate=(data,dateKey)=>{const date=parse(dateKey),bills=list(data.money?.bills);return bills.filter(bill=>{const due=dueInfo(bill),repeat=bill.repeat||'One-time';if(!due)return false;if(repeat==='One-time')return!!due.date&&key(due.date)===dateKey;if(repeat==='Monthly')return date.getDate()===due.day;if(repeat==='Yearly')return!!due.date&&date.getDate()===due.date.getDate()&&date.getMonth()===due.date.getMonth();if(repeat==='Quarterly')return!!due.date&&date.getDate()===due.date.getDate()&&((date.getMonth()-due.date.getMonth()+12)%3===0);if(repeat==='Weekly'||repeat==='Biweekly'){if(!due.date)return false;const days=Math.floor((date-due.date)/86400000),every=repeat==='Weekly'?7:14;return days>=0&&days%every===0}return false})};
const taskTitle=task=>task?.text||task?.title||'Untitled task';
const weekDates=date=>{const start=parse(date);start.setDate(start.getDate()-start.getDay());return Array.from({length:7},(_,index)=>{const day=new Date(start);day.setDate(start.getDate()+index);return key(day)})};
const eventMinutes=event=>{if(!event.start||!event.end)return 0;const [sh,sm]=event.start.split(':').map(Number),[eh,em]=event.end.split(':').map(Number);return Math.max(0,(eh*60+em)-(sh*60+sm))};

function renderPlanner({root,store}){
 let selected=key(new Date()),month=new Date();month.setDate(1);
 const dayData=(data,date=selected)=>data.days?.[date]||data.dayNotes?.[date]||{};
 const closeModal=box=>{box.remove();document.body.classList.remove('v17-modal-open')};
 const openEventForm=()=>{
  if(document.querySelector('.v18-event-modal'))return;
  const box=document.createElement('div');box.className='v17-modal v18-event-modal';box.setAttribute('role','dialog');box.setAttribute('aria-modal','true');
  box.innerHTML=`<div class="v17-modal-box"><button type="button" class="v17-modal-close" data-close aria-label="Close">×</button><h2>✨ Add event</h2><p class="v17-muted">Add something to ${esc(dayName(parse(selected)))}.</p><input id="evTitle" placeholder="Event or appointment" autocomplete="off"><div class="v17-planner-grid"><label><span>Date</span><input id="evDate" type="date" value="${selected}"></label><label><span>Start time</span><input id="evStart" type="time"></label><label><span>End time</span><input id="evEnd" type="time"></label></div><label class="v17-day-notes"><span>Notes</span><textarea id="evNotes" placeholder="Optional notes..."></textarea></label><div class="v17-modal-actions"><button type="button" data-close>Cancel</button><button type="button" id="saveEvent" class="primary">♡ Save event</button></div></div>`;
  document.body.appendChild(box);document.body.classList.add('v17-modal-open');
  const close=()=>closeModal(box);box.querySelectorAll('[data-close]').forEach(button=>button.onclick=close);box.onclick=event=>{if(event.target===box)close()};
  box.querySelector('#saveEvent').onclick=()=>{const title=box.querySelector('#evTitle').value.trim(),date=box.querySelector('#evDate').value||selected,start=box.querySelector('#evStart').value,end=box.querySelector('#evEnd').value;if(!title)return box.querySelector('#evTitle').focus();if(start&&end<start){box.querySelector('#evEnd').setCustomValidity('End time must be after the start time.');return box.querySelector('#evEnd').reportValidity()}store.update(data=>({...data,events:[...(data.events||[]),{id:uid(),title,date,start,end,notes:box.querySelector('#evNotes').value.trim()}]}));selected=date;month=new Date(parse(date).getFullYear(),parse(date).getMonth(),1);close();draw()};
 };
 const openDayReview=()=>{
  if(document.querySelector('.v18-day-review-modal'))return;
  const data=store.get(),note=dayData(data),tasks=(data.tasks||[]).filter(task=>task.date===selected),events=(data.events||[]).filter(event=>event.date===selected).sort((a,b)=>(a.start||'').localeCompare(b.start||'')),workShifts=shiftsForDate(data.workSchedule,selected),bills=billsForDate(data,selected);
  const box=document.createElement('div');box.className='v18-day-review-modal';box.setAttribute('role','dialog');box.setAttribute('aria-modal','true');
  box.innerHTML=`<div class="v17-modal-box v18-day-review-box"><button type="button" class="v17-modal-close" data-close aria-label="Close">×</button><div class="v18-review-heading"><div class="v18-review-icon">📖</div><div><span class="v17-eyebrow">STRAWBERRY MOCHA • DAY REVIEW</span><h2>${esc(dayName(parse(selected)))}</h2><p class="v17-muted">A soft little place to remember, edit, and reset.</p></div></div><div class="v18-review-summary"><span>✓ ${tasks.filter(task=>task.done).length}/${tasks.length} tasks</span><span>✨ ${events.length} event${events.length===1?'':'s'}</span><span>💼 ${workShifts.length} work shift${workShifts.length===1?'':'s'}</span></div><section class="v18-review-section"><h3>📝 Your day</h3><div class="v17-planner-grid"><label><span>Mood</span><select id="reviewMood"><option value="">Choose gently…</option>${MOODS.map(mood=>`<option value="${esc(mood)}" ${note.mood===mood?'selected':''}>${moodEmoji[mood]} ${esc(mood)}</option>`).join('')}</select></label><label><span>Energy</span><select id="reviewEnergy"><option value="">Choose…</option>${['Low','Medium','High','Zoomies'].map(energy=>`<option value="${energy}" ${note.energy===energy?'selected':''}>${({Low:'🌙',Medium:'🌥',High:'☀️',Zoomies:'⚡'})[energy]} ${energy}</option>`).join('')}</select></label><label><span>Movement</span><input id="reviewMovement" placeholder="Walk, Pilates, stretching…" value="${esc(note.movement||'')}"></label></div><label class="v17-day-notes"><span>What happened today?</span><textarea id="reviewNotes" placeholder="The little moments count too…">${esc(note.notes||'')}</textarea></label></section><section class="v18-review-section"><h3>💼 Work shifts</h3>${workShifts.map(shift=>`<div class="v17-event"><span><b>💼 Work</b><small>${esc(shiftLabel(shift))}</small></span></div>`).join('')||'<p class="v17-empty">No work shift scheduled. Edit it from Work. ♡</p>'}</section><section class="v18-review-section"><h3>☀️ Tasks</h3>${tasks.map(task=>`<label class="v18-review-task"><input type="checkbox" data-review-task="${esc(task.id)}" ${task.done?'checked':''}><span>${esc(task.text||task.title||'Untitled task')}</span></label>`).join('')||'<p class="v17-empty">No tasks were planned for this day. ♡</p>'}</section><section class="v18-review-section"><h3>✨ Events</h3>${events.map(event=>`<div class="v17-event"><span><b>📌 ${esc(event.title)}</b><small>${esc(event.start||'Any time')}${event.end?` – ${esc(event.end)}`:''}</small>${event.notes?`<small>${esc(event.notes)}</small>`:''}</span></div>`).join('')||'<p class="v17-empty">Nothing scheduled yet. Add it from the planner. ♡</p>'}</section><div class="v17-modal-actions"><button type="button" data-close>Cancel</button><button type="button" id="saveDayReview" class="primary">♡ Save day review</button></div></div>`;
  box.querySelector('.v18-review-summary')?.insertAdjacentHTML('afterend',`<section class="v18-review-section v18-bill-review"><h3>🧾 Bills due</h3>${bills.map(bill=>`<div class="v17-event"><span><b>🧾 ${esc(bill.name||'Bill')}</b><small>${esc(bill.repeat||'Scheduled')} • ${money(Number(bill.amount)||0)}</small>${bill.due?`<small>Due ${esc(bill.due)}</small>`:''}</span></div>`).join('')||'<p class="v17-empty">No recurring bills are due this day. ♡</p>'}</section>`);
  document.body.appendChild(box);document.body.classList.add('v17-modal-open');
  const close=()=>closeModal(box);box.querySelectorAll('[data-close]').forEach(button=>button.onclick=close);box.onclick=event=>{if(event.target===box)close()};
  box.querySelector('#saveDayReview').onclick=()=>{const review={mood:box.querySelector('#reviewMood').value,energy:box.querySelector('#reviewEnergy').value,movement:box.querySelector('#reviewMovement').value.trim(),notes:box.querySelector('#reviewNotes').value.trim(),savedAt:new Date().toISOString()},checks=new Map([...box.querySelectorAll('[data-review-task]')].map(input=>[String(input.dataset.reviewTask),input.checked]));store.update(data=>({...data,days:{...(data.days||{}),[selected]:{...(data.days?.[selected]||{}),...review}},dayNotes:{...(data.dayNotes||{}),[selected]:{...(data.dayNotes?.[selected]||{}),...review}},tasks:(data.tasks||[]).map(task=>checks.has(String(task.id))?{...task,done:checks.get(String(task.id))}:task)}));close();draw()};
 };
 const draw=()=>{
  const data=store.get(),first=new Date(month.getFullYear(),month.getMonth(),1,12),start=(first.getDay()+7)%7,daysInMonth=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();let cells='';
  for(let index=0;index<start;index++)cells+='<div class="v17-cal-empty"></div>';
  for(let day=1;day<=daysInMonth;day++){const date=new Date(month.getFullYear(),month.getMonth(),day,12),dateKey=key(date),count=(data.events||[]).filter(event=>event.date===dateKey).length+(data.tasks||[]).filter(task=>task.date===dateKey).length,bills=billsForDate(data,dateKey),review=dayData(data,dateKey),badge=count?`<span>${count}</span>`:review.notes||review.mood?'<span>♡</span>':'';cells+=`<button type="button" class="v17-day ${dateKey===selected?'selected':''} ${dateKey===key(new Date())?'today':''}" data-day="${dateKey}" aria-label="Open ${esc(dayName(date))}"><b>${day}</b>${badge}${bills.length?`<i class="v18-bill-dot">🧾${bills.length>1?bills.length:''}</i>`:''}</button>`}
  const weekly=weekDates(selected).map(dateKey=>{const date=parse(dateKey),events=(data.events||[]).filter(event=>event.date===dateKey).sort((a,b)=>String(a.start||'').localeCompare(String(b.start||''))),tasks=(data.tasks||[]).filter(task=>task.date===dateKey),fixed=events.reduce((sum,event)=>sum+eventMinutes(event),0),load=tasks.filter(task=>!task.done&&!task.parked).reduce((sum,task)=>sum+(Number(task.durationMin)||0),0),available=Math.max(0,16*60-fixed),overloaded=load>available;return `<article class="sm-week-day ${dateKey===key(new Date())?'today':''}"><header><div><small>${date.toLocaleDateString(undefined,{weekday:'long'})}</small><h3>${date.toLocaleDateString(undefined,{month:'short',day:'numeric'})}</h3></div><button type="button" data-plan-day="${dateKey}">＋ Task</button></header><section><b>📌 Fixed</b>${events.map(event=>`<div class="sm-fixed-row"><span>${esc(event.title||'Event')}</span><small>${esc(event.start||'Any time')}${event.end?` – ${esc(event.end)}`:''}</small></div>`).join('')||'<small class="v17-muted">Nothing fixed</small>'}</section><section><b>🍓 Flexible</b>${tasks.map(task=>`<div class="sm-flex-row ${task.done?'done':''}"><span>${task.done?'✓':'○'} ${esc(taskTitle(task))}</span><small>${task.durationMin?`${task.durationMin} min`:''}${task.effort?` • ${esc(task.effort)}`:''}</small><div><button type="button" data-move-task="${esc(task.id)}" data-from="${dateKey}">Move</button><button type="button" data-unavailable-task="${esc(task.id)}" data-date="${dateKey}">${task.unavailableOn?.includes(dateKey)?'Available':'Pause'}</button></div></div>`).join('')||'<small class="v17-muted">No flexible tasks yet</small>'}</section><footer>${load?`${load} min flexible`:''}${overloaded?'<span>♡ This day may be overloaded. Consider moving something.</span>':''}</footer></article>`}).join('');
  root.innerHTML=`<section class="v18-planner"><div class="v17-planner-hero"><div><div class="v18-badge">📅 KAT’S KORNER • WEEKLY PLANNING</div><h1>${monthName(month)}</h1><p>Future Kat gives tasks a day. TaskBot chooses the order later. ♡</p></div><div class="v17-planner-actions"><button type="button" data-today>Today</button><button type="button" data-prev aria-label="Previous month">‹</button><button type="button" data-next aria-label="Next month">›</button></div></div><section class="sm-weekly-planner"><header><div><h2>🍓 This week</h2><p class="v17-muted">Fixed events have times. Flexible tasks simply belong to a day.</p></div><button type="button" class="primary" data-add-event>＋ Fixed event</button></header><div class="sm-week-grid">${weekly}</div></section><div class="v17-calendar-wrap"><div class="v17-calendar-head">${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(day=>`<b>${day}</b>`).join('')}</div><div class="v17-calendar"><div class="v17-cal-grid">${cells}</div></div></div><div class="v18-planner-foot"><span>📖 Tap any date for its day review</span><button type="button" class="primary" data-add-event>＋ Add fixed event</button></div></section>`;
 };
  root.addEventListener('click',event=>{const target=event.target.closest?.('[data-day],[data-today],[data-prev],[data-next],[data-add-event],[data-plan-day],[data-move-task],[data-unavailable-task]');if(!target||!root.contains(target))return;event.preventDefault();if(target.matches('[data-day]')){selected=target.dataset.day;month=new Date(parse(selected).getFullYear(),parse(selected).getMonth(),1);draw();openDayReview()}else if(target.matches('[data-today]')){selected=key(new Date());month=new Date();month.setDate(1);draw();openDayReview()}else if(target.matches('[data-prev]')){month=new Date(month.getFullYear(),month.getMonth()-1,1);draw()}else if(target.matches('[data-next]')){month=new Date(month.getFullYear(),month.getMonth()+1,1);draw()}else if(target.matches('[data-plan-day]')){const text=window.prompt('Flexible task for this day?');if(text?.trim())createTask(store,{id:uid(),text:text.trim(),date:target.dataset.planDay,done:false})}else if(target.matches('[data-move-task]')){const date=window.prompt('Move this task to which date? (YYYY-MM-DD)',target.dataset.from);if(/^\d{4}-\d{2}-\d{2}$/.test(date||''))moveTask(store,String(target.dataset.moveTask),date)}else if(target.matches('[data-unavailable-task]')){const id=String(target.dataset.unavailableTask),date=target.dataset.date;store.update(data=>({...data,tasks:(data.tasks||[]).map(task=>String(task.id)!==id?task:{...task,unavailableOn:(task.unavailableOn||[]).includes(date)?task.unavailableOn.filter(value=>value!==date):[...(task.unavailableOn||[]),date]})}))}else openEventForm()});
 store.subscribe(draw);draw();
}
export{renderPlanner};
