const pad=n=>String(n).padStart(2,'0');
const key=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const parse=s=>{const [y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d,12)};
const monthName=d=>d.toLocaleDateString(undefined,{month:'long',year:'numeric'});
const dayName=d=>d.toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'});
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2);
const MOODS=['Loved','Happy','Calm','Tender','Excited','Confident','Okay','Meh','Blank','Sleepy','Drained','Overwhelmed','Sad','Sensitive','Frustrated','Irritated','Overloaded','Hopeful','Focused','Feeling cute'];
const moodEmoji={Loved:'🥰',Happy:'😊',Calm:'😌',Tender:'🥹',Excited:'🤩',Confident:'😎',Okay:'🙂',Meh:'😐',Blank:'😶',Sleepy:'😴',Drained:'🥱',Overwhelmed:'😮‍💨',Sad:'😔',Sensitive:'🥺',Frustrated:'😣',Irritated:'😤',Overloaded:'🤯',Hopeful:'🌱',Focused:'🧠','Feeling cute':'🎀'};

function renderPlanner({root,store}){
 let selected=key(new Date()),month=new Date();month.setDate(1);
 const dayData=(data,date=selected)=>data.days?.[date]||data.dayNotes?.[date]||{};
 const closeModal=box=>{box.remove();document.body.classList.remove('v17-modal-open')};
 const openEventForm=()=>{
  if(document.querySelector('.v18-event-modal'))return;
  const box=document.createElement('div');box.className='v17-modal v18-event-modal';box.setAttribute('role','dialog');box.setAttribute('aria-modal','true');
  box.innerHTML=`<div class="v17-modal-box"><button type="button" class="v17-modal-close" data-close aria-label="Close">×</button><h2>✨ Add event</h2><p class="v17-muted">Add something to ${esc(dayName(parse(selected)))}.</p><input id="evTitle" placeholder="Event or appointment" autocomplete="off"><div class="v17-planner-grid"><label><span>Date</span><input id="evDate" type="date" value="${selected}"></label><label><span>Start time</span><input id="evStart" type="time"></label><label><span>End time</span><input id="evEnd" type="time"></label></div><label class="v17-day-notes"><span>Notes</span><textarea id="evNotes" placeholder="Optional notes..."></textarea></label><div class="v17-modal-actions"><button type="button" data-close>Cancel</button><button type="button" id="saveEvent" class="primary">♡ Save event</button></div></div>`;
  document.body.appendChild(box);document.body.classList.add('v17-modal-open');
  const close=()=>closeModal(box);box.querySelectorAll('[data-close]').forEach(button=>button.onclick=close);box.onclick=event=>{if(event.target===box)close()};
  box.querySelector('#saveEvent').onclick=()=>{const title=box.querySelector('#evTitle').value.trim(),date=box.querySelector('#evDate').value||selected,start=box.querySelector('#evStart').value,end=box.querySelector('#evEnd').value;if(!title)return box.querySelector('#evTitle').focus();if(start&&end<start){box.querySelector('#evEnd').setCustomValidity('End time must be after the start time.');return box.querySelector('#evEnd').reportValidity()}store.update(data=>({...data,events:[...(data.events||[]),{id:uid(),title,date,start,end,notes:box.querySelector('#evNotes').value.trim()}]}));selected=date;month=new Date(parse(date).getFullYear(),parse(date).getMonth(),1);close();draw()};
 };
 const openDayReview=()=>{
  if(document.querySelector('.v18-day-review-modal'))return;
  const data=store.get(),note=dayData(data),tasks=(data.tasks||[]).filter(task=>task.date===selected),events=(data.events||[]).filter(event=>event.date===selected).sort((a,b)=>(a.start||'').localeCompare(b.start||''));
  const box=document.createElement('div');box.className='v18-day-review-modal';box.setAttribute('role','dialog');box.setAttribute('aria-modal','true');
  box.innerHTML=`<div class="v17-modal-box v18-day-review-box"><button type="button" class="v17-modal-close" data-close aria-label="Close">×</button><div class="v18-review-heading"><div class="v18-review-icon">📖</div><div><span class="v17-eyebrow">STRAWBERRY MOCHA • DAY REVIEW</span><h2>${esc(dayName(parse(selected)))}</h2><p class="v17-muted">A soft little place to remember, edit, and reset.</p></div></div><div class="v18-review-summary"><span>✓ ${tasks.filter(task=>task.done).length}/${tasks.length} tasks</span><span>✨ ${events.length} event${events.length===1?'':'s'}</span></div><section class="v18-review-section"><h3>📝 Your day</h3><div class="v17-planner-grid"><label><span>Mood</span><select id="reviewMood"><option value="">Choose gently…</option>${MOODS.map(mood=>`<option value="${esc(mood)}" ${note.mood===mood?'selected':''}>${moodEmoji[mood]} ${esc(mood)}</option>`).join('')}</select></label><label><span>Energy</span><select id="reviewEnergy"><option value="">Choose…</option>${['Low','Medium','High','Zoomies'].map(energy=>`<option value="${energy}" ${note.energy===energy?'selected':''}>${({Low:'🌙',Medium:'🌥',High:'☀️',Zoomies:'⚡'})[energy]} ${energy}</option>`).join('')}</select></label><label><span>Movement</span><input id="reviewMovement" placeholder="Walk, Pilates, stretching…" value="${esc(note.movement||'')}"></label></div><label class="v17-day-notes"><span>What happened today?</span><textarea id="reviewNotes" placeholder="The little moments count too…">${esc(note.notes||'')}</textarea></label></section><section class="v18-review-section"><h3>☀️ Tasks</h3>${tasks.map(task=>`<label class="v18-review-task"><input type="checkbox" data-review-task="${esc(task.id)}" ${task.done?'checked':''}><span>${esc(task.text||task.title||'Untitled task')}</span></label>`).join('')||'<p class="v17-empty">No tasks were planned for this day. ♡</p>'}</section><section class="v18-review-section"><h3>✨ Events</h3>${events.map(event=>`<div class="v17-event"><span><b>📌 ${esc(event.title)}</b><small>${esc(event.start||'Any time')}${event.end?` – ${esc(event.end)}`:''}</small>${event.notes?`<small>${esc(event.notes)}</small>`:''}</span></div>`).join('')||'<p class="v17-empty">Nothing scheduled yet. Add it from the planner. ♡</p>'}</section><div class="v17-modal-actions"><button type="button" data-close>Cancel</button><button type="button" id="saveDayReview" class="primary">♡ Save day review</button></div></div>`;
  document.body.appendChild(box);document.body.classList.add('v17-modal-open');
  const close=()=>closeModal(box);box.querySelectorAll('[data-close]').forEach(button=>button.onclick=close);box.onclick=event=>{if(event.target===box)close()};
  box.querySelector('#saveDayReview').onclick=()=>{const review={mood:box.querySelector('#reviewMood').value,energy:box.querySelector('#reviewEnergy').value,movement:box.querySelector('#reviewMovement').value.trim(),notes:box.querySelector('#reviewNotes').value.trim(),savedAt:new Date().toISOString()},checks=new Map([...box.querySelectorAll('[data-review-task]')].map(input=>[String(input.dataset.reviewTask),input.checked]));store.update(data=>({...data,days:{...(data.days||{}),[selected]:{...(data.days?.[selected]||{}),...review}},dayNotes:{...(data.dayNotes||{}),[selected]:{...(data.dayNotes?.[selected]||{}),...review}},tasks:(data.tasks||[]).map(task=>checks.has(String(task.id))?{...task,done:checks.get(String(task.id))}:task)}));close();draw()};
 };
 const draw=()=>{
  const data=store.get(),first=new Date(month.getFullYear(),month.getMonth(),1,12),start=(first.getDay()+7)%7,daysInMonth=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();let cells='';
  for(let index=0;index<start;index++)cells+='<div class="v17-cal-empty"></div>';
  for(let day=1;day<=daysInMonth;day++){const date=new Date(month.getFullYear(),month.getMonth(),day,12),dateKey=key(date),count=(data.events||[]).filter(event=>event.date===dateKey).length+(data.tasks||[]).filter(task=>task.date===dateKey).length,review=dayData(data,dateKey);cells+=`<button type="button" class="v17-day ${dateKey===selected?'selected':''} ${dateKey===key(new Date())?'today':''}" data-day="${dateKey}" aria-label="Open ${esc(dayName(date))}"><b>${day}</b>${count?`<span>${count}</span>`:review.notes||review.mood?'<span>♡</span>':''}</button>`}
  root.innerHTML=`<section class="v18-planner"><div class="v17-planner-hero"><div><div class="v18-badge">📅 STRAWBERRY MOCHA • PLANNER</div><h1>${monthName(month)}</h1><p>Tap a day to open its little review page. ♡</p></div><div class="v17-planner-actions"><button type="button" data-today>Today</button><button type="button" data-prev aria-label="Previous month">‹</button><button type="button" data-next aria-label="Next month">›</button></div></div><div class="v17-calendar-wrap"><div class="v17-calendar-head">${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(day=>`<b>${day}</b>`).join('')}</div><div class="v17-calendar"><div class="v17-cal-grid">${cells}</div></div></div><div class="v18-planner-foot"><span>📖 Tap any date for its day review</span><button type="button" class="primary" data-add-event>＋ Add event</button></div></section>`;
 };
 root.addEventListener('click',event=>{const target=event.target.closest?.('[data-day],[data-today],[data-prev],[data-next],[data-add-event]');if(!target||!root.contains(target))return;event.preventDefault();if(target.matches('[data-day]')){selected=target.dataset.day;month=new Date(parse(selected).getFullYear(),parse(selected).getMonth(),1);draw();openDayReview()}else if(target.matches('[data-today]')){selected=key(new Date());month=new Date();month.setDate(1);draw();openDayReview()}else if(target.matches('[data-prev]')){month=new Date(month.getFullYear(),month.getMonth()-1,1);draw()}else if(target.matches('[data-next]')){month=new Date(month.getFullYear(),month.getMonth()+1,1);draw()}else openEventForm()});
 store.subscribe(draw);draw();
}
export{renderPlanner};
