const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const makeId=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8);
const list=v=>Array.isArray(v)?v:(v&&typeof v==='object'?Object.values(v):[]);
const pad=n=>String(n).padStart(2,'0');
const dateKey=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const nextRepeat=(date,repeat)=>{const d=new Date(`${date||dateKey(new Date())}T12:00:00`);if(Number.isNaN(d.getTime()))return date||dateKey(new Date());if(repeat==='Daily')d.setDate(d.getDate()+1);else if(repeat==='Weekly')d.setDate(d.getDate()+7);else if(repeat==='Monthly')d.setMonth(d.getMonth()+1);else if(repeat==='Yearly')d.setFullYear(d.getFullYear()+1);return dateKey(d)};
function renderReminders({root,store}){
 let adding=false,editing=null;
 const draw=()=>{const d=store.get(),all=list(d.reminders),upcoming=all.filter(x=>!x.completed).sort((a,b)=>String(a.date||'').localeCompare(String(b.date||''))||String(a.time||'').localeCompare(String(b.time||''))),done=all.filter(x=>x.completed);const edit=editing?all.find(x=>String(x.id)===String(editing)):null;
 root.innerHTML=`<section class="v17-card"><div class="v17-home-hero"><div class="v17-eyebrow">🍓 KATOS • REMINDERS</div><div class="v17-home-heading"><div><h1>🔔 Reminders</h1><p>Keep the little things from becoming brain confetti. ♡</p></div><div class="v17-hero-berry">🎀</div></div></div><section class="v17-card"><header><div><h2>🔔 Upcoming</h2><p class="v17-muted">${upcoming.length} reminder${upcoming.length===1?'':'s'} waiting</p></div><button class="primary" id="toggleAdd">${adding?'× Close':'＋ Reminder'}</button></header>${upcoming.map(x=>`<article class="v17-reminder-row"><button class="v17-check" data-complete="${esc(x.id)}">○</button><div><b>${x.type==='Birthday'?'🎂 ':''}${esc(x.title||x.name||'Reminder')}</b><small>${esc(x.date||'No date')}${x.time?' • '+esc(x.time):''}${x.repeat?' • '+esc(x.repeat):''}</small></div><button data-snooze="${esc(x.id)}">💤 Snooze</button><button data-edit="${esc(x.id)}">✎</button><button data-delete="${esc(x.id)}">×</button></article>`).join('')||'<div class="v17-empty">✨ Nothing pending. Your future self is breathing easier.</div>'}</section><section class="v17-card"><header><h2>🌸 Completed</h2><span class="v17-pill">${done.length}</span></header>${done.map(x=>`<article class="v17-reminder-row completed"><button class="v17-check" data-complete="${esc(x.id)}">✓</button><div><b>${x.type==='Birthday'?'🎂 ':''}${esc(x.title||x.name||'Reminder')}</b><small>${esc(x.date||'No date')}${x.time?' • '+esc(x.time):''}</small></div><button data-edit="${esc(x.id)}">✎</button><button data-delete="${esc(x.id)}">×</button></article>`).join('')||'<div class="v17-empty">No completed reminders yet.</div>'}</section>${(adding||edit)?`<section class="v17-card"><header><h2>${edit?'✎ Edit Reminder':'＋ New Reminder'}</h2><button id="closeForm">×</button></header><div class="v17-money-form"><label>Type<select id="rType"><option ${edit?.type!=='Birthday'?'selected':''}>Reminder</option><option ${edit?.type==='Birthday'?'selected':''}>Birthday</option></select></label><input id="rTitle" placeholder="Reminder" value="${esc(edit?.title||edit?.name||'')}"><input id="rDate" type="date" value="${esc(edit?.date||'')}"><input id="rTime" type="time" value="${esc(edit?.time||'')}"><select id="rRepeat"><option value="">Doesn't repeat</option><option ${edit?.repeat==='Daily'?'selected':''}>Daily</option><option ${edit?.repeat==='Weekly'?'selected':''}>Weekly</option><option ${edit?.repeat==='Monthly'?'selected':''}>Monthly</option><option ${edit?.repeat==='Yearly'?'selected':''}>Yearly</option></select><p class="v17-muted">🎂 Birthday reminders repeat yearly. Completing a repeating reminder moves it to its next occurrence instead of losing it.</p><button class="primary" id="saveReminder">♡ ${edit?'Save changes':'Save reminder'}</button></div></section>`:''}</section>`;
 root.querySelector('#toggleAdd')?.addEventListener('click',()=>{adding=!adding;editing=null;draw()});root.querySelector('#closeForm')?.addEventListener('click',()=>{adding=false;editing=null;draw()});
 root.querySelector('#rType')?.addEventListener('change',e=>{if(e.target.value==='Birthday'){const repeat=root.querySelector('#rRepeat');if(repeat)repeat.value='Yearly'}});
 root.querySelector('#saveReminder')?.addEventListener('click',()=>{const type=root.querySelector('#rType').value;const item={id:edit?.id||makeId(),type,title:root.querySelector('#rTitle').value.trim(),date:root.querySelector('#rDate').value,time:root.querySelector('#rTime').value,repeat:type==='Birthday'?'Yearly':root.querySelector('#rRepeat').value,completed:edit?.completed||false};if(!item.title)return;store.update(x=>({...x,reminders:edit?list(x.reminders).map(v=>String(v.id)===String(edit.id)?{...v,...item}:v):[...list(x.reminders),item]}));adding=false;editing=null});
 root.querySelectorAll('[data-complete]').forEach(b=>b.onclick=()=>{const rid=b.dataset.complete;store.update(x=>({...x,reminders:list(x.reminders).map(v=>{if(String(v.id)!==rid)return v;if(v.completed)return{...v,completed:false};if(v.repeat)return{...v,date:nextRepeat(v.date,v.repeat),completed:false};return{...v,completed:true}})}))});
 root.querySelectorAll('[data-snooze]').forEach(b=>b.onclick=()=>{const rid=b.dataset.snooze,rem=all.find(v=>String(v.id)===String(rid));if(!rem)return;const choice=prompt('Snooze: type 1 for 2 hours, 2 for tomorrow, or 3 to pick a date.','2');if(!choice)return;let date=rem.date||dateKey(new Date()),time=rem.time||'';if(choice.trim()==='1'){const now=new Date();now.setHours(now.getHours()+2);date=dateKey(now);time=`${pad(now.getHours())}:${pad(now.getMinutes())}`}else if(choice.trim()==='2'){const tomorrow=new Date();tomorrow.setDate(tomorrow.getDate()+1);date=dateKey(tomorrow)}else if(choice.trim()==='3'){const picked=prompt('New reminder date (YYYY-MM-DD)',date);if(!/^\d{4}-\d{2}-\d{2}$/.test(picked||''))return;date=picked}else return;store.update(x=>({...x,reminders:list(x.reminders).map(v=>String(v.id)===String(rid)?{...v,date,time,completed:false}:v)}))});
 root.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{editing=b.dataset.edit;adding=false;draw()});root.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{const rid=b.dataset.delete;store.update(x=>({...x,reminders:list(x.reminders).filter(v=>String(v.id)!==rid)}))});
 };store.subscribe(draw);draw();
}
export{renderReminders};