const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const makeId=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8);
const list=v=>Array.isArray(v)?v:(v&&typeof v==='object'?Object.values(v):[]);
function renderReminders({root,store}){
 let adding=false,editing=null;
 const draw=()=>{const d=store.get(),all=list(d.reminders),upcoming=all.filter(x=>!x.completed).sort((a,b)=>String(a.date||'').localeCompare(String(b.date||''))||String(a.time||'').localeCompare(String(b.time||''))),done=all.filter(x=>x.completed);const edit=editing?all.find(x=>String(x.id)===String(editing)):null;
 root.innerHTML=`<section class="v17-card"><div class="v17-home-hero"><div class="v17-eyebrow">🍓 STRAWBERRY MOCHA • REMINDERS</div><div class="v17-home-heading"><div><h1>🔔 Reminders</h1><p>Keep the little things from becoming brain confetti. ♡</p></div><div class="v17-hero-berry">🎀</div></div></div><section class="v17-card"><header><div><h2>🔔 Upcoming</h2><p class="v17-muted">${upcoming.length} reminder${upcoming.length===1?'':'s'} waiting</p></div><button class="primary" id="toggleAdd">${adding?'× Close':'＋ Reminder'}</button></header>${upcoming.map(x=>`<article class="v17-reminder-row"><button class="v17-check" data-complete="${esc(x.id)}">○</button><div><b>${esc(x.title||x.name||'Reminder')}</b><small>${esc(x.date||'No date')}${x.time?' • '+esc(x.time):''}${x.repeat?' • '+esc(x.repeat):''}</small></div><button data-edit="${esc(x.id)}">✎</button><button data-delete="${esc(x.id)}">×</button></article>`).join('')||'<div class="v17-empty">✨ Nothing pending. Your future self is breathing easier.</div>'}</section><section class="v17-card"><header><h2>🌸 Completed</h2><span class="v17-pill">${done.length}</span></header>${done.map(x=>`<article class="v17-reminder-row completed"><button class="v17-check" data-complete="${esc(x.id)}">✓</button><div><b>${esc(x.title||x.name||'Reminder')}</b><small>${esc(x.date||'No date')}${x.time?' • '+esc(x.time):''}</small></div><button data-edit="${esc(x.id)}">✎</button><button data-delete="${esc(x.id)}">×</button></article>`).join('')||'<div class="v17-empty">No completed reminders yet.</div>'}</section>${(adding||edit)?`<section class="v17-card"><header><h2>${edit?'✎ Edit Reminder':'＋ New Reminder'}</h2><button id="closeForm">×</button></header><div class="v17-money-form"><input id="rTitle" placeholder="Reminder" value="${esc(edit?.title||edit?.name||'')}"><input id="rDate" type="date" value="${esc(edit?.date||'')}"><input id="rTime" type="time" value="${esc(edit?.time||'')}"><select id="rRepeat"><option value="">Doesn't repeat</option><option ${edit?.repeat==='Daily'?'selected':''}>Daily</option><option ${edit?.repeat==='Weekly'?'selected':''}>Weekly</option><option ${edit?.repeat==='Monthly'?'selected':''}>Monthly</option></select><button class="primary" id="saveReminder">♡ ${edit?'Save changes':'Save reminder'}</button></div></section>`:''}</section>`;
 root.querySelector('#toggleAdd')?.addEventListener('click',()=>{adding=!adding;editing=null;draw()});root.querySelector('#closeForm')?.addEventListener('click',()=>{adding=false;editing=null;draw()});
 root.querySelector('#saveReminder')?.addEventListener('click',()=>{const item={id:edit?.id||makeId(),title:root.querySelector('#rTitle').value.trim(),date:root.querySelector('#rDate').value,time:root.querySelector('#rTime').value,repeat:root.querySelector('#rRepeat').value,completed:edit?.completed||false};if(!item.title)return;store.update(x=>({...x,reminders:edit?list(x.reminders).map(v=>String(v.id)===String(edit.id)?item:v):[...list(x.reminders),item]}));adding=false;editing=null});
 root.querySelectorAll('[data-complete]').forEach(b=>b.onclick=()=>{const id=b.dataset.complete;store.update(x=>({...x,reminders:list(x.reminders).map(v=>String(v.id)===id?{...v,completed:!v.completed}:v)}))});root.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{editing=b.dataset.edit;adding=false;draw()});root.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{const id=b.dataset.delete;store.update(x=>({...x,reminders:list(x.reminders).filter(v=>String(v.id)!==id)}))});
 };store.subscribe(draw);draw();
}
export{renderReminders};