const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const id=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
const statuses=['Not Started','In Progress','Completed','Transferred'];
const pct=(n,d)=>d?Math.round(n/d*100):0;
const cp=c=>Math.max(0,Math.min(100,Number(c?.progress)||0));
const css=`.sm-school{--ink:#674941;--muted:#9a817b;--pink:#e99ab7;--soft:#fff0f5;--line:#eadbd6;color:var(--ink)}.sm-hero{background:linear-gradient(135deg,#f7d8e4,#fff9f2);border:1px solid #efd9df;border-radius:28px;padding:22px;margin-bottom:10px}.sm-title{font-size:30px;margin:4px 0}.sm-sub,.sm-muted{color:var(--muted);font-size:11px}.sm-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:9px 0}.sm-stat,.sm-card{background:rgba(255,253,251,.95);border:1px solid var(--line);border-radius:19px;padding:13px}.sm-stat small{display:block;color:#b96d88;font-size:9px;font-weight:900}.sm-stat b{display:block;font-size:21px;margin-top:3px}.sm-card{margin:10px 0}.sm-card h2{margin:0 0 4px;font-size:16px}.sm-bar{height:10px;background:#f0e5e5;border-radius:99px;overflow:hidden}.sm-bar i{display:block;height:100%;background:linear-gradient(90deg,#e99ab7,#cfe0b8);border-radius:99px;transition:width .25s}.sm-row{display:flex;justify-content:space-between;align-items:center;gap:8px}.sm-input,.sm-select,.sm-area{border:1px solid var(--line);border-radius:12px;background:#fff;color:var(--ink);padding:9px;font:inherit}.sm-area{width:100%;min-height:70px;resize:vertical;box-sizing:border-box}.sm-btn{border:1px solid var(--line);border-radius:12px;padding:9px 12px;background:#fff;color:var(--ink);font-weight:800}.sm-primary{background:linear-gradient(105deg,#e99ab7,#cfe0b8);color:#fff;border:0}.sm-danger{background:#fff3f5;color:#b96d88;border-color:#f0c7d5}.sm-two{display:grid;grid-template-columns:1fr 1fr;gap:10px}.sm-course,.sm-task,.sm-goal{border:1px solid var(--line);border-radius:16px;background:#fffaf6;padding:11px;margin:7px 0}.sm-course{cursor:pointer;text-align:left;width:100%;color:var(--ink)}.sm-task.done{opacity:.65}.sm-task.done .task-name{text-decoration:line-through}.sm-task input{accent-color:#e99ab7}.sm-list{margin-top:8px}.sm-form{display:grid;grid-template-columns:1.5fr .7fr 1fr auto;gap:7px}.sm-reflect{display:grid;grid-template-columns:1fr 1fr;gap:8px}.sm-reflect label{display:grid;gap:4px;color:var(--muted);font-size:10px;font-weight:800}.sm-reflect label:last-child{grid-column:1/-1}.sm-pill{background:#fff0f5;color:#b96d88;border-radius:99px;padding:5px 9px;font-size:9px;font-weight:900}.sm-empty{text-align:center;padding:18px;color:var(--muted);border:1px dashed var(--line);border-radius:15px}@media(max-width:800px){.sm-grid{grid-template-columns:1fr 1fr}.sm-two,.sm-reflect{grid-template-columns:1fr}.sm-reflect label:last-child{grid-column:auto}.sm-form{grid-template-columns:1fr 1fr}.sm-form button{grid-column:1/-1}}`;
function install(){if(document.getElementById('sm-school-v22-style'))return;const s=document.createElement('style');s.id='sm-school-v22-style';s.textContent=css;document.head.appendChild(s)}
function renderSchool({root,store}){install();let selected=null,adding=false,addingTask=false,addingGoal=false;
 const draw=()=>{const d=store.get(),courses=d.courses||[],tasks=d.schoolTasks||[],goals=d.schoolGoals||[],total=Math.max(Number(d.totalClasses)||courses.length,1),completed=courses.filter(c=>['Completed','Transferred'].includes(c.status)).length,degree=pct(completed,total),current=courses.find(c=>c.status==='In Progress'),course=selected?courses.find(c=>String(c.id)===String(selected)):null;const upcoming=tasks.filter(t=>!t.done&&t.due).sort((a,b)=>String(a.due).localeCompare(String(b.due))).slice(0,5);
 root.innerHTML=`<div class="sm-school"><section class="sm-hero"><div class="v17-eyebrow">🍓 STRAWBERRY MOCHA • MY LITTLE CLASSROOM</div><h1 class="sm-title">My Little Classroom. 🎓</h1><div class="sm-sub">One class at a time. Keep the wins, questions, deadlines, and little victories in one cozy place. ♡</div></section><div class="sm-grid"><div class="sm-stat"><small>DEGREE PROGRESS</small><b>${degree}%</b></div><div class="sm-stat"><small>COMPLETED</small><b>${completed}/${total}</b></div><div class="sm-stat"><small>IN PROGRESS</small><b>${courses.filter(c=>c.status==='In Progress').length}</b></div><div class="sm-stat"><small>TASKS LEFT</small><b>${tasks.filter(t=>!t.done).length}</b></div></div>
 <section class="sm-card"><div class="sm-row"><div><h2>🎓 Degree progress</h2><div class="sm-muted">${completed} completed out of ${total} total classes</div></div><span class="sm-pill">${degree}%</span></div><div class="sm-bar" style="margin-top:10px"><i style="width:${degree}%"></i></div><div class="sm-row" style="margin-top:9px"><input class="sm-input" id="totalClasses" type="number" min="1" value="${Number(d.totalClasses)||''}" placeholder="Total classes"><button class="sm-btn sm-primary" id="saveTotal">♡ Save total</button></div></section>
 <div class="sm-two"><section class="sm-card"><div class="sm-row"><div><h2>📚 Current class</h2><div class="sm-muted">Your main focus right now.</div></div></div>${current?`<button class="sm-course" data-open="${esc(current.id)}"><b>${esc(current.name)}</b><div class="sm-row"><span class="sm-muted">${esc(current.status)}</span><strong>${cp(current)}%</strong></div><div class="sm-bar"><i style="width:${cp(current)}%"></i></div></button>`:'<div class="sm-empty">🌱 Mark one course In Progress to make it your focus.</div>'}</section>
 <section class="sm-card"><div class="sm-row"><div><h2>📅 Coming up</h2><div class="sm-muted">Your next little deadlines.</div></div><span class="sm-pill">${upcoming.length}</span></div>${upcoming.map(t=>`<div class="sm-task"><b>${esc(t.name)}</b><div class="sm-muted">${esc(t.course||'School')} • ${esc(t.due)}</div></div>`).join('')||'<div class="sm-empty">✨ Nothing due yet.</div>'}</section></div>
 <section class="sm-card"><div class="sm-row"><div><h2>📚 Course shelf</h2><div class="sm-muted">Tap a course to open its home base.</div></div><span class="sm-pill">${courses.length} courses</span></div>${courses.map((c,i)=>`<button class="sm-course" data-open="${esc(c.id)}"><div class="sm-row"><b>${['📖','🌷','🧁','⭐','📝'][i%5]} ${esc(c.name||'Untitled course')}</b><strong>${cp(c)}%</strong></div><div class="sm-muted">${esc(c.status||'Not Started')}</div><div class="sm-bar"><i style="width:${cp(c)}%"></i></div></button>`).join('')||'<div class="sm-empty">📚 Add your first course below.</div>'}</section>
 <section class="sm-card"><div class="sm-row"><div><h2>📝 School tasks</h2><div class="sm-muted">Assignments, exams, readings, projects, and tiny next steps.</div></div><button class="sm-btn sm-primary" id="toggleTask">＋ Task</button></div>${addingTask?`<div class="sm-form" style="margin-top:9px"><input class="sm-input" id="taskName" placeholder="Task name"><input class="sm-input" id="taskDue" type="date"><input class="sm-input" id="taskCourse" placeholder="Course"><button class="sm-btn sm-primary" id="saveTask">Save</button></div>`:''}<div class="sm-list">${tasks.map(t=>`<div class="sm-task ${t.done?'done':''}"><div class="sm-row"><label><input type="checkbox" data-task="${esc(t.id)}" ${t.done?'checked':''}> <span class="task-name">${esc(t.name)}</span></label><span class="sm-muted">${esc(t.due||'No due date')}</span></div><div class="sm-muted">${esc(t.course||'School')}</div></div>`).join('')||'<div class="sm-empty">🌱 No school tasks yet.</div>'}</div></section>
 <section class="sm-card"><div class="sm-row"><div><h2>🎯 Course goals</h2><div class="sm-muted">Keep the next few wins small and visible.</div></div><button class="sm-btn sm-primary" id="toggleGoal">＋ Goal</button></div>${addingGoal?`<div class="sm-form" style="margin-top:9px"><input class="sm-input" id="goalName" placeholder="Goal"><input class="sm-input" id="goalCourse" placeholder="Course"><button class="sm-btn sm-primary" id="saveGoal">Save</button></div>`:''}<div class="sm-list">${goals.map(g=>`<div class="sm-goal"><label><input type="checkbox" data-goal="${esc(g.id)}" ${g.done?'checked':''}> ${esc(g.name)}</label><div class="sm-muted">${esc(g.course||'School')}</div></div>`).join('')||'<div class="sm-empty">🌱 No course goals yet.</div>'}</div></section>
 ${course?`<section class="sm-card"><div class="sm-row"><div><h2>🎓 ${esc(course.name)}</h2><div class="sm-muted">Course home base</div></div><button class="sm-btn" id="closeCourse">×</button></div><div class="sm-two" style="margin-top:10px"><label class="sm-muted">Progress %<input class="sm-input" id="editProgress" type="number" min="0" max="100" value="${cp(course)}"></label><label class="sm-muted">Status<select class="sm-select" id="editStatus">${statuses.map(s=>`<option ${s===course.status?'selected':''}>${s}</option>`).join('')}</select></label></div><h3>📝 Class reflection</h3><div class="sm-reflect"><label>What did I learn?<textarea class="sm-area" id="rLearn">${esc(course.reflection?.learn||'')}</textarea></label><label>What was confusing?<textarea class="sm-area" id="rHard">${esc(course.reflection?.hard||'')}</textarea></label><label>What am I proud of?<textarea class="sm-area" id="rProud">${esc(course.reflection?.proud||'')}</textarea></label><label>What should I work on?<textarea class="sm-area" id="rWork">${esc(course.reflection?.work||'')}</textarea></label><label>Overall thoughts<textarea class="sm-area" id="rOverall">${esc(course.reflection?.overall||'')}</textarea></label></div><div class="sm-row" style="margin-top:9px"><button class="sm-btn sm-danger" id="archiveCourse">🗄 Archive course</button><button class="sm-btn sm-primary" id="saveCourse">♡ Save course</button></div></section>`:''}
 <section class="sm-card"><div class="sm-row"><div><h2>🌱 Add a course</h2><div class="sm-muted">Set it up once, then grow it as you go.</div></div><button class="sm-btn sm-primary" id="toggleAdd">＋ Add course</button></div>${adding?`<div class="sm-form" style="margin-top:9px"><input class="sm-input" id="newCourse" placeholder="Course name"><input class="sm-input" id="newProgress" type="number" min="0" max="100" value="0"><select class="sm-select" id="newStatus">${statuses.map(s=>`<option>${s}</option>`).join('')}</select><button class="sm-btn sm-primary" id="addCourse">♡ Add</button></div>`:''}</section></div>`;
 root.querySelector('#saveTotal')?.addEventListener('click',()=>{const n=Math.max(1,Number(root.querySelector('#totalClasses').value)||1);store.update(x=>({...x,totalClasses:n}))});
 root.querySelector('#toggleTask')?.addEventListener('click',()=>{addingTask=!addingTask;draw()});
 root.querySelector('#saveTask')?.addEventListener('click',()=>{const n=root.querySelector('#taskName').value.trim();if(!n)return;store.update(x=>({...x,schoolTasks:[...(x.schoolTasks||[]),{id:id(),name:n,due:root.querySelector('#taskDue').value,course:root.querySelector('#taskCourse').value.trim(),done:false}]}));addingTask=false});
 root.querySelectorAll('[data-task]').forEach(e=>e.addEventListener('change',()=>store.update(x=>({...x,schoolTasks:(x.schoolTasks||[]).map(t=>String(t.id)===String(e.dataset.task)?{...t,done:e.checked}:t)}))));
 root.querySelector('#toggleGoal')?.addEventListener('click',()=>{addingGoal=!addingGoal;draw()});
 root.querySelector('#saveGoal')?.addEventListener('click',()=>{const n=root.querySelector('#goalName').value.trim();if(!n)return;store.update(x=>({...x,schoolGoals:[...(x.schoolGoals||[]),{id:id(),name:n,course:root.querySelector('#goalCourse').value.trim(),done:false}]}));addingGoal=false});
 root.querySelectorAll('[data-goal]').forEach(e=>e.addEventListener('change',()=>store.update(x=>({...x,schoolGoals:(x.schoolGoals||[]).map(g=>String(g.id)===String(e.dataset.goal)?{...g,done:e.checked}:g)}))));
 root.querySelectorAll('[data-open]').forEach(e=>e.addEventListener('click',()=>{selected=e.dataset.open;draw()}));root.querySelector('#closeCourse')?.addEventListener('click',()=>{selected=null;draw()});
 root.querySelector('#saveCourse')?.addEventListener('click',()=>{let p=Math.max(0,Math.min(100,Number(root.querySelector('#editProgress').value)||0)),s=root.querySelector('#editStatus').value;if(['Completed','Transferred'].includes(s))p=100;store.update(x=>({...x,courses:(x.courses||[]).map(c=>String(c.id)===String(selected)?{...c,progress:p,status:s,reflection:{learn:root.querySelector('#rLearn').value,hard:root.querySelector('#rHard').value,proud:root.querySelector('#rProud').value,work:root.querySelector('#rWork').value,overall:root.querySelector('#rOverall').value}}:c)}))});
 root.querySelector('#archiveCourse')?.addEventListener('click',()=>{const item=(store.get().courses||[]).find(c=>String(c.id)===String(selected));if(!item)return;store.update(x=>({...x,courses:(x.courses||[]).filter(c=>String(c.id)!==String(selected)),archive:[...(x.archive||[]),{type:'course',item,archivedAt:new Date().toISOString()}]}));selected=null});
 root.querySelector('#toggleAdd')?.addEventListener('click',()=>{adding=!adding;draw()});root.querySelector('#addCourse')?.addEventListener('click',()=>{const n=root.querySelector('#newCourse').value.trim();if(!n)return;let p=Math.max(0,Math.min(100,Number(root.querySelector('#newProgress').value)||0)),s=root.querySelector('#newStatus').value;if(['Completed','Transferred'].includes(s))p=100;store.update(x=>({...x,courses:[...(x.courses||[]),{id:id(),name:n,progress:p,status:s,reflection:{}}]}));adding=false});
 };store.subscribe(draw);draw()}
export{renderSchool};