const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const makeId=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8);
const list=v=>Array.isArray(v)?v:(v&&typeof v==='object'?Object.values(v):[]);
function renderWellness({root,store}){
 let adding=false,editing=null;
 const draw=()=>{const d=store.get(),w=d.wellness||{},entries=list(w.entries),today=new Date().toISOString().slice(0,10),todayEntries=entries.filter(x=>x.date===today),avgMood=todayEntries.length?Math.round(todayEntries.reduce((n,x)=>n+Number(x.mood||0),0)/todayEntries.length):0,edit=editing?entries.find(x=>String(x.id)===String(editing)):null;
 root.innerHTML=`<section class="v17-card"><div class="v17-home-hero"><div class="v17-eyebrow">🍓 STRAWBERRY MOCHA • WELLNESS</div><div class="v17-home-heading"><div><h1>🌸 Wellness</h1><p>A gentle place to check in with yourself. No perfection required. ♡</p></div><div class="v17-hero-berry">🌷</div></div></div><section class="v17-card"><header><div><h2>🌸 Today's Check-In</h2><p class="v17-muted">${todayEntries.length} check-in${todayEntries.length===1?'':'s'} today</p></div><strong>${avgMood?avgMood+'/5':'—'}</strong></header><div class="v17-wellness-stats"><div><b>💧</b><span>Water</span><strong>${todayEntries.reduce((n,x)=>n+Number(x.water||0),0)} cups</strong></div><div><b>😌</b><span>Mood</span><strong>${avgMood?avgMood+'/5':'Not logged'}</strong></div><div><b>😴</b><span>Sleep</span><strong>${todayEntries[0]?.sleep?esc(todayEntries[0].sleep)+'h':'Not logged'}</strong></div></div></section><section class="v17-card"><header><div><h2>📝 Wellness Log</h2><p class="v17-muted">Track what actually matters to you.</p></div><button class="primary" id="toggleAdd">${adding?'× Close':'＋ Check-in'}</button></header>${entries.sort((a,b)=>String(b.date||'').localeCompare(String(a.date||''))).map(x=>`<article class="v17-wellness-row"><div><b>${esc(x.date||'No date')}</b><small>${x.mood?'Mood '+esc(x.mood)+'/5':''}${x.sleep?' • Sleep '+esc(x.sleep)+'h':''}${x.water?' • Water '+esc(x.water)+' cups':''}</small>${x.note?`<p>${esc(x.note)}</p>`:''}</div><button data-edit="${esc(x.id)}">✎</button><button data-delete="${esc(x.id)}">×</button></article>`).join('')||'<div class="v17-empty">🌷 No check-ins yet. Start gently.</div>'}</section>${adding||edit?`<section class="v17-card"><header><h2>${edit?'✎ Edit Check-In':'＋ Wellness Check-In'}</h2><button id="closeForm">×</button></header><div class="v17-money-form"><input id="wDate" type="date" value="${esc(edit?.date||today)}"><label>Mood (1–5)<input id="wMood" type="number" min="1" max="5" value="${esc(edit?.mood||'')}"></label><label>Sleep hours<input id="wSleep" type="number" min="0" max="24" step="0.5" value="${esc(edit?.sleep||'')}"></label><label>Water cups<input id="wWater" type="number" min="0" step="1" value="${esc(edit?.water||'')}"></label><textarea id="wNote" placeholder="How are you feeling?">${esc(edit?.note||'')}</textarea><button class="primary" id="saveWellness">♡ ${edit?'Save changes':'Save check-in'}</button></div></section>`:''}</section>`;
 root.querySelector('#toggleAdd')?.addEventListener('click',()=>{adding=!adding;editing=null;draw()});root.querySelector('#closeForm')?.addEventListener('click',()=>{adding=false;editing=null;draw()});root.querySelector('#saveWellness')?.addEventListener('click',()=>{const item={id:edit?.id||makeId(),date:root.querySelector('#wDate').value,mood:Number(root.querySelector('#wMood').value)||0,sleep:Number(root.querySelector('#wSleep').value)||0,water:Number(root.querySelector('#wWater').value)||0,note:root.querySelector('#wNote').value};store.update(x=>({...x,wellness:{...(x.wellness||{}),entries:edit?list(x.wellness?.entries).map(v=>String(v.id)===String(edit.id)?item:v):[...list(x.wellness?.entries),item]}}));adding=false;editing=null});root.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{editing=b.dataset.edit;adding=false;draw()});root.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{const id=b.dataset.delete;store.update(x=>({...x,wellness:{...(x.wellness||{}),entries:list(x.wellness?.entries).filter(v=>String(v.id)!==id)}}))});
 };store.subscribe(draw);draw();
}
export{renderWellness};