const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const makeId=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8);
const list=v=>Array.isArray(v)?v:(v&&typeof v==='object'?Object.values(v):[]);
function renderWins({root,store}){
 let adding=false,editing=null;
 const draw=()=>{const d=store.get(),all=list(d.wins),edit=editing?all.find(x=>String(x.id)===String(editing)):null;
 root.innerHTML=`<section class="v17-card"><div class="v17-home-hero"><div class="v17-eyebrow">🍓 STRAWBERRY MOCHA • WINS</div><div class="v17-home-heading"><div><h1>🏆 Wins</h1><p>Proof that you did more than your brain gives you credit for. ♡</p></div><div class="v17-hero-berry">🏆</div></div></div><section class="v17-card"><header><div><h2>🏆 My Wins</h2><p class="v17-muted">${all.length} win${all.length===1?'':'s'} collected</p></div><button class="primary" id="toggleWin">${adding?'× Close':'＋ Win'}</button></header>${all.map(x=>`<article class="v17-win-row"><div class="v17-win-icon">${esc(x.emoji||'🏆')}</div><div><b>${esc(x.title||x.name||'Untitled win')}</b><small>${esc(x.date||'No date')}${x.category?' • '+esc(x.category):''}</small>${x.note?`<p>${esc(x.note)}</p>`:''}</div><button data-edit="${esc(x.id)}">✎</button><button data-delete="${esc(x.id)}">×</button></article>`).join('')||'<div class="v17-empty">✨ Your first win is waiting to be celebrated.</div>'}</section>${adding||edit?`<section class="v17-card"><header><h2>${edit?'✎ Edit Win':'＋ Celebrate a Win'}</h2><button id="closeWin">×</button></header><div class="v17-money-form"><input id="winTitle" placeholder="What did you accomplish?" value="${esc(edit?.title||edit?.name||'')}"><input id="winDate" type="date" value="${esc(edit?.date||new Date().toISOString().slice(0,10))}"><input id="winCategory" placeholder="Category" value="${esc(edit?.category||'')}"><input id="winEmoji" placeholder="Emoji" value="${esc(edit?.emoji||'🏆')}"><textarea id="winNote" placeholder="Why are you proud of this?">${esc(edit?.note||'')}</textarea><button class="primary" id="saveWin">♡ ${edit?'Save changes':'Save win'}</button></div></section>`:''}</section>`;
 root.querySelector('#toggleWin')?.addEventListener('click',()=>{adding=!adding;editing=null;draw()});root.querySelector('#closeWin')?.addEventListener('click',()=>{adding=false;editing=null;draw()});root.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{editing=b.dataset.edit;adding=false;draw()});root.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{const id=b.dataset.delete;store.update(x=>({...x,wins:list(x.wins).filter(v=>String(v.id)!==id)}))});root.querySelector('#saveWin')?.addEventListener('click',()=>{const title=root.querySelector('#winTitle').value.trim();if(!title)return;const item={id:edit?.id||makeId(),title,date:root.querySelector('#winDate').value,category:root.querySelector('#winCategory').value.trim(),emoji:root.querySelector('#winEmoji').value.trim()||'🏆',note:root.querySelector('#winNote').value};store.update(x=>({...x,wins:edit?list(x.wins).map(v=>String(v.id)===String(edit.id)?item:v):[...list(x.wins),item]}));adding=false;editing=null});
 };store.subscribe(draw);draw();
}
export{renderWins};