import assert from'node:assert/strict';
import{webcrypto}from'node:crypto';
import{readFile}from'node:fs/promises';
import{APPROVED_CANONICAL_COUNTS,APPROVED_CANONICAL_RECOVERY,CANONICAL_RECOVERY_BACKUP_PREFIX,CANONICAL_RECOVERY_BUILD,CanonicalRecoveryCloudClient,RECOVERY_FAILURE_CODES,createOneTimeCanonicalRecovery}from'./sync-canonical-recovery.js';
import{canonicalContent,diagnoseCanonicalState,hashCanonicalState,stableSerialize}from'./sync-envelope.js';
import{countCanonicalCollections}from'./sync-diagnostics.js';
import{CANONICAL_ROLLBACK_MARKER}from'./sync-canonical-recovery.js';
import{STORAGE_KEYS,auxiliaryDefaults}from'./sync-storage.js';
import{SYNC_STATES}from'./sync-engine.js';

globalThis.crypto??=webcrypto;
class MemoryStorage{constructor(values={}){this.values=new Map(Object.entries(values));this.setCalls=[];this.removeCalls=[];this.clearCalls=0}get length(){return this.values.size}key(i){return[...this.values.keys()][i]??null}getItem(k){return this.values.has(k)?this.values.get(k):null}setItem(k,v){this.setCalls.push(String(k));this.values.set(String(k),String(v))}removeItem(k){this.removeCalls.push(String(k));this.values.delete(String(k))}clear(){this.clearCalls++;this.values.clear()}}

const localState={schemaVersion:4,life:{tasks:[{id:'task-1',title:'Current task'}],reminders:[],routines:[{id:'routine-mtqi367v-ii32b9',name:'Shower',active:true}],routineInstances:[{id:'routine-instance-mtj2k0ev-q4dwcz',routineId:'msxx950a731b42',date:'2026-09-01'}],events:[]},money:{savingsGoals:[],hq:{accounts:[],transactions:[],bills:[],billInstances:[],subscriptions:[],goals:[]}},work:{gig:{platforms:[],orders:[],payouts:[],goals:[]},gigShifts:[],hq:{clients:[],supervisors:[],sessionPlans:[],scheduleExceptions:[],goalLibrary:[],materialLibrary:[]}},education:{programs:[],courses:[],requirements:[],items:[],transferResults:[],transferEvaluations:[],terms:[]},lifestyle:{movement:{plans:[]},hobbies:{items:[]},growth:{goals:[]}},v4:{brainDump:[],archive:[{archivedAt:'2026-09-01T19:37:52.581Z',id:'msxx950a731b42',kind:'routine'}],mochiniLife:{mood:'content'}}};
const cloudState=structuredClone(localState);cloudState.life.tasks[0].title='Older cloud task';const auxiliary=auxiliaryDefaults();
async function envelope(state,revision,device=null){const content=canonicalContent(state,auxiliary);return{format:'katos-sync-envelope',schemaVersion:1,revision,updatedAt:null,updatedByDevice:device,contentHash:await hashCanonicalState(content),...content}}
const snapshotState=structuredClone(cloudState);snapshotState.life.events.push({id:'msxwag4n2tv1ea4f39g',title:'Car cleaning'},{id:'msy2xzqx6r4lpkhkjbj',title:'Hang out with Isaac'});snapshotState.life.routines.push({id:'msxx8rtpzuwg2u',name:'Take my meds'},{id:'msxx9l8508co7t',name:'Wrap my hair'},{id:'mszezukzwnbpkd',name:'Pilates'});snapshotState.v4.archive.push({id:'archive-mtlvhq97-9rhefb',title:'I need to get Isaac a birthday gift'});
const local=await envelope(localState,null),oldCloud=await envelope(cloudState,5,'accepted-recovery'),snapshot=await envelope(snapshotState,4,'recovery-finalize'),counts=countCanonicalCollections(local);
const config={localHash:local.contentHash,cloudRevision:5,cloudHash:oldCloud.contentHash,snapshotRevision:4,snapshotHash:snapshot.contentHash,localSource:STORAGE_KEYS.renderedPlanner,localPlannerSchema:4,localSerializedBytes:diagnoseCanonicalState(local).serializedBytes,counts};
const storageValues=()=>({[STORAGE_KEYS.recoveryLock]:'1',[STORAGE_KEYS.renderedPlanner]:JSON.stringify({data:localState}),[STORAGE_KEYS.ledger]:JSON.stringify(auxiliary[STORAGE_KEYS.ledger]),[STORAGE_KEYS.dailyNotes]:JSON.stringify(auxiliary[STORAGE_KEYS.dailyNotes]),[STORAGE_KEYS.roomDetails]:JSON.stringify(auxiliary[STORAGE_KEYS.roomDetails]),[STORAGE_KEYS.spendingBudgets]:JSON.stringify(auxiliary[STORAGE_KEYS.spendingBudgets]),sm_v4_beta_before_restore_1:'preserve'});

class FakeCloud{
  constructor(mode='success',snapshotValid=true){this.envelope=structuredClone(oldCloud);this.row={data:{legacy:'cloud-five'},revision:5,content_hash:null,last_device_id:'accepted-recovery'};this.calls=[];this.mode=mode;this.snapshotValid=snapshotValid;this.userId='user-1'}
  async current(){this.calls.push('current');if(this.badReadOnce){this.badReadOnce=false;return{envelope:{...structuredClone(this.envelope),contentHash:'f'.repeat(64)},row:structuredClone(this.row),userId:this.userId}}return{envelope:structuredClone(this.envelope),row:structuredClone(this.row),userId:this.userId}}
  async prepareRollbackSnapshot(args){this.calls.push('prepare');assert.equal(args.expectedRevision,5);assert.deepEqual(args.expectedData,{legacy:'cloud-five'});return{userId:this.userId,row:{status:'OK',snapshot_id:'snapshot-five'}}}
  async snapshotById(id){this.calls.push('snapshot-read');const hash=this.snapshotValid?oldCloud.contentHash:'0'.repeat(64);return{userId:this.userId,row:{id,user_id:this.userId,data:{legacy:'cloud-five'},revision:5,reason:CANONICAL_ROLLBACK_MARKER,content_hash:hash,created_at:'2026-09-09T00:00:00Z'},envelope:{...structuredClone(oldCloud),contentHash:hash}}}
  async promote(args){this.calls.push('promote');assert.equal(Object.isFrozen(args.newData),true);this.promotedData=structuredClone(args.newData);this.envelope={...structuredClone(args.newData),revision:6,updatedByDevice:'device-test'};this.row={data:structuredClone(args.newData),revision:6,content_hash:local.contentHash,last_device_id:'device-test'};if(this.mode==='bad')this.badReadOnce=true;if(this.mode==='concurrent'){this.envelope={...structuredClone(oldCloud),revision:7,contentHash:'e'.repeat(64)};this.row={data:{thirdParty:true},revision:7,content_hash:'e'.repeat(64)}}return{userId:this.userId,row:{status:'OK',new_revision:6,stored_hash:local.contentHash}}}
  async rollback(args){this.calls.push('rollback');assert.equal(args.expectedFailedRevision,6);this.envelope={...structuredClone(oldCloud),revision:7,updatedByDevice:'automatic-rollback'};this.row={data:{legacy:'cloud-five'},revision:7,content_hash:oldCloud.contentHash};return{userId:this.userId,row:{status:'OK',new_revision:7,stored_hash:oldCloud.contentHash}}}
}
const engine=()=>({state:SYNC_STATES.PAUSED,canWriteCloud:()=>false,fetchCloudDiagnostics:async()=>({ok:true,envelope:structuredClone(oldCloud)}),fetchCloudSnapshot:async()=>({ok:true,envelope:structuredClone(snapshot)})});

assert.equal(CANONICAL_RECOVERY_BUILD,'7.0.7-one-time-canonical-recovery');assert.equal(APPROVED_CANONICAL_RECOVERY.localHash,'b67b18371ee35accee0b5f5d8aee39f4651429ee5c0322dfe83528abac1b9504');assert.equal(APPROVED_CANONICAL_COUNTS.money.transactions,42);assert.equal(APPROVED_CANONICAL_COUNTS.gigWork.plannedShifts,9);assert.equal(APPROVED_CANONICAL_COUNTS.other.archive,39);

const storage=new MemoryStorage(storageValues()),cloud=new FakeCloud(),controller=createOneTimeCanonicalRecovery({storage,engine:engine(),cloudClient:cloud,config,deviceId:'device-test',now:()=>1788920000000});
const before=stableSerialize([...storage.values]);const unconfirmed=await controller.run({confirmed:false});assert.equal(unconfirmed.failureCode,RECOVERY_FAILURE_CODES.CONFIRMATION_REQUIRED);assert.equal(cloud.calls.length,0);assert.equal(stableSerialize([...storage.values]),before,'recovery never runs on load or diagnostics');
const result=await controller.run({confirmed:true});assert.equal(result.ok,true,result.text);assert.equal(result.status,'RECOVERY COMPLETE — CLOUD MATCHES IPAD');assert.equal(result.postWriteCloud.revision,6);assert.equal(result.postWriteCloud.hash,local.contentHash);assert.equal(result.integrityPassed,18);assert.equal(result.recoveryMode,true);assert.equal(result.syncState,'PAUSED');assert.equal(result.rollbackSnapshot.verified,true);assert.equal(result.localBackup.verified,true);assert.match(result.localBackup.key,new RegExp(`^${CANONICAL_RECOVERY_BACKUP_PREFIX}`));assert.match(result.text,/Canonical equality with iPad: PASS/);assert.match(result.text,/18\/18 PASS/);assert.doesNotMatch(result.text,/access_token|refresh_token|Bearer /i);
assert.deepEqual(cloud.calls,['current','current','prepare','snapshot-read','promote','current']);assert.equal(storage.setCalls.length,1);assert.equal(storage.setCalls[0],result.localBackup.key);assert.equal(storage.setCalls.some(key=>[STORAGE_KEYS.renderedPlanner,STORAGE_KEYS.planner,STORAGE_KEYS.ledger,STORAGE_KEYS.dailyNotes,STORAGE_KEYS.roomDetails,STORAGE_KEYS.spendingBudgets,STORAGE_KEYS.recoveryLock].includes(key)),false);assert.deepEqual(storage.removeCalls,[]);assert.equal(storage.clearCalls,0);
assert.equal(cloud.promotedData.plannerState.life.tasks[0].title,'Current task');assert.equal(cloud.promotedData.plannerState.v4.archive.some(row=>row.id==='msxx950a731b42'),true);assert.equal(cloud.promotedData.plannerState.life.routines.some(row=>row.id==='msxx950a731b42'),false);assert.equal((await controller.run({confirmed:true})).idempotent,true);assert.equal(cloud.calls.filter(call=>call==='promote').length,1);

const failed=async(overrides,mode='success',snapshotValid=true)=>{const c=new FakeCloud(mode,snapshotValid),s=new MemoryStorage(storageValues()),r=await createOneTimeCanonicalRecovery({storage:s,engine:engine(),cloudClient:c,config:{...config,...overrides},deviceId:'device-test'}).run({confirmed:true});return{c,s,r}};
assert.equal((await failed({localHash:'0'.repeat(64)})).r.failureCode,RECOVERY_FAILURE_CODES.LOCAL_HASH_CHANGED);assert.equal((await failed({counts:{...counts,dailyShit:{...counts.dailyShit,tasks:2}}})).r.failureCode,RECOVERY_FAILURE_CODES.LOCAL_COUNTS_CHANGED);
const badSnapshot=await failed({},'success',false);assert.equal(badSnapshot.r.failureCode,RECOVERY_FAILURE_CODES.ROLLBACK_SNAPSHOT_VERIFY_FAILED);assert.equal(badSnapshot.c.calls.includes('promote'),false);
const rolledBack=await failed({},'bad');assert.equal(rolledBack.r.status,'RECOVERY VERIFICATION FAILED');assert.equal(rolledBack.r.rollback.succeeded,true);assert.equal(rolledBack.c.calls.includes('rollback'),true);
const concurrent=await failed({},'concurrent');assert.equal(concurrent.r.failureCode,RECOVERY_FAILURE_CODES.MANUAL_CLOUD_INTERVENTION_REQUIRED);assert.equal(concurrent.r.rollback.refused,true);assert.equal(concurrent.c.calls.includes('rollback'),false);

let release;const gate=new Promise(resolve=>release=resolve),lockingCloud=new FakeCloud();lockingCloud.current=async()=>{lockingCloud.calls.push('current');await gate;return{envelope:structuredClone(oldCloud),row:structuredClone(lockingCloud.row),userId:'user-1'}};const locking=createOneTimeCanonicalRecovery({storage:new MemoryStorage(storageValues()),engine:engine(),cloudClient:lockingCloud,config,deviceId:'device-test'}),first=locking.run({confirmed:true}),double=await locking.run({confirmed:true});assert.equal(double.failureCode,RECOVERY_FAILURE_CODES.OPERATION_IN_PROGRESS);release();await first;

let rpcOptions;const injectedEngine={authentication:async()=>({state:'AUTHENTICATED',session:{access_token:'token',user:{id:'user-1'}}}),requestEndpoint:async(_url,session,options)=>{rpcOptions=options;return{response:{ok:true,json:async()=>[{status:'OK',snapshot_id:'snapshot'}]},session,authFailure:null}}};const rpcClient=new CanonicalRecoveryCloudClient({engine:injectedEngine});assert.equal((await rpcClient.prepareRollbackSnapshot({expectedRevision:5,expectedData:{a:1},expectedHash:'a'.repeat(64),deviceId:'device'})).row.status,'OK');assert.equal(rpcOptions.method,'POST');assert.match(rpcOptions.body,/p_expected_revision/);

const lab=await readFile(new URL('./sync-lab.js',import.meta.url),'utf8'),index=await readFile(new URL('../index.html',import.meta.url),'utf8'),bootstrap=await readFile(new URL('../bootstrap.js',import.meta.url),'utf8'),sql=await readFile(new URL('../../supabase/migrations/20260908_safe_katos_planner_foundation.sql',import.meta.url),'utf8');
assert.match(index,/7\.0\.8-phone-canonical-bootstrap/);assert.match(bootstrap,/sync\/sync-lab\.js\?v=7\.0\.8-phone-canonical-bootstrap/);assert.match(lab,/Promote this iPad to cloud/);assert.match(lab,/Confirm guarded recovery/);assert.equal((lab.match(/canonicalRecovery\.run\(/g)||[]).length,1);
assert.match(sql,/prepare_katos_recovery_snapshot/);assert.match(sql,/promote_katos_canonical_recovery/);assert.match(sql,/rollback_katos_canonical_recovery/);assert.match(sql,/v_current\.data is distinct from p_expected_data/);assert.match(sql,/pg_advisory_xact_lock/);assert.match(sql,/security definer/i);assert.equal((sql.match(/set search_path = ''/g)||[]).length,3);assert.match(sql,/revoke all on table public\.planner_data_v3 from public, anon, authenticated/);assert.doesNotMatch(sql,/service_role/i);

console.log('V5 guarded canonical recovery confirmation, exact gates, verified backup/snapshot, CAS promotion, read-back integrity, idempotency, and rollback safety passed');
