import{createStore}from'./storage.js?v=22.1.16-20260817';
import{createRouter}from'./router.js?v=22.1.16-20260817';

function installFloatingIslands(){
 if(document.getElementById('sm-floating-islands'))return;
 const style=document.createElement('style');style.id='sm-floating-islands';
 style.textContent=`
  body:has(.v21-main .v17-card:has(> .v17-money-form)),body:has(.v21-main .sm-card:has(> .sm-form)),body:has(.v21-main .sm-garden .v17-card:has(> .sm-add)){overflow:hidden}
  body:has(.v21-main .v17-card:has(> .v17-money-form))::after,body:has(.v21-main .sm-card:has(> .sm-form))::after,body:has(.v21-main .sm-garden .v17-card:has(> .sm-add))::after{content:"";position:fixed;inset:0;z-index:1000;background:rgba(89,57,69,.30);backdrop-filter:blur(16px) saturate(.88);-webkit-backdrop-filter:blur(16px) saturate(.88);animation:sm-island-fade .18s ease-out}
  .v21-main .v17-card:has(> .v17-money-form),.v21-main .sm-card:has(> .sm-form),.v21-main .sm-garden .v17-card:has(> .sm-add){position:fixed!important;z-index:1001!important;left:50%!important;top:50%!important;transform:translate(-50%,-50%)!important;width:min(760px,calc(100vw - 36px))!important;max-height:calc(100dvh - 36px)!important;overflow:auto!important;margin:0!important;padding:30px 32px 28px!important;border:2px solid rgba(255,255,255,.86)!important;border-radius:34px!important;background:linear-gradient(135deg,#fff0f7 0%,#fffaf7 52%,#eff8e9 100%)!important;box-shadow:0 30px 90px rgba(70,42,57,.30),0 0 0 1px rgba(242,166,197,.42)!important;animation:sm-island-rise .24s cubic-bezier(.2,.8,.2,1)}
  .v21-main .v17-card:has(> .v17-money-form),.v21-main .sm-card:has(> .sm-form),.v21-main .sm-garden .v17-card:has(> .sm-add){isolation:isolate}
  .v21-main .v17-card:has(> .v17-money-form)::before,.v21-main .sm-card:has(> .sm-form)::before,.v21-main .sm-garden .v17-card:has(> .sm-add)::before{content:"✦   ✧   🍓   ✧   ✦";position:absolute;inset:14px 24px auto auto;z-index:-1;color:rgba(201,87,131,.30);font-size:19px;letter-spacing:.28em;pointer-events:none}
  .v21-main .v17-card:has(> .v17-money-form) header,.v21-main .sm-card:has(> .sm-form) header,.v21-main .sm-garden .v17-card:has(> .sm-add) .sm-garden-head{display:grid!important;grid-template-columns:78px 1fr auto;align-items:center;gap:16px;min-height:82px;padding:0 0 19px!important;margin:0 0 21px!important;border-bottom:2px dashed rgba(231,167,193,.55)!important;position:relative}
  .v21-main .v17-card:has(> .v17-money-form) header::before,.v21-main .sm-card:has(> .sm-form) header::before,.v21-main .sm-garden .v17-card:has(> .sm-add) .sm-garden-head::before{content:"📝";display:grid;place-items:center;width:70px;height:64px;border:2px solid #d77d9f;border-radius:15px;background:linear-gradient(145deg,#fffdfd,#ffe8f0);box-shadow:inset 0 0 0 5px rgba(255,255,255,.72),0 8px 18px rgba(188,106,141,.16);font-size:33px;transform:rotate(-4deg)}
  .v21-main .v17-card:has(> .v17-money-form) header::after,.v21-main .sm-card:has(> .sm-form) header::after,.v21-main .sm-garden .v17-card:has(> .sm-add) .sm-garden-head::after{content:"🎀";position:absolute;left:50%;bottom:-17px;transform:translateX(-50%);padding:0 14px;background:#fff8fa;color:#e890b0;font-size:22px;line-height:1}
  .v21-main .v17-card:has(> .v17-money-form) header h2,.v21-main .sm-card:has(> .sm-form) header h2,.v21-main .sm-garden .v17-card:has(> .sm-add) .sm-garden-head h2{margin:0!important;color:#c95783!important;font-size:clamp(25px,4vw,36px)!important;line-height:1.05!important;font-weight:950!important;letter-spacing:-.04em!important}
  .v21-main .v17-card:has(> .v17-money-form) header p,.v21-main .sm-card:has(> .sm-form) header p,.v21-main .sm-garden .v17-card:has(> .sm-add) .sm-garden-head p{display:none!important}
  .v21-main .v17-card:has(> .v17-money-form) header button,.v21-main .sm-card:has(> .sm-form) header button,.v21-main .sm-garden .v17-card:has(> .sm-add) .sm-garden-head button{grid-column:3!important;grid-row:1!important;width:50px!important;height:50px!important;padding:0!important;border:2px solid #efbfd2!important;border-radius:18px!important;background:#fff8fb!important;color:#d4638e!important;font-size:29px!important;line-height:1!important;box-shadow:0 8px 18px rgba(176,102,132,.13)!important}
  .v21-main .v17-card:has(> .v17-money-form) .v17-money-form,.v21-main .sm-card:has(> .sm-form) .sm-form,.v21-main .sm-garden .v17-card:has(> .sm-add) .sm-add{display:grid!important;gap:14px!important;margin:0!important}
  .v21-main .v17-card:has(> .v17-money-form) .v17-money-form>*:not(button),.v21-main .sm-card:has(> .sm-form) .sm-form>*:not(button),.v21-main .sm-garden .v17-card:has(> .sm-add) .sm-add>*:not(button){min-height:56px!important;border:1.5px solid #efc1d4!important;border-radius:17px!important;background:rgba(255,255,255,.87)!important;box-shadow:0 8px 22px rgba(190,125,150,.07)!important;padding:14px 16px!important}
  .v21-main .v17-card:has(> .v17-money-form) .v17-money-form label,.v21-main .sm-card:has(> .sm-form) .sm-form label{display:grid;gap:8px;padding:15px 17px!important;border:1.5px solid #efc1d4;border-radius:20px;background:rgba(255,255,255,.72);color:#c95783;font-weight:900}
  .v21-main .v17-card:has(> .v17-money-form) .v17-money-form label input,.v21-main .v17-card:has(> .v17-money-form) .v17-money-form label textarea,.v21-main .v17-card:has(> .v17-money-form) .v17-money-form label select,.v21-main .sm-card:has(> .sm-form) .sm-form label input,.v21-main .sm-card:has(> .sm-form) .sm-form label textarea{width:100%;min-height:52px;border:1.5px solid #edb6ce!important;border-radius:15px!important;background:#fffafd!important;padding:12px 14px!important}
  .v21-main .v17-card:has(> .v17-money-form) .v17-money-form button.primary,.v21-main .sm-card:has(> .sm-form) .sm-form button.primary,.v21-main .sm-garden .v17-card:has(> .sm-add) .sm-add button{justify-self:end;min-width:190px;min-height:54px;border:2px solid rgba(255,255,255,.82)!important;border-radius:18px!important;background:linear-gradient(105deg,#ee8fb7,#d4e5b9)!important;box-shadow:0 10px 24px rgba(196,148,158,.25)!important;font-size:17px!important}
  @keyframes sm-island-fade{from{opacity:0}to{opacity:1}}@keyframes sm-island-rise{from{opacity:0;transform:translate(-50%,-47%) scale(.97)}to{opacity:1;transform:translate(-50%,-50%) scale(1)}}
  @media(max-width:700px){.v21-main .v17-card:has(> .v17-money-form),.v21-main .sm-card:has(> .sm-form),.v21-main .sm-garden .v17-card:has(> .sm-add){width:calc(100vw - 20px)!important;max-height:calc(100dvh - 20px)!important;padding:23px 19px!important;border-radius:27px!important}.v21-main .v17-card:has(> .v17-money-form) header,.v21-main .sm-card:has(> .sm-form) header,.v21-main .sm-garden .v17-card:has(> .sm-add) .sm-garden-head{grid-template-columns:58px 1fr auto;gap:11px;min-height:65px}.v21-main .v17-card:has(> .v17-money-form) header::before,.v21-main .sm-card:has(> .sm-form) header::before,.v21-main .sm-garden .v17-card:has(> .sm-add) .sm-garden-head::before{width:52px;height:49px;font-size:26px}.v21-main .v17-card:has(> .v17-money-form) header button,.v21-main .sm-card:has(> .sm-form) header button,.v21-main .sm-garden .v17-card:has(> .sm-add) .sm-garden-head button{width:44px!important;height:44px!important}.v21-main .v17-card:has(> .v17-money-form) .v17-money-form button.primary,.v21-main .sm-card:has(> .sm-form) .sm-form button.primary,.v21-main .sm-garden .v17-card:has(> .sm-add) .sm-add button{width:100%;justify-self:stretch}}
 `;
 document.head.appendChild(style);
}

export function createApp({root,renderTab}){installFloatingIslands();const store=createStore();const router=createRouter({initial:location.hash.slice(1)||'home',onChange:page=>renderTab(page,{root,store,router})});renderTab(router.page,{root,store,router});return{store,router}}
