export const DATA_KEY='sm_v16';
export const BACKUP_KEY='sm_v16_backup';
export const DEFAULT_DATA={events:[],reminders:[],tasks:[],routines:[],habits:[],goals:[],wins:[],courses:[],archive:[],days:{},money:{},brain:'',totalClasses:0,demoTasksCleaned:false};
export const localDateKey=(date=new Date())=>{const d=new Date(date);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
export const asList=value=>Array.isArray(value)?value:(value&&typeof value==='object'?Object.values(value):[]);
export const moneyTotals=money=>{const data=money||{};const total=key=>asList(data[key]).reduce((sum,item)=>sum+Number(item?.amount??0),0);const income=total('income');const spent=total('expenses');const bills=asList(data.bills).filter(item=>!item?.paid).reduce((sum,item)=>sum+Number(item?.amount||0),0);const cash=Number(data.cash?.amount??data.cash??0);return{income,spent,bills,cash,available:income-spent-bills+cash}};
export function normalize(input={}){const data={...structuredClone(DEFAULT_DATA),...input};for(const key of ['events','reminders','tasks','routines','habits','goals','wins','courses','archive','brainNotes'])if(!Array.isArray(data[key]))data[key]=[];if(!data.days||typeof data.days!=='object')data.days={};if(!data.money||typeof data.money!=='object')data.money={};return data}
const readSaved=(storage,key)=>{try{const saved=JSON.parse(storage.getItem(key)||'null');return saved?.data||saved||null}catch{return null}};
const savedAt=data=>Date.parse(data?.__smUpdatedAt||'')||0;
export function loadLocalData(storage=localStorage){try{const primary=readSaved(storage,DATA_KEY),backup=readSaved(storage,BACKUP_KEY),source=savedAt(backup)>savedAt(primary)?backup:primary,data=normalize(source||{});data.tasks=(data.tasks||[]).filter(task=>{const text=String(task?.text||task?.title||'').trim().toLowerCase();return text!=='go to bed'&&text!=='finish this planner'});data.demoTasksCleaned=true;if(!data.__smUpdatedAt)data.__smUpdatedAt=new Date().toISOString();saveLocalData(data,storage);return data}catch{return structuredClone(DEFAULT_DATA)}}
export function saveLocalData(data,storage=localStorage){const normalized=normalize(data),record=JSON.stringify({data:normalized});storage.setItem(DATA_KEY,record);storage.setItem(BACKUP_KEY,record)}
