/* One actual-money ledger. Gig orders record earned work; only payout deposits hit accounts. */
const list=v=>Array.isArray(v)?v:[],obj=v=>v&&typeof v==='object'&&!Array.isArray(v),now=()=>new Date().toISOString(),day=()=>new Date().toISOString().slice(0,10),uid=p=>`${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;
export const DEFAULT_FINANCE={version:1,accounts:[],ledger:[],categories:[],bills:[],subscriptions:[],goals:[],goalContributions:[],incomeSources:[],payRates:[],gigPlatforms:[],gigOrders:[],gigPayouts:[],gigGoals:[],legacyMetadata:{}};
export const normalizeFinance=v=>{const x={...structuredClone(DEFAULT_FINANCE),...(obj(v)?v:{})};for(const key of ['accounts','ledger','categories','bills','subscriptions','goals','goalContributions','incomeSources','payRates','gigPlatforms','gigOrders','gigPayouts','gigGoals'])x[key]=list(x[key]);return x};
export const withFinance=(state,change)=>({...state,finance:change(normalizeFinance(state.finance))});
const find=(items,id)=>list(items).find(x=>String(x.id)===String(id));
const active=item=>item.active!==false&&!item.archivedAt;
export function addAccount(state,d={}){const name=String(d.name||'').trim();if(!name)return{ok:false,error:'Account name is required.',state};const account={id:d.id||uid('account'),name,institution:d.institution||'',type:d.type||'checking',active:d.active!==false,openingBalance:Number(d.openingBalance)||0,openingBalanceDate:d.openingBalanceDate||day(),creditLimitOptional:Number(d.creditLimitOptional)||0,aprOptional:Number(d.aprOptional)||0,minimumPaymentOptional:Number(d.minimumPaymentOptional)||0,dueDayOptional:Number(d.dueDayOptional)||0,notes:d.notes||'',createdAt:now(),updatedAt:now(),archivedAt:null};return{ok:true,account,state:withFinance(state,f=>({...f,accounts:[...f.accounts,account]}))};}
export const getAccounts=state=>normalizeFinance(state.finance).accounts;
export const getAccount=(state,id)=>find(normalizeFinance(state.finance).accounts,id)||null;
const posted=t=>['posted','cleared'].includes(t.status||'posted')&&!t.archivedAt&&!t.voided;
const effect=(account,t)=>{const n=Number(t.amount)||0,credit=['credit_card','loan'].includes(account.type);if(t.type==='transfer_out')return -n;if(t.type==='transfer_in')return credit?-n:n;if(t.type==='income')return credit?-n:n;if(t.type==='expense'||t.type==='fee')return credit?n:-n;if(t.type==='refund')return credit?-n:n;if(t.type==='payment')return credit?-n:-n;if(t.type==='adjustment')return n;return 0};
export const getAccountBalance=(state,id,{includePending=false}={})=>{const f=normalizeFinance(state.finance),account=find(f.accounts,id);if(!account)return null;return (Number(account.openingBalance)||0)+f.ledger.filter(t=>t.accountId===id&&(posted(t)||(includePending&&t.status==='pending'))).reduce((sum,t)=>sum+(t.type==='adjustment'?(Number(t.adjustmentSigned??t.amount)||0):effect(account,t)),0)};
export const getLiquidCashTotal=state=>getAccounts(state).filter(a=>active(a)&&['checking','savings','cash','prepaid'].includes(a.type)).reduce((sum,a)=>sum+(getAccountBalance(state,a.id)||0),0);
export const getLiabilities=state=>getAccounts(state).filter(a=>['credit_card','loan'].includes(a.type)).map(a=>({...a,balance:getAccountBalance(state,a.id),utilization:a.creditLimitOptional?Math.max(0,getAccountBalance(state,a.id))/a.creditLimitOptional:null}));
export function addLedgerTransaction(state,d={}){if(!d.accountId||!find(normalizeFinance(state.finance).accounts,d.accountId))return{ok:false,error:'Choose an account.',state};const amount=Math.abs(Number(d.amount)||0);if(!amount)return{ok:false,error:'Enter an amount.',state};const transaction={id:d.id||uid('ledger'),accountId:d.accountId,type:d.type||'expense',amount,adjustmentSigned:d.adjustmentSigned==null?null:Number(d.adjustmentSigned),date:d.date||day(),timeOptional:d.timeOptional||null,merchantOrSource:d.merchantOrSource||'',categoryId:d.categoryId||null,description:d.description||'',status:d.status||'posted',linkedTransferId:d.linkedTransferId||null,linkedGigPayoutId:d.linkedGigPayoutId||null,linkedBillInstanceId:d.linkedBillInstanceId||null,linkedExternalId:d.linkedExternalId||null,gigPlatformId:d.gigPlatformId||null,gigWorkDateOptional:d.gigWorkDateOptional||null,source:d.source||'manual',notes:d.notes||'',createdAt:d.createdAt||now(),updatedAt:now(),archivedAt:null};return{ok:true,transaction,state:withFinance(state,f=>({...f,ledger:[...f.ledger,transaction]}))};}
export const updateLedgerTransaction=(state,id,changes={})=>withFinance(state,f=>({...f,ledger:f.ledger.map(t=>t.id===id?{...t,...changes,id:t.id,amount:Math.abs(Number(changes.amount??t.amount)||0),updatedAt:now()}:t)}));
export function createTransfer(state,{fromAccountId,toAccountId,amount,date=day(),description=''}){const f=normalizeFinance(state.finance);if(!find(f.accounts,fromAccountId)||!find(f.accounts,toAccountId)||fromAccountId===toAccountId)return{ok:false,error:'Choose two different accounts.',state};const transferId=uid('transfer'),out=addLedgerTransaction(state,{accountId:fromAccountId,type:'transfer_out',amount,date,description,linkedTransferId:transferId,source:'transfer'});const incoming=addLedgerTransaction(out.state,{accountId:toAccountId,type:'transfer_in',amount,date,description,linkedTransferId:transferId,source:'transfer'});return{ok:true,transferId,transactions:[out.transaction,incoming.transaction],state:incoming.state};}
export function reconcileAccount(state,accountId,actualBalance,reason='unknown discrepancy'){const current=getAccountBalance(state,accountId),delta=Number(actualBalance)-Number(current);if(!Number.isFinite(delta))return{ok:false,error:'Enter an actual balance.',state};if(Math.abs(delta)<.005)return{ok:true,transaction:null,state};return addLedgerTransaction(state,{accountId,type:'adjustment',amount:Math.abs(delta),date:day(),description:`Reconciliation: ${reason}`,notes:`Actual ${actualBalance}; KatOS was ${current}`,status:'cleared',source:'reconciliation',adjustmentSigned:delta,...(delta<0?{amount:Math.abs(delta)}:{amount:delta})});}
// adjustment needs its signed direction stored without exposing a second balance field
export const normalizedEffect=(account,t)=>t.type==='adjustment'?(Number(t.adjustmentSigned??t.amount)||0):effect(account,t);
export function getLedgerTransactions(state,filters={}){let rows=normalizeFinance(state.finance).ledger.filter(t=>!t.archivedAt);for(const [key,value] of Object.entries(filters)){if(value==null||value==='')continue;if(key==='from')rows=rows.filter(t=>t.date>=value);else if(key==='to')rows=rows.filter(t=>t.date<=value);else rows=rows.filter(t=>String(t[key])===String(value))}return rows.sort((a,b)=>`${b.date}${b.timeOptional||''}`.localeCompare(`${a.date}${a.timeOptional||''}`));}
export function getCashFlowSummary(state,{from='0000-01-01',to='9999-12-31',includePending=false}={}){const rows=getLedgerTransactions(state,{from,to}).filter(t=>(includePending?['pending','posted','cleared'].includes(t.status):posted(t))&&!t.archivedAt);let income=0,spending=0,refunds=0;for(const t of rows){if(t.type==='income')income+=t.amount;else if(['expense','fee'].includes(t.type))spending+=t.amount;else if(t.type==='refund')refunds+=t.amount}return{income,spending,refunds,net:income-spending+refunds,transactions:rows};}
export const getIncomeSummary=(state,range)=>getCashFlowSummary(state,range).income;
export const getSpendingSummary=(state,range)=>getCashFlowSummary(state,range).spending-getCashFlowSummary(state,range).refunds;
export function addBill(state,d={}){const name=String(d.name||'').trim();if(!name)return{ok:false,error:'Bill name is required.',state};const bill={id:d.id||uid('bill'),name,categoryId:d.categoryId||null,expectedAmount:Number(d.expectedAmount)||0,amountType:d.amountType||'fixed',accountIdOptional:d.accountIdOptional||null,recurrence:d.recurrence||'monthly',dueDay:Number(d.dueDay)||1,active:d.active!==false,autopay:!!d.autopay,linkedSubscriptionIdOptional:d.linkedSubscriptionIdOptional||null,notes:d.notes||'',createdAt:now(),updatedAt:now(),archivedAt:null};return{ok:true,bill,state:withFinance(state,f=>({...f,bills:[...f.bills,bill]}))};}
const monthAdd=(date,add)=>{const d=new Date(`${date}T12:00:00`);d.setMonth(d.getMonth()+add);return d.toISOString().slice(0,10)};
export function getBillInstances(state,{from=day(),to=monthAdd(day(),2)}={}){const f=normalizeFinance(state.finance),out=[];for(const bill of f.bills.filter(active)){for(let cursor=from.slice(0,7)+'-01';cursor<=to.slice(0,7)+'-01';cursor=monthAdd(cursor,1)){const year=Number(cursor.slice(0,4)),month=Number(cursor.slice(5,7)),days=new Date(year,month,0).getDate(),due=`${cursor.slice(0,7)}-${String(Math.min(bill.dueDay||1,days)).padStart(2,'0')}`,id=`bill:${bill.id}:${due}`;if(due<from||due>to)continue;const payment=f.ledger.find(t=>t.linkedBillInstanceId===id&&posted(t));out.push({id,billId:bill.id,name:bill.name,dueDate:due,expectedAmount:bill.expectedAmount,status:payment?'paid':due<day()?'overdue':'upcoming',paymentTransactionId:payment?.id||null,bill})}}return out.sort((a,b)=>a.dueDate.localeCompare(b.dueDate));}
export const getUpcomingBills=(state,range)=>getBillInstances(state,range);
export function addSubscription(state,d={}){const name=String(d.name||'').trim();if(!name)return{ok:false,error:'Subscription name is required.',state};const sub={id:d.id||uid('subscription'),name,amount:Number(d.amount)||0,billingCycle:d.billingCycle||'monthly',renewalDate:d.renewalDate||null,accountIdOptional:d.accountIdOptional||null,categoryId:d.categoryId||null,active:d.active!==false,status:d.status||'active',cancellationDateOptional:d.cancellationDateOptional||null,trialEndDateOptional:d.trialEndDateOptional||null,linkedBillId:d.linkedBillId||null,externalSource:d.externalSource||null,externalId:d.externalId||null,notes:d.notes||'',createdAt:now(),updatedAt:now()};return{ok:true,subscription:sub,state:withFinance(state,f=>({...f,subscriptions:[...f.subscriptions,sub]}))};}
export const getSubscriptions=state=>normalizeFinance(state.finance).subscriptions.filter(s=>s.status!=='canceled'&&!s.archivedAt);
export function addFinancialGoal(state,d={}){const title=String(d.title||'').trim();if(!title)return{ok:false,error:'Goal title is required.',state};const goal={id:d.id||uid('goal'),title,targetAmount:Number(d.targetAmount)||0,targetDateOptional:d.targetDateOptional||null,progressMethod:d.progressMethod||'manual_amount',linkedAccountIds:list(d.linkedAccountIds),manualAmountOptional:Number(d.manualAmountOptional)||0,status:d.status||'active',priority:d.priority||'Whenever',notes:d.notes||'',createdAt:now(),updatedAt:now()};return{ok:true,goal,state:withFinance(state,f=>({...f,goals:[...f.goals,goal]}))};}
export const getFinancialGoals=state=>normalizeFinance(state.finance).goals.filter(g=>g.status!=='archived');
export const getGoalProgress=(state,id)=>{const f=normalizeFinance(state.finance),goal=find(f.goals,id);if(!goal)return null;const contributions=f.goalContributions.filter(c=>c.goalId===id).reduce((s,c)=>s+c.amount,0),amount=goal.progressMethod==='linked_account'?goal.linkedAccountIds.reduce((s,a)=>s+(getAccountBalance(state,a)||0),0):goal.progressMethod==='contributions'?contributions:goal.manualAmountOptional;return{goal,amount,percent:goal.targetAmount?Math.min(100,Math.round(amount/goal.targetAmount*100)):0,remaining:Math.max(0,goal.targetAmount-amount)};};
export function addGoalContribution(state,d={}){if(!d.goalId||!find(normalizeFinance(state.finance).goals,d.goalId))return{ok:false,error:'Choose a goal.',state};const amount=Math.abs(Number(d.amount)||0);if(!amount)return{ok:false,error:'Enter contribution amount.',state};const contribution={id:d.id||uid('goal-contribution'),goalId:d.goalId,amount,date:d.date||day(),linkedTransactionIdOptional:d.linkedTransactionIdOptional||null,notes:d.notes||'',createdAt:now(),updatedAt:now()};return{ok:true,contribution,state:withFinance(state,f=>({...f,goalContributions:[...f.goalContributions,contribution]}))};}
export function addPayRate(state,d={}){const rate=Number(d.hourlyRate);if(!Number.isFinite(rate)||rate<0)return{ok:false,error:'Enter a valid hourly rate.',state};const record={id:d.id||uid('pay-rate'),sourceId:d.sourceId||'aba-work',hourlyRate:rate,effectiveFrom:d.effectiveFrom||day(),effectiveToOptional:d.effectiveToOptional||null,notes:d.notes||'',createdAt:now(),updatedAt:now()};return{ok:true,record,state:withFinance(state,f=>({...f,payRates:[...f.payRates,record]}))};}
export function getEstimatedWorkEarnings(workHours={},state){const rates=normalizeFinance(state.finance).payRates.filter(r=>r.sourceId==='aba-work').sort((a,b)=>String(b.effectiveFrom).localeCompare(String(a.effectiveFrom))),rate=rates[0]?.hourlyRate||null,hours=(Number(workHours.actualMinutes)||Number(workHours.scheduledMinutes)||0)/60;return{hours,hourlyRate:rate,estimated:rate==null?null:hours*rate,label:'Estimated earned — not deposited money'};}
export function addGigPlatform(state,d={}){const name=String(d.name||'').trim();if(!name)return{ok:false,error:'Platform name is required.',state};const platform={id:d.id||uid('platform'),name,active:d.active!==false,iconOptional:d.iconOptional||'🛍️',payoutMethodOptional:d.payoutMethodOptional||'',notes:d.notes||'',createdAt:now(),updatedAt:now()};return{ok:true,platform,state:withFinance(state,f=>({...f,gigPlatforms:[...f.gigPlatforms,platform]}))};}
export const getGigPlatforms=state=>normalizeFinance(state.finance).gigPlatforms.filter(active);
export const gigGross=order=>['basePay','promoPay','tip','bonus','reimbursement','otherPay'].reduce((s,k)=>s+(Number(order?.[k])||0),0);
export function addGigOrder(state,d={}){if(!d.platformId)return{ok:false,error:'Choose a platform.',state};const order={id:d.id||uid('gig-order'),platformId:d.platformId,date:d.date||day(),startedAtOptional:d.startedAtOptional||null,completedAtOptional:d.completedAtOptional||null,basePay:Number(d.basePay)||0,promoPay:Number(d.promoPay)||0,tip:Number(d.tip)||0,bonus:Number(d.bonus)||0,reimbursement:Number(d.reimbursement)||0,otherPay:Number(d.otherPay)||0,mileageOptional:Number(d.mileageOptional)||0,activeMinutesOptional:Number(d.activeMinutesOptional)||0,onlineMinutesOptional:Number(d.onlineMinutesOptional)||0,status:d.status||'completed',payoutBatchIdOptional:d.payoutBatchIdOptional||null,notes:d.notes||'',createdAt:now(),updatedAt:now(),archivedAt:null};return{ok:true,order,state:withFinance(state,f=>({...f,gigOrders:[...f.gigOrders,order]}))};}
export const updateGigOrder=(state,id,changes={})=>withFinance(state,f=>({...f,gigOrders:f.gigOrders.map(o=>o.id===id?{...o,...changes,id:o.id,updatedAt:now()}:o)}));
export const getGigOrders=(state,filters={})=>{let rows=normalizeFinance(state.finance).gigOrders.filter(o=>!o.archivedAt);for(const [k,v] of Object.entries(filters)){if(v!=null&&v!=='')rows=rows.filter(o=>String(o[k])===String(v))}return rows.sort((a,b)=>b.date.localeCompare(a.date));};
export function getGigEarningsSummary(state,{from='0000-01-01',to='9999-12-31'}={}){const f=normalizeFinance(state.finance),orders=getGigOrders(state).filter(o=>o.date>=from&&o.date<=to&&o.status!=='canceled'),gross=orders.reduce((s,o)=>s+gigGross(o),0),tips=orders.reduce((s,o)=>s+o.tip,0),active=orders.reduce((s,o)=>s+o.activeMinutesOptional,0),online=orders.reduce((s,o)=>s+o.onlineMinutesOptional,0),mileage=orders.reduce((s,o)=>s+o.mileageOptional,0),expenses=f.ledger.filter(t=>posted(t)&&t.gigWorkDateOptional>=from&&t.gigWorkDateOptional<=to&&['expense','fee'].includes(t.type)).reduce((s,t)=>s+t.amount,0);return{orders,gross,tips,ordersCount:orders.length,activeMinutes:active,onlineMinutes:online,mileage,linkedExpenses:expenses,simpleNet:gross-expenses,averagePerOrder:orders.length?gross/orders.length:null,perActiveHour:active?gross/(active/60):null,perOnlineHour:online?gross/(online/60):null,perMile:mileage?gross/mileage:null};}
export const getGigEarningsForRange=(state,range)=>getGigEarningsSummary(state,range);
export function getGigPlatformComparison(state,range={}){const f=normalizeFinance(state.finance);return getGigPlatforms(state).map(p=>{const summary=getGigEarningsSummary(state,range),orders=summary.orders.filter(o=>o.platformId===p.id),gross=orders.reduce((s,o)=>s+gigGross(o),0),tips=orders.reduce((s,o)=>s+o.tip,0),active=orders.reduce((s,o)=>s+o.activeMinutesOptional,0),miles=orders.reduce((s,o)=>s+o.mileageOptional,0);return{platform:p,orders:orders.length,gross,tips,averagePerOrder:orders.length?gross/orders.length:null,perActiveHour:active?gross/(active/60):null,mileage:miles,perMile:miles?gross/miles:null}}).filter(x=>x.orders||f.gigPlatforms.some(p=>p.id===x.platform.id));}
export function addGigPayout(state,d={}){if(!d.platformId)return{ok:false,error:'Choose a platform.',state};const f=normalizeFinance(state.finance),orders=list(d.orderIds).map(id=>find(f.gigOrders,id)).filter(Boolean),gross=orders.reduce((s,o)=>s+gigGross(o),0),payout={id:d.id||uid('gig-payout'),platformId:d.platformId,periodStartOptional:d.periodStartOptional||null,periodEndOptional:d.periodEndOptional||null,orderIds:orders.map(o=>o.id),grossAmount:d.grossAmount??gross,adjustmentsOptional:Number(d.adjustmentsOptional)||0,payoutAmount:Number(d.payoutAmount??gross)||0,payoutDate:d.payoutDate||null,destinationAccountId:d.destinationAccountId||null,status:d.status||'pending',linkedLedgerTransactionId:d.linkedLedgerTransactionId||null,notes:d.notes||'',createdAt:now(),updatedAt:now()};return{ok:true,payout,state:withFinance(state,x=>({...x,gigPayouts:[...x.gigPayouts,payout],gigOrders:x.gigOrders.map(o=>payout.orderIds.includes(o.id)?{...o,payoutBatchIdOptional:payout.id,status:o.status==='completed'?'payout_pending':o.status}:o)}))};}
export function markGigPayoutPaid(state,id,{accountId,date=day()}={}){const f=normalizeFinance(state.finance),payout=find(f.gigPayouts,id);if(!payout)return{ok:false,error:'Payout not found.',state};const externalId=`gig-payout:${payout.id}`,existing=f.ledger.find(t=>t.linkedExternalId===externalId);let next=state,transaction=existing;if(!existing){const out=addLedgerTransaction(state,{accountId:accountId||payout.destinationAccountId,type:'income',amount:payout.payoutAmount,date,merchantOrSource:`Gig payout`,linkedGigPayoutId:payout.id,linkedExternalId:externalId,source:'gig_payout',status:'posted'});if(!out.ok)return out;next=out.state;transaction=out.transaction}next=withFinance(next,x=>({...x,gigPayouts:x.gigPayouts.map(p=>p.id===id?{...p,status:'paid',payoutDate:date,destinationAccountId:accountId||p.destinationAccountId,linkedLedgerTransactionId:transaction.id,updatedAt:now()}:p),gigOrders:x.gigOrders.map(o=>payout.orderIds.includes(o.id)?{...o,status:'paid'}:o)}));return{ok:true,transaction,state:next};}
export const getPendingGigPayouts=state=>normalizeFinance(state.finance).gigPayouts.filter(p=>p.status!=='paid');export const getGigPayouts=(state,{from='0000-01-01',to='9999-12-31'}={})=>normalizeFinance(state.finance).gigPayouts.filter(p=>(p.payoutDate||'9999-12-31')>=from&&(p.payoutDate||'0000-01-01')<=to);
export function addGigGoal(state,d={}){const goal={id:d.id||uid('gig-goal'),title:d.title||'Gig goal',period:d.period||'day',startDate:d.startDate||day(),endDate:d.endDate||day(),targetAmount:Number(d.targetAmount)||0,platformId:d.platformId||null,createdAt:now(),updatedAt:now()};return{ok:true,goal,state:withFinance(state,f=>({...f,gigGoals:[...f.gigGoals,goal]}))};}
export const getGigGoalProgress=(state,id)=>{const goal=find(normalizeFinance(state.finance).gigGoals,id);if(!goal)return null;const earned=getGigEarningsSummary(state,{from:goal.startDate,to:goal.endDate}).orders.filter(o=>!goal.platformId||o.platformId===goal.platformId).reduce((s,o)=>s+gigGross(o),0);return{goal,earned,remaining:Math.max(0,goal.targetAmount-earned),percent:goal.targetAmount?Math.min(100,Math.round(earned/goal.targetAmount*100)):0};};
export const getMoneySummary=state=>{const flow=getCashFlowSummary(state,{});return{liquidCash:getLiquidCashTotal(state),cashFlow:flow,liabilities:getLiabilities(state),upcomingBills:getUpcomingBills(state,{})}};
export const getUpcomingFinancialActions=state=>[...getUpcomingBills(state,{}).filter(x=>x.status!=='paid').map(x=>({kind:'bill',id:x.id,title:`Pay ${x.name}`,date:x.dueDate})),...getSubscriptions(state).filter(x=>x.trialEndDateOptional||x.renewalDate).map(x=>({kind:'subscription',id:x.id,title:`Review ${x.name}`,date:x.trialEndDateOptional||x.renewalDate}))].sort((a,b)=>String(a.date).localeCompare(String(b.date)));
export function publishFinancialAction(store,{kind,id,title,scheduledDate,priority='Important',metadata={}}){return store?.createAction?store.createAction({source:'money',externalId:`finance:${kind}:${id}`,text:title,scheduledDate,priority,metadata:{financialKind:kind,financialId:id,...metadata}}):{ok:false,error:'Daily Shit action API unavailable.'};}
