/* Stage 6 lifestyle domains. They own the things Kat enjoys/develops; Daily Shit owns actions. */
const list=v=>Array.isArray(v)?v:[];
const obj=v=>v&&typeof v==='object'&&!Array.isArray(v);
const now=()=>new Date().toISOString();
const day=(value=new Date())=>{const d=new Date(value);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const uid=prefix=>`${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;
const find=(items,id)=>list(items).find(item=>String(item.id)===String(id));
const active=item=>item.active!==false&&!item.archivedAt;
const rangeFilter=(items,{from='0000-01-01',to='9999-12-31'}={})=>items.filter(item=>String(item.date||item.targetDateOptional||'')>=from&&String(item.date||item.targetDateOptional||'')<=to);

export const DEFAULT_LIFESTYLE={version:1,movement:{types:[],activities:[],plans:[],goals:[]},hobbies:{items:[],projects:[],resources:[]},growth:{areas:[],goals:[],milestones:[],wins:[],reflections:[]},legacyMyLoves:[]};
export const normalizeLifestyle=input=>{const x={...structuredClone(DEFAULT_LIFESTYLE),...(obj(input)?input:{})};for(const domain of ['movement','hobbies','growth'])x[domain]={...structuredClone(DEFAULT_LIFESTYLE[domain]),...(obj(x[domain])?x[domain]:{})};for(const key of ['types','activities','plans','goals'])x.movement[key]=list(x.movement[key]);for(const key of ['items','projects','resources'])x.hobbies[key]=list(x.hobbies[key]);for(const key of ['areas','goals','milestones','wins','reflections'])x.growth[key]=list(x.growth[key]);x.legacyMyLoves=list(x.legacyMyLoves);return x};
export const withLifestyle=(state,change)=>({...state,lifestyle:change(normalizeLifestyle(state.lifestyle))});

export function addMovementType(state,d={}){const name=String(d.name||'').trim();if(!name)return{ok:false,error:'Movement type needs a name.',state};const item={id:d.id||uid('movement-type'),name,category:d.category||'Other',iconOptional:d.iconOptional||'🏃',active:d.active!==false,defaultDurationOptional:Number(d.defaultDurationOptional)||0,defaultIntensityOptional:d.defaultIntensityOptional||'',notes:d.notes||'',createdAt:now(),updatedAt:now()};return{ok:true,item,state:withLifestyle(state,x=>({...x,movement:{...x.movement,types:[...x.movement.types,item]}}))}}
export const getMovementTypes=state=>normalizeLifestyle(state.lifestyle).movement.types.filter(active);
export function addMovementActivity(state,d={}){const title=String(d.title||'').trim();if(!title)return{ok:false,error:'Movement activity needs a title.',state};const item={id:d.id||uid('movement'),typeId:d.typeId||null,title,date:d.date||day(),status:d.status||'planned',plannedMinutes:Number(d.plannedMinutes)||0,actualMinutes:Number(d.actualMinutes)||0,intensity:d.intensity||'',energyBeforeOptional:d.energyBeforeOptional||'',energyAfterOptional:d.energyAfterOptional||'',notes:d.notes||'',sourcePlanIdOptional:d.sourcePlanIdOptional||null,linkedActionIdOptional:d.linkedActionIdOptional||null,createdAt:now(),updatedAt:now(),completedAt:null};return{ok:true,item,state:withLifestyle(state,x=>({...x,movement:{...x.movement,activities:[...x.movement.activities,item]}}))}}
export const updateMovementActivity=(state,id,changes={})=>withLifestyle(state,x=>({...x,movement:{...x.movement,activities:x.movement.activities.map(item=>item.id===id?{...item,...changes,id:item.id,updatedAt:now()}:item)}}));
export const completeMovementActivity=(state,id,actualMinutes)=>updateMovementActivity(state,id,{status:'completed',actualMinutes:Number(actualMinutes)||find(normalizeLifestyle(state.lifestyle).movement.activities,id)?.plannedMinutes||0,completedAt:now()});
export const skipMovementActivity=(state,id)=>updateMovementActivity(state,id,{status:'skipped'});
export const getMovementActivities=(state,filters={})=>rangeFilter(normalizeLifestyle(state.lifestyle).movement.activities,filters).filter(item=>(!filters.typeId||item.typeId===filters.typeId)&&(!filters.status||item.status===filters.status)).sort((a,b)=>String(b.date).localeCompare(String(a.date)));
export const getMovementForDate=(state,date=day())=>getMovementActivities(state,{from:date,to:date});
export const getMovementSummary=(state,range={})=>{const items=getMovementActivities(state,range).filter(item=>item.status==='completed'),minutes=items.reduce((sum,item)=>sum+(Number(item.actualMinutes)||Number(item.plannedMinutes)||0),0),dates=new Set(items.map(item=>item.date)),counts=new Map();for(const item of items)counts.set(item.typeId||item.title,(counts.get(item.typeId||item.title)||0)+1);const favorite=[...counts.entries()].sort((a,b)=>b[1]-a[1])[0]?.[0]||null;return{activities:items,sessions:items.length,totalMinutes:minutes,movementDays:dates.size,favoriteTypeId:favorite}};
export function addMovementPlan(state,d={}){const title=String(d.title||'').trim();if(!title)return{ok:false,error:'Movement plan needs a title.',state};const item={id:d.id||uid('movement-plan'),title,activityItems:list(d.activityItems),defaultDuration:Number(d.defaultDuration)||0,preferredDaysOptional:list(d.preferredDaysOptional),active:d.active!==false,notes:d.notes||'',createdAt:now(),updatedAt:now(),archivedAt:null};return{ok:true,item,state:withLifestyle(state,x=>({...x,movement:{...x.movement,plans:[...x.movement.plans,item]}}))}}
export const getMovementPlans=state=>normalizeLifestyle(state.lifestyle).movement.plans.filter(active);
export function addMovementGoal(state,d={}){const title=String(d.title||'').trim();if(!title)return{ok:false,error:'Movement goal needs a title.',state};const item={id:d.id||uid('movement-goal'),title,metric:d.metric||'sessions',target:Number(d.target)||0,period:d.period||'week',typeId:d.typeId||null,active:d.active!==false,notes:d.notes||'',createdAt:now()};return{ok:true,item,state:withLifestyle(state,x=>({...x,movement:{...x.movement,goals:[...x.movement.goals,item]}}))}}
export const getMovementGoals=state=>normalizeLifestyle(state.lifestyle).movement.goals.filter(active);
export const getMovementGoalProgress=(state,id,range={})=>{const goal=find(normalizeLifestyle(state.lifestyle).movement.goals,id);if(!goal)return null;const summary=getMovementSummary(state,range),items=goal.typeId?summary.activities.filter(item=>item.typeId===goal.typeId):summary.activities,value=goal.metric==='minutes'?items.reduce((sum,item)=>sum+(item.actualMinutes||item.plannedMinutes||0),0):items.length;return{goal,value,percent:goal.target?Math.min(100,Math.round(value/goal.target*100)):0}};
export function getRecommendedMovement(state,{energy='medium',availableMinutes=30,date=day()}={}){const planned=getMovementForDate(state,date).find(item=>['planned','active'].includes(item.status));if(planned)return{primary:planned,reason:'Already planned for today'};const types=getMovementTypes(state).filter(item=>!item.defaultDurationOptional||item.defaultDurationOptional<=availableMinutes);const rank=item=>{const intensity=String(item.defaultIntensityOptional||'').toLowerCase(),fit=energy==='low'?(intensity==='gentle'||intensity==='low'?4:0):energy==='high'?(intensity==='spicy'||intensity==='high'?4:1):2;return fit+(item.defaultDurationOptional&&item.defaultDurationOptional<=availableMinutes?2:0)};const sorted=[...types].sort((a,b)=>rank(b)-rank(a)||a.name.localeCompare(b.name));return{primary:sorted[0]?{...sorted[0],title:sorted[0].name,plannedMinutes:sorted[0].defaultDurationOptional}:null,backup:sorted[1]?{...sorted[1],title:sorted[1].name,plannedMinutes:sorted[1].defaultDurationOptional}:null,reason:'Matches your available energy and time'};}

export function addHobby(state,d={}){const title=String(d.title||'').trim();if(!title)return{ok:false,error:'Hobby needs a title.',state};const item={id:d.id||uid('hobby'),title,category:d.category||'Other',status:d.status||'current',energyLevelOptional:d.energyLevelOptional||'',typicalMinutesOptional:Number(d.typicalMinutesOptional)||0,setupEffortOptional:d.setupEffortOptional||'',requiresSuppliesOptional:!!d.requiresSuppliesOptional,notes:d.notes||'',createdAt:now(),updatedAt:now(),archivedAt:null};return{ok:true,item,state:withLifestyle(state,x=>({...x,hobbies:{...x.hobbies,items:[...x.hobbies.items,item]}}))}}
export const updateHobby=(state,id,changes={})=>withLifestyle(state,x=>({...x,hobbies:{...x.hobbies,items:x.hobbies.items.map(item=>item.id===id?{...item,...changes,id:item.id,updatedAt:now()}:item)}}));
export const archiveHobby=(state,id)=>updateHobby(state,id,{status:'archived',archivedAt:now()});
export const getHobbies=(state,filters={})=>normalizeLifestyle(state.lifestyle).hobbies.items.filter(item=>!item.archivedAt&&(!filters.status||item.status===filters.status));
export const getCurrentHobbies=state=>getHobbies(state).filter(item=>['current','exploring'].includes(item.status));
export const getHobby=(state,id)=>find(normalizeLifestyle(state.lifestyle).hobbies.items,id)||null;
export function addHobbyProject(state,d={}){const title=String(d.title||'').trim();if(!title||!d.hobbyId)return{ok:false,error:'Project needs a hobby and title.',state};const item={id:d.id||uid('hobby-project'),hobbyId:d.hobbyId,title,status:d.status||'active',progressOptional:Number(d.progressOptional)||0,targetDateOptional:d.targetDateOptional||null,notes:d.notes||'',createdAt:now(),updatedAt:now(),completedAt:null};return{ok:true,item,state:withLifestyle(state,x=>({...x,hobbies:{...x.hobbies,projects:[...x.hobbies.projects,item]}}))}}
export const getHobbyProjects=(state,hobbyId)=>normalizeLifestyle(state.lifestyle).hobbies.projects.filter(item=>item.hobbyId===hobbyId&&!item.archivedAt);
export const getActiveHobbyProjects=state=>normalizeLifestyle(state.lifestyle).hobbies.projects.filter(item=>item.status==='active'&&!item.archivedAt);
export const completeHobbyProject=(state,id)=>withLifestyle(state,x=>({...x,hobbies:{...x.hobbies,projects:x.hobbies.projects.map(item=>item.id===id?{...item,status:'completed',completedAt:now(),updatedAt:now()}:item)}}));
export function addHobbyResource(state,d={}){const title=String(d.title||'').trim();if(!title||!d.hobbyId)return{ok:false,error:'Resource needs a hobby and title.',state};const item={id:d.id||uid('hobby-resource'),hobbyId:d.hobbyId,title,type:d.type||'resource',status:d.status||'available',notes:d.notes||'',createdAt:now()};return{ok:true,item,state:withLifestyle(state,x=>({...x,hobbies:{...x.hobbies,resources:[...x.hobbies.resources,item]}}))}}
export const getHobbyResources=(state,hobbyId)=>normalizeLifestyle(state.lifestyle).hobbies.resources.filter(item=>item.hobbyId===hobbyId);
export function getHobbyRecommendation(state,{energy='medium',availableMinutes=30,mode='normal'}={}){const rank=item=>{let score=item.status==='current'?5:2;if(energy==='low'&&item.energyLevelOptional==='low')score+=4;if(energy==='high'&&item.energyLevelOptional==='high')score+=4;if(item.typicalMinutesOptional&&item.typicalMinutesOptional<=availableMinutes)score+=3;if(mode==='tiny'&&item.typicalMinutesOptional<=15)score+=4;if(mode==='locked_in'&&item.typicalMinutesOptional>=30)score+=3;return score};const choices=getCurrentHobbies(state).sort((a,b)=>rank(b)-rank(a)||a.title.localeCompare(b.title));return{primary:choices[0]||null,backup:choices[1]||null,reason:choices.length?'A current hobby matched your mood and time.':'Add a current or exploring hobby and I can pick for you.'};}

export function addGrowthArea(state,d={}){const title=String(d.title||'').trim();if(!title)return{ok:false,error:'Growth area needs a title.',state};const item={id:d.id||uid('growth-area'),title,iconOptional:d.iconOptional||'🌱',active:d.active!==false,order:Number(d.order)||0,notes:d.notes||'',createdAt:now(),updatedAt:now(),archivedAt:null};return{ok:true,item,state:withLifestyle(state,x=>({...x,growth:{...x.growth,areas:[...x.growth.areas,item]}}))}}
export const getGrowthAreas=state=>normalizeLifestyle(state.lifestyle).growth.areas.filter(active).sort((a,b)=>a.order-b.order||a.title.localeCompare(b.title));
export function addGrowthGoal(state,d={}){const title=String(d.title||'').trim();if(!title)return{ok:false,error:'Growth goal needs a title.',state};const item={id:d.id||uid('growth-goal'),areaId:d.areaId||null,title,whyOptional:d.whyOptional||'',status:d.status||'active',startedAt:d.startedAt||day(),targetDateOptional:d.targetDateOptional||null,completedAt:null,notes:d.notes||'',createdAt:now(),updatedAt:now(),archivedAt:null};return{ok:true,item,state:withLifestyle(state,x=>({...x,growth:{...x.growth,goals:[...x.growth.goals,item]}}))}}
export const getGrowthGoals=(state,filters={})=>normalizeLifestyle(state.lifestyle).growth.goals.filter(item=>!item.archivedAt&&(!filters.status||item.status===filters.status));
export const getActiveGrowthGoals=state=>getGrowthGoals(state,{status:'active'});
export const getGrowthGoal=(state,id)=>find(normalizeLifestyle(state.lifestyle).growth.goals,id)||null;
export function addGrowthMilestone(state,d={}){const title=String(d.title||'').trim();if(!title||!d.goalId)return{ok:false,error:'Milestone needs a goal and title.',state};const item={id:d.id||uid('growth-milestone'),goalId:d.goalId,title,status:d.status||'open',order:Number(d.order)||0,completedAt:null,linkedSourceOptional:d.linkedSourceOptional||null,linkedExternalIdOptional:d.linkedExternalIdOptional||null,targetDateOptional:d.targetDateOptional||null,notes:d.notes||'',createdAt:now(),updatedAt:now()};return{ok:true,item,state:withLifestyle(state,x=>({...x,growth:{...x.growth,milestones:[...x.growth.milestones,item]}}))}}
export const getGrowthMilestones=(state,goalId)=>normalizeLifestyle(state.lifestyle).growth.milestones.filter(item=>item.goalId===goalId).sort((a,b)=>a.order-b.order);
export const completeGrowthMilestone=(state,id)=>withLifestyle(state,x=>({...x,growth:{...x.growth,milestones:x.growth.milestones.map(item=>item.id===id?{...item,status:'completed',completedAt:now(),updatedAt:now()}:item)}}));
export function getRecommendedGrowthStep(state){for(const goal of getActiveGrowthGoals(state)){const next=getGrowthMilestones(state,goal.id).find(item=>item.status!=='completed');if(next)return{goal,milestone:next,title:next.title}}return null;}
export function addGrowthWin(state,d={}){const title=String(d.title||'').trim();if(!title)return{ok:false,error:'Win needs a title.',state};const item={id:d.id||uid('growth-win'),title,date:d.date||day(),source:d.source||'manual',externalIdOptional:d.externalIdOptional||null,categoryOptional:d.categoryOptional||null,noteOptional:d.noteOptional||'',pinned:!!d.pinned,createdAt:now()};return{ok:true,item,state:withLifestyle(state,x=>({...x,growth:{...x.growth,wins:x.growth.wins.some(win=>win.source===item.source&&win.externalIdOptional&&win.externalIdOptional===item.externalIdOptional)?x.growth.wins:[...x.growth.wins,item]}}))}}
export const getGrowthWins=(state,filters={})=>rangeFilter(normalizeLifestyle(state.lifestyle).growth.wins,filters).filter(item=>!filters.source||item.source===filters.source).sort((a,b)=>String(b.date).localeCompare(String(a.date)));
export const getRecentGrowthWins=(state,limit=5)=>getGrowthWins(state).slice(0,limit);
export function addGrowthReflection(state,d={}){const text=String(d.text||'').trim();if(!text)return{ok:false,error:'Reflection needs a little text.',state};const item={id:d.id||uid('growth-reflection'),goalIdOptional:d.goalIdOptional||null,date:d.date||day(),text,moodOptional:d.moodOptional||'',createdAt:now()};return{ok:true,item,state:withLifestyle(state,x=>({...x,growth:{...x.growth,reflections:[...x.growth.reflections,item]}}))}}

/** Stable Daily Shit integration. The domain object stays canonical and survives action completion. */
export function publishLifestyleAction(store,{source,id,title,scheduledDate,energy='Medium',estimatedMinutes=0,metadata={}}){return store?.createAction?store.createAction({source,externalId:`${source}:${id}`,text:title,scheduledDate,energy,estimatedMinutes,metadata:{lifestyleSource:source,lifestyleId:id,...metadata}}):{ok:false,error:'Daily Shit action API unavailable.'}}
