import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';

const source=path=>readFile(new URL(path,import.meta.url),'utf8');
const url=code=>`data:text/javascript;base64,${Buffer.from(code).toString('base64')}`;
const mochini=url(`export const readableReason=r=>({assigned_today:'It is already assigned to today.',fits_capacity:'It fits your current capacity.'}[r?.code||r]||'KatOS used the current planner information.');export const buildMochiniPresentation=e=>({message:e?.state?.openTaskCount?'A task fits.':'Rest counts too.'});`);
const tasks=url(`export const taskTitle=t=>t?.text||t?.title||'Untitled task';export const openTasksForDate=(state,date)=>(state.tasks||[]).filter(t=>t.date===date&&!t.done);`);
const events=url(`export const eventsForDate=(state,date)=>(state.events||[]).filter(e=>e.date===date);export const nextTimedEvent=(state,date)=>eventsForDate(state,date).filter(e=>e.start).sort((a,b)=>a.start.localeCompare(b.start))[0]||null;export const eventsInRange=(state,{date,range})=>{const day=new Date(date+'T12:00:00'),end=new Date(day);if(range==='tomorrow'){day.setDate(day.getDate()+1);end.setDate(end.getDate()+1)}else if(range==='week')end.setDate(end.getDate()+(7-end.getDay())%7);const key=d=>d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');return(state.events||[]).filter(e=>e.date>=key(day)&&e.date<=key(end));};`);
const data=url(`export const localDateKey=value=>{const date=value?new Date(value):new Date();return date.getFullYear()+'-'+String(date.getMonth()+1).padStart(2,'0')+'-'+String(date.getDate()).padStart(2,'0')};`);
const deadlines=url(`export const upcomingDeadlines=(state,{date}={})=>(state.deadlines||[]).filter(item=>!date||item.date===date);`);
const workSchedule=url(`export const normalizeWorkSchedule=value=>value||{weekly:{}};export const shiftsForDate=(schedule,date)=>schedule?.weekly?.[new Date(date+'T12:00:00').toLocaleDateString('en-US',{weekday:'long'}).toLowerCase()]||[];export const shiftLabel=shift=>shift.start+' – '+shift.end;`);
const guidedRoutines=url(`export const routineModeState=(state)=>state.routineModeState||{active:false,routine:null,currentTask:null};`);
const dayContext=url((await source('./logic/mochini-day-context.js')).replace("'../data.js?v=22.1.21-20260817'",`'${data}'`).replace("'./tasks.js?v=22.1.21-20260817'",`'${tasks}'`).replace("'./events.js?v=22.1.21-20260817'",`'${events}'`).replace("'./deadlines.js?v=22.1.21-20260817'",`'${deadlines}'`));
const intents=url((await source('./mochini-intents.js')).replace("'./mochini.js?v=22.1.28-20260818'",`'${mochini}'`).replace("'./logic/tasks.js?v=22.1.19-20260817'",`'${tasks}'`).replace("'./logic/events.js?v=22.1.19-20260817'",`'${events}'`).replace("'./logic/mochini-day-context.js?v=22.1.21-20260817'",`'${dayContext}'`).replace("'./logic/deadlines.js?v=22.1.16-20260817'",`'${deadlines}'`).replace("'./work-schedule.js?v=22.1.16-20260817'",`'${workSchedule}'`).replace("'./guided-routines.js?v=22.1.30-20260818'",`'${guidedRoutines}'`));
const {answerMochiniIntent,matchMochiniIntent,normalizeMochiniInput}=await import(intents);
const task={id:'one',text:'Take medication',date:'2026-08-17'};
const state={tasks:[task],events:[{id:'event',title:'Class',date:'2026-08-17',start:'15:00'}]};
const evaluation={date:'2026-08-17',state:{capacity:'High',openTaskCount:1,eligibleTaskCount:1},recommendedNextAction:{task,reasons:[{code:'assigned_today'},{code:'fits_capacity'}]},candidates:[{task,reasons:[{code:'assigned_today'}]}],deadlines:[{title:'Submit quiz',date:'2026-08-18',urgency:'tomorrow'}],routines:{total:2,completed:1,remaining:1},alerts:[],escalation:{needsBigMochi:false,reasons:[]}};
const answer=(input,session={})=>answerMochiniIntent(matchMochiniIntent(input),{state,evaluation,session});
assert.equal(normalizeMochiniInput(' What’s next?? '),'whats next');
['What should I do?','What’s next?','What should I do next?','What should I start with?','Pick something for me.'].forEach(input=>assert.equal(matchMochiniIntent(input).intent,'ask_next_task'));
const next=answer('What should I do?');assert.match(next.answer,/Take medication/);assert.equal(next.escalation,false);
assert.equal(matchMochiniIntent("I don't want to do this anymore").intent,'ask_resistance');
assert.match(answer('Why?',{lastRecommendation:next.recommendation,lastReasons:next.recommendation.reasons}).answer,/assigned to today/i);
assert.match(answer('Why?').answer,/haven’t picked/i);
assert.equal(matchMochiniIntent('What do I have today?').intent,'ask_day_context');assert.match(answer('What do I have today?').answer,/Take medication/);
['Do I have any more tasks to do?','Do I have anything left?','What tasks are left?','What’s left?','What do I still need to do?','Am I done with my tasks?','How many tasks do I have left?','Any tasks left?','What do I need to do today?'].forEach(input=>assert.equal(matchMochiniIntent(input).intent,'ask_task_status',input));
assert.match(answer('Do I have any more tasks to do?').answer,/1 task left today/i);assert.match(answer('What tasks are left?').answer,/Take medication/);assert.match(answerMochiniIntent(matchMochiniIntent('Am I done?'),{state:{tasks:[]},evaluation:{...evaluation,state:{...evaluation.state,openTaskCount:0}},session:{}}).answer,/clear/i);
assert.equal(matchMochiniIntent('Any deadlines?').intent,'ask_deadlines');assert.match(answer('Any deadlines?').answer,/Submit quiz/);
assert.equal(matchMochiniIntent('How are my routines?').intent,'ask_routines');assert.match(answer('How are my routines?').answer,/1 step left/);
assert.equal(matchMochiniIntent('What is my next event?').intent,'ask_next_event');assert.match(answer('What is my next event?').answer,/Class/);
const workState={...state,workSchedule:{weekly:{sunday:[],monday:[],tuesday:[],wednesday:[],thursday:[],friday:[],saturday:[{id:'shift',start:'13:00',end:'17:00'}]}},brainNotes:[{id:'capture',title:'Pink folders',createdAt:'2026-08-17T10:00:00Z'}],guidedRoutines:[{id:'night',name:'Night Routine',taskIds:['one'],gatewayTaskId:'one'}],schoolTasks:[{id:'school',name:'Essay',due:'2026-08-18',done:false}],deadlines:[{id:'school-deadline',source:'school_task',title:'Essay',date:'2026-08-18',urgency:'tomorrow'}]};
assert.equal(matchMochiniIntent('Do I work today?').intent,'ask_work_schedule');assert.match(answerMochiniIntent(matchMochiniIntent('When do I work today?'),{state:{...workState,workSchedule:{weekly:{monday:[{id:'shift',start:'13:00',end:'17:00'}]}}},evaluation,session:{}}).answer,/13:00/);
assert.equal(matchMochiniIntent('What routines do I have?').intent,'ask_routine_info');assert.match(answerMochiniIntent(matchMochiniIntent("What's my night routine?"),{state:workState,evaluation,session:{}}).answer,/Night Routine/);
assert.equal(matchMochiniIntent('What do I need to make sure I do?').intent,'ask_protected_tasks');assert.match(answerMochiniIntent(matchMochiniIntent('What do I need to make sure I do?'),{state:{...state,tasks:[{...task,isProtected:true}]},evaluation,session:{}}).answer,/Take medication/);
assert.equal(matchMochiniIntent("What's my closest school deadline?").intent,'ask_school');assert.match(answerMochiniIntent(matchMochiniIntent("What's my closest school deadline?"),{state:workState,evaluation,session:{}}).answer,/Essay/);
assert.equal(matchMochiniIntent("What's in my Catch-All?").intent,'ask_catch_all');assert.match(answerMochiniIntent(matchMochiniIntent("What's in my Catch-All?"),{state:workState,evaluation,session:{}}).answer,/Pink folders/);
['Low','Medium','High'].forEach(capacity=>assert.match(answerMochiniIntent({intent:'ask_capacity'},{state,evaluation:{...evaluation,state:{...evaluation.state,capacity}},session:{}}).answer,new RegExp(capacity)));
assert.equal(matchMochiniIntent('How does today look?').intent,'ask_today_summary');assert.match(answer('How does today look?').answer,/open task/);
assert.equal(matchMochiniIntent('Anything coming up?').intent,'ambiguous');assert.deepEqual(answer('Anything coming up?').choices,['ask_tasks','ask_next_event','ask_deadlines']);
assert.equal(matchMochiniIntent('Tell me a joke').intent,'unknown');assert.equal(answer('Tell me a joke').escalation,true);
assert.equal(matchMochiniIntent('Should I completely change my plan for school?').intent,'complex');assert.equal(answer('Should I completely change my plan for school?').escalation,true);
const mutation=answer('Delete that task.');assert.equal(mutation.intent,'mutation_request');assert.equal(mutation.escalation,false);assert.match(mutation.answer,/can’t change/i);
const noTasks=answerMochiniIntent({intent:'ask_tasks'},{state:{tasks:[]},evaluation:{...evaluation,state:{...evaluation.state,openTaskCount:0}},session:{}});assert.match(noTasks.answer,/clear/i);
const noDeadline=answerMochiniIntent({intent:'ask_deadlines'},{state,evaluation:{...evaluation,deadlines:[]},session:{}});assert.match(noDeadline.answer,/No upcoming/i);
const noRoutine=answerMochiniIntent({intent:'ask_routines'},{state,evaluation:{...evaluation,routines:{total:0,completed:0,remaining:0}},session:{}});assert.match(noRoutine.answer,/No routines/i);
const noEvent=answerMochiniIntent({intent:'ask_next_event'},{state:{...state,events:[]},evaluation,session:{}});assert.match(noEvent.answer,/Nothing fixed/i);
assert.equal(matchMochiniIntent('What events do I have this week?').intent,'ask_events_range');assert.match(answer('What events do I have today?').answer,/Class/);assert.equal(answer('What events do I have today?').escalation,false);assert.match(answerMochiniIntent(matchMochiniIntent('What events do I have this week?'),{state:{...state,events:[]},evaluation,session:{}}).answer,/Nothing scheduled this week/i);assert.equal(answerMochiniIntent(matchMochiniIntent('What events do I have this week?'),{state:{...state,events:[]},evaluation,session:{}}).escalation,false);
const hyperEvaluation={...evaluation,hyperfixation:{active:true,focus:{label:'KatOS'},nextFixedEvent:state.events[0]}};assert.match(answerMochiniIntent(matchMochiniIntent('What is my fixation?'),{state,evaluation:hyperEvaluation,session:{}}).answer,/KatOS/);assert.match(answerMochiniIntent(matchMochiniIntent('Can I keep going?'),{state,evaluation:hyperEvaluation,session:{}}).answer,/Class/);assert.match(answerMochiniIntent(matchMochiniIntent('End hyperfixation mode'),{state,evaluation:hyperEvaluation,session:{}}).answer,/Home/);
const gatewayTask={id:'gateway',text:'Shower',date:'2026-08-17',isGatewayTask:true,routineId:'self-care'};
const gatewayEvaluation={...evaluation,recommendedNextAction:{task:gatewayTask,reasons:[{code:'gateway_task'}]},candidates:[{task:gatewayTask,reasons:[{code:'gateway_task'}]}]};
assert.match(answerMochiniIntent(matchMochiniIntent('What should I do?'),{state:{tasks:[gatewayTask]},evaluation:gatewayEvaluation,session:{}}).answer,/gateway task/i);
assert.match(answerMochiniIntent(matchMochiniIntent("I don't want to do this"),{state:{tasks:[gatewayTask]},evaluation:gatewayEvaluation,session:{lastRecommendation:gatewayEvaluation.recommendedNextAction}}).answer,/first step/i);
const protectedTask={id:'protected',text:'Work videos',date:'2026-08-17',isProtected:true};
const protectedEvaluation={...evaluation,recommendedNextAction:{task:protectedTask,reasons:[{code:'protected_commitment'}]},candidates:[{task:protectedTask,reasons:[{code:'protected_commitment'}]}]};
assert.match(answerMochiniIntent(matchMochiniIntent('What should I do?'),{state:{tasks:[protectedTask]},evaluation:protectedEvaluation,session:{}}).answer,/protected commitment/i);
assert.equal(matchMochiniIntent('Protect this task').intent,'request_protect_last_recommendation');
assert.match(answerMochiniIntent(matchMochiniIntent('Protect this task'),{state:{tasks:[task]},evaluation,session:{lastRecommendation:next.recommendation}}).answer,/only if you approve/i);
assert.match(answerMochiniIntent(matchMochiniIntent('Protect this task'),{state,evaluation,session:{}}).answer,/recommend a task first/i);
const deferredTask={id:'deferred',text:'Shower',date:'2026-08-17',timesDeferred:3};
const deferredEvaluation={...evaluation,recommendedNextAction:{task:deferredTask,reasons:[{code:'deferred_repeatedly'}]},candidates:[{task:deferredTask,reasons:[{code:'deferred_repeatedly'}]}]};
assert.match(answerMochiniIntent(matchMochiniIntent('What should I do?'),{state:{tasks:[deferredTask]},evaluation:deferredEvaluation,session:{}}).answer,/moved a few times/i);
const protectedFixation={...evaluation,hyperfixation:{active:true,focus:{label:'KatOS'},nextFixedEvent:null},candidates:[{task:protectedTask,reasons:[]}]};assert.match(answerMochiniIntent(matchMochiniIntent('Can I keep going?'),{state:{tasks:[protectedTask]},evaluation:protectedFixation,session:{}}).answer,/waiting for the baton/i);
assert.deepEqual(state,{tasks:[task],events:[{id:'event',title:'Class',date:'2026-08-17',start:'15:00'}]});
console.log('Mochini deterministic intent tests: PASS');
