import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';

const source=path=>readFile(new URL(path,import.meta.url),'utf8');
const url=code=>`data:text/javascript;base64,${Buffer.from(code).toString('base64')}`;
const mochini=url(`export const readableReason=r=>({assigned_today:'It is already assigned to today.',fits_capacity:'It fits your current capacity.'}[r?.code||r]||'KatOS used the current planner information.');export const buildMochiniPresentation=e=>({message:e?.state?.openTaskCount?'A task fits.':'Rest counts too.'});`);
const tasks=url(`export const taskTitle=t=>t?.text||t?.title||'Untitled task';export const openTasksForDate=(state,date)=>(state.tasks||[]).filter(t=>t.date===date&&!t.done);`);
const events=url(`export const nextTimedEvent=(state,date)=>((state.events||[]).filter(e=>e.date===date&&e.start).sort((a,b)=>a.start.localeCompare(b.start))[0]||null);export const eventsInRange=(state,{date,range})=>{const day=new Date(date+'T12:00:00'),end=new Date(day);if(range==='tomorrow'){day.setDate(day.getDate()+1);end.setDate(end.getDate()+1)}else if(range==='week')end.setDate(end.getDate()+(7-end.getDay())%7);const key=d=>d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');return(state.events||[]).filter(e=>e.date>=key(day)&&e.date<=key(end));};`);
const intents=url((await source('./mochini-intents.js')).replace("'./mochini.js?v=22.1.19-20260817'",`'${mochini}'`).replace("'./logic/tasks.js?v=22.1.19-20260817'",`'${tasks}'`).replace("'./logic/events.js?v=22.1.19-20260817'",`'${events}'`));
const {answerMochiniIntent,matchMochiniIntent,normalizeMochiniInput}=await import(intents);
const task={id:'one',text:'Take medication',date:'2026-08-17'};
const state={tasks:[task],events:[{id:'event',title:'Class',date:'2026-08-17',start:'15:00'}]};
const evaluation={date:'2026-08-17',state:{capacity:'High',openTaskCount:1,eligibleTaskCount:1},recommendedNextAction:{task,reasons:[{code:'assigned_today'},{code:'fits_capacity'}]},candidates:[{task,reasons:[{code:'assigned_today'}]}],deadlines:[{title:'Submit quiz',date:'2026-08-18',urgency:'tomorrow'}],routines:{total:2,completed:1,remaining:1},alerts:[],escalation:{needsBigMochi:false,reasons:[]}};
const answer=(input,session={})=>answerMochiniIntent(matchMochiniIntent(input),{state,evaluation,session});
assert.equal(normalizeMochiniInput(' What’s next?? '),'whats next');
['What should I do?','What’s next?','Pick something for me.'].forEach(input=>assert.equal(matchMochiniIntent(input).intent,'ask_next_task'));
const next=answer('What should I do?');assert.match(next.answer,/Take medication/);assert.equal(next.escalation,false);
assert.match(answer('Why?',{lastRecommendation:next.recommendation,lastReasons:next.recommendation.reasons}).answer,/assigned to today/i);
assert.match(answer('Why?').answer,/haven’t picked/i);
assert.equal(matchMochiniIntent('What do I have today?').intent,'ask_tasks');assert.match(answer('What do I have today?').answer,/Take medication/);
assert.equal(matchMochiniIntent('Any deadlines?').intent,'ask_deadlines');assert.match(answer('Any deadlines?').answer,/Submit quiz/);
assert.equal(matchMochiniIntent('How are my routines?').intent,'ask_routines');assert.match(answer('How are my routines?').answer,/1 step left/);
assert.equal(matchMochiniIntent('What is my next event?').intent,'ask_next_event');assert.match(answer('What is my next event?').answer,/Class/);
['Low','Medium','High'].forEach(capacity=>assert.match(answerMochiniIntent({intent:'ask_capacity'},{state,evaluation:{...evaluation,state:{...evaluation.state,capacity}},session:{}}).answer,new RegExp(capacity)));
assert.equal(matchMochiniIntent('How does today look?').intent,'ask_today_summary');assert.match(answer('How does today look?').answer,/open task/);
assert.equal(matchMochiniIntent('Anything coming up?').intent,'ambiguous');assert.deepEqual(answer('Anything coming up?').choices,['ask_tasks','ask_next_event','ask_deadlines']);
assert.equal(matchMochiniIntent('Tell me a joke').intent,'unknown');assert.equal(answer('Tell me a joke').escalation,true);
assert.equal(matchMochiniIntent('Should I completely change my plan for school?').intent,'complex');assert.equal(answer('Should I completely change my plan for school?').escalation,true);
const mutation=answer('Delete that task.');assert.equal(mutation.intent,'mutation_request');assert.equal(mutation.escalation,false);assert.match(mutation.answer,/can’t change/i);
const noTasks=answerMochiniIntent({intent:'ask_tasks'},{state:{tasks:[]},evaluation:{...evaluation,state:{...evaluation.state,openTaskCount:0}},session:{}});assert.match(noTasks.answer,/clear/i);
const noDeadline=answerMochiniIntent({intent:'ask_deadlines'},{state,evaluation:{...evaluation,deadlines:[]},session:{}});assert.match(noDeadline.answer,/No upcoming/i);
const noRoutine=answerMochiniIntent({intent:'ask_routines'},{state,evaluation:{...evaluation,routines:{total:0,completed:0,remaining:0}},session:{}});assert.match(noRoutine.answer,/No routines/i);
const noEvent=answerMochiniIntent({intent:'ask_next_event'},{state:{...state,events:[]},evaluation,session:{}});assert.match(noEvent.answer,/Nothing fixed/i);
assert.equal(matchMochiniIntent('What events do I have this week?').intent,'ask_events_range');assert.match(answer('What events do I have today?').answer,/Class/);assert.equal(answer('What events do I have today?').escalation,false);assert.match(answerMochiniIntent(matchMochiniIntent('What events do I have this week?'),{state:{...state,events:[]},evaluation,session:{}}).answer,/Nothing scheduled this week/i);assert.equal(answerMochiniIntent(matchMochiniIntent('What events do I have this week?'),{state:{...state,events:[]},evaluation,session:{}}).escalation,false);
const hyperEvaluation={...evaluation,hyperfixation:{active:true,focus:{label:'KatOS'},nextFixedEvent:state.events[0]}};assert.match(answerMochiniIntent(matchMochiniIntent('What is my fixation?'),{state,evaluation:hyperEvaluation,session:{}}).answer,/KatOS/);assert.match(answerMochiniIntent(matchMochiniIntent('Can I keep going?'),{state,evaluation:hyperEvaluation,session:{}}).answer,/Class/);assert.match(answerMochiniIntent(matchMochiniIntent('End hyperfixation mode'),{state,evaluation:hyperEvaluation,session:{}}).answer,/Home/);
assert.deepEqual(state,{tasks:[task],events:[{id:'event',title:'Class',date:'2026-08-17',start:'15:00'}]});
console.log('Mochini deterministic intent tests: PASS');
