/* Study Nook owns academic facts. Daily Shit receives only linked actions. */
const list=v=>Array.isArray(v)?v:[],obj=v=>v&&typeof v==='object'&&!Array.isArray(v);
const now=()=>new Date().toISOString(),uid=p=>`${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;
const dateKey=()=>new Date().toISOString().slice(0,10);
export const STUDY_NOOK_VERSION=1;
export const DEFAULT_STUDY_NOOK={version:STUDY_NOOK_VERSION,institutions:[],providers:[],programs:[],requirements:[],courses:[],assignments:[],terms:[],transferMappings:[],transferEvaluations:[],transferResults:[],studySessions:[],importantDates:[],documents:[]};
export const normalizeStudyNook=value=>{const next={...structuredClone(DEFAULT_STUDY_NOOK),...(obj(value)?value:{})};for(const key of ['institutions','providers','programs','requirements','courses','assignments','terms','transferMappings','transferEvaluations','transferResults','studySessions','importantDates','documents'])next[key]=list(next[key]);return next};
export const withStudyNook=(state,change)=>({...state,studyNook:change(normalizeStudyNook(state.studyNook))});
const byId=(items,id)=>list(items).find(item=>String(item.id)===String(id));
export const getAcademicPrograms=state=>normalizeStudyNook(state.studyNook).programs;
export const getActiveAcademicPrograms=state=>getAcademicPrograms(state).filter(p=>['active','preparing'].includes(p.status));
export const getAcademicProgram=(state,id)=>byId(normalizeStudyNook(state.studyNook).programs,id)||null;
export const getCompletedPrograms=state=>getAcademicPrograms(state).filter(p=>['completed','archived'].includes(p.status)||p.archivedAt);
export function addInstitution(state,draft={}){const name=String(draft.name||'').trim();if(!name)return{ok:false,error:'Institution name is required.',state};const institution={id:draft.id||uid('institution'),name,shortName:draft.shortName||name,type:draft.type||'college',active:draft.active!==false,websiteOptional:draft.websiteOptional||'',notes:draft.notes||'',createdAt:now(),updatedAt:now()};return{ok:true,institution,state:withStudyNook(state,h=>({...h,institutions:[...h.institutions,institution]}))};}
export function addProvider(state,draft={}){const name=String(draft.name||'').trim();if(!name)return{ok:false,error:'Provider name is required.',state};const provider={id:draft.id||uid('provider'),name,type:draft.type||'other',active:draft.active!==false,notes:draft.notes||'',createdAt:now(),updatedAt:now()};return{ok:true,provider,state:withStudyNook(state,h=>({...h,providers:[...h.providers,provider]}))};}
export function addAcademicProgram(state,draft={}){const title=String(draft.title||'').trim();if(!title)return{ok:false,error:'Program title is required.',state};const program={id:draft.id||uid('program'),title,shortTitle:draft.shortTitle||title,level:draft.level||'other',programType:draft.programType||'degree',institutionId:draft.institutionId||null,major:draft.major||'',concentration:draft.concentration||'',status:draft.status||'planned',startDate:draft.startDate||null,expectedCompletionDate:draft.expectedCompletionDate||null,completionDate:draft.completionDate||null,totalCreditsRequired:Number(draft.totalCreditsRequired)||0,activeTermId:draft.activeTermId||null,requirementSetId:draft.requirementSetId||null,notes:draft.notes||'',createdAt:now(),updatedAt:now(),archivedAt:null};return{ok:true,program,state:withStudyNook(state,h=>({...h,programs:[...h.programs,program]}))};}
export const updateAcademicProgram=(state,id,changes={})=>withStudyNook(state,h=>({...h,programs:h.programs.map(p=>p.id===id?{...p,...changes,id:p.id,updatedAt:now()}:p)}));
export const confirmProgramComplete=(state,id,date=dateKey())=>updateAcademicProgram(state,id,{status:'completed',completionDate:date,archivedAt:now()});
export function addRequirement(state,draft={}){const title=String(draft.title||'').trim();if(!title||!draft.programId)return{ok:false,error:'A program and requirement title are required.',state};const requirement={id:draft.id||uid('requirement'),programId:draft.programId,requirementKey:draft.requirementKey||title.toLowerCase().replace(/\W+/g,'-'),title,requirementType:draft.requirementType||'course',creditsRequired:Number(draft.creditsRequired)||0,status:draft.status||'remaining',category:draft.category||'',satisfiedByCourseId:draft.satisfiedByCourseId||null,satisfiedByTransferId:draft.satisfiedByTransferId||null,order:Number(draft.order)||0,notes:draft.notes||'',createdAt:now(),updatedAt:now()};return{ok:true,requirement,state:withStudyNook(state,h=>({...h,requirements:[...h.requirements,requirement]}))};}
export function addCourse(state,draft={}){const title=String(draft.title||draft.name||'').trim();if(!title||!draft.programId)return{ok:false,error:'A program and course title are required.',state};const course={id:draft.id||uid('course'),programId:draft.programId,providerId:draft.providerId||null,title,courseCode:draft.courseCode||'',credits:Number(draft.credits)||0,status:draft.status||'planned',progressPercent:Math.max(0,Math.min(100,Number(draft.progressPercent)||0)),startDate:draft.startDate||null,targetDate:draft.targetDate||null,completionDate:draft.completionDate||null,termId:draft.termId||null,requirementIds:list(draft.requirementIds),transferStatus:draft.transferStatus||'not_applicable',priority:draft.priority||'Whenever',queueOrder:Number(draft.queueOrder)||0,pinned:!!draft.pinned,gradeOptional:draft.gradeOptional||'',scoreOptional:draft.scoreOptional||'',notes:draft.notes||'',createdAt:now(),updatedAt:now(),archivedAt:null};return{ok:true,course,state:withStudyNook(state,h=>({...h,courses:[...h.courses,course]}))};}
export const updateCourse=(state,id,changes={})=>withStudyNook(state,h=>({...h,courses:h.courses.map(c=>c.id===id?{...c,...changes,id:c.id,progressPercent:Math.max(0,Math.min(100,Number(changes.progressPercent??c.progressPercent)||0)),updatedAt:now()}:c)}));
export const getActiveCourses=(state,programId)=>normalizeStudyNook(state.studyNook).courses.filter(c=>c.programId===programId&&['in_progress','queued','waiting'].includes(c.status));
export const getCourseAssignments=(state,courseId)=>normalizeStudyNook(state.studyNook).assignments.filter(a=>a.courseId===courseId).sort((a,b)=>(a.order||0)-(b.order||0));
export function addAssignment(state,draft={}){const title=String(draft.title||'').trim();if(!title||!draft.programId||!draft.courseId)return{ok:false,error:'Assignment title, program, and course are required.',state};const assignment={id:draft.id||uid('assignment'),programId:draft.programId,courseId:draft.courseId,title,type:draft.type||'assignment',status:draft.status||'not_started',progressPercent:Number(draft.progressPercent)||0,dueDate:draft.dueDate||null,dueTime:draft.dueTime||null,hardDeadline:!!draft.hardDeadline,order:Number(draft.order)||0,scoreOptional:draft.scoreOptional||'',gradeOptional:draft.gradeOptional||'',notes:draft.notes||'',linkedActionId:draft.linkedActionId||null,createdAt:now(),updatedAt:now(),completedAt:null};return{ok:true,assignment,state:withStudyNook(state,h=>({...h,assignments:[...h.assignments,assignment]}))};}
export const updateAssignment=(state,id,changes={})=>withStudyNook(state,h=>({...h,assignments:h.assignments.map(a=>a.id===id?{...a,...changes,id:a.id,updatedAt:now(),completedAt:changes.status==='completed'?(a.completedAt||now()):a.completedAt}:a)}));
export const completeAssignment=(state,id)=>updateAssignment(state,id,{status:'completed',progressPercent:100});
export function addTransferEvaluation(state,draft={}){if(!draft.programId)return{ok:false,error:'Choose a program.',state};const evaluation={id:draft.id||uid('evaluation'),programId:draft.programId,institutionId:draft.institutionId||null,evaluationDate:draft.evaluationDate||dateKey(),status:draft.status||'valid',totalCreditsAccepted:Number(draft.totalCreditsAccepted)||0,sourceLabel:draft.sourceLabel||'Official evaluation',notes:draft.notes||'',createdAt:now(),updatedAt:now()};return{ok:true,evaluation,state:withStudyNook(state,h=>({...h,transferEvaluations:[...h.transferEvaluations,evaluation]}))};}
export function addTransferResult(state,draft={}){if(!draft.evaluationId||!draft.requirementId)return{ok:false,error:'Evaluation and requirement are required.',state};const result={id:draft.id||uid('transfer-result'),evaluationId:draft.evaluationId,requirementId:draft.requirementId,sourceCourseId:draft.sourceCourseId||null,decision:draft.decision||'pending',creditsAccepted:Number(draft.creditsAccepted)||0,notes:draft.notes||'',createdAt:now(),updatedAt:now()};return{ok:true,result,state:withStudyNook(state,h=>({...h,transferResults:[...h.transferResults,result]}))};}
export const getLatestTransferEvaluation=(state,programId)=>normalizeStudyNook(state.studyNook).transferEvaluations.filter(e=>e.programId===programId&&e.status!=='superseded').sort((a,b)=>String(b.evaluationDate).localeCompare(String(a.evaluationDate)))[0]||null;
const latestResults=(state,programId)=>{const h=normalizeStudyNook(state.studyNook),e=getLatestTransferEvaluation(state,programId);return e?h.transferResults.filter(r=>r.evaluationId===e.id):[]};
export function getDegreeProgress(state,programId){const h=normalizeStudyNook(state.studyNook),program=byId(h.programs,programId);if(!program)return null;const requirements=h.requirements.filter(r=>r.programId===programId),results=latestResults(state,programId),courses=h.courses.filter(c=>c.programId===programId),acceptedByRequirement=new Map(results.filter(r=>['accepted','partial'].includes(r.decision)).map(r=>[r.requirementId,r]));const satisfied=requirements.filter(r=>r.status==='satisfied'||r.status==='waived'||acceptedByRequirement.has(r.id)||r.satisfiedByCourseId&&byId(courses,r.satisfiedByCourseId)?.status==='completed'||courses.some(c=>c.status==='completed'&&c.requirementIds.includes(r.id)&&providerIsInstitution(h,c,program)));const acceptedSources=new Map();for(const r of acceptedByRequirement.values()){const key=r.sourceCourseId||r.id;acceptedSources.set(key,Math.max(acceptedSources.get(key)||0,r.creditsAccepted))}const transferred=[...acceptedSources.values()].reduce((a,b)=>a+b,0),institutional=courses.filter(c=>c.status==='completed'&&providerIsInstitution(h,c,program)).reduce((sum,c)=>sum+c.credits,0),officialSatisfied=Math.min(program.totalCreditsRequired||Infinity,transferred+institutional),remaining=Math.max(0,(program.totalCreditsRequired||0)-officialSatisfied);return{program,percent:program.totalCreditsRequired?Math.round(officialSatisfied/program.totalCreditsRequired*100):0,totalCredits:program.totalCreditsRequired,officialSatisfiedCredits:officialSatisfied,transferredCredits:transferred,institutionalCredits:institutional,remainingCredits:remaining,satisfiedRequirements:satisfied.length,totalRequirements:requirements.length,inProgressRequirements:requirements.filter(r=>r.status==='in_progress'||courses.some(c=>c.requirementIds.includes(r.id)&&c.status==='in_progress')).length,remainingRequirements:requirements.length-satisfied.length};}
export const getDegreeProgressByLevel=(state,level)=>{const program=getAcademicPrograms(state).filter(p=>p.level===level&&!['withdrawn','archived'].includes(p.status)).sort((a,b)=>['active','preparing','planned','completed'].indexOf(a.status)-['active','preparing','planned','completed'].indexOf(b.status))[0];return program?getDegreeProgress(state,program.id):null};
export const getAcademicProgramSummary=(state,programId)=>{const program=getAcademicProgram(state,programId),progress=program&&getDegreeProgress(state,programId);return program?{id:program.id,title:program.title,level:program.level,status:program.status,completionDate:program.completionDate,progress}:null};
const providerIsInstitution=(h,course,program)=>{const provider=byId(h.providers,course.providerId);return provider?.type==='degree_institution'||course.providerId===program.institutionId};
export function getTransferSummary(state,programId){const h=normalizeStudyNook(state.studyNook),courses=h.courses.filter(c=>c.programId===programId),latest=latestResults(state,programId);return{planned:courses.filter(c=>['eligible_planned','researching'].includes(c.transferStatus)).length,inProgress:courses.filter(c=>c.transferStatus==='in_progress_external').length,completedExternal:courses.filter(c=>['completed_external','transcript_not_sent','transcript_sent','pending_evaluation'].includes(c.transferStatus)).length,accepted:latest.filter(r=>r.decision==='accepted').reduce((n,r)=>n+r.creditsAccepted,0),pending:latest.filter(r=>r.decision==='pending').reduce((n,r)=>n+r.creditsAccepted,0),rejected:latest.filter(r=>r.decision==='rejected').length,evaluation:getLatestTransferEvaluation(state,programId)};}
export const getCurrentFocusCourse=(state,programId)=>{const courses=getActiveCourses(state,programId),assignments=normalizeStudyNook(state.studyNook).assignments;return courses.filter(c=>c.pinned).at(0)||courses.filter(c=>assignments.some(a=>a.courseId===c.id&&a.hardDeadline&&a.status!=='completed')).sort((a,b)=>String(assignments.find(x=>x.courseId===a.id)?.dueDate||'9999').localeCompare(String(assignments.find(x=>x.courseId===b.id)?.dueDate||'9999')))[0]||courses.filter(c=>c.status==='in_progress').sort((a,b)=>b.progressPercent-a.progressPercent)[0]||courses.sort((a,b)=>(a.queueOrder||0)-(b.queueOrder||0))[0]||null;};
export function getRecommendedAcademicNextStep(state,programId){const h=normalizeStudyNook(state.studyNook),focus=getCurrentFocusCourse(state,programId),assignments=h.assignments.filter(a=>a.programId===programId&&a.status!=='completed');const hard=assignments.filter(a=>a.hardDeadline&&a.dueDate).sort((a,b)=>String(a.dueDate).localeCompare(String(b.dueDate)))[0],current=assignments.filter(a=>a.courseId===focus?.id&&a.status!=='completed').sort((a,b)=>(a.order||0)-(b.order||0))[0];const item=hard||current;if(item)return{kind:'assignment',id:item.id,title:item.title,courseId:item.courseId,reason:hard?'Hard academic deadline':'Next item in current course'};if(focus)return{kind:'course',id:focus.id,title:focus.title,courseId:focus.id,reason:'Current academic focus'};return null;}
export const getUpcomingAcademicDeadlines=(state,{from=dateKey(),to='9999-12-31'}={})=>normalizeStudyNook(state.studyNook).assignments.filter(a=>a.dueDate&&a.dueDate>=from&&a.dueDate<=to&&a.status!=='completed').sort((a,b)=>a.dueDate.localeCompare(b.dueDate));
export function addStudySession(state,draft={}){if(!draft.programId)return{ok:false,error:'Choose a program.',state};const session={id:draft.id||uid('study-session'),programId:draft.programId,courseId:draft.courseId||null,date:draft.date||dateKey(),targetMinutes:Number(draft.targetMinutes)||0,actualMinutesOptional:Number(draft.actualMinutesOptional)||0,goal:draft.goal||'',status:draft.status||'planned',notes:draft.notes||'',linkedActionId:draft.linkedActionId||null,createdAt:now(),updatedAt:now()};return{ok:true,session,state:withStudyNook(state,h=>({...h,studySessions:[...h.studySessions,session]}))};}
export const getStudySessions=(state,{from='0000-01-01',to='9999-12-31'}={})=>normalizeStudyNook(state.studyNook).studySessions.filter(s=>s.date>=from&&s.date<=to);
export function publishStudyAction(store,{kind,id,title,scheduledDate,deadlineDate=null,deadlineType='soft',priority='Should do',metadata={}}){return store?.createAction?store.createAction({source:'study',externalId:`study-nook:${kind}:${id}`,text:title,scheduledDate,deadlineDate,deadlineType,priority,metadata:{studyKind:kind,studyId:id,...metadata}}):{ok:false,error:'Daily Shit action API unavailable.'};}
