/* Work HQ is intentionally an information model.  Daily Shit remains the only
 * action model; this module only publishes linked work actions through its API. */
export const WORK_HQ_VERSION=1;
export const WEEKDAYS=['sunday','monday','tuesday','wednesday','thursday','friday','saturday'];
const list=value=>Array.isArray(value)?value:[];
const object=value=>value&&typeof value==='object'&&!Array.isArray(value);
const stamp=()=>new Date().toISOString();
const uid=prefix=>`${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;
const dateKey=value=>{const d=value instanceof Date?new Date(value):value?new Date(`${String(value).slice(0,10)}T12:00:00`):new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const addDays=(date,days)=>{const d=new Date(`${dateKey(date)}T12:00:00`);d.setDate(d.getDate()+days);return dateKey(d)};
const weekday=date=>WEEKDAYS[new Date(`${dateKey(date)}T12:00:00`).getDay()];
const sessionKey=(clientId,date,start='')=>`work-session:${clientId}:${date}:${start||'any'}`;

export const CAREER_REQUIREMENT_SETS={
 rbt_2026:{id:'rbt_2026',effectiveFrom:'2026-01-01',label:'RBT requirements (2026)',source:'BACB RBT Handbook',milestones:[
  ['eligibility','Eligibility'],['training','Qualifying training'],['competency','Initial Competency Assessment'],['application','Application submitted'],['approval','Application/authorization approved'],['exam','RBT examination'],['certification','Certification active']
 ]},
 bcaba_2027:{id:'bcaba_2027',effectiveFrom:'2027-01-01',label:'BCaBA roadmap (verify before use)',milestones:[['education','Bachelor’s degree'],['coursework','Required coursework verified'],['fieldwork','Eligible supervised fieldwork verified'],['application','Application submitted/approved'],['exam','BCaBA examination'],['certification','BCaBA active']]},
 bcba_2027:{id:'bcba_2027',effectiveFrom:'2027-01-01',label:'BCBA roadmap (verify before use)',milestones:[['education','Master’s degree or higher'],['coursework','Required coursework verified'],['fieldwork','Eligible supervised fieldwork verified'],['application','Application submitted/approved'],['exam','BCBA examination'],['certification','BCBA active']]},
 rbt_maintenance_2026:{id:'rbt_maintenance_2026',effectiveFrom:'2026-01-01',supervisionPercent:5,professionalDevelopmentHours:12,cycleYears:2}
};
export const DEFAULT_WORK_HQ={version:WORK_HQ_VERSION,clients:[],supervisors:[],materials:[],scheduleExceptions:[],sessionPlans:[],career:{currentRole:'bt_rlt',rbtRequirementSetId:'rbt_2026',rbtMilestones:{},exam:{status:'pending',date:null,time:null,location:null,notes:'',result:null},leadRbtChecklist:[],degreeProgress:{}},professionalDevelopment:[],fieldworkRecords:[],documents:[]};
export const normalizeWorkHQ=input=>{const value=object(input)?input:{};const next={...structuredClone(DEFAULT_WORK_HQ),...value,career:{...structuredClone(DEFAULT_WORK_HQ.career),...(object(value.career)?value.career:{})}};for(const key of ['clients','supervisors','materials','scheduleExceptions','sessionPlans','professionalDevelopment','fieldworkRecords','documents'])next[key]=list(next[key]);for(const client of next.clients){client.serviceSchedule=list(client.serviceSchedule);client.programCodes=list(client.programCodes);client.preferredMaterials=list(client.preferredMaterials);client.supervisorIds=list(client.supervisorIds)}return next};
export const withWorkHQ=(state,change)=>({...state,workHQ:change(normalizeWorkHQ(state.workHQ))});
export const activeClients=state=>normalizeWorkHQ(state.workHQ).clients.filter(client=>client.active!==false&&!client.archivedAt);
export const prepStatus=plan=>{if(!plan)return{label:'Not planned',done:0,total:0};const checks=list(plan.prepChecklist),total=checks.length,done=checks.filter(item=>item.packed).length;if(total&&done===total)return{label:'Ready',done,total};return{label:'Started',done,total}};
export function getWorkSessionsForDate(state,date=dateKey()){
 const hq=normalizeWorkHQ(state.workHQ),target=dateKey(date),out=[];
 for(const client of activeClients(state))for(const slot of client.serviceSchedule.filter(slot=>slot.weekday===weekday(target))){
  const exception=hq.scheduleExceptions.find(item=>item.clientId===client.id&&(item.date===target||(item.type==='moved'&&item.originalDate===target)));
  if(exception?.type==='canceled'||(exception?.type==='moved'&&exception.originalDate===target))continue;
  const override=exception?.type==='time_override'?exception:null;
  const start=override?.startTime||slot.startTime||'',end=override?.endTime||slot.endTime||'';
  const key=sessionKey(client.id,target,start),plan=hq.sessionPlans.find(item=>item.sessionKey===key);
  out.push({id:key,sessionKey:key,clientId:client.id,client,date:target,startTime:start,endTime:end,setting:override?.setting||slot.setting||client.setting||'',supervisorId:override?.supervisorId||slot.supervisorId||client.supervisorIds[0]||null,plan,prep:prepStatus(plan),scheduledMinutes:minutes(start,end),status:target<dateKey()?'past':'upcoming'});
 }
 for(const exception of hq.scheduleExceptions.filter(item=>['extra_session','moved'].includes(item.type)&&item.date===target)){const client=hq.clients.find(item=>item.id===exception.clientId);if(!client||client.active===false)continue;const key=sessionKey(client.id,target,exception.startTime||'');const plan=hq.sessionPlans.find(item=>item.sessionKey===key);out.push({id:key,sessionKey:key,clientId:client.id,client,date:target,startTime:exception.startTime||'',endTime:exception.endTime||'',setting:exception.setting||client.setting||'',supervisorId:exception.supervisorId||client.supervisorIds[0]||null,plan,prep:prepStatus(plan),scheduledMinutes:minutes(exception.startTime,exception.endTime),status:target<dateKey()?'past':'upcoming',exception});}
 return out.sort((a,b)=>a.startTime.localeCompare(b.startTime)||a.client.alias.localeCompare(b.client.alias));
}
export function getWorkSessionsForRange(state,start,end){let date=dateKey(start),out=[];while(date<=dateKey(end)){out=out.concat(getWorkSessionsForDate(state,date));date=addDays(date,1)}return out;}
export const getUpcomingSessions=(state,{from=dateKey(),limit=8}={})=>getWorkSessionsForRange(state,from,addDays(from,20)).filter(item=>item.status==='upcoming').slice(0,limit);
export const getSessionPlan=(state,key)=>normalizeWorkHQ(state.workHQ).sessionPlans.find(plan=>plan.sessionKey===key)||null;
export function upsertSessionPlan(state,draft){const hq=normalizeWorkHQ(state.workHQ),existing=hq.sessionPlans.find(plan=>plan.sessionKey===draft.sessionKey),now=stamp();const plan={...existing,...draft,id:existing?.id||draft.id||uid('plan'),programCodes:list(draft.programCodes??existing?.programCodes),materials:list(draft.materials??existing?.materials),prepChecklist:list(draft.prepChecklist??existing?.prepChecklist),createdAt:existing?.createdAt||now,updatedAt:now};return withWorkHQ(state,current=>({...current,sessionPlans:existing?current.sessionPlans.map(item=>item.id===existing.id?plan:item):[...current.sessionPlans,plan]}));}
export function duplicateSessionPlan(state,sourceKey,targetSession){const source=getSessionPlan(state,sourceKey);if(!source)return state;return upsertSessionPlan(state,{...source,id:null,sessionKey:targetSession.sessionKey,clientId:targetSession.clientId,date:targetSession.date,startTime:targetSession.startTime,endTime:targetSession.endTime,prepChecklist:list(source.prepChecklist).map(item=>({...item,packed:false}))});}
export function addClient(state,draft={}){const alias=String(draft.alias||draft.displayName||'').trim();if(!alias)return{ok:false,error:'An alias or client code is required.',state};const now=stamp(),client={id:draft.id||uid('client'),alias,displayName:String(draft.displayName||alias).trim(),color:draft.color||'strawberry',icon:draft.icon||'🍓',active:draft.active!==false,setting:draft.setting||'',defaultDurationMinutes:Number(draft.defaultDurationMinutes)||0,supervisorIds:list(draft.supervisorIds),serviceSchedule:list(draft.serviceSchedule),programCodes:list(draft.programCodes),preferredMaterials:list(draft.preferredMaterials),notes:draft.notes||'',createdAt:draft.createdAt||now,updatedAt:now};return{ok:true,client,state:withWorkHQ(state,hq=>({...hq,clients:[...hq.clients,client]}))};}
export function updateClient(state,id,changes={}){return withWorkHQ(state,hq=>({...hq,clients:hq.clients.map(client=>client.id===id?{...client,...changes,id:client.id,updatedAt:stamp(),serviceSchedule:list(changes.serviceSchedule??client.serviceSchedule),programCodes:list(changes.programCodes??client.programCodes),preferredMaterials:list(changes.preferredMaterials??client.preferredMaterials)}:client)}));}
export const archiveClient=(state,id)=>updateClient(state,id,{active:false,archivedAt:stamp()});
export function addSupervisor(state,draft={}){const alias=String(draft.aliasOrName||'').trim();if(!alias)return{ok:false,error:'A supervisor name or alias is required.',state};const supervisor={id:draft.id||uid('supervisor'),aliasOrName:alias,credentialType:draft.credentialType||'BCBA',role:draft.role||'',emailOptional:draft.emailOptional||'',phoneOptional:draft.phoneOptional||'',active:draft.active!==false,notes:draft.notes||'',createdAt:stamp(),updatedAt:stamp()};return{ok:true,supervisor,state:withWorkHQ(state,hq=>({...hq,supervisors:[...hq.supervisors,supervisor]}))};}
export function addMaterial(state,draft={}){const name=String(draft.name||'').trim();if(!name)return{ok:false,error:'A material needs a name.',state};const material={id:draft.id||uid('material'),name,category:draft.category||'Other',clientIds:list(draft.clientIds),active:draft.active!==false,notesOptional:draft.notesOptional||'',createdAt:stamp(),updatedAt:stamp()};return{ok:true,material,state:withWorkHQ(state,hq=>({...hq,materials:[...hq.materials,material]}))};}
export const setScheduleException=(state,draft)=>withWorkHQ(state,hq=>{const item={id:draft.id||uid('exception'),...draft,date:dateKey(draft.date),createdAt:draft.createdAt||stamp()};const exists=hq.scheduleExceptions.find(x=>x.id===item.id);return{...hq,scheduleExceptions:exists?hq.scheduleExceptions.map(x=>x.id===item.id?item:x):[...hq.scheduleExceptions,item]}});
export function getCareerProgress(state,stage='rbt'){const hq=normalizeWorkHQ(state.workHQ),set=CAREER_REQUIREMENT_SETS[stage==='rbt'?hq.career.rbtRequirementSetId:stage==='bcaba'?'bcaba_2027':'bcba_2027']||CAREER_REQUIREMENT_SETS.rbt_2026,marks=stage==='rbt'?hq.career.rbtMilestones:{};const completed=set.milestones.filter(([key])=>marks[key]===true).length;return{set,completed,total:set.milestones.length,percent:Math.round((completed/set.milestones.length)*100)};}
export const isRbtCertified=state=>normalizeWorkHQ(state.workHQ).career.rbtMilestones.certification===true;
export function updateCareer(state,changes){return withWorkHQ(state,hq=>({...hq,career:{...hq.career,...changes}}));}
export function updateRbtMilestone(state,key,value){return withWorkHQ(state,hq=>{const rbtMilestones={...hq.career.rbtMilestones,[key]:value};return{...hq,career:{...hq.career,rbtMilestones,currentRole:key==='certification'&&value?'rbt':hq.career.currentRole}}});}
export function fieldworkSummary(state,target){const records=normalizeWorkHQ(state.workHQ).fieldworkRecords.filter(item=>item.certificationTarget===target);const total=records.reduce((sum,item)=>sum+(Number(item.totalHours)||0),0),restricted=records.reduce((sum,item)=>sum+(Number(item.restrictedHours)||0),0),unrestricted=records.reduce((sum,item)=>sum+(Number(item.unrestrictedHours)||0),0),supervision=records.reduce((sum,item)=>sum+(Number(item.supervisionHours)||0),0);return{records,total,restricted,unrestricted,supervision,supervisionPercent:total?Math.round((supervision/total)*1000)/10:0};}
export function addFieldworkRecord(state,draft={}){const target=['bcaba','bcba'].includes(draft.certificationTarget)?draft.certificationTarget:null;if(!target)return{ok:false,error:'Choose BCaBA or BCBA fieldwork.',state};const record={id:draft.id||uid('fieldwork'),certificationTarget:target,year:Number(draft.year)||new Date().getFullYear(),month:Number(draft.month)||new Date().getMonth()+1,fieldworkType:draft.fieldworkType||'supervised',supervisorId:draft.supervisorId||null,totalHours:Number(draft.totalHours)||0,restrictedHours:Number(draft.restrictedHours)||0,unrestrictedHours:Number(draft.unrestrictedHours)||0,supervisionHours:Number(draft.supervisionHours)||0,individualSupervisionHours:Number(draft.individualSupervisionHours)||0,groupSupervisionHours:Number(draft.groupSupervisionHours)||0,observationMinutes:Number(draft.observationMinutes)||0,verificationStatus:draft.verificationStatus||'unverified',notes:draft.notes||'',createdAt:stamp(),updatedAt:stamp()};return{ok:true,record,state:withWorkHQ(state,hq=>({...hq,fieldworkRecords:[...hq.fieldworkRecords,record]}))};}
export function addProfessionalDevelopment(state,draft={}){const title=String(draft.title||'').trim();if(!title)return{ok:false,error:'Professional-development activity needs a title.',state};const entry={id:draft.id||uid('pd'),title,date:draft.date||dateKey(),provider:draft.provider||'',pduHours:Number(draft.pduHours)||0,type:draft.type||'Other',documentationLocationOptional:draft.documentationLocationOptional||'',notes:draft.notes||'',createdAt:stamp(),updatedAt:stamp()};return{ok:true,entry,state:withWorkHQ(state,hq=>({...hq,professionalDevelopment:[...hq.professionalDevelopment,entry]}))};}
export const professionalDevelopmentTotal=state=>normalizeWorkHQ(state.workHQ).professionalDevelopment.reduce((sum,item)=>sum+(Number(item.pduHours)||0),0);
export const getDegreeProgress=(state,degree)=>normalizeWorkHQ(state.workHQ).career.degreeProgress?.[degree]||null;
export const getWorkHoursForRange=(state,start,end)=>getWorkSessionsForRange(state,start,end).reduce((summary,session)=>{const actual=Number(session.plan?.actualMinutes);return{scheduledMinutes:summary.scheduledMinutes+session.scheduledMinutes,actualMinutes:summary.actualMinutes+(Number.isFinite(actual)&&actual>0?actual:0),sessions:summary.sessions+1}}, {scheduledMinutes:0,actualMinutes:0,sessions:0});
/** Stable Stage 1 bridge. Passing the store lets the app own persistence and idempotent external-id upserts. */
export function publishWorkAction(store,{kind,id,title,scheduledDate,priority='Should do',metadata={}}){if(!store?.createAction)return{ok:false,error:'Daily Shit action API is unavailable.'};return store.createAction({source:'rbt',externalId:`work-hq:${kind}:${id}`,text:title,scheduledDate,priority,metadata:{workKind:kind,workId:id,...metadata}});}
const minutes=(start,end)=>{if(!start||!end)return 0;const [sh,sm]=start.split(':').map(Number),[eh,em]=end.split(':').map(Number);return Math.max(0,(eh*60+em)-(sh*60+sm));};
